config/core/test-configs-chromeos.yaml
After adding several device types we can optimize config, to make
configuration less complex and reduce probability of mistakes while
adding new devices in future.
=> CHROMEOS test-configs-chromeos.yaml: Simplify device_type configuration

config/runtime/base/python.jinja2
The Node state names have changed and "complete" has now been replaced
with "done".  Update the base python.jinja2 template accordingly.
=> config/runtime: replace 'done' state with 'complete'

kernelci/db/kernelci_api.py
Instead of returning entire paginated response
received from API, return only list of node
objects by fetching value of 'items' key.
=> kernelci_api: return only 'items' from 'get_nodes'

config/core/build-configs.yaml, config/core/test-configs.yaml, config/lava/v4l2-decoder-conformance/generic-depthcharge-tftp-nfs-v4l2-decoder-conformance-template.jinja2, config/lava/v4l2-decoder-conformance/generic-grub-tftp-nfs-v4l2-decoder-conformance-template.jinja2, config/lava/v4l2-decoder-conformance/generic-qemu-v4l2-decoder-conformance-template.jinja2, config/lava/v4l2-decoder-conformance/generic-uboot-tftp-nfs-v4l2-decoder-conformance-template.jinja2, config/lava/v4l2-decoder-conformance/v4l2-decoder-conformance.jinja2
Add the V4L2 decoder conformance test plans for the AV1, H264, H265, VP8 and VP9 formats.
Run the tests only on next, mainline and media trees for now.
Enable the H264, VP8 and VP9 test plans on the `rk3399-gru-kevin` Chromebook.
=> test-configs.yaml: Add V4L2 decoder conformance tests on rk3399-gru-kevin

config/core/build-configs.yaml
Add CONFIG_INTERCONNECT_QCOM_SC7180=y to the arm64-chromebook fragment which is needed for sc7180-trogdor-lazor-limozeen.
=> build-configs.yaml: add INTERCONNECT_QCOM_SC7180 to arm64-chromebook

kernelci/lab/lava/__init__.py
As we found there is one more place where dtb might be added
to generated job name, removing it, to shorten job name length.
=> CHROMEOS lava/__init__.py: Remove dtb from job name

config/core/test-configs-chromeos.yaml
As we built new version of rootfs with PR #1404, it includes mount of rootfs by fixed PARTUUID, which improve operation of devices with unstable block device names.
=> CHROMEOS test-configs-chromeos.yaml: Update rootfs for modules-install

config/core/build-configs.yaml, config/k8s/job-build.jinja2, doc/kci_build.md, kci_build, kernelci/build.py
AMD Stoneyridge require early loaded firmware for GPU,
and it have to be loaded before rootfs is mounted, so
firmware have to be embedded inside kernel.
This PR enables such function during kernel build.
If option is present and non-empty, it will fetch linux-firmware repository,
and only then will start building kernel, so kernel can take from it all files it need to embed.
Fixes #1370
=> Add embedded firmware handling

config/k8s/gen.py, kernelci/cli.py, kernelci/config/__init__.py, kernelci/lab/__init__.py, kernelci/lab/kubernetes.py, kernelci/lab/lava/__init__.py, kernelci/lab/shell.py
When no YAML configuration path is provided, load either from a local `config/core` directory or from the system-wide `/etc/kernelci/core` if they exist.
=> Load YAML config from /etc/kernelci/core by default

config/rootfs/debos/scripts/bullseye-gst-fluster.sh
As caching has been enabled on kernelci1 host the CACHING_SERVICE needs
to be updated in the bullseye-gst-fluster.sh script.
Add download URLs printing as it doesn't add much in the logs, but
simplifies debugging in case of failure.
=> rootfs/bullseye-gst-fluster: Update caching service URL

config/core/test-configs-chromeos.yaml, config/lava/chromeos/cros-boot.jinja2
Grunt is having a variation on block_device when
booted, so the idea of this fix is to set a static
part-uuid independent of the block_device used.
=> CHROMEOS cros-boot.jinja2: set a static part-uuid for grunt

config/rootfs/debos/overlays/cros-flash/opt/chromeos/install-modules
As we have fixed PARTUUID value, we can make logic of
mounting block device with ChromeOS much simpler by
mounting it using PARTUUID label.
=> CHROMEOS install-modules: Modify rootfs device mount

config/core/rootfs-configs.yaml
The sparc64 buildroot builds aren't working, which is blocking buildroot updates for all the other architectures.  As there's no test definition in test-configs.yaml using sparc64, drop the buildroot sparc64 builds for now until they're fixed properly and there's a use-case for it.
=> rootfs-configs.yaml: drop sparc64 buildroot builds

config/core/test-configs.yaml
=> test-configs.yaml: update bullseye-gst-gluster rootfs URLs to 20220913.0

scripts/lava-v2-callback.py
PyYAML requires explicitly provided loader class when parsing YAML content from file
(https://github.com/yaml/pyyaml/commit/c2743653bc89e42679ba097b4f9888db47c61d63)
This commit fixes places which were left with the old yaml.load() method call and eventually caused script to crash.
=> scripts/lava-v2-callback.py: Fix YAML loading

config/k8s/job-build.jinja2
Drop the git clone of kernelci-core as the Docker image already has it installed system-wide with the configuration files in /etc/kernelci.
=> config/k8s: drop kernelci-core git clone

config/core/rootfs-images.yaml, config/core/test-configs-cip.yaml, config/core/test-configs.yaml, kci_test, kernelci/config/base.py, kernelci/config/test.py
Add a command to automatically generate the YAML configuration with the rootfs images URLs when they exist and leave them to their previous URLs when getting HTTP 404.  For example:
```
kci_test update_rootfs_url --release=20220913.0 --output=config/core/rootfs-image.yaml
```
=> kci_test update_rootfs_urls

kernelci/db/kernelci_api.py
Depends on https://github.com/kernelci/kernelci-api/pull/179
Implement database method to get the count of all nodes matching attributes from API.
=> T37615 kernelci_api: add 'Database.count_nodes()' method

config/lava/chromeos/cros-boot.jinja2
If we specify non-ChromeOS device name in kci_test, it might generate cryptic error. It is better to generate proper reason, why test generation failed.
Fixes #1326 
=> CHROMEOS cros-boot.jinja2: Improve error message on invalid target

config/docker/kci_docker
Add --no-cache argument to kci_docker to disable the Docker cache when building images.
Fixes #1441
=> config/docker: add kci_docker --no-cache argument

config/docker/debos.jinja2
Split the "go get" and "go install" commands into two lines as it's not useful to have them on the same line and now we can better tell when something fails what is causing it.
=> config/docker: split lines in debos.jinja2

config/docker/base/debos.jinja2, config/docker/debos.jinja2
Move debos.jinja2 to base/debos.jinja2 and use godebos/debos as the base image since we can now just add fragments on top of it.
Fixes #1440
=> config/docker: use godebos/debos as base image for debos

doc/kci_build.md, doc/kci_rootfs.md
As we have new docker image building system in place, and naming changed as well, update documentation for correct docker image names.
=> docs: Update docker image names

config/docker/data/add_modules.sh, config/docker/data/ssh_retry.sh, config/docker/data/tast_parser.py
Copy CrOS docker-related files so it can be used with kci_docker.
Similar to gcc-10-x86.jinja2 and reference to gcc-header-fix.patch,
we need to have files in place beforehand to reference them in Dockerfiles.
=> CHROMEOS docker/data: Copy CrOS related files for kci_docker

config/docker/cros-baseline.jinja2, config/docker/cros-qemu-modules.jinja2, config/docker/cros-sdk.jinja2, config/docker/cros-tast.jinja2, config/docker/fragment/cros-lava.jinja2
Migrate remaining ChromeOS related images to new template based kci_docker.
=> CHROMEOS config/docker: Migrate CrOS to kci_docker

config/lava/chromeos/cros-tast.jinja2, config/lava/chromeos/tast.jinja2
As in new Docker images we are using unified username for CrOS, we need to update some of LAVA templates that are using old username 'cros-tast' to new - 'cros'.
=> CHROMEOS config/lava/cros*: Update home path in tast tests

kci_rootfs
Add support for specifying more than one rootfs type and architecture for kci_rootfs list_variants command.
It's possible to use --rootfs-type and --arch options multiple times in a single command call. All values create a list which is used to filter the results.
E.g.
./kci_rootfs list_variants --rootfs-type debos --rootfs-type buildroot
will narrow down the list of variants to only debos and buildroot rootfs types.
=> kci_rootfs: Support multiple archs and rootfs types

config/rootfs/chromiumos/scripts/build_board.sh, config/rootfs/chromiumos/scripts/create_manifest.py
For troubleshooting procedures we need extended information about ChromiumOS build. This patch adds manifest.json file on build, that contain such information, similar to debos approach.
=> CHROMEOS build_board.sh: Extract rootfs build information

config/k8s/wait.py, kernelci/build.py
After analysis of Jenkins job runs we are able to identify few weak spots where job might fail early, while it is still possible to recover and continue.
This patches are addressing this, as attempt to improve job execution success rate.
Fixes #1451 
Fixes https://github.com/kernelci/kernelci-project/issues/124
Fixes #1461 
Fixes #1462
=> Improving jobs reliability

config/rootfs/chromiumos/scripts/build_board.sh
The CrOS userpace does not support the latest kernels
used by KernelCI in the sense that they miss selinux
policies for newer watches which fail as described in
https://github.com/kernelci/kernelci-core/issues/1372
We can't just disable selinux at boot via the kernel
cmdline selinux=0 because that will cause packages like
the upstart init system to fail, so we need to actually
disable them during image builds.
=> CHROMEOS build_board.sh: disable selinux use flags

config/rootfs/chromiumos/cros-snapshot-release-R106-15054.B.xml
Monthly update of ChromiumOS repository snapshoft manifest. This file required to be added before updating version entries in rootfs config files.
=> CHROMEOS cros-snapshot*.xml: Add manifest for R106 release

config/rootfs/debos/scripts/bullseye-ltp.sh
This PR fix the LTP rootfs build which fail currently due to open_posix_testsuite.
=> debos: bullseye-ltp: fix build

config/rootfs/debos/rootfs.yaml, config/rootfs/debos/scripts/crush.sh
DUT need to have a correct time and cannot rely on having a RTC for that.
This is needed for lot of tests which need to have a correct time. Moslty all x509/TLS based actions, like doing apt (over https).
Signed-off-by: Corentin Labbe <clabbe@baylibre.com>
=> debos: enable systemd-timesync

config/core/test-configs.yaml
Add an entry for the mt8192-asurada-spherion-r0 device and enable the
baseline tests for it.
At this moment the devicetree for this machine is only available on linux-next.
baseline test LAVA run: https://lava.collabora.dev/scheduler/job/6896370
baseline-nfs test LAVA run: https://lava.collabora.dev/scheduler/job/6900379
=> test-configs.yaml: Add mt8192-asurada-spherion-r0

config/core/test-configs.yaml
This is the PR for the board configuration in https://github.com/kernelci/kernelci-core/pull/1232. This board is not yet available in the Kontron KernelCI.
=> test-configs.yaml: add Kontron KSwitch D10 MMT 8G

config/k8s/job-build.jinja2
Annotate the build jobs and the pods they create with Kubernetes labels
for job parameters, allowing use of these labels to be used when doing
queries via the Kubernetes interfaces. For example we can list all jobs
scheduled for build 12345 with:
kubectl get jobs -l kernelci/build=12345
which can help with debugging, and is generally idiomatic for
Kubernetes.
=> config/k8s: Add labels to the build jobs and their pods

config/core/build-configs.yaml
Add builds for mathiasbgg/for-next with minimal set of variants.
Resolves: https://github.com/kernelci/kernelci-core/issues/1465
=> build-configs.yaml: Add for-next branch from matthiasbgg tree

config/lava/chromeos/cros-tast.jinja2
As tast tests keep evolving, local docker require new file that seems working as kind of RPC server. Without this file tast tests can be listed, but cannot be executed.
This patch need to be enabled only after all Chromebooks are flashed to R106.
=> CHROMEOS cros-tast.jinja2: Add new file required by R106 tast

config/core/build-configs.yaml
Several Chromebooks require firmware files that need to be loaded early, so it should be built in kernel.
* amdgpu/raven2_gpu_info.bin required by zork
* i915/glk_dmc_ver1_04.bin by octopus
* i915/kbl_dmc_ver1_04.bin by sona, hatch, rammus
* rtl_nic/rtl8153a-4.fw by sarien, volteer, dedede
=> build-configs.yaml: Add missing firmware files for Chromebooks

config/k8s/job-build.jinja2
In some cases, for example when specified docker image is not available, job might loop infinitely and if there is many of them, it can occupy all nodes and block all builders.
Fixes #1492
=> job-build.jinja2: Limit job retries

config/k8s/job-build.jinja2
As reported and observed we have numerous issues with stale docker images on k8s builders. One of possible reasons is that by default pull policy for image with specified tag is **IfNotPresent**, which we need to change to **Always**.
=> job-build.jinja2: Set image pull policy as Always

kernelci/build.py
If we check for last commit, and it fails - we just get return code 1. But it is important to differentiate, if tree got deleted it might fail with 404 code, if it is just temporary git problems it will produce different HTTP error code.
It will be useful to do periodic cleanup of git trees that are dont exist anymore, by checking jenkins logs.
=> build.py: Add printout of HTTP error code during last commit retrieval

config/lava/chromeos/cros-boot.jinja2, config/rootfs/debos/overlays/cros-flash/opt/chromeos/install-modules
As we flash all rootfs with fixed PARTUUID, we can remove block device option from script parameters completely.
=> CHROMEOS cros-boot&install-modules: Finalize using PARTUUID mount

config/core/build-configs.yaml
After adding initial file, it appeared AMD drivers require more files to operate properly.
Based on test results:
https://storage.chromeos.kernelci.org/kernelci/chromeos-stable/chromeos-stable-20221121.0/x86_64/cros---chromeos-5.15-x86_64-chromeos-amd-stoneyridge.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS_GZIP=n/clang-14/lab-collabora/cros-tast-platform-lenovo-TPad-C13-Yoga-zork_chromeos.html https://storage.chromeos.kernelci.org/kernelci/chromeos-stable/chromeos-stable-20221121.0/x86_64/cros---chromeos-5.15-x86_64-chromeos-amd-stoneyridge.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS_GZIP=n/clang-14/lab-collabora/cros-tast-platform-asus-CM1400CXA-dalboz_chromeos.html
=> build-configs.yaml: Add more missing files for AMD Stoneyridge Chromebooks

config/core/rootfs-configs-chromeos.yaml, config/core/test-configs-chromeos.yaml, config/rootfs/chromiumos/scripts/build_board.sh
Add more Chromebooks for rootfs generation, with relevant fixes. Also organize fixes alphabetically in script and fix minor formatting issues.
Additionally add tast tests for this Chromebooks.
=> CHROMEOS build_board/rootfs-configs: Add more Chromebooks for rootfs

kernelci/config/__init__.py
Fixes https://github.com/kernelci/kernelci-core/issues/1528
Need to fix "NameError: name 'v' is not defined" from `load_yaml` function when try to load YAML configurations from a file.
Fixes: 4f9c0db2 ("kernelci.config: add _iterate_yaml_files() to simplify code")
=> T39140 kernelci/config: fix YAML configuration load failure

config/core/test-configs.yaml
This 2 commits intended to enable kselftest on sona (nami baseboard) Chromebook.
Related to: 
https://github.com/kernelci/kernelci-core/pull/1507
https://github.com/kernelci/kernelci-core/pull/1505
https://github.com/kernelci/kernelci-core/pull/1506
=> Add kselftest-landlock on x86 sona

config/core/test-configs.yaml
Remove smc tests on qemu, as it can create false positive.
=> config/core/test-configs: remove smc test from qemu

kernelci/db/kernelci_api.py
Need to retrieve 'items' key to get list of regression nodes from the`/nodes` endpoint response in `Database.get_regressions_by_node_id` method. This change is due to implementation of pagination in API.
=> kernelci_api: Use 'items' key to get regression nodes

config/core/test-configs.yaml, kernelci/config/test.py
Change the hifive-unleashed-a00 class to riscv64-dtb as this platform is a riscv64 platform. This will allow using riscv64 debian images in order to run kselftest or ltp.
However keep using the "riscv" arch for buildroot.
=> set hifive as riscv64

config/core/test-configs.yaml
LAVA use old qemu network options which does not work on riscV qemu. So add network via extra-options with the new full explicit network options.
=> qemu: add network to riscV qemu

config/core/test-configs.yaml
As only one device available in lab-collabora and it have very long queue of tests scheduled, reduce amount of tests to bare minimum
=> test-configs.yaml: Reduce tests on odroid-xu3

config/core/build-configs-stable.yaml
ARMv3 was removed in gcc-9, so there is no point trying to compile this platforms with gcc.
Fixes https://github.com/kernelci/kernelci-core/issues/1508
=> build-configs.yaml: Disable ARMv3 platforms from gcc-10

config/core/build-configs.yaml, config/docker/rustc-1.62.jinja2
config: add rust build configurations
Starting with the upcoming v6.1, mainline Linux has merged the
initial Rust infrastructure so this adds some configs for build
testing it together with some sample modules.
The kernel requires a specific version of rustc, so we add the
rustc-1.62 build environment which derives from clang-15, since
a C compiler is still required to build the kernel and the
supported kernel version is 15 (we might bump this later).
Obviously GCC can be used as well but for now testing all the
toolchain combinations does not add significant value. In the
future more toolchain combinations can be used as needed.
The official "offline" toolchain installation method is used as
documented at [1] with sha256sum and because some distros like
Debian stable might not provide up …
=> config: add rust build configurations

config/docker/fragment/kselftest.jinja2, config/docker/gcc-10-riscv64.jinja2
This PR fixes the build of some kselftest testsuites for riscv64 platforms by using the cross compiled libc6 package.
Also install clang in order to build kselftest testsuites that require it.
Note that some kselftest testsuites are still failing to build due to the fact that several libs that are needed are not available yet for riscv64.
=> Fix the build of some kselftest testsuites for riscv64

config/core/build-configs.yaml, config/docker/rustc-1.62.jinja2
commit 7d846c58ce8d82552372213a955bbe9c2fd309fa
Author: Adrian Ratiu <adrian.ratiu@collabora.com>
Date:   Tue Dec 6 15:15:02 2022 +0200
build-configs: move rust builds under mainline cfg
PR #1468 added the mainline rust build in a separate
`rust` build configuration instead of adding to the
already existing mainline config which can cause
unnecessary builds. Move it in the proper place.
While at it also change the x86_64_arch anchor to
build just the base x86_64_defconfig to avoid
unnecessary allmodconfig rebuilds.
Fixes: 43875d0e47f2 ("config: add rust build configurations")
Suggested-by: Guillaume Tucker <guillaume.tucker@collabora.com>
Reviewed-by: Miguel Ojeda <ojeda@kernel.org>
Reviewed-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
Signed-off-by: Adrian Ratiu …
=> Misc rust build fixes

config/core/build-configs.yaml
It seems AMD GPU fetch many small firmware files that are hard to know/find list, so i had to build kernel again and again, to figure out list required for particular Chromebook lenovo-TPad-C13-Yoga-zork. Expected outcome that Tast tests finally will run properly on Chromebooks with AMD Raven chipset.
=> build-configs.yaml: Add missing firmware files for zork

config/lava/baseline/baseline.jinja2, config/lava/cros-ec/cros-ec.jinja2
We can try to use retry option in case of serial corruption, to improve reliability of jobs on devices with slow or unreliable serial console. It should decrease rate of false positive on baseline test failures.
For example failed test:
```
1455 17:17:20.117173  + KERNELCI_LAVA=y /bin/sh /opt/kernelci/dmesg.sh
1456 17:17:20.142263  <8>[   17.024549] <LAVA_SIGNAL_TESTCASE TEST_CASE_ID=crit RESULT=pass UNITS=lines MEASUREMENT=0>
1457 17:17:20.142531  Received signal: <TESTCASE> TEST_CASE_ID=crit RESULT=pass UNITS=lines MEASUREMENT=0
1458 17:17:20.142631  Unknown test uuid. The STARTRUN signal for this test action was not received correctly.
1460 17:17:20.142813  end: 3.1 lava-test-shell (duration 00:00:00) [common]
1462 17:17:20.143021  lava-test-retry failed: 1 of 1 attempts. 'Invalid …
```
=> baseline.jinja2: Add failure_retry to test

config/core/test-configs.yaml, kernelci/config/test.py
as discussed in PR #1487 , this is not correct and should be reverted.
=> revert "set hifive as riscv64" (PR #1487)

config/core/build-configs.yaml
commit 58f7ecbe7574fb1071ac8c92ec645c7ff3402f41                                                                                           
Author: Adrian Ratiu <adrian.ratiu@collabora.com>
Date:   Fri Dec 2 16:03:03 2022 +0200
build-configs: add rust next trees
This adds a rust build to the linux-next integration tree as well
as the maintainer 'rust-next' tree.
Suggested-by: Guillaume Tucker <guillaume.tucker@collabora.com>
=> build-configs: add rust next trees

config/core/rootfs-configs.yaml
Add 2 new rootfs for riscV.
Signed-off-by: Corentin Labbe <clabbe@baylibre.com>
=> rootfs: add sid-kselftest and sid-ltp

config/core/build-configs.yaml
As requested by Kevin Hilman, adding two trees for riscv, testing all available riscv configurations.
Fixes https://github.com/kernelci/kernelci-core/issues/1463
=> build-configs.yaml: Add 2 riscv trees to monitor

config/core/test-configs.yaml
Map the kernel arch name "riscv" to debian arch name "riscv64"
=> test-configs: add riscv to arch map

config/core/rootfs-images.yaml, config/core/test-configs-riscv.yaml, config/core/test-configs.yaml, config/lava/kselftest/generic-qemu-ramdisk-kselftest-template.jinja2, config/lava/ltp/generic-qemu-ramdisk-ltp-template.jinja2
Duplicating the test plans that are planned to be run on the hifive-unleased platform.
In the future, more or less the same will be added for the qemu_riscv64 platform.
This approach has the advantage of being easily "revertable" when riscv is finally supported by the stable debian and it does not change the kernelci internal logic.
Note that the riscv64 test plan success depends on https://github.com/kernelci/kernelci-core/pull/1467
Also I ignored the CI checks failing due to the test plans not being in an alphabetical order, prefering to group the riscv test plans.
This PR follows https://github.com/kernelci/kernelci-core/pull/1478
=> duplicate testplans for riscv

config/rootfs/debos/scripts/create_initrd_ramdisk.sh
If initramfs expects nfs we need to have also ethernet device to be available. In some cases network device are really slow to detect and it cases panic on ipconfig stage
Fixes https://github.com/kernelci/kernelci-core/issues/1532
=> create_initrd_ramdisk.sh: Add script for ethernet device wait

kci_data, kernelci/cli.py, kernelci/db/kernelci_api.py
Add command-line utility to `kci_data` to create new users.
Tested on local:
```
./kci_data create_user --username jeny --password jeny --db-config api --db-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJib2IiLCJzY29wZXMiOlsiYWRtaW4iXX0.t3bAE-pHSzZaSHp7FMlImqgYvL6f_0xDUD-nQwxEm3k --is-admin 1
{'_id': '62873c99c7fa5742896cc432', 'username': 'jeny', 'hashed_password': '$2b$12$rL9zT6Xtj1sgFpoZVNrNZu3WE.MBwDSNBXD/nondmY3ZORIc61IYu', 'active': True, 'is_admin': True}
```
=> T35399 Create new user utility

kernelci/db/kernelci_api.py
Drop `get_regressions_by_node_id` method as it is
not needed anymore for regression tracking.
=>  T39237 db/kernelci_api: drop unused method related to regression

config/core/test-configs-chromeos.yaml, config/lava/chromeos/cros-boot.jinja2, kernelci/test.py
This series of patches add support for arm64 Chromebooks and enable one of them sc7180-trogdor-lazor-limozeen, which have rootfs generated and almost ready for testing.
=> Add ChromeOS support for arm64 and one arm64 Chromebook

config/rootfs/debos/rootfs.yaml
Current full rootfs lack an init link and so are unbootable. The init link is create after full rootfs are generated but before the minimal ones. Move the init link creation before full rootfs are generated.
=> debos: create init link for full rootfs

kci_rootfs
Add mising import kernelci.config which is used in this script. Somehow it worked before by having it imported implictly by some lucky mechanism.
=> kci_rootfs: add missing import kernelci.config

config/core/build-configs-stable.yaml
Now that 4.4.y LTS has reached EOL, the CIP project have picked up long term stable maintenance for 4.4.y.
* linux-4.4.y-st: Essentially 4.4 LTS
* linux-4.4.y-st-rc: Release candidate branch
* linux-4.4.y-st-rt: linux-4.4.y-st + PREEMPT-RT support
* linux-4.4.y-st-rt-rebase: linux-4.4.y-st-rt but with all RT patches rebased on top
This is for issue https://github.com/kernelci/kernelci-core/issues/1543
=> build-configs-stable.yaml: Add CIP 4.4-stable branches

config/docker/fragment/gcloud.jinja2
```
CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```
As recommended it can be installed by apt, in our gcloud jinja template fragment
=> gcloud.jinja2: Add gcloud plugin as required by google cloud

config/lava/baseline/baseline.jinja2
As upstream version use slightly different path for helpers we need to update LAVA definition to use that properly.
=> baseline.jinja2: Update bootrr helpers path

config/core/build-configs.yaml
Enable all kernel configs required to get all devices on
mt8183-kukui-jacuzzi-juniper-sku16 probing.
A lot of these configs are the same as in #1325. After one of the PRs is merged I'll rebase the other to have only the missing ones. I'll also send these configs upstream.
=> build-configs.yaml: Add kernel configs for juniper

config/lava/cros-ec/cros-ec.jinja2, config/rootfs/debos/scripts/bullseye-cros-ec-tests.sh
I inherited the cros-ec tests repo ownership from Enric and they now live here: https://github.com/hardboprobot/cros-ec-tests
Also, I made a few changes in the tests to enable a `--verbosity` option and to sync some of the tests to the current (as of v6.0) IIO ABI so that they go back to green.
=> Sync with latest cros-ec test changes

config/core/build-configs.yaml, config/core/test-configs.yaml
Add a riscv build for SMP-disabled (e.g. `CONFIG_SMP=n`)
Align riscv tree/branch names to naming convention.
Update test plan filters for riscv platforms.
=> misc riscv updates, cleanups

config/core/rootfs-configs.yaml
This patchset adds the required firmwares for GPU and hardware enc/decoder, necessary to run certain tests on Qualcomm sc7180-trogdor
=> rootfs-configs: Trogdor: Add Adreno 630 and Venus-5.2 firmwares

config/rootfs/debos/scripts/install-bootrr.sh
As tested on staging, bootrr need to be updated to latest commit Because it was forgotten on last update and LAVA template is changed, this is especially important to do before next rootfs update
=> install-bootrr.sh: Update bootrr to latest commit

config/core/test-configs.yaml, config/lava/v4l2-decoder-conformance/v4l2-decoder-conformance.jinja2, config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py
Use -t option in fluster to set a timeout for each decoding. Keep 30s as default value and set a 90s timeout for `rk3399-gru-kevin`.
=> config/v4l2-decoder-conformance: set decoding timeout in fluster

config/docker/kci_docker, setup.py
**kci_docker: Enable adding version to image tag**
Introduce `--image-version/-V` to specify image version which will be added at the end of the image tag.
**setup.py: Add extras_require with development dependencies**
Define extras_require with development packages. It's now possible to use pip to install kernelci package in a regular or development version.
E.g.
```    
pip install kernelci  # install regular version
pip install kernelci[dev]  # install development versio
```
=> Add docker image versioning

config/lava/chromeos/cros-boot.jinja2
If we fail installing modules there is no point to continue test, as in best case it will fail, and in worst it will give false results
=> CHROMEOS cros-boot.jinja2: Add lava-test-raise for modules-install

config/lava/chromeos/cros-boot.jinja2
As all ChromiumOS installs we have unified PARTUUID, we dont need anymore block device name. We can mount all by PARTUUID.
=> CHROMEOS cros-boot.jinja2: Leave only PARTUUID option

config/core/test-configs-chromeos.yaml
Current arm64 missing latest updates for modules-install script, update it to most recent, tested build.
=> CHROMEOS test-configs-chromeos.yaml: Add updated cros-flash for arm64

config/core/test-configs-chromeos.yaml
For video encoding and decoding in x86 (amd/intel) we have vaapi and some arm64 have v4l m2m video codec offloading implemented in kernel drivers. ChromeOS uses this API have tast tests for it, so we need to use them, as we have most of Chromebooks x86 - add first VAAPI tast tests.
Fixes https://github.com/kernelci/kernelci-core/issues/670
=> CHROMEOS test-configs-chromeos.yaml: Add additional hardware offload tests

config/core/test-configs.yaml
As explained in https://github.com/kernelci/kernelci-core/issues/1496 we need to test only several trees, and current way it match also net-next kernel, not only next. With regex, as verified manually it should solve issue.
Fixes https://github.com/kernelci/kernelci-core/issues/1496
=> test-configs.yaml: Fix tree match for v4l tests

config/k8s/job-build.jinja2
Add set -e to the build job template so that if any command fails the job aborts rather than trying to run subsequent commands as that's destined to keep piling up more failure.
=> config/k8s: add set -e to build jobs

config/k8s/job-build.jinja2, kci_build, kci_rootfs, kernelci/build.py, kernelci/cli.py, kernelci/legacy.py, kernelci/rootfs.py, kernelci/storage/__init__.py, kernelci/storage/backend.py, kernelci/storage/ssh.py
Rework the `kci_build` and `kci_rootfs` commands to use the new Storage class whenever appropriate.  Move old legacy code to `kernelci.legacy` and don't update it to use the new Storage as this code is specific to the backend / storage interaction and can only be used with the backend API.
=> Storage rework

config/core/test-configs.yaml
Ideally we'd cover more boards (rseq is supported on x86 too and a big.LITTLE board wouldn't go amiss for arm64) but this gets things going.
=> Enable rseq kselftests

config/core/rootfs-images.yaml
Skipping bullseye-v4l2 due to build failure #1619.
=> rootfs-images.yaml: update rootfs URLs to 20230109.0

kci_bisect, kci_build, kci_data, kci_rootfs, kci_test, kernelci/cli.py, kernelci/config/__init__.py, kernelci/config/base.py
This permits separating the configuration for a local KernelCI instance used in a conventional CI pipeline into two parts:
- The default configuration data can be taken directly from KernelCI itself (or a fork thereof, as required).
- The local configuration can specified separately, and merged in on top of the defaults KernelCI provides.
For example, in one common case of testing local kernel tree in CI, we can provide our own LAVA lab, own device types, own test suites on top of the KernelCI provided backbone, without maintaining a mandatory fork of KernelCI that contains our configuration data, and adds maintenance burden.
=> Allow configuration to be loaded from multiple sources

config/core/build-configs.yaml, config/docker/rustc-1.66.jinja2
Rust 1.66.0 will be the next version supported by the kernel [1].
Therefore, add `rustc-1.66` as a new build environment alongside `rustc-1.62` (which can be removed later on when the new version hits mainline), and then move `rust-for-linux_rust` to it.
Link: https://github.com/Rust-for-Linux/linux/pull/947 [1]
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
=> Rust 1.66.0

config/core/build-configs.yaml
Until we have the needed pieces in place in `rustc` and the kernel to support IBT/Retpoline/Rethunk (which will take at least a couple months); disable the relevant configs for the moment.
This avoids the 2000+ warnings from `objtool` that we currently generate in the logs.
Link: https://storage.kernelci.org/mainline/master/v6.1-11554-g785d21ba2f44/x86_64/x86_64_defconfig+rust/rustc-1.62/logs/build-warnings.log
Link: https://github.com/Rust-for-Linux/linux/issues/945
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
=> build-configs: rust: disable IBT/Retpoline/Rethunk for the moment

config/core/build-configs.yaml
While working on refresing https://github.com/kernelci/kernelci-core/pull/511, I see that KCI already have now a crypto fragment, but it miss some important options.
So let's enable in-kernel crypto selftest.
=> Add more crypto options

config/core/rootfs-images.yaml, config/core/test-configs.yaml
In order to get coverage of new architecture extension that are only available in emulation enable the arm64 selftests in qemu, using a ramdisk for the filesystem as we do for the RISC-V kselftests running qemu.
=> test-configs: Enable arm64 kselftests on qemu

config/lava/kselftest/kselftest.jinja2
We build our kselftest rootfs images with all the dependencies for kselftest already installed and therefore do not need to install the incomplete set that the test-defintions tempalte attempts to install at runtime, skip doing so in order to speed up our kselftest jobs and allow them to run on very low memory systems where apt struggles without swap.
=> config/lava/kselftest: Don't install dependencies for kselftest at runtime

config/core/test-configs-chromeos.yaml
Fixed tests help to compare fixed kernels to upstream kernels. Especially it is important now to have arm64 results comparing with upstream kernels.
=> CHROMEOS test-configs-chromeos.yaml: Add back -fixed tests

config/core/test-configs.yaml
As real use cases show - we need to test kselftest kernels on baseline/baseline-nfs, because for example it looks like some boards unable to boot +kselftest builds, but booting fine with similar build without this fragment.
baseline tests help a lot with testing general "bootability" of kernel.
=> test-configs.yaml: Remove kselftest from baseline* blocklist

config/core/lab-configs.yaml, kernelci/config/base.py
These are a handful of fixes in the `kernelci.config` package:
* Drop unused `config_path` attribute in `lab-configs.yaml`
* Use numerical values rather than strings for LAVA lab min/max priorities
* Allow 0 to be a valid YAML attribute value
=> kernelci.config fixes

config/core/test-configs-riscv.yaml
Rename the default_filters top-level tag with as riscv_default_filters to avoid conflict with the global default_filters defined in test-configs.yaml.  As all the YAML files are loaded together, this was overriding the defaults for all the configs and not just riscv.
Also, as the filters defined in riscv_default_filters are used with anchors, it's just a place to define them within this file so the test_plans tag is not needed.  It is however used with the special default_filters tag as defaults for the Python code that loads the configs and not just YAML anchors.
Fixes: 39d2645e7e4a ("test-configs.yaml: Duplicate the tests to be run on riscv64")
=> test-configs-riscv.yaml: fix conflict with global default_filters

kernelci/config/base.py
This is an unexpected consequence of filter merging: the arrays inside the default filter items we accidentally shared with the filter instances, which meant that, unexpectedly, when merging in new filter items we also corrupted the default filters. This in turn led to filter items being applied inappropriately in other places, in a way that was impossible to predict from the surface YAML.
Signed-off-by: Ed Smith <ed.smith@collabora.com>
=> kernelci.config.base: Do not corrupt default filter lists

config/core/db-configs.yaml
After storage rework PR we need to add back storage config for ChromeOS instance.
=> CHROMEOS db-configs.yaml: Add ChromeOS storage config

config/docker/clang-11-arm.jinja2, config/docker/clang-11-arm64.jinja2, config/docker/clang-11-armv5.jinja2, config/docker/clang-11-mips.jinja2, config/docker/clang-11-riscv64.jinja2, config/docker/clang-11-x86.jinja2, config/docker/clang-14-arm.jinja2, config/docker/clang-14-arm64.jinja2, config/docker/clang-14-armv5.jinja2, config/docker/clang-14-mips.jinja2, config/docker/clang-14-riscv64.jinja2, config/docker/clang-14-x86.jinja2, config/docker/clang-15-arm.jinja2, config/docker/clang-15-arm64.jinja2, config/docker/clang-15-armv5.jinja2, config/docker/clang-15-mips.jinja2, config/docker/clang-15-riscv64.jinja2, config/docker/clang-15-x86.jinja2, config/docker/clang-16-arm.jinja2, config/docker/clang-16-arm64.jinja2, config/docker/clang-16-armv5.jinja2, config/docker/clang-16-mips.jinja2, config/docker/clang-16-riscv64.jinja2, config/docker/clang-16-x86.jinja2
Since clang provides a single toolchain binary which supports all target architectures we currently provide a single clang container for each version which is used for all architecture builds.  These containers include some very basic cross compilation support required for things like the vDSO but do not include enough to build real userspace applications since those generally also need libgcc, and adding our current kselftest fragments will only pull in the libraries for one architecture.
Rather than installing all userspace libraries for all architectures follow the pattern for GCC and add per architecture clang templates, layerd on top of the existing architecture neutral ones.  These templates add libgcc and can also be used with the kselftest fragment or other fragments that install …
=> config/docker: Add architecture specific clang templates

config/core/rootfs-configs.yaml, config/core/rootfs-images.yaml, config/core/test-configs.yaml, config/lava/libhugetlbfs/generic-barebox-tftp-nfs-libhugetlbfs-template.jinja2, config/lava/libhugetlbfs/generic-depthcharge-tftp-nfs-libhugetlbfs-template.jinja2, config/lava/libhugetlbfs/generic-grub-tftp-nfs-libhugetlbfs-template.jinja2, config/lava/libhugetlbfs/generic-qemu-ramdisk-libhugetlbfs-template.jinja2, config/lava/libhugetlbfs/generic-uboot-tftp-nfs-libhugetlbfs-template.jinja2, config/lava/libhugetlbfs/libhugetlbfs.jinja2, config/rootfs/debos/scripts/bullseye-libhugetlbfs.sh
The libhugetlbfs testsuite is a small, quick running and reliable testsuite which is really good for finding issues in the kernel's memory management subsystem, let's enable it for use in KernelCI. This involves the addition of a new filesystem image containing the testsuite which we then use with the existing LAVA test definitions.
=> Enable libhugetlbfs testsuite

config/core/test-configs.yaml
There are a number of smaller LTP test sets that provide some kernel level coverage which we don't currently run. This pull request provides the basic mapping of these tests into KernelCI.
To make merging a bit easier all the tests are only enabled on Tritium for now. In order to avoid conflicts in staging it also incorporates the commit adding the basic stanza for the larger syscalls test set, that is also in a separate pull request to enable that test set which adds enablement of the test set.
If this gets merged then there should most likely be followups revisiting where we run the tests.
=> Enable smaller LTP test sets

.github/workflows/main.yml, kci, kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/validate.py, requirements-dev.txt, setup.py
Enable `pylint` to run on the new `kci` script and the `kernelci.cli` package.  The intention is to keep enabling it on all the code that will be used with the new KernelCI API & Pipeline implementation.
Depends on #1585
=> Add pylint to the GitHub checks for all new code

kci_test, kernelci/cli/base.py, kernelci/legacy.py
The --storage command line argument is only used with legacy commands now so move it to kernelci.legacy accordingly.
=> kernelci.cli: move Args.storage to kernelci.legacy

kernelci/config/base.py, kernelci/config/build.py, kernelci/config/db.py, kernelci/config/lab.py, kernelci/config/rootfs.py, kernelci/config/storage.py, kernelci/config/test.py, kernelci/lab/lava/__init__.py
Introduce a new method `._get_yaml_attributes()` as an intermediate step towards getting all the configuration objects inherit `yaml.YAMLObject` so they can be parsed and dumped directly by the `yaml` package.  This PR covers all the primitive configuration attributes and leaves out special ones that relate to other specific config objects.  It enables many objects to be serialised back to YAML already.
=> kernelci.config rework: add get_yaml_attributes() method

config/docker/clang-11-riscv64.jinja2, config/docker/clang-14-riscv64.jinja2, config/docker/clang-15-riscv64.jinja2, config/docker/clang-16-riscv64.jinja2
In order to have the kselftests built correctly when using the riscv clang templates, install the riscv cross compiled version of libgcc-10-dev.
=> config/docker: Get specific libs for the riscv clang templates

config/core/build-configs.yaml
Now that the Clang images are built on a per-arch basis, update the build_environment definitions in build-configs.yaml to use the same arch name mapping as for GCC.
Fixes: 2fbb59c2c768 ("config/docker: Add architecture specific clang templates")
=> build-configs.yaml: fix clang arch names

config/core/build-configs.yaml
Add clang-15 builds for the riscv trees.  
The riscv trees are only built for ARCH=riscv and a small subset of defconfigs.
=> build-configs: add clang-15 for riscv trees

config/core/build-configs.yaml
Add Lee's backlight and mfd git trees and build configs with minimal variants.  Drop the Android 3.18 tree as it has reached its end of life now.
Replaces #459
=> Add Lee's backlight and mfd trees

kernelci/lab/lava/__init__.py
Since 96d636627f ("kernelci.lab.lava: rework priority scale") jobs submitted to at least my lab have been ignoring the configured priority range and using the full range of available priorities.  The commit has the logic to scale plan priorities but it doesn't seem to be taking effect for reasons that are not obvious to me, possibly due to confusion over the treatment of a 0 priority value as a logical value.
This is severely disrupting my own use of my lab since the baseline jobs are submitted with vastly higher priority than any of my normal jobs so juts revert the commit for now.
=> kernelci.lab.lava: Fix priority scaling

config/rootfs/debos/scripts/install-firmware.sh, kernelci/build.py
Two patches to fix firmware handling using copy-firmware.sh, as without it we doesn't have symlinked firmware files.
First to address firmware extraction for rootfs, second to address firmware extraction for building in-kernel.
=> Fix firmware handling

config/core/rootfs-configs.yaml
Recently firmware structure was changed in commit: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=ad9fdba
So now we have just two files.
But one of them missing due mistake.
I've sent fix upstream also: https://lore.kernel.org/linux-firmware/5dc7081a8b793baf08f20df6b641a86a80c9e15c.camel@collabora.com/T/#u
Fixes: https://github.com/kernelci/kernelci-core/issues/1619
=> rootfs-configs.yaml: Fix qcom/venus-5.4/venus firmware files issues

config/k8s/job-build.jinja2
Being discussed in https://github.com/kernelci/kernelci-core/issues/1677 
This reverts commit 46976d4df272d2d16edfda80fdf57e44f72b9e52.
=> Revert "config/k8s: add set -e to build jobs"

config/core/build-configs-chromeos.yaml
Update and add to build variants Kernel 6.1 as it is new LTS, and possible target for future uprevs.
=> CHROMEOS build-configs-chromeos.yaml: Add Kernel 6.1 builds

kernelci/config/base.py, kernelci/config/build.py, kernelci/config/db.py, kernelci/config/lab.py, kernelci/config/rootfs.py, kernelci/config/storage.py, kernelci/config/test.py, tests/configs/file-system-types.yaml, tests/configs/trees.yaml, tests/test_configs.py
Add test cases using `unittest` for loading, dumping and loading again the configuration to check the generated YAML is correct.  Also start using `yaml.YAMLObject` as a base class for the `Tree` and `RootFSType` objects to make the standard code dump them automatically with `yaml.dump()`.
=> config: add tests and use yaml.YAMLObject

config/docker/clang-16.jinja2
Signed-off-by: Vince Hillier <vince@revenni.com>
=> llvm-toolchain-bullseye doesn't contain clang-16 anymore

config/core/build-configs.yaml
Mediatek and Rockchip emit a lot of error messages about missing firmware even on baseline job, which might affect tests not only by fact of missing firmware, but also repeating messages disrupting LAVA console. As firmware is relative small we can add it directly to Chromebook kernels.
Fixes: https://github.com/kernelci/kernelci-core/issues/1652
=> build-configs.yaml: Add missing firmware for Mediatek and Rockchip

config/core/build-configs.yaml
In-kernel built GRE (enabled by bpf tests) enables gretap0 and erspan0 interfaces that will interfere with NFS mounting process.
```
[   85.853957] IP-Config: Retrying forever (NFS root)...
[   85.859646] 8021q: adding VLAN 0 to HW filter on device bond0
[   85.865790] IP-Config: Failed to open gretap0
[   85.870388] IP-Config: Failed to open erspan0
[   85.893370] Sending DHCP requests ...... timed out!
[  174.558388] IP-Config: Retrying forever (NFS root)...
[  174.563981] 8021q: adding VLAN 0 to HW filter on device bond0
[  174.570159] IP-Config: Failed to open gretap0
[  174.574766] IP-Config: Failed to open erspan0
[  174.597406] Sending DHCP requests ...... timed out!
[  256.873757] IP-Config: Retrying forever (NFS root)...
[  256.879563] 8021q: adding VLAN 0 to HW filter on device …
```
=> build-configs.yaml: Remove GRE as it interferes with nfs boot

kernelci/config/base.py, kernelci/config/build.py, tests/configs/build-environments.yaml, tests/configs/builds.yaml, tests/configs/fragments.yaml, tests/test_configs.py
Rework all the build configuration classes to be based on `YAMLConfigObject` and update tests accordingly to cover all the YAML dump and reload for the build configs using sample files.
=> Rework all build config and test YAML dump / reload

kernelci/build.py
When doing incremental builds, the firmware-files output directory is still present from the previous build which results in mkdir to fail. To take this use-case into account, which is required for manual builds and the automated bisection, always delete any firmware-files output directory first.
Fixes: 71fca1277c1d ("build.py: Add proper handling for linux-firmware by copy-firmware.sh")
=> kernelci.build: fix mkdir firmware-files

config/core/test-configs.yaml
Current RISCV qemu have only one cpu, so let's add a variant with more CPU.
=> test-configs: qemu-riscv: add a SMP variant

kci_build, kernelci/build.py, kernelci/config/build.py, tests/test_configs.py
Drop the kernelci.config.build.BuildEnvironment.arch_params
property which was returning a shallow copy of the _arch_params
dictionary.  This caused some misleading use-cases as the
property could appear mutable while it wasn't.  For example,
benv.arch_params.update({...})  would not actually change the
data stored in build_env.
As there already were methods for retrieving the arch_params
data, refactor these methods to be more generic with
.get_arch_param() to directly return any parameter for a given
architecture.  If the parameter is a dictionary, a copy is
returned to still ensure this is a read-only operation.
Update the .to_yaml() implementation accordingly by reading the
internal _arch_params as well as the unit tests.
=> BuildEnvironment: drop arch_params property

config/core/lab-configs.yaml
lab-baylibre is having large queues of jobs that don't finish in time for (useful) KernelCI results.  Let's attempt to reduce the load on teh lab by limiting the number of trees that are tested in lab-baylibre.  To be expanded later after reevaluating lab load.
=> lab-configs: lab-baylibre: use passlist

config/core/test-configs.yaml
The QDF2400 is rather slow to boot, taking about 5 minutes to run even a baseline test, meaning that when exposed to the full set of trees we end up spending most of our time running boot tests. Constrain the set of trees covered to just mainline and -next where it's most interesting, allowing us to use it for broader coverage of test cases. The device has a unique microarchitecture but is not widely deployed, though we do have few ACPI machines which is unfortunate.
While we're at it drop the filters for v3.x (that's not really relevant any more) and for defconfig (which passes a lot of defconfig+X anyway).
=> test-configs.yaml: Only test mainline and -next on QDF2400

config/core/build-configs-android.yaml
Add new Android tree as requested, and remove old tree (also as suggest in maillist),
as we are reaching peak capacity on large builds.
Reference: https://groups.io/g/kernelci/topic/please_add_android14_6_1/95717503
Fixes https://github.com/kernelci/kernelci-core/issues/1659
=> build-configs.yaml: Add android14-6.1

config/core/build-configs-chromeos.yaml
Kernel 5.10 is no more relevant for ChromeOS testing, remove it from configuration files.
=> CHROMEOS build-configs-chromeos.yaml: Remove 5.10 from ChromeOS tests

config/core/rootfs-configs-chromeos.yaml, config/rootfs/chromiumos/cros-snapshot-release-R106-15054.B.xml, config/rootfs/chromiumos/scripts/build_board.sh
This adds initial ChromiumOS image build support for MTK boards.
The manifest is updated to point to some dev branches on gitlab which contain downstream fixes or features we need be pushed upstream to ChromiumOS. Links below.
Besides upstreaming the ChromiumOS changes, future work may involve figuring out a way to pass the `cros://` config fragments (downloaded by the kernelci-core kernel builds) to the SDK, because right now we're just storing them in the kernel branch defconfig. Maybe the SDK bulids could be extended to download the `cros://` configs itself.
The kernel" currently bundled inside the MTK images is v6.2-rc6 which contains good upstream support with some backports. In the future we should upgrade it as well, dropping the upstreamed patches.
In particular the minigbm hack …
=> Add mediatek image builds

config/core/build-configs.yaml
As testing shows, Qualcomm GPU doesn't work properly when OCMEM is compiled as module.
Fixes https://github.com/kernelci/kernelci-core/issues/1696
=> build-configs.yaml: Compile-in OCMEM in kernel

config/core/build-configs.yaml
As we have some configs with this fragment without defconfig, we need to add NFS options, so kernel configuration can pass baseline-nfs tests.
=> build-configs.yaml: Add NFS options to arm64-chromebook

config/core/build-configs.yaml
As TPM reset and several other features that require NVRAM offset lookups - we need to enable newly added option for acpi tables exported on Chromebooks. It will allow to lookup for NVRAM offset to manage such things like TPM ownership.
=> build-configs.yaml: Enable chromeos_acpi support

.github/workflows/main.yml, config/core/api-configs.yaml, config/runtime/base/python.jinja2, kernelci/config/__init__.py, kernelci/config/api.py, kernelci/db/kernelci_api.py, tests/configs/api-configs.yaml, tests/test_configs.py
Add kernelci.config.api to load the YAML configuration required to access a KernelCI API instance.  This is intended to replace the config.db which was about providing an abstraction layer for various API and backend / database implementations.
=> Add kernelci.config.api

config/core/test-configs.yaml
With the increased number of trees and increased activity in some of those trees we aren't getting anywhere near being able to run the tests we currently schedule on Pine64+ in the labs we have.  Tune down the number of tests to help us get through the tests reliably and promptly.
=> test-configs.yaml: Tune down the number of tests run on Pine64+

config/docker/fragment/kselftest.jinja2
Add liburing-dev to the list of libraries installed by the kselftest
fragment.  This is required in particular for the vm tests, to fix
this build warning:
Warning: missing liburing support. Some COW tests will be skipped.
=>     config/docker: add liburing to kselftest fragment

config/core/test-configs-chromeos.yaml
As Mediatek upstream efforts significantly improved kernel support of relevant platforms, it will be great to test upstream kernels with ChromeOS rootfs.
This patch add mt8183 based kukui-jacuzzi-juniper Chromebook.
=> CHROMEOS test-configs-chromeos.yaml: Add new Mediatek Chromebook jacuzzi

config/core/test-configs.yaml
Due to increased numbers of trees and activity in some of those trees we are not managing to get through the tests we currently schedule on Juno. Tune down the number of tests to try to ensure we get through things promptly and reliably.
=> test-configs.yaml: Tune down number of tests run on Juno

config/core/test-configs.yaml
Due to an increase in the number of commits tested, due to increasing numbers of trees and activity in some of the larger ones like stable, we are not managing to get through all the scheduled jobs on the UDOO boards.  Trim the list of tests scheduled on these boards to just those that exercise hardware and features specific to them.
=> test-configs.yaml: Tune down number of tests run on i.MX UDOO boards

config/core/test-configs.yaml
Though looking at the code it was supported at time of release the stable kernels have been failing to boot on these boards for quite some time (since April 2022 for v4.14 in my lab for example), and testing with the initial releases from Linus and a GCC 8 toolchain I'm getting no output on boot so there's no obvious prospect of bisecting.
Given the length of time that things have been failing just stop scheduling tests, we can reenable if someone goes and fixes things but probably there are no users of these kernels on these boards who are keeping up to date with fixes any more.
=> test-configs.yaml: Don't run v4.x stables on Le Potato

kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/node.py
Add an initial sub-command `kci node` with the following syntax:
```
kci node get <ID>
kci node find attr1=value attr2=value
kci node count attr1=value attr2=value
```
Sample `kernelci.conf`:
```ini
[DEFAULT]
verbose: True
api_config: docker-host
[api:docker-host]
api_token: <secret token here>
[node]
```
For example:
```
kernelci@015bba541c79:~/kernelci-core$ ./kci node get 6374b725e778513908e04384 --indent='  '
{
"_id": "6374b725e778513908e04384",
"kind": "node",
"name": "checkout",
"path": [
"checkout"
],
"group": null,
"revision": {
"tree": "mainline",
"url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git",
"branch": "master",
"commit": "59d0d52c30d4991ac4b329f049cc37118e00f5b0",
"describe": null,
"version": null
},
"parent": null,
"state": "done",
"result": null, …
```
=> Add kci node sub-command

.github/workflows/main.yml, Makefile
Clean up the Makefile and move checks from the GitHub workflow `main.yaml` config to the Makefile to make it easier to run them by hand and in a reproducible way.
=> Makefile cleanup

config/core/build-configs-stable.yaml
As Linux 6.1 declared as LTS, we need to add testing for stable trees, rc-queues and such, similar to other LTS kernels.
=> build-configs-stable.yaml: Add Linux 6.1 LTS stable trees testing

kernelci/db/kernelci_api.py
Add an enum class for holding pending Node states. 
Add instance variable`_pending_node_states` to `KernelCI_API` class store enum for pending node states.
Implement method `get_pending_node_states` to get pending node states to use in pipeline client services.
This is to align the node states with API until we have a mechanism to get the states from API in place.
=> T39494 kernelci_api: Add enum class for node states

config/core/test-configs-chromeos.yaml
This commit adds support for testing the Chromebook mt8192-asurada-spherion-r0 device using the Tast.
This Mediatek support added just recently, and it is mostly WIP, so it will be very useful to track for possible regressions.
=> CHROMEOS test-configs-chromeos.yaml: Add Chromebook mt8192-asurada-spherion-r0

config/rootfs/chromiumos/scripts/build_board.sh
This commit introduces a patch that allows for the extraction of CR50 firmware, enabling it to be flashed separately. Prior to this patch, ChromeOS would attempt to reflash the CR50 during rootfs installation, which required manual intervention to powercycle the device. By extracting the firmware and making it a separate step, we can now plan for proper testing by Labs personnel.
=> CHROMEOS build_board.sh: Extract and move CR50 firmware during build

.github/workflows/main.yml
Tweak how linter annotations are run to only cover with pylint the *.py files and kci, and only add pycodestyle annotations to the kci_* and scripts/kci-* tools.
Tested with #1749
=> workflows: run pycodestyle on standalone scripts

kci_test, kernelci/runtime/__init__.py, kernelci/runtime/kubernetes.py, kernelci/runtime/lava/__init__.py, kernelci/runtime/lava/lava_rest.py, kernelci/runtime/lava/lava_xmlrpc.py, kernelci/runtime/shell.py, setup.py, tests/test_runtime.py
Rename the `kernelci.lab` package as `kernelci.runtime` and update all areas of the code accordingly.  Add an extra unit test to check all the runtime types can be initialised.
=> Rename kernelci.lab as kernelci.runtime

kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/node.py, kernelci/cli/user.py, kernelci/db/kernelci_api.py
Add an initial implementation of the `kci user` tool with a command to get the current user's data.  For example:
```
kernelci@e4625cc550a0:~/core$ ./kci user me --indent='  ' --api-config=docker-host
{
"_id": "62d91818f79fc24661556e46",
"username": "admin",
"hashed_password": "$2b$12$MZnf5VmvFKikPbpJ9ePTO.AJUh9DbLg/ypr.k6eWslK14.e8r55sq",
"active": true,
"is_admin": true
}
```
Also introduce a new base class `APICommand` for running commands that interact with the API.
=> Initial `kci user` tool and `APICommand` base class

config/core/build-configs-chromeos.yaml
Add build using the for-kernelci branch of Collabora's chromeos-kernel tree. This branch is used to integrate patches for MediaTek based Chromebooks.
=> CHROMEOS build-configs-chromeos.yaml: Add collabora-chromeos-kernel

config/core/rootfs-configs.yaml, config/core/rootfs-images.yaml, config/core/test-configs.yaml
Add a rootfs to run kselftest on Debian bookworm, and update the kselftest-alsa test plan to use it instead. Bookworm is needed since it includes more recent versions of the alsa-ucm-conf, libasound2 and alsa-utils packages than the ones available in bullseye, allowing us to access UCM files for more recent platforms. In the end this allows more thorough testing of audio on these machines and better scores.
I created [a bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029272) on libasound2 to see if a backport to stable was possible, but since I haven't heard back from the maintainer in a while, let's get this going with debian testing. If the packages are ever backported we can switch to those then.
=> Add and use bookworm rootfs for kselftest-alsa

Makefile, kernelci/api/__init__.py, kernelci/cli/base.py, setup.py
As an intermediate step before having a new `API` class with API bindings, add the `kernelci.api` package with a loader to dynamically import the matching module.  Right now the module is hard-coded but it will become useful when supporting different API versions.
This also decouples the Python dependencies needed for the API with the command line tools e.g. `cloudevents` is now only imported when an API object is needed (this particular Python package is not in Debian so it's particularly inconvenient).
=> Add `kernelci.api` to load the existing API module

config/core/test-configs.yaml, config/lava/v4l2-decoder-conformance/v4l2-decoder-conformance.jinja2, config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py, config/rootfs/debos/scripts/bullseye-gst-fluster.sh
Reduce the size of the GStreamer build in the `bullseye-gst-fluster` rootfs, by disabling non essential components for V4L2 decoder tests. Enable also the `videocodectestsink` element through the additional `debugutils` plugin, which improves the performance of fluster tests.
With this GStreamer configuration, the score for VP9 tests on `rk3399-gru-kevin` improves from 169/305 to 228/305.
Add extra arguments in the decoder test job definition to specify the number of decoding parallel jobs and the decoder to be ran.
=> Refine GStreamer config and job definition args for V4L2 decoder tests

config/core/build-configs-cip.yaml
Also add Riscv configuration for 5.10.y-cip
=> build-configs-cip: Use cip-kernel-configs for kernels (5.10.y-cip, 4.4.y-cip)

kci_bisect, kci_build, kci_data, kci_rootfs, kci_test, kernelci/cli/base.py, kernelci/config/__init__.py
Allow `yaml_config` and `extra_configs` to be defined in the settings file and consolidate the code to have only one path for loading the configuration.
=> Consolidate YAML config file arguments

Makefile, setup.py
Fix all pycodestyle and pylint errors in setup.py and enable them in the Makefile.
=> setup.py: fix coding style and pylint errors

kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/job.py
Add a `kci job` command to run jobs with the new API.  Sample commands:
```
kci job register --input-node-id=<checkout node id> --plan=kver --id-only
kci job generate --runtime-config=shell --platform-config=shell --node-id=<job node id>
kci job submit --runtime-config=shell job/kver
```
Fixes #1728 
Depends on #1773
=> Add `kci job` command

config/core/test-configs.yaml
arm64 debug configurations are starting to get rather large and run into
problems booting with the default memory allocation of 512m, especially in
UEFI configurations. Increase the amount of memory guests are given to a
gigabyte to avoid these issues.
=> test-configs.yaml: Raise memory allocation for arm64 qemu

config/core/rootfs-configs.yaml
Some of the LTP tests (eg, syscalls) can use the NTFS and VFAT utilities to expand coverage so add them to the LTP rootfs.  They are fairly small.
=> rootfs-configs.yaml: Add more userspace filesystem utilities for LTP

config/core/test-configs.yaml
Add IGT KMS test plan for MediaTek and enable on MediaTek Chromebooks: Hana, Juniper and Spherion. Even though all three use the same DRM driver (mediatek), each one has a different display pipeline, so it's worth testing on all of them.
Hana (MT8173 Elm based) uses a PS8640 DSI-eDP bridge. Spherion (MT8192 Asurada based) and Juniper (MT8183 Kukui Jacuzzi based) both use the ANX7625 DSI-DP bridge, but they use different eDP panels: Spherion has IVO 0x075d; Juniper has AUO 0x145c.
=> Add and run igt-kms-mediatek on MediaTek Chromebooks

config/core/test-configs-chromeos.yaml
For last 2 releases QEMU is broken for ChromeOS, and it doesn't look there is easy solution to fix that.
I am commenting temporary all relevant entries with hope, that in new releases it might work or issue might be fixed. Also commenting is important to not waste lab QEMU resources and docker pull limits.
=> CHROMEOS test-configs-chromeos.yaml: Disable QEMU

config/core/rootfs-configs-chromeos.yaml, config/rootfs/debos/scripts/bullseye-cros-flash.sh
Add gsctool build script to enable CR50 flashing over TPM device.
=> CHROMEOS rootfs-configs-chromeos.yaml: Add bullseye-cros-flash.sh to bullseye-cros-flash

config/rootfs/debos/scripts/bullseye-cros-ec-tests.sh
This repo has been moved to the KernelCI github project.
Signed-off-by: Ricardo Cañuelo <ricardo.canuelo@collabora.com>
=> rootfs/debos/scripts: update cros-ec-tests upstream repo

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/__init__.py, kernelci/cli/api.py, kernelci/cli/base.py, kernelci/cli/job.py, kernelci/cli/user.py
Add an initial `kernelci.api.API` base abstract class with an implementation for the `latest` version.  Also update some `kci` command line tools to use the API by hand.
Depends on https://github.com/kernelci/kernelci-api/pull/224
=> Initial kernelci.api.API base abstract class

config/core/rootfs-configs.yaml
With the pending addition of AT91SAM9G20-EK which is ARMv5 based we need
an armel build of kselftest in order to allow us to run kselftests on
that platform.
=> rootfs-configs: Enable armel kselftest builds

kernelci/cli/api.py, kernelci/cli/base.py, kernelci/cli/job.py, kernelci/cli/node.py, kernelci/cli/user.py
Add a `catch_http_error` decorator and use it in a new method `APICommand._api_call()`.  Update all the command line tools that use the API to use this and improve error reporting.
=> Add decorator to catch HTTP errors in command line tools

.github/workflows/main.yml, Makefile, kernelci/config/base.py, requirements-dev.txt
Add a check to run `mypy` on the `kernelci.api` modules and enable GitHub annotations on all `.py` files.
=> Enable `mypy` to run on `kernelci.api` modules

requirements.txt, setup.py
Upgrade Cloudevents to 1.9.0 in order to pass `mypy` checks.  Also upgrade the minimum Python version from 3.6 to 3.7 as 3.6 is end-of-life and not supported by recent packages such as Cloudevents.
=> Upgrade to Cloudevents 1.9.0 and Python 3.7

kernelci/storage/ssh.py, requirements.txt, setup.py
Storage_ssh class implementation relied on scp binary being installed in the operating system. Implementation based on paramiko and scp Python packages reduces the dependency on underlying system tools and adds better control of the file transfer.
Replaces #1594 (rebased with new `file_paths` 2-tuple argument and destination directory)
=> kernelci.storage.ssh: Replace scp binary calls with paramiko

config/core/rootfs-configs-chromeos.yaml, config/rootfs/chromiumos/cros-snapshot-release-R100-14526.B.xml, config/rootfs/chromiumos/cros-snapshot-release-R102-14695.B.xml, config/rootfs/chromiumos/cros-snapshot-release-R106-15054.B.xml, config/rootfs/chromiumos/scripts/build_board.sh, config/rootfs/chromiumos/scripts/create_manifest.py, config/rootfs/debos/scripts/bullseye-cros-flash.sh
This PR contains commits related to Chrome OS  rootfs images definitions and build tools.
They have been cherry-picked from the `chromeos` branch as a part of the upstreaming process.
They need to be thoroughly tested to make sure nothing has been missed.
=> Move chromeos rootfs related commits from chromeos branch to main

config/runtime/base/python.jinja2
Update the base Python template to use the new kernelci.api package rather than the kernelci.db.kernelci_api module which is now deprecated.
=> config/runtime: use kernelci.api in base Python template

config/runtime/base/kubernetes.jinja2
As these jobs are "batch" jobs, disable automatic restarts and add options to automatically delete the jobs when they're done after a short period of time.  This is still useful to manually inspect logs when some jobs fail.
=> config/runtime: set restartPolicy to Never

kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/node.py, kernelci/cli/show.py
Add "kci show results" to show results from a node and recursively all its child nodes hierarchy in a human-readable way.
=> kernelci.cli.show: add command to show results

kernelci/cli/__init__.py, kernelci/cli/docker.py, requirements.txt
Fixes https://github.com/kernelci/kernelci-core/issues/1770
Add a command line utility `kci docker` from `config.docker.kci_docker` script.
The tool will be used in the same way as `kci_docker` script to generate Dockerfiles from Jinja2 templates and build images. It has `name`, `generate`, and `build` as sub-commands.
The script has been reworked to add base command classes to incorporate common arguments and methods for sub-commands.
Also, fixed some `pylint` errors by adding module and function docstrings.
Improved `fragment` option.
=> T41052 Convert kci_docker into a kci docker command

config/runtime/base/kubernetes.jinja2, config/runtime/base/python.jinja2, kernelci/cli/job.py, kernelci/runtime/__init__.py
Add the ability to provide a storage configuration in the job templates so that job definitions can upload files to storage.
=> Make storage YAML config available in job templates

tests/test_api.py
Add an initial basic unit test for the API bindings.  This simply creates API and APIHelper objects for each configuration in the sample api-configs.yaml to check the objects can be initialised correctly.
=> tests: add API bindings unit tests

config/runtime/base/python.jinja2
Move the call to job.submit() in python.jinja2 inside the top-level try-except block to catch any exceptions while submitting results. This is to avoid getting failing jobs stuck in a restart loop in Kubernetes.
Some fine-tuning could be done later if legitimate infrastructure errors can be separated from bugs to benefit from restarts.  Maybe this could be a staging vs production policy choice.
=> config/runtime: move job.submit() in try-except block

config/runtime/base/kubernetes-python.jinja2, config/runtime/base/python.jinja2
This PR fixes a couple of loose ends in `python.jinja2`:
* fix order of imports to pass pylint checks (system, third-party, local)
* always return 0 with Kubernetes jobs to avoid restarts when test cases failed
=> Small fixes in `python.jinja2`

kernelci/api/helper.py
Fix how APIHelper.submit_results() is updating the root node by only updating the appropriate fields.  The flat copy used to overwrite artifacts and created time etc.
=> kernelci.api.helper: fix submit_results()

config/docker/fragment/kunit.jinja2
Install minimal QEMU packages to run KUnit on x86.  This is useful as an alternative to UML, but adding all the architectures shouldn't be necessary as KUnit tests aren't supposed to depend on a real CPU architecture.
=> config/docker: kunit: install QEMU for x86

config/rootfs/chromiumos/scripts/build_board.sh
In case of newest kernels built for cherry, as in PR #1832 we need a bit different wildcard pattern to extract dtb. This commit was tested by hand on cherry and asurada targets
=> build_board.sh: Improve DTB copy wildcard pattern

kernelci/cli/api.py, kernelci/cli/base.py, kernelci/cli/base_api.py, kernelci/cli/job.py, kernelci/cli/node.py, kernelci/cli/pubsub.py, kernelci/cli/show.py, kernelci/cli/user.py
Move APICommand to a new module kernelci.cli.base_api so that dependencies such as cloudevents aren't imported in kernelci.cli.base. This allows commands that don't use the API to be run without having cloudevents (or other API-specific dependencies) installed and limits the base module to only common base code for all the commands.
Update all the related tools using APICommand accordingly.
=> kernelci.cli: add .base_api module for APICommand

config/docker/README.md
Since the `kci_docker` script has been converted to `kci docker` command line tool, update the documentation to modify all the sample commands and related instructions.
The commands are modified based on latest changes to update `fragments` option to be positional argument.
Also, added `--prefix` argument to commands as the default value of the flag has been discarded in the tool.
Also, fix a minor typo  in `Docker images and tag names` section.
=> T41623 config/docker/README.md: update documentation for `kci docker`

config/rootfs/chromiumos/scripts/build_board.sh
Disable `builtin_fw_mali_g57` flag as the firmware is not required when `panfrost` is enabled.
=> T41021 build_board: disable mali-G57 workaround firmware

config/core/rootfs-configs-chromeos.yaml
As we have ChromiumOS ARM64 Chromebooks, we need "flasher" image for them too.
=> CHROMEOS rootfs-configs-chromeos.yaml: Add arm64 to bullseye-cros-flash

Makefile, kernelci/cli/config.py, kernelci/cli/job.py, kernelci/config/__init__.py, kernelci/config/job.py, kernelci/runtime/__init__.py, kernelci/runtime/docker.py, kernelci/runtime/kubernetes.py, kernelci/runtime/shell.py, tests/configs/jobs.yaml, tests/test_configs.py
This is a first step to move away from build and test configurations and start using a new common job definition.  Update `kci job` accordingly.
=> Add initial `Job` config class and rework `Runtime` accordingly

config/core/test-configs.yaml
Minimal support for mt8365-evk board has recently landed upstream.  Add to KernelCI.
=> test-configs: add mt8365-evk board

config/core/test-configs.yaml
Add 3 TI K3 boards, all supported upstream in mainline and availabe in lab-baylibre.
- k3-am625-sk
- k3-j721e-sk
- k3-j721e-beagleboneai64
For now, just enable baseline.
=> test-configs: add TI K3 boards

config/docker/rustc-1.62-x86.jinja2, config/docker/rustc-1.66-x86.jinja2
As we have now docker image template with arch, such as: compiler:arch-fragments...
We need to add also template for rustc arch, x86 at moment.
=> rustc-1.6*-x86.jinja2: Add arch specific templates

config/lava/kselftest/kselftest.jinja2
Currently we are using the LKFT skipfile for kselftest however this is
not ideal since it contains a lot of bitrotten entries for tests that
now run correctly (eg, the recently removed skip for the futex tests)
and masks any changes in state for the listed tests.  Since the
test-defintions integration will try to insert defaults if we don't
supply anything at all use /dev/null as the default test list, providing
an empty skiplist.
This also means we don't need to worry about getting skipgen installed
on the targets and running it which speeds things up ever so slightly.
If we need to skip tests we should probably maintain our own lists.
=> config/lava/kselftest: Don't use a skipfile

config/runtime/base/python.jinja2
Catch HTTPError exceptions in the base python.jinja2 template to show errors with details from the API.  This typically contain extra information about why the data was not valid, as provided by Pydantic.
=> config/runtime: base: catch HTTPError in python.jinja2

kernelci/config/runtime.py, kernelci/runtime/docker.py
Add a `timeout` parameter for the docker runtime which specifies a timeout for the Docker API.  If not set, the client will be using the SDK's default which is typically 60s.
Update kernelci.runtime.docker accordingly to use it.
=> kernelci.config.runtime: add Docker API timeout

kci_test, kernelci/legacy/lava/__init__.py, kernelci/runtime/__init__.py, kernelci/runtime/kubernetes.py, tests/test_runtime.py
Remove unused code from the base `kernelci.runtime.Runtime` now that we have `shell`, `docker` and `kubernetes` runtimes implemented.
=> Clean up the `Runtime` base class

config/rootfs/chromiumos/scripts/generate_cros_manifest.sh
To create new version manifest we need to fetch it a bit unusual way using ChromiumOS SDK.
We had it as comments in build_board.sh, but this create more complexity, so it is better to make proper script to automate this process.
=> generate_cros_manifest.sh: Add tool to generate ChromiumOS xml manifest

kci_test, kernelci/legacy/lava/__init__.py, kernelci/test.py
Right now some test names might exceed LAVA name limit and as result overwrite each other definition filenames.
We need to handle it properly:
1)Better to fail on generation, than silently overwrite
2)Try to shorten some keywords, when it is possible
=> Handle file collision better in case of very long test names

kernelci/config/runtime.py, tests/configs/lava-runtimes.yaml, tests/configs/runtimes.yaml, tests/test_configs.py, tests/test_runtime.py
Convert the Runtime configuration to proper YAML objects so they can be dumped back to plain YAML.  Update unit tests accordingly with a separate config file for LAVA with checks for the lab priorities.
=> kernelci.config.runtime: convert to proper YAML objects

config/core/test-configs.yaml
The ethernet works fine on these boards so we can cover NFS.
=> test-configs.yaml: Cover NFS boots on Raspberry Pi 1B

tests/api/conftest.py
Append child node name to `Node.path` field in `APIHelperTestData.update_kunit_child_node` just like `APIHelper._prepare_results` method that generates various fields for child nodes.
=> T41723 tests/api: fix child node `path` field

config/core/test-configs.yaml
This board has not been booting successfully in KernelCI for a long time, and the SoC support was removed upstream for v6.4[1], so let's just drop this board that nobody cares about anymore.
[1] https://lore.kernel.org/r/20230331-topic-oxnas-upstream-remove-v2-0-e51078376f08@linaro.org
=> test-configs: remove oxnas board

config/core/test-configs.yaml
Add the Radxa Rock 5b board, based on the Rockchip RK3588 SoC. This board is available in the collabora staging lab at the moment and should soon be available in the collabora production lab as well. Mainline suppot is minimal at the moment, specficially no networking yet, thus starting with just baseline for now.
=> test-configs: Add Radxa Rock 5b board

config/core/test-configs.yaml
The selftests previously known as vm have been renamed upstream to mm.
Update our configurations to reflect this, leaving the old vm name in place
so that runs on older kernels from before the rename continue to happen and
using filters to avoid scheduling each on the kernels where they don't
exist.
=> test-configs.yaml: Update for vm selftests rename to mm

kernelci/api/__init__.py, kernelci/api/helper.py, kernelci/api/latest.py, tests/api/conftest.py, tests/api/test_api.py
Now the API will send responses with field names and not with alias, update `Node._id` to `Node.id` in kernelci API module.
Update unit tests for `APIHelper` class according to the latest change for `Node._id` field in `kernelci.api` module.
=> T41945 kernelci.api: update `Node._id` field

kernelci/cli/base_api.py, kernelci/cli/node.py, kernelci/cli/show.py, kernelci/runtime/__init__.py
Now the API will send responses with field names and not with alias, update `Node._id` to `Node.id` in `kernelci.cli` and `kernelci.runtime` module.
This was breaking `runner` service.
=> T41945 Update Node._id in `kernelci.cli` and `kernelci.runtime` module

kernelci/cli/job.py, kernelci/runtime/__init__.py, kernelci/runtime/docker.py, kernelci/runtime/kubernetes.py, kernelci/runtime/shell.py
Add a `Runtime.wait()` abstract method with implementations for `shell`, `docker` and `kubernetes` to wait for a given job to complete and get the exit status code.  Use it with `kci job submit --wait`.
=> Add `Runtime.wait()` method and use it with `kci job submit --wait`

kernelci/cli/pubsub.py
Add a `kci pubsub send_event --json` argument to parse the event input as JSON from stdin.  Otherwise it's simply read as a plain string.
=> kernelci.cli: pubsub: add --json to parse JSON input

config/rootfs/debos/scripts/bullseye-v4l2.sh
Starting with commit c252c887c4e3 ("Drop autoconf/automake support"), the v4l-utils project has dropped support for autoconf in favor of the meson build system. Update the script to use meson.
=> bullseye-v4l2.sh: Move from autoconf to meson for v4l-utils

config/core/build-configs.yaml, config/docker/rustc-1.68-x86.jinja2, config/docker/rustc-1.68.jinja2
Rust 1.68.2 will be the next version supported by the kernel, already submitted to the LKML.
Furthermore, I would like to start tracking the latest version, please see the commit message at [2] and a previous discussion at [3].
Therefore, add `rustc-1.68` as a new build environment.
Link: https://lore.kernel.org/rust-for-linux/20230418214347.324156-1-ojeda@kernel.org/ [1]
Link: https://lore.kernel.org/all/20230418214347.324156-4-ojeda@kernel.org/ [2]
Link: https://lore.kernel.org/rust-for-linux/CANiq72mT3bVDKdHgaea-6WiZazd8Mvurqmqegbe5JZxVyLR8Yg@mail.gmail.com/ [3]
=> config: add `rustc-1.68` build environment

.github/workflows/main.yml
With the current settings the github action checks will only run for either pushes or pull requests to main/chromeos branches. This can be annoying when working on a personal branch as the actions (linters, sanity checks) aren't run until a PR is created.
The current actions are quite quick (less then one minute) so it shouldn't be a problem to simply always run them.
=> github: Always run actions for push/pull_requests

config/docker/cros-tast.jinja2, config/docker/data/tast_test_list.py
Copy the script responsible for getting the list of tast tests available on the current build to the docker image used by cros.
After discussing with @mgalka we decided to make this script available on the public repository of the Kernel CI project because we had a problem sharing the file with the LAVA, once it was available in a Gitlab repository with limited access by the members. Other pros involve installing a dependency on the image and making it available; it will also avoid blocking a LAVA device when installing pip and requests library, which is a requirement for the script. 
I did not apply the changes on the `old-docker`. I assumed it is something deprecated on some level, but let me know if I am wrong.
=> CHROMEOS docker/data add tast_test_list script

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-kselftest.sh
The releases for alsa-ucm-conf are sparse. Instead of relying on the alsa-ucm-conf debian package, fetch the UCM directly from the main branch in the git repository to avoid having to wait for releases. This will allow us to start testing audio on machines using alsa-kselftest as soon as the machine's UCM is merged upstream.
It's worth pointing out that this is fetching the latest UCM files from git while still using the latest tagged release for alsa-lib and alsa-utils. It is possible that a UCM could be updated to rely on functionality from the latest alsa-lib, causing a regression for the machines that use that UCM, which would only be fixed when a new alsa-lib version gets released and packaged. A way around this would be to also build alsa-lib and alsa-utils from source. But since …
=> rootfs-configs.yaml: Fetch ALSA UCM files from git

config/core/test-configs.yaml
After manually parsing logs i noticed on several devices: "acpi-cpufreq: probe of acpi-cpufreq failed with error -17" It will be useful to watch more closely if this subsystem works properly on all devices.
I am adding this test on devices that are 5 or more in lab.
=> test-configs.yaml: Add kselftest-cpufreq to devices

tests/api/test_api.py
Add test for `APIHelper._prepare_results` method that used to prepare hierarchy of test results.
=> T41723 tests/api/test_api: implement `test_prepare_results`

config/core/build-configs-chromeos.yaml, config/core/build-configs.yaml
This PR adds the needed kernel config and patches to get ChromeOS working and the tast tests passing on mt8192-asurada-spherion running 6.1.
This is the list of backported patches (all of them are merged upstream, except for the last one, which should be merged soon):
* [MT8192 Asurada devicetree - Part 2](https://lore.kernel.org/all/20221102190611.283546-1-nfraprado@collabora.com/#r)
* [soc: mediatek: Introduce mediatek-regulator-coupler driver](https://lore.kernel.org/all/20221006115816.66853-1-angelogioacchino.delregno@collabora.com/#r)
* [MTK: Undesired set_rate on main PLLs and GPU DVFS](https://lore.kernel.org/all/20221024102307.33722-1-angelogioacchino.delregno@collabora.com/#r)
* [arm64: dts: mt8186: Add power domains controller](https://lore.kernel.org/all/20221123135531.23221-3-a …
=> CHROMEOS MT8192-asurada-spherion passing tast on 6.1

kernelci/cli/config.py
Add 'runtimes' and 'api_configs' to the list of YAML configs to validate.
=> kernelci.cli: config: validate runtimes and api configs

kernelci/cli/config.py
Add a "kci config list" command to dump all the entries in a given section of the YAML configuration.  This has a few advantages over the raw YAML: it should be easier to read, anchors are expanded and the entries are loaded from all the YAML config files found.
=> kernelci.cli: config: add "list" command to list entries

kernelci/config/__init__.py
Config entries that are a list of strings can be sorted, but lists of dicts can't.  Skip the alphabetical order check for those (e.g. the scheduler configs).
Fixes: 7e936c9672b5 ("kernelci.config: add validate_yaml() method")
=> kernelci.config: fix validate_yaml() for list of dicts

config/docker/cros-tast.jinja2
If gsutil already latest version it will return on exit(1), and will break Docker building recipe.
We add || true to not fail, if it is already latest version, or even if update failed, as it is not critical procedure.
=> CHROMEOS cros-tast.jinja2: Don't fail if gsutil already latest

config/core/build-configs.yaml
This moves both `rust-for-linux_rust-next` and `next`'s Rust variant.
As discussed [1], for this kind of upgrades, we will move KernelCI first and then I will apply push the branch. The run is expected to fail if it happens to run between those two moves.
Link: https://github.com/kernelci/kernelci-core/pull/1890#issuecomment-1515062402 [1]
=> build-configs.yaml: move `rust-next` to Rust 1.68

kernelci/runtime/__init__.py
Store the provided user and token as private class attributes so that derived classes can make use of it.
=> kernelci.runtime: add ._user and ._token

kernelci/legacy/lava/__init__.py, kernelci/runtime/__init__.py
Rework the code that registers Jinja2 custom functions directly into the Runtime class.  This is in preparation for handling LAVA job templates in particular.
=> Rework custom Jinja2 functions

kernelci/cli/job.py
Add the `kci job {generate,submit} --runtime-token` argument for runtimes that require a token to be passed on the command line (e.g. LAVA).  Some runtimes such as Kubernetes load their credentials from the environment instead.
=> kernelci.cli: job: add --runtime-token

config/runtime/base/python.jinja2, kernelci/runtime/__init__.py, kernelci/runtime/kubernetes.py
Rework the template parameters to directly pass objects rather than YAML dumps or just the node ID.  This relies on the `yaml_dump()` custom Jinja2 function added by #1918.  Update the `python.jinja2` base template accordingly to use the objects and reduce the number of parameters.
=> Runtime params rework

config/core/test-configs-chromeos.yaml
Update ChromeOS tast tests, as with version update some got removed, and some, similar, got added.
=> CHROMEOS test-configs-chromeos.yaml: Update tast test list for R111

config/core/test-configs-chromeos.yaml
Run Tast tests on MediaTek Chromebooks with the MediaTek integration branch (collabora-chromeos-kernel).
That branch already has in its own defconfig all configs needed to run on MediaTek chromebooks with a ChromeOS userspace, so neither the downstream config nor any fragment are needed. For that reason, add separate test_configs entries that filters only based on this tree.
=> CHROMEOS test-configs.yaml: Run tast on MediaTek with collabora branch

config/core/build-configs-stable.yaml
Even though it's not an LTS, I still think it's worth testing the latest stable releases and release candidates.
Note we missed adding v6.2.y testing.
=> build-configs-stable.yaml: Add Linux 6.3 stable trees

kernelci/api/helper.py, kernelci/cli/pubsub.py, tests/api/test_api.py
Add a `APIHelper.receive_event_data()` method to directly return the payload of the CloudEvent object.  Update unit tests accordingly and also use it in the `kci pubsub` implementation.
=> Add `APIHelper.receive_event_data()` method

config/rootfs/chromiumos/scripts/build_board.sh
This is patches to make ChromiumOS work for trogdor and grunt
=> CHROMEOS build_board.sh: Add trogdor and grunt R111 workarounds

kernelci/cli/base.py, kernelci/cli/sched.py, kernelci/runtime/__init__.py, kernelci/scheduler.py
Add `Options.get_from_section()` and `kernelci.runtime.get_all_runtimes()` to get all the Runtime objects even if they require some tokens to be constructed (e.g. LAVA labs).  The tokens can be loaded from the settings file without relying on `--runtime-config` since this doesn't apply when iterating through all the runtimes.
=> Add `runtimes.get_all_runtimes()` using tokens for the Scheduler

config/core/test-configs-chromeos.yaml
As images got fixed and rebuilt, we need to update download links
=> CHROMEOS test-configs-chromeos.yaml: Update download links for trogdor/grunt

config/core/test-configs.yaml
As kingoftown got different dtb name in new kernels, as mentioned in https://github.com/kernelci/kernelci-core/issues/1941 , one of ways to solve this issue to add one more device entry with base_name pointing to initial device name.
=> test-configs.yaml: Add one more device entry for different dtb file

config/core/build-configs.yaml, config/core/rootfs-configs.yaml
The qcom-venus driver is loaded quite early on in boot and requires the venus firmware. As the firmware binary is relatively small, build it into the Chromebooks kernel image to allow the video codecs driver to probe correctly on `trogdor` devices.
Remove the firmware binary from the `bullseye-v4l2` ramdisk/rootfs config.
=> Build qcom-venus firmware into kernel image

config/core/test-configs.yaml
The sigaltstack test is *tiny* so the time taken to boot a test platform is
going to dwarf the time taken to actually run the tests but it's relevant
to some development work I'm doing so let's add some test coverage for it.
Add the fragment for it and run it on two platforms in my lab.
=> test-configs.ymal: Add sigaltstack kselftest coverage

kernelci/runtime/lava.py
Add a LogParser class to handle the LAVA job log and get a plain text log with the output from the platform's serial console.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/214
=> kernelci.runtime: lava: add LAVA log parser

config/runtime/base/lava.jinja2
Add a metadata entry with the name of the storage config so that the callback handler can upload artifacts to storage (e.g. job logs).
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/214
=> config/runtime: lava: add storage_config_name metadata

kernelci/storage/__init__.py
Fix how urljoin is being used to produce the public URL for uploaded artifacts by using a relative path for the 2nd part of the URL. Otherwise, any trailing path after the hostname in the base URL would be discarded.
For example, when joining this base URL with this artifact file name:
http://storage.something.com/blah
node-1234/file.txt
the returned URL as-is would be:
http://storage.something.com/node-1234/file.txt
However, when using ./node-1234/file.txt, the returned value is now:
http://storage.something.com/blah/node-1234/file.txt
which is the expected one.
As a result, always add a leading '.' to the artifact file path when joining it with the base URL to get the full correct public URL.
Fixes: 670c867141c1 ("kernelci.storage: add base Storage interface class")
=> kernelci.storage: fix urljoin relative path

kernelci/cli/base.py
Add `Options._default_section` variable to read `DEFAULT` section from `.toml` file and update `Options.get` method accordingly.
=> kernelci.cli.base: optimize TOML file parsing

config/rootfs/chromiumos/scripts/build_board.sh
As tested this hack not required anymore as Google fixed corrupted git cache issue.
Fixes: e8c2b38d4ff3 ("build_board.sh: Add workaround for chrome-icu git cache corruption")
=> config/rootfs: build_board.sh: Remove hack for corrupted git cache

config/core/test-configs-chromeos.yaml
Enable V4L2 stateful decoder tast tests on `sc7180-trogdor-kingoftown` and `sc7180-trogdor-lazor-limozeen`.
=> Enable V4L2 decoder tast tests on trogdor Chromebooks

config/core/rootfs-configs-chromeos.yaml
Also merge the 2 commits to update the Chromium OS rootfs images to R111 and then R114 following the added snapshots.
=> Chromium OS: use R114 rootfs images

config/rootfs/debos/scripts/bullseye-cros-flash.sh
As we faced error while extracting CR50 archive, https://github.com/kernelci/kernelci-core/issues/1968, it is better to ignore modified time in tar archive.
=> bullseye-cros-flash.sh: Update repository for CR50 flashing tools

config/docker/base/host-tools.jinja2, config/docker/cros-baseline.jinja2, config/docker/cros-qemu-modules.jinja2, config/docker/cros-tast.jinja2, config/docker/gcc-10-x86.jinja2
Use the kernelci.org production branch when downloading Docker data files at build time rather than the fixed git sha1 revisions.  This was needed initially to bootstrap the templates before they got merged, now we can use the kernelci.org branch to get updates automatically in sync with production.
=> config/docker: use kernelci.org branch for data files

kernelci/cli/sched.py, kernelci/config/job.py, kernelci/config/scheduler.py, kernelci/scheduler.py, tests/configs/jobs.yaml, tests/configs/scheduler.yaml
Update the YAML config to have `event` attributes in the scheduler entries rather than `Job.run_on` as discussed on the mailing list and GitHub.
Fixes https://github.com/kernelci/kernelci-pipeline/issues/221
=> Scheduler event config

config/core/test-configs.yaml
The i.MX8MP has networking so we can at least cover the baseline-nfs
tests, and the main reason it's in my lab is that it has interesting
audio hardware so run the ALSA selftests too (the audio isn't in the
upstream DT yet but the tests handle this gracefully).
=> test-configs.yaml: Expand coverage for i.MX8MP-EVK

config/rootfs/chromiumos/scripts/build_board.sh
During build of ChromiumOS on certain builders it fail during ChromiumOS build with multiple malloc failure messages. Similar but reported for Gentoo and libsandbox, as workaround they just disable build sandbox feature, and we do the same.
=> build_board.sh: Add libsandbox bug workaround

config/core/build-configs-android.yaml
Add the following branches for the Android common kernel as requested by Todd:
- android15-6.1
- android14-6.1-lts
- android14-5.15-lts
=> build-configs-android.yaml: add new 6.1 and 5.15 branches

config/core/build-configs-android.yaml, config/core/build-configs-stable.yaml
Tweak the build configs to reduce coverage a bit further.  The stable and android configs were still building hundreds of arm configs, now they're trimmed down to the main ones.
=> Tweak build configs to reduce coverage

config/lava/chromeos/cros-tast.jinja2
As some of DUT might have batteries removed, abrupt poweroff might cause issues with storage. Better to make sure all buffers are sync and try to poweroff gracefully.
Not sure yet, if we will give them enough time, probably worth to add small additional delay later.
=> CHROMEOS cros-tast.jinja2: Reduce chance of filesystem corruption

kci_build
Pass the "meta" variable to _compress_gki_artifacts() so it can get the kernel image name.  This had been failing silently for a while as testing GKI builds isn't always easy.
Fixes: df511e1088c0 ("kci_build: rework push_kernel to use Storage")
=> kci_build: fix missing "meta" variable for GKI builds

requirements.txt
Update all the PyPI requirement package versions to the latest stable releases to get bug fixes and drop support for early Python versions.
Depends on #1980
=> Update requirements to latest releases

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/base.py, kernelci/cli/base_api.py, kernelci/cli/node.py, kernelci/cli/user.py
Added commands to `kci user` for getting user groups by ID and attributes.
Newly added sample commands:
```
kci user get_group <group-id>
kci user find_groups
kci user find_groups name=admin
```
=> `kci user` command for user groups

config/core/test-configs.yaml
Move the kernel tree filter used for the V4L2 decoder conformance tests out of the test plan definitions and specify the reference trees on a per-device basis. Use the same `videodec_timeout` value for all the devices running these decoder tests.
=> test-configs.yaml: Move videodec_timeout param and kernel tree filter for decoder tests

config/rootfs/debos/overlays/cros-flash/opt/chromeos/flash
```
++ losetup -P -f --show chromiumos_test_image.bin
+ dev=/dev/loop0
+ mount /dev/loop0p3 chromeos -o ro
mount: /root/chromeos: mount(2) system call failed: No such file or directory.
```
Workaround is to wait up to 10 sec until partition table get detected. Sometimes it takes a bit of time.
=> CHROMEOS flash: Add retry to detect p3

config/rootfs/debos/overlays/cros-flash/opt/chromeos/flash
Previous attempt to fix partition propagation delay were not fully reliable, still some flashing jobs, such as https://lava.collabora.dev/scheduler/job/11100799 had issue when /dev/loop0p3 available, but fails to mount. 
I tested new approach, where i literally retry to mount partition several times (with delay) until it succeed. 
Tested: https://lava.collabora.dev/scheduler/job/11101029
=> CHROMEOS flash: Improve mount reliability

config/core/test-configs-chromeos.yaml
As we have integrated several bugfixes, especially partition detection delay that fixes unreliable flashing issue, we need to switch to latest rootfs.
=> CHROMEOS test-configs-chromeos.yaml: Update bullseye-cros-flash rootfs

config/lava/base/kernel-ci-base.jinja2
The deferred_probe_timeout kernel parameter establishes how long to wait until the remaining devices might start being probed without their dependencies satisfied. Its default value is 10, however I've observed that at least on arm64 platforms, it consistently takes slightly longer, around 13 seconds, from when the timer is started to when udev is run and loads the modules for the remaining devices.
Increase the timeout to 20 seconds in order to give enough time for the machines to boot and probe all devices and their dependencies. This timeout is run in a separate kernel thread, so changing it shouldn't have any impact on the boot time.
Machines that I checked the boot delay on:
mt8192-asurada-spherion: https://lava.collabora.dev/scheduler/job/11063320
mt8195-cherry-tomato: …
=> config/lava: Extend deferred_probe_timeout

config/docker/base/host-tools.jinja2, config/docker/cros-baseline.jinja2, config/docker/cros-qemu-modules.jinja2, config/docker/cros-tast.jinja2, config/docker/gcc-10-x86.jinja2
Fix indentation in GitHub file URLs wrapped over multiple lines.  The indentation was being added in the middle of the URLs, causing a failure to build the image.
Fixes: 6ea6fcbdce1a ("config/docker: use kernelci.org branch for data files")
=> config/docker: fix indentation in GitHub URLs

config/core/build-configs.yaml
Add the videodec arm64 fragment again to mainline, next and media build configs so that the video decoder tests can be run.
=> build-configs.yaml: add videodec to mainline, next, media

config/core/test-configs.yaml
Update the filters to run the v4l2-decoder-conformance-* tests only on next, mainline and media trees using the common anchor.
=> test-configs.yaml: update the filters for v4l2 decoder test configs

config/core/rootfs-images.yaml
The bullseye-gst-fluster rootfs image for arm64 has been rebuilt to extend coverage.  Update the URL accordingly and by hand since rootfs automated updates are currently disabled.
=> rootfs-images.yaml: use new bullseye-gst-fluster arm64 image

config/lava/boot-nfs/generic-depthcharge-tftp-nfs-template.jinja2, config/lava/boot-nfs/generic-uboot-tftp-nfs-template.jinja2
The depthcharge and uboot templates add extra_kernel_args to the context only on the ramdisk templates, but not in the NFS ones. Update the NFS templates so they also set the kernel arguments.
Thanks to @crazoes for noticing this issue.
Note that this only syncs the ramdisk and NFS so that they're the same (except for the `nfs/ramdisk` command) for all boot methods. The barebox, grub and ipxe templates don't set the kernel arguments on neither the ramdisk nor the nfs templates, so they're not touched.
=> config/lava: Add missing extra_kernel_args to NFS variants

config/core/test-configs.yaml
The formats that can be tested by fluster on trogdor Chromebooks are H.264, H.265 and VP8. Fix the list of fluster decoder test plans accordingly.
=> test-configs.yaml: Fix list of fluster tests on kingoftown Chromebooks

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/base.py, kernelci/cli/node.py, kernelci/cli/user.py
Fixes https://github.com/kernelci/kernelci-core/issues/2016
Added commands to `kci user` for getting user profiles by attributes.
Newly added sample commands:
```
kci user find_users
kci user find_users --limit 2
kci user find_users profile.username=admin
```
Added pagination related optional arguments to `kernelci.cli.base` as they have been used by multiple commands like `kci node find` and `kci user find_groups`.
Optimized `kci node find` command handler.
=> `kci user` commands for user profiles

config/core/test-configs.yaml
Enable V4L2 decoder conformance tests on mt8192-asurada-spherion-r0 for H264, VP8 and VP9 formats.
Set a 90s timeout for each decoding.
=> Enable decoder conformance tests on mt8192-asurada-spherion-r0

config/core/build-configs.yaml
Add "for-firmware-kernelci" branch for chrome-platform-firmware.
Also move the variants to chrome_platform_variants as it is common for chrome-platform and chrome-platform-firmware.
=> build-configs.yaml: add entry for chrome-platform-firmware

config/core/rootfs-configs-chromeos.yaml
Add new rootfs type for guybrush board. Already built, tested and deployed rootfs for it.
=> CHROMEOS rootfs-configs-chromeos.yaml: Add guybrush board

config/core/rootfs-configs-chromeos.yaml
Add new rootfs type for `brya` & `puff` boards. Tested to build without any additional change.
=> rootfs-configs-chromeos: add brya & puff

config/core/build-configs.yaml
The clang-11 toolchain doesn't support riscv but the mainline build config for riscv relies on the standard arch list which is also used for clang-16 and clang-17 which do support riscv.  As a result, some builds were being scheduled with clang-11 for riscv and since the clang-11 build environment config doesn't list riscv there's no translation to the Debian arch name riscv64 causing the build jobs to fail to pull the Docker image (and causing some congestion in Kubernetes as a side-effect).
Fix this by removing riscv from the clang-11 mainline build config.
Fixes: ddb1c84f466f ("build-configs: update riscv_clang_configs")
=> build-configs.yaml: Drop broken riscv clang-11 config

kernelci.toml.sample, kernelci/cli/base.py, kernelci/runtime/__init__.py
The older settings file `.conf` is using `":"` to define sub-section of components such as databases and runtimes e.g. `db:docker-host`. Use dotted keys for these components as it is a more standard way to define child sections in TOML. The syntax is `section_name.section_config` e.g. `db.docker-host`. In case the section configuration has `"."` (dot)
in the name, it needs to be surrounded by `""` (double-quotes) to parse it properly with TOML decoder e.g. `db."staging.kernelci.org"`
=> TOML settings: use dotted keys

config/core/test-configs-chromeos.yaml
Reference kernel in R114 doesn't use -r1 suffix as in newest kernels in upstream.
=> CHROMEOS test-configs-chromeos.yaml: Update dtb filename in reference

config/core/build-configs.yaml
Kernel config changes to get MT8195 booting and with full platform support (once missing firmware and kernel series for the display land).
This should land after #1957, as that's the PR enabling baseline tests on MT8195 Tomato in the first place.
=> build-configs.yaml: Kernel configs for MT8195 Tomato

config/core/build-configs.yaml
At current moment amdgpu fails to init, due missing firmware files, for example:
```
3.604417] amdgpu 0000:03:00.0: Direct firmware load for amdgpu/green_sardine_asd.bin failed with error -2
```
=> build-configs.yaml: Add guybrush missing firmware files

config/docker/cros-sdk.jinja2, config/docker/cros-tast.jinja2, config/docker/data/tast_parser.py, config/docker/fragment/cros-lava.jinja2
Often tast execution fail and parser quit silently, not even raising error, which leads to hidden failures that are caught too late. This patch fixes that.
=> CHROMEOS tast_parser.py: Raise critical error if tast run fails

config/core/test-configs-chromeos.yaml
Temporary disable fixed tests, as they force devices to go into self_repair mode and wipe stateful partition.
=> CHROMEOS test-configs-chromeos.yaml: Disable -fixed tests

config/core/test-configs-chromeos.yaml
V4L2 stateful decoder tast tests have been renamed in R114. Update the list of tests for `trogdor` Chromebooks accordingly.
=> CHROMEOS test-configs-chromeos.yaml: Update list of tast decoder test for R114

config/core/test-configs-chromeos.yaml
Enable the cros-tast-mm-decode test plan on trogdor Chromebooks.
=> CHROMEOS test-configs-chromeos.yaml: Run cros-tast-mm-decode on trogdor

config/core/test-configs-chromeos.yaml
Enable V4L2 stateless decoder tast tests and `cros-tast-video` tast tests on `mt8192-asurada-spherion-r0` and install the required dependencies on `chromiumos-asurada`.
MT8192 decoder support is only present in the `linux-next` tree at the moment; run the tests on the `collabora-chromeos-kernel` tree for now.
=> Enable decoder tast tests on mt8192-asurada-spherion-r0

config/rootfs/chromiumos/scripts/build_board.sh, config/rootfs/chromiumos/scripts/fixes/postbuild-release-R114-15437.B.sh, config/rootfs/chromiumos/scripts/fixes/postbuild-release-R116-15509.B.sh
As described in b/295364868 if this flag is enabled in mke2fs, and we test in KernelCI newest kernel (post-5.15), it will convert fs using this flag and then when we load pre-5.15,
on old kernel, it will not be able to mount filesystem, and as result initiate self_repair with wipe of stateful partition.
=> CHROMEOS build_board.sh: Add step to remove orphan_files feature

config/docker/clang-17.jinja2
clang-17 repo name slightly changed, update it
=> clang-17.jinja2: Fix clang-17 repository

config/core/build-configs-chromeos.yaml
Current ChromeOS release using clang-17 for kernel builds, it is better to be up to date on compiler and update it from obsolete clang-14.
=> CHROMEOS build-configs-chromeos.yaml: Switch to clang-17

config/core/test-configs-chromeos.yaml
We discovered more useful tast tests that can be used for KernelCI.
=> CHROMEOS test-configs-chromeos.yaml: Add more tast tests

config/core/test-configs-chromeos.yaml
Marking as draft as the needed artifacts have not been uploaded to storage yet.
=> CHROMEOS test-configs-chromeos.yaml: add test configs for brya & puff

kernelci/api/__init__.py, kernelci/api/latest.py
Add a missing abstract method entry in the API abstract base class.
Disable the too-many-public-methods pylint checks as the class now has
too many method to pass.
Fixes: f3227a3b3891 ("kernelci.api.latest: implement method for changing user password")
Signed-off-by: Paweł Wieczorek <pawiecz@collabora.com>
=> kernelci.api: add missing API bindings for changing user's password

config/docker/fragment/gcloud.jinja2
Wrap long lines in the gcloud.jinja2 Docker template fragment to make it more readable and consistent with all the other files.
=> config/docker: gcloud: wrap long lines

config/docker/fragment/helm.jinja2, config/docker/k8s.jinja2
Add a Docker template fragment to install the Helm tool in k8s images. This is useful for deploying new packages such as ingress-nginx and cert-manager for the API deployment in particular.
=> config/docker: helm: add template fragment to install Helm

config/docker/fragment/azure-cli.jinja2
Remove extra whitespace and wrap lines before the pipe | character to make it easier to read and more consistent with the other files.
=> config/docker: azure-cli: clean up formatting

kernelci/cli/show.py
Show the node owner in `kci show results` to be able to tell which user created the node.
=> kernelci.cli: show: add owner

config/core/test-configs-chromeos.yaml
As we prepared everything and built images, it's time to switch to R116.
=> CHROMEOS test-configs-chromeos.yaml: Update build images to R116

config/rootfs/chromiumos/scripts/fixes/packagefix-release-R116-15509.B.sh
During the testing we noticed that some boards still need TPM flag to be enabled manually, to work properly.
=> CHROMEOS packagefix-release-R116-15509.B.sh: Add tpm workarounds

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/user.py
Add an API method and `kci user add` command to create new API users.
=> Add support for creating new API users

config/runtime/base/kubernetes.jinja2
Switch the storage credentials to the upload SAS token for Azure Files temporarily.  Ideally this should be done dynamically in the template.
=> config/runtime: kubernetes: use Azure Files SAS instead of SSH

config/core/test-configs-chromeos.yaml
Some tests while shown in list - doesn't exist in reality. Remove them, so they dont break testing
=> CHROMEOS test-configs-chromeos.yaml: Remove missing tests

kernelci/cli/base_api.py
When not providing a value for --indent when a command returns some JSON data, do not indent at all rather than indenting with 0 spaces.
Fixes: de31ee73e926 ("kernelci.cli.base: add ._print_json() helper method")
=> kernelci.cli: kci: fix default value for --indent

config/runtime/base/kubernetes.jinja2
Use the early access JWT token rather than the staging one by default. Then staging can have a patch to use the staging one.
This is also a temporary measure until it's all fixed with template parameters.
=> config/runtime: kubernetes: use early access JWT

config/runtime/base/lava.jinja2
Replace the KernelCI API job name prefix with "KernelCI AKS" to be able to differenciate with the staging ones which should have "KernelCI staging" instead.
=> config/runtime: lava: use KernelCI AKS in job names

kernelci/cli/show.py
Add underlines for each job (or group of results) and only show the node names rather than the full path to improve readability.  Also avoid doing queries to get child nodes when the maximum recursion depth has been reached.
=> Tweak format of `kci show` and avoid unnecessary API queries

config/core/test-configs-chromeos.yaml
After viewing diff of R114->R116 tests i found similar to existing tests might be added, or some that doesn't take significant lab time.
=> CHROMEOS test-configs-chromeos.yaml: Update tast tests

config/core/test-configs-chromeos.yaml
We need better support of onboard ethernet, we can use one of KernelCI built kernels for that.
=> CHROMEOS test-configs-chromeos.yaml: Update x86 kernel

config/core/test-configs-chromeos.yaml
Flash rootfs is used to install modules and for ChromeOS imaging. Let's try newer distro, as also we need newer ext4 tools.
=> CHROMEOS test-configs-chromeos.yaml: Update bullseye to bookworm in flash rootfs

config/core/test-configs-chromeos.yaml
Run the fluster decoder conformance tests on the `collabora-chromeos-kernel` tree.
=> CHROMEOS Enable fluster tests on asurada with collabora-chromeos-kernel

config/core/test-configs-chromeos.yaml
Enable V4L2 decoder conformance tests on `mt8195-cherry-tomato-r2_chromeos` for H264, VP8 and VP9 formats. Run the tests on the `for-kernelci` branch of the `collabora-chromeos-kernel` tree.
=> CHROMEOS test-configs-chromeos.yaml: Enable fluster tests on tomato for collabora-chromeos-kernel tree

kernelci/cli/base.py
By default we can specify config file by --api-config, if not, kci will search config at predefined places.
Now we can also set config file path by environment variable KCI_SETTINGS.
=> cli/base.py: Implement KCI_SETTINGS env variable handling

config/core/test-configs.yaml
This reverts commit 491a3dba7b3b2c433fc1f6518600ac0eb33492ab.
Enable all the test configurations again to measure the added load and related costs in the infrastructure.
=> Revert "test-configs.yaml: reduce coverage to bare minimal"

config/core/test-configs.yaml
The FVP is extremely slow and we've got some quite CPU intensive tests
scheduled for it, including things like the KVM selftests which are very
CPU intensive and end up taking on the order of six hours to run.  Since
we only have a few donated FVPs we're routinely dropping jobs on the
floor, restrict to just running core upstream trees plus the arm64
architecture tree to give us more chance of making it through the jobs
we schedule.  I've included stable but it might need to be removed too
given that we tend to get a lot of stable updates together.
=> test-configs.yaml: Limit trees we test on FVP

kernelci/cli/storage.py
Always print the URL of the uploaded artifact as otherwise there may not be any easy way to find it again later.
Fixes: c514b5884e44 ("kernelci.cli.storage: add command to upload files etc.")
=> kernelci.cli: storage: always print the artifact URL

kernelci/runtime/docker.py
docker.run wont tolerate in env variable any comments or empty data, as it will try to interpret it as variable with unacceptable name. So we can just skip comments and empty lines.
=> runtime/docker: Don't add to env comments

kernelci/cli/base_api.py
Right now for operators we are using "magic" suffix such as __gt, __lt and so on, which is not documented and a bit non-intuitive. We can make cli tool more intuitive with this patch, where it will hide from user this magic, until we find better mechanism to handle operators as mentioned in https://github.com/kernelci/kernelci-api/issues/356
Example tested:
```
kci node find 'created>2023-09-17' 'state=done' 'group=kver'
```
Fixes: https://github.com/kernelci/kernelci-api/issues/356
=> base_api.py: Implement operators and document them in cli help

config/core/test-configs.yaml
We have new device in staging lab, its one only, so we just run baseline and baseline-nfs for verifying bootability and network operation.
=> test-configs.yaml: Enable acer-chromebox-cxi5-brask for testing

config/core/build-configs-chromeos.yaml, kernelci/build.py
This PR includes the 6.6 build definition for ChromeOS, which itself relies on a (small) change to `kernelci/build.py` so we can use a ChromeOS branch name which includes the `/` character
=> CHROMEOS add build definition for 6.6 kernel

kernelci/test.py
Since https://git.kernel.org/linus/724ba6751532055db75992fc6ae21c3e322e94a7, the ARM dts files were moved to subdirectories and the configs do not match any more, which results in boards not receiving test jobs for kernels since that commit.
Instead of adding the new directory prefix to every config (which would cause problems with testing stable trees), only compare the basename (and assume that it's unique).
=> kernelci.test: match configs by dtb basename

config/runtime/base/kubernetes.jinja2
As we are in development process, we need to keep container a bit longer after failure or completion, so we can have enough time to catch logs on early failure.
=> kubernetes.jinja2: Increase timeout before container destroy

config/core/api-configs.yaml, kernelci/config/api.py, kernelci/legacy/cli/base_api.py, tests/api/conftest.py, tests/configs/api-configs.yaml, tests/test_configs.py
Rename the YAML entry 'api_configs' to 'api' as per the GitHub discussion.  The new kci command line tool will also have an --api option to specify the API config to use.
Update standard YAML configuration and unit tests accordingly.
Link: https://github.com/kernelci/kernelci-core/discussions/1907#discussioncomment-5718754
=> kernelci.config: rename 'api_configs' to 'api'

kernelci.toml.sample, kernelci/settings.py, tests/kernelci-settings.toml, tests/test_settings.py
Implement the TOML settings handling again in a new `kenrelci.settings` module.  This is based on the legacy one but also takes into account new features required for the `kci` command line tool as per https://github.com/kernelci/kernelci-project/discussions/261
=> TOML settings rework

config/runtime/base/python.jinja2
As the kernelci.config module is being rewritten, it no longer implicitly import other submodules.  Explicitly import kernelci.config.storage in python.jinja2 to avoid missing import errors.
=> config/runtime: base: import kernelci.config.storage

kci_data, kci_test, kernelci/config/__init__.py, kernelci/config/api.py, kernelci/config/job.py, kernelci/config/runtime.py, kernelci/config/scheduler.py, kernelci/config/storage.py, kernelci/legacy/config/__init__.py, kernelci/legacy/config/base.py, kernelci/legacy/config/build.py, kernelci/legacy/config/db.py, kernelci/legacy/config/rootfs.py, kernelci/legacy/config/test.py, setup.py, tests/test_configs.py
Move the modules that relate to the legacy YAML implementation to kernelci.legacy.config.  This is still loaded as part of the main configuration to provide backwards-compatibility until support is eventually dropped.
Update unit tests, imports and setup.py accordingly.
=> kernelci.legacy: move legacy config implementation

config/core/storage.yaml, kernelci/config/storage.py, tests/configs/storage-configs.yaml, tests/test_configs.py
Rename the top-level 'storage_configs' entry to 'storage' as per the GitHub discussion and move it from db-configs.yaml to storage.yaml. Keep a 'storage_configs' key in the configuration dictionary for backwards compatibility with legacy tools.
Update unit tests accordingly.
Link: https://github.com/kernelci/kernelci-core/discussions/1907
=> config/core: move storage_configs to storage in storage.yaml

Makefile, kci, kernelci/cli/__init__.py, requirements.txt, tests/kernelci-cli.toml, tests/test_cli.py
Rework the `kernelci.cli` module and `kci` entry point using the Click framework.
=> Rework `kernelci.cli` with Click framework

config/core/test-configs-cip.yaml
updating isar-cip-core rootfs to currently the last one 20231004 this also update the image from buster to bookworm
=> config/core/test-configs-cip: update isar-cip-core rootfs to 20231004 bookworm

kernelci/cli/__init__.py
Fix the split_attributes() docstring as the attributes are meant to be a list of key=value strings rather than a single string with all the attributes.  The command line parser should already split each attribute into a separate string.  Also mention that spaces can be used around operators with examples using double quotes.
Fixes: 0a62fb90d404 ("kernelci.cli: rewrite split_attributes() method")
=> kernelci.cli: fix split_attributes() docstring

config/core/db-configs.yaml
Add back the db_configs entries which got lost by mistake while reworking the storage configs.
Fixes: 68b04800c0f0 ("config/core: move storage_configs to storage in storage.yaml")
=> config/core: add back db_configs which were deleted with storage rework

kci, kernelci/cli/user.py, kernelci/legacy/cli/user.py
Implement parts of `kci user` with the new framework based on Click and remove the corresponding old implementation code.
=> Rework `kci user` with new framework

setup.py
Add the missing kernelci.cli package to the list of packages to install.
This was missing when adding the new kernelci.cli implementation and went unnoticed when using the code from the Git checkout.
Fixes: ec7f5c61ae53 ("kernelci.cli: rewrite with Click framework")
=> setup.py: add missing kernelci.cli package

config/runtime/base/lava.jinja2, kernelci/runtime/__init__.py
Add environment variable KCI_INSTANCE that will adjust job name prefix for LAVA.
Probably in future similar way we can customize k8s and docker names as well.
=> runtime: Add instance ID for LAVA runtime

kernelci/cli/__init__.py, tests/kernelci-cli.toml, tests/test_cli.py
Deal with cases where an option can have multiple values by converting it always to a list and loading the default list value from TOML when it's not supplied on the command line.
Update unit tests accordingly.
Fixes #2158
=> kernelci.cli: support multiple values with default in TOML

kci, kernelci/cli/api.py
Add back the 'kci api hello' command as it's required as part of the Early Access setup documentation page.  This is also a placeholder for implementing other generic API commands to get the API instance version, URLs and other details.
Fixes #2158
=> kernelci.cli: add api module with hello command

kci, kernelci/cli/__init__.py, kernelci/cli/storage.py
Add implementation for `kci storage upload` subcommand using the new framework with Click.
Fixes #2158
=> kernelci.cli: add storage subcommand

kernelci/cli/__init__.py
Allow multiple values for the --yaml-config option so that the YAML configuration can be stored in different directories and files in various locations.  The code to merge them all is already in place.
Fixes #2158
=> kernelci.cli: Allow multiple values for --yaml-config

config/core/test-configs.yaml
For some reason when reenabling the tests that were disabled due to load
issues those for verdin were skipped, enable everything now.
Also enable the clone3() selftests, they are not currently covered at all
on arm64 and the board is generally very lightly loaded.
=> test-configs.yaml: Enable more tests on verdin

config/core/test-configs-chromeos.yaml
When this entry got added back in august, a copy+paste error resulted in the asurada dtb being used for cherry, leading to boot failures while flashing R118.
=> CHROMEOS: test-configs-chromeos: fix reference cherry dtb name

config/docker/base/host-tools.jinja2, kernelci/build.py
Add rdfind to packages as it is required now by linux-firmware and make execution of copy-firmware fails on errors.
=> CHROMEOS: Fix linux-firmware dependencies

config/core/test-configs-chromeos.yaml
While flashing & testing Chrmoiumos R116 -> R118 upgrade,
it was noticed there is a grunt board which does not run
CrOS tests, so this adds the necessary definitions to be
able to install ChromeOS and run tests on it.
=> CHROMEOS: test-configs-chromeos: add hp-14-db0003na-grunt

kernelci/api/__init__.py, kernelci/api/latest.py
Drop the API bindings that aren't used any more now that the user management implementation has been replaced with fastapi-users:
* API.security_scopes
* API.password_hash
* API.change_password
Update kernelci.api.latest accordingly.  No unit tests need to be adjusted and the kernelci.cli tools are already using the new bindings.
=> kernelci.api: drop unused bindings after user rework

config/core/test-configs-chromeos.yaml
Further testing the ChromiumOS R118 uprev revealed we're also missing a volteer board type.
=> CHROMEOS: test-configs-chromeos: add acer-cp514-2h-1160g7-volteer

config/core/test-configs.yaml
The decoder conformance tests require the chromebook-decoders-filter, specifically defined for these tests only. Move the tests to a dedicated test plan. This re-enables baseline tests for trogdor Chromebooks on the stable kernel tree.
=> test-configs.yaml: Move decoder tests for trogdor to separate plan

kernelci/runtime/__init__.py
=> config/runtime: base: reenable platform configs to override previously set values

config/core/test-configs.yaml
V4L2 stateful VP9 decoder support has been recently added to fluster. Enable VP9 fluster tests on trogdor Chromebooks.
=> test-configs.yaml: Run VP9 fluster tests on trogdor

config/core/rootfs-configs.yaml, config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py, config/rootfs/debos/scripts/bullseye-gst-fluster.sh
In https://github.com/chromeos/cros-codecs/issues/6, we want to run `cros-codecs` through fluster in LAVA to make sure nothing is broken on each PR.
The idea would be to use the already existing `bullseye-gst-fluster` rootfs in this repository.
To do that some dependencies are added to access the VA device with the rootfs.
This PR also adds `wget` in the rootfs to retrieve the built `ccdec` binary.
Another dependency is `intel-media-va-driver-non-free` from the `non-free` repository on `amd64` as the free version has issues with a lot of the test vectors.
Tests jobs will be submitted by the `cros-codecs` Github action and this rootfs will be downloaded by LAVA for each commit on the repository
The rootfs size deltas are as follow:
|       File        | …
=> Add dependencies for cros-codecs CI

config/core/build-configs.yaml, config/core/test-configs-chromeos.yaml
Tested on upstream 6.6, works as well as for other MTK devices
=> CHROMEOS test-configs-chromeos.yaml: add test config for cherry

config/core/test-configs.yaml
Add `kselftest-dt` test plan, to run the probe test on dt-based platforms. Enable the test on mtk and qcom arm64 based Chromebooks.
=> test-configs: Enable kselftest-dt on mtk and qcom Chromebooks 

config/core/build-configs-android.yaml
As per Todd Kjos email we are gradually enabling allmodconfig, then if system can handle load properly, we will enable allyesconfig.
=> build-configs-android.yaml: Enable allmodconfig

config/core/test-configs-chromeos.yaml
Some Tast tests aren't run on x86 chromebooks, making it difficult to come up with a unified reporting format.
Moreover, having a `-fixed` version of each Tast test plan is useful to track regressions between the ChromeOS kernel and mainline, so add the missing `cros-tast-ui-fixed`.
=> CHROMEOS test-configs-chromeos: run same tests on x86 and arm64 chromebooks

kernelci/cli/__init__.py, tests/test_cli.py
Add the --page-length / -l and --page-number / -n options for paginated API data.  Provide a kernelci.cli.get_pagination() function to convert these arguments into the offset / limit values used with the API as pagination is easier with relative numbers on the command line.  Add unit tests accordingly to test this function.
=> kernelci.cli: add pagination options and helper

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/user.py
=> Add `kci user` commands (was #2157)

config/core/test-configs.yaml
I keep a fairly close watch on the state of support for boards in my lab,
including monitoring the device tree selftests. Since these tests are quick
to run enable them for the DT boards I have.
=> test-configs.yaml: Enable kselftest-dt for boards in my lab

kernelci/cli/__init__.py, tests/test_cli.py
Allow the same attribute to be provided several times in .split_attributes().  This is useful when looking for database entries that match one of a set of values e.g. name=foo?name=bar to find entries named 'foo' or 'bar'.
Update unit tests accordingly with an additional one to test the generated request URL with multiple values for the same parameter.
=> kernelci.cli: allow multiple values for .split_attributes()

config/core/test-configs-chromeos.yaml
These are new tests added in R118 which are known to work. We can extend coverage more, especially on the storage side but we need some bugs like b:311421846 fixed first.
=> CHROMEOS: test-configs-chromeos: add some new tests in R118

kernelci/api/__init__.py, kernelci/api/latest.py
Move the helper methods out of the API() abstract class to make the actual bindings clearer.  This will also make it possible to have nested classes for different parts of the API e.g. `api.node.find()` and `api.node.find()` rather than all the methods in a single ever-growing class.
=> Rework `kernelci.api.API` class internals to have only abstract bindings

kernelci/api/helper.py
This one shouldn't break anything, it's safe to merge but a review is appreciated.
Related to https://github.com/kernelci/kernelci-pipeline/pull/363
This is a provisional fix to prevent listeners from crashing when waiting for node events upon reception of a different type of event.
=> kernelci.api.helper: ignore non-node events in get_node_from_event()

kernelci/api/__init__.py
On 'node find' with --limit we are failing because _get return different object type.
=> api/__init__.py: Fix _get_paginated logic

config/core/build-configs-chromeos.yaml, kernelci/build.py, kernelci/legacy/lava/__init__.py
Use shortening service to reduce job length, as it is excessively long.
=> CHROMEOS test.py: Truncate very long cross:// repo name

config/core/build-configs-chromeos.yaml
ChromiumOS' kernel repo now includes a `chromeos-6.6` branch, so let's use that one instead of the CI-generated one.
=> CHROMEOS build-configs-chromeos: update 6.6 reference branch

kernelci/api/__init__.py, kernelci/api/helper.py, kernelci/api/latest.py, kernelci/cli/event.py
Depends on https://github.com/kernelci/kernelci-api/pull/417 and https://github.com/kernelci/kernelci-core/pull/2203
Add `kci event push` command to push event to a given Redis unicast list. Add `kci event pop` command to pop event from the list for a single consumer.
=> Add `kci event` commands for unicast list `push` and `pop`

kci, kernelci/api/helper.py, kernelci/cli/__init__.py, kernelci/cli/job.py
Rework `kci` commands to manage KernelCI jobs with `Click` framework.
Tested locally for `kver` job:
```
$ ./kci job new kver --node-id=6465cd3c73281d29430d3071
{"id": "656ad50f8cff329b0e4ad092", "kind": "node", "name": "kver", "path": ["checkout", "kver"], "group": "kver", "revision": {"tree": "kernelci", "url": "https://github.com/kernelci/linux.git", "branch": "staging-mainline", "commit": "ac37cbde135450309a2b6c3b66331912d744b4c9", "describe": "staging-mainline-20230517.0", "version": {"version": 6, "patchlevel": 4, "sublevel": null, "extra": "-rc2-1-gac37cbde1354", "name": null}}, "parent": "6465cd3c73281d29430d3071", "state": "running", "result": null, "artifacts": {"tarball": "http://172.17.0.1:8002/linux-kernelci-staging-mainline-staging-mainline-20230517.0.tar.gz"}, "data": null, …
```
=> kernelci.cli: rework `kci job` commands with `Click`

config/core/build-configs-chromeos.yaml
Although most devices can use upstream 6.6 as-is, `cherry` still requires a few additional patches. Therefore, we create a new `chromeos-stable_6.6-backported-arm64` build config similar to the existing 6.1-based one.
=> CHROMEOS build-configs-chromeos: add new 6.6-based branch

config/core/build-configs.yaml, config/core/test-configs.yaml
Add missing Wifi firmwares and reduce the suspend modes tested to the ones supported to get the suspend/resume tests passing on the MT8192-Spherion Chromebook.
Results went from 3/23 (passing/total) to 13/13. LAVA log: https://lava.collabora.dev/scheduler/job/12152307
This will make suspend regressions on Spherion detectable.
=> Get suspend/resume tests passing on the MT8192-Spherion Chromebook

kernelci/cli/__init__.py, kernelci/cli/job.py
Fix a few cosmetic issues in the kernelci.cli.job implementation:
* fix alphabetical order in kernelci.cli.Args with runtime arg
* avoid breaking long strings by moving them to their on line
* fix copyright years as this was originally written in 2022
Fixes: 9ef18ea92d3c ("kernelci.cli: rework `kci job` commands")
=> kernelci.cli: tidy up job command

kernelci/cli/__init__.py
The CommandSettings object is used as the Click command context so use a local "settings" variable in Kci.invoke() to make this clear.  Also drop the .secrets property which was broken and actually not used.
Fixes: ec7f5c61ae53 ("kernelci.cli: rewrite with Click framework")
=> kernelci.cli: fix context and CommandSettings.secrets

kernelci/cli/user.py
Depends https://github.com/kernelci/kernelci-api/pull/430
Send API token for getting existing users' information as the endpoint has made accessible to only authorized users.
=> kernelci.cli.user: send token to GET users requests

config/runtime/base/kubernetes.jinja2
Add safe defaults, so in case too many jobs scheduled they will not crash cluster with parallel builds.
=> runtime/kubernetes.jinja2: Add safe defaults

config/rootfs/chromiumos/scripts/build_board.sh
Recent Chromebooks such as `corsola` or `skyrim` use `ti50` instead of `cr50`. This change ensures this is also taken into account so we don't leave any of those firmware on our images but still extract those as board artifacts.
=> CHROMEOS build_board: cleanup/extract ti50 firmware as well

config/core/build-configs.yaml
rust-for-linux-samples was used for building rust test modules, recently unused.
enable it for rust-next as it have substitute the previous rust branch.
=> build-configs.yaml: Add rust-for-linux-samples to rust-next

config/core/runtime-configs.yaml
Switch the tree filter to a regex with the primary goal of running tests for "stable", but not stable* (e.g. stable-rc-queue) due the number of jobs currently being too much for lab-baylibre.
=> config: runtime: lab-baylibre: switch to regex for tree

kernelci/cli/__init__.py, kernelci/cli/api.py, kernelci/cli/event.py, kernelci/cli/job.py, kernelci/cli/node.py, kernelci/cli/user.py
Add `kernelci.cli.get_api()` and `.get_api_helper()` functions and use then in all the `kci` subcommands accordingly to remove repeated code.
=> Add `kernelci.cli.get_api()` and update commands

config/core/build-configs.yaml
Both trogdors (qualcomm) and also the mediatek boards fail the
graphics.KernelConfig because they expect DRM_VGEM = n.
Example:
https://chromeos.kernelci.org/test/case/id/656ca345e2496d30984c084f/
=> CHROMEOS: build-configs: remove DRM_VGEM from arm chromebook cfg

kernelci/cli/user.py
Depends on https://github.com/kernelci/kernelci-api/pull/431
Send API token for getting user matching given ID as the endpoint has made accessible to only authorized users.
=> kernelci.cli.user: send API token to GET user matching ID

kernelci/cli/node.py
Update `kci node find` implementation to use get_pagination() with the standard command line page options.
=> kernelci.cli: use get_pagination() in kci node

kernelci/cli/__init__.py, kernelci/cli/api.py, kernelci/cli/event.py, kernelci/cli/job.py, kernelci/cli/node.py, kernelci/cli/user.py
Add kernelci.cli.echo_json() function as a convenience for the common
use-case where some JSON data needs to be dumped on stdout.  Update
all subcommands accordingly to use it.  This takes into account that
indent=0 should mean no formatting, rather than indentation with only
line returns and no spaces.
=> kernelci.cli: add echo_json() function

config/core/test-configs.yaml
We don't currently run the networking selftests since they don't play
nicely with NFS root filesystems as a result of reconfiguring networking.
This isn't an issue with emulated platforms where we use a disk image as
our root filesystem so let's pick one and run the tests there. They're
pretty heavyweight so give it a large timeout.
=> test-configs.yaml: Enable networking selftests

config/core/test-configs.yaml
While many examples of regex matches use a start of line anchor to
ensure there aren't trees matched unexpectedly there are quite a few
examples that appear to unintentionally omit them.  Update them to have
the anchors.
=> test-configs.yaml: Add start of line anchors to regexes

kernelci/cli/event.py, kernelci/cli/node.py
Use click.File rather than sys.stdin for reading input data.  If the
file name is '-' then it will use stdin which is standard practice.
=> kernelci.cli: use click.File for reading input

config/core/build-configs.yaml, config/core/rootfs-configs-chromeos.yaml, config/core/test-configs-chromeos.yaml, config/rootfs/chromiumos/scripts/build_board.sh, config/rootfs/chromiumos/scripts/fixes/packagefix-release-R118-15604.B.sh
This is a new addition to Collabora's LAVA Lab. This board is based on an AMD Mendocino chipset, hence the use of the generic x86 defconfig.
=> CHROMEOS Add configs for Skyrim

config/core/build-configs.yaml, config/core/rootfs-configs-chromeos.yaml, config/core/test-configs-chromeos.yaml, config/rootfs/chromiumos/cros-snapshot-release-R118-15604.B.xml
`corsola` is a new type of Mediatek-based chromebooks recently added to the Collabora lab. This PR adds the necessary manifest and config changes to be able to build (working) ChromeOS images and test this board in KernelCI.
=> CHROMEOS Update R118 manifest for corsola and add tests for this device

kernelci/cli/api.py, kernelci/cli/event.py, kernelci/cli/node.py
Add the catch_http_error decorator to all the commands that make some
API calls.  This improves the user experience noticeably as it avoids
having a noisy exception trace and also adds any the details provided
by the API from the HTTP error data.
For example:
$ ./kci node get --api=staging abcd
Error: 400 Client Error: Bad Request for url: https://staging.kernelci.org:9000/latest/node/abcd
'abcd' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
The last line there is not part of the standard exception handling,
and it's needed in order for the user to understand what the actual
problem was (rather than there was just an HTTP error).
Fixes #2223
=> kernelci.cli: use catch_http_error in all API calls

config/core/build-configs-stable.yaml
As per https://github.com/kernelci/kernelci-core/issues/2254 adding 6.6 to kernelci
=> Adding stable and rc-queue for kernel 6.6

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/user.py
Similarly to API.Node, refactor the user API endpoint bindings with a new API.User abstract class.  Update the LatestAPI implementation and `kernelci.cli.user` accordingly.  There doesn't appear to be any unit tests for this part of the API.
As a side-effect, the Pylint check for too many public methods can be enabled again as the base API abstract class has now fewer of them since each nested class is taking care of a specific part of the API.
The user groups are still in the API class and should be moved to API.User or a new API.Group class.  This can be done as a follow-up, it wasn't very clearly defined initially so I've left it out for now.
Similarly, there should be API.Event or API.PubSub etc. for the other parts of the API.
=> Add API.User abstract class

config/core/rootfs-configs.yaml, config/rootfs/debos/rootfs.yaml, kernelci/legacy/config/rootfs.py, kernelci/rootfs.py
Some images might exceed 1GB default size, for example fluster tests that include a lot of test vectors.
We need configurable parameters to solve that.
=> rootfs: Add imagesize parameter

config/core/test-configs.yaml
We use yaml alias which hide that kselftest by default uses bullseye. So we need to change this parameter to bookworm.
=> test-configs.yaml: Enable bookworm rootfs on kselftest-net_qemu

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/event.py
Implement `kci event stats` command to get details of existing Pub/Sub subscribers.
```
$ ./kci event stats --indent=2
[
{
"id": 773,
"channel": "test",
"user": "admin",
"created": "2023-12-22T07:03:53.335397",
"last_poll": null
}
]
```
=> kernelci.cli: add command for getting PubSub subscribers stats

config/core/rootfs-configs.yaml
The net kselftests require a number of userspace utilities which we
don't currently include in the kselftest rootfs, add them to the
bookworm-kselftest image so we can run more of the suite.
=> rootfs-configs.yaml: Add runtime dependencies for net selftests

kernelci/cli/user.py
Since GET `/users` request is now restricted to authorized users only, it is not possible to retrieve user information in user verification request to get email address. Instead of getting username, directly ask for email address in the command argument to fix the issue.
=> kernelci.cli.user: fix user verification

kernelci/cli/user.py
Since GET `/users` request is now restricted to authorized users only, it is not possible to retrieve user information in password reset request to get email address. Instead of getting username, directly ask for email address in the
command argument to fix the issue.
=> kernelci.cli.user: fix password reset

kernelci/api/helper.py
It is very helpful to see platform name and runtime name. In lab case it include lab name and device name, for example.
=> api/helper: Add optional platform and runtime fields

config/core/build-configs-stable.yaml
Enable testing for `stable-rc` tree for Linux-6.6.y.
=> build-configs-stable: add `stable-rc_6.6`

config/core/test-configs.yaml, config/rootfs/debos/scripts/bullseye-gst-fluster.sh
Run the fluster Chromium 10-bit AV1 test suite on cherry and the H.264 fidelity range extension test suite on asurada, cherry, lazor, kingoftown and kevin Chromebooks.
=> Enable AV1 chromium 10-bit and H264 fr-ext tests

config/core/test-configs-chromeos.yaml
Enable tast decoder tests for AV1, H264, HEVC, VP8 and VP9 on the `mt8195-cherry-tomato-r2` Chromebook, on the `collabora-chromeos-kernel` tree.
Enable AV1 and HEVC fluster tests on the `collabora-chromeos-kernel` tree too.
=> CHROMEOS test-configs-chromeos.yaml: Enable tast tests and AV1, HEVC fluster tests on mt8195-cherry-tomato-r2

config/core/test-configs.yaml
This is another Meson board from Libretech with some new audio hardware
to test that I have in my lab, enable baseline tests plus tests relevant for
the platform support and also KVM since the board has VHE which we don't
currently have good coverage for.
=> test-configs.yaml: Add LibreTech Solitude

config/core/build-configs.yaml
Embed the scp.img firmware for mt8183 and mt8186 into the arm64-chromebook kernel, like was already done for other MediaTek chromebooks. This ensures the SCP can fully boot on those platforms independent of the rootfs used. In particular it makes the cros-ec-rpmsg check in the dt-kselftest pass.
=> build-configs.yaml: Add scp.img for mt8183/mt8186 to arm64-chromebook

config/core/test-configs.yaml
The Alta is another new board from LibreTech again based on an AMLogic
SoC, it uses the same PCB as Solitude but has a different lower end SoC
mounted.  Enable basic tests relevant to the hardware present on the
board.
=> test-configs.yaml: Add LibreTech Alta

config/core/test-configs.yaml
This is a STM32MP157A based board, including ethernet support. Enable
basic boot tests plus suites that cover specific features found on the
board.
=> test-configs.yaml: Add Avenger96

kernelci/api/models.py, kernelci/api/models_base.py, requirements.txt
Related to https://github.com/kernelci/kernelci-api/pull/433 (that PR depends on this one)
Bring the API models used by the user-facing endpoints from the kernelci-api repo to this one so that they can be used by the kernelci-api code and the helpers in this repo.
Bring the base model definitions here as well into a separate file (models_base.py) so that they can be used by the models here and by the internal kernelci-api models.
=> kernelci.api: refactor user-facing API models

config/core/test-configs.yaml
Let's take advantage of the ability of Avenger96 to boot the full
kselftest configuration, including adding the config fragment for the
ftrace tests which has been blocked by the issues with finding something
that can boot the kernel with all the kselftest options enabled.
=> test-configs: Additional kselftests for Avenger96

config/core/test-configs.yaml
The ftrace kselftests are very useful but currently we don't try to run
it, add the config fragment and enable it on Juno.  Since a config
fragment is required this will be a lot easier to deploy with the
kselftest-slim PR (https://github.com/kernelci/kernelci-core/pull/1759)
merged.
We will also need https://github.com/Linaro/test-definitions/pull/431
for this to be useful, at the minute the test is unconditionally skipped
everywhere by the Linaro skipfile due to what appear to be no longer
relevant reasons.
=> test-configs.yaml: arm64 ftrace selftsts coverage

kernelci/kbuild.py
This is initial implementation of kernel build steps, probably on very early stages and doesn't use properly other kernelci primitives and functions.
Main purpose is to reduce complexity and move out kernel build from jinja2 templates in pipeline. This can be also foundation to implement 3-step kernel build. (prepare, build, upload)
=> kernelci/kbuild.py: Initial kbuild offloading library implementation

config/core/build-configs.yaml
It seems qcom-lt tree changed location, and emitting error during jenkins monitor job. Updating to new URL.
=> build-configs.yaml: Update qcom-lt tree URL

config/core/test-configs.yaml
We are not covering the LKDTM selftests on any arm64 platforms since
while it's enabled for some of them we're struggling to run the
kselftest kernel on any of them.  Since Juno does currently seem to be
booting the kselftest kernels fine and has some bandwidth let's schedule
the LKDTM tests there.
=> test-configs.yaml: Enable LKDTM selftests on Juno

config/core/test-configs.yaml
The timeout for kselftest-ftrace is a little tight, at least on the
Avenger96 (which while fairly modern is still a 32 bit arm board), bump
the timeout up a bit so we don't get spurious timeouts - we were seeing
timeouts while getting the results off the board so don't need much.
=> test-configs.yaml: Increase timeout for kselftest-ftrace

config/core/test-configs.yaml
The DT selftests were only introduced in v6.7, don't try to run them on
stable kernels.  We should really block v6.1 as well but we're not doing
regexp matching here so the syntax is awkward, we can always improve
later.
=> test-configs.yaml: Block kselftest-dt in older kernels

kernelci/cli/user.py
Enable user to provide pagination arguments like `page_length` and `page_number` for `kci user find` command.
=> kernelci.cli: enable pagination arguments for `kci user find`

config/core/test-configs.yaml
The i.MX8MP has a video decoder IP, add coverage of the CODECs it
supports on the i.MX8MP boards we cover (all of them already have
stanzas).
=> test-configs.yaml: Add video decoder coverage for i.MX8MP

config/core/test-configs.yaml
The SoC on the Solitude has an upstream supported video decoder IP,
enable coverage for the CODECs it supports.
=> test-configs.yaml: Enable V4L decoder coverage on Solitude

config/core/test-configs.yaml
The SoC on the LibreTech Alta has a video decoder IP which is supported
upstream, enable coverage of the CODECs it supports.
=> test-configs.yaml: Enable video decoder coverage on Alta

kernelci/kbuild.py
In MongoDB, when you need to query nested fields where the field name includes dots (.), such as artifacts.job.txt, you face a common issue. MongoDB interprets the dots as separators for nested documents. We should avoid using dots in field names.
Suppose we have:
```
{
"artifacts": {
"job.txt": "data"
}
}
```
In this case, artifacts.job.txt is intended to be a single field name. However, MongoDB interprets artifacts.job.txt as artifacts -> job -> txt, assuming job is a nested document within artifacts, and txt is a field within job.
When you try to query this field directly, MongoDB will look for a nested structure rather than a field with dots in its name. This leads to confusion and errors in querying and manipulating data. To handle such field names, you typically need to use special …
=> kbuild.py: Map artifact fields to proper key names

config/core/test-configs.yaml
I've added two Renegade Elites to my lab (and whichever lab used to have
them seems to have removed them) so let's enable all the hardware
relevant tests that had been commented out.  Also enable kselftest-dt
since it's a DT based platform.
=> test-configs.yaml: Enable hardware relevant tests on Renegade Elite

config/rootfs/chromiumos/scripts/build_board.sh
This PR packs multiple small improvement and fixes to the `build_board.sh` script we use to build CrOS images:
* fixes a build failure when a single board/baseboard has multiple `chipset-*` parents (affects `baseboard-brya`)
* fixes script error when the compressed CrOS image already exists (e.g. when restarting the build after it previously failed at a later stage)
* ensure the repo remote and branch are properly determined even in cases where the repo owner is different from the user executing the script (e.g. a normal user and root, respectively)
=> CHROMEOS Small fixes for build_board.sh

config/core/test-configs.yaml
The Raspberry Pi platforms are DT based, enable the DT selftests for
those boards where we have NFS baseline tests enabled.
=> test-configs.yaml: Enable DT selftests for Raspberry Pi

config/core/test-configs.yaml
The Raspberry Pis have audio devices, enable the ALSA selftests to
provide some coverage of them.
=> test-configs.yaml: Enable ALSA selftests for Raspberry Pi 4B

kernelci/api/models.py
This patch was initially submitted as kernelci/kernelci-api#380 but required moving after merging kernelci/kernelci-api#433.
=> api.models: Add patchset field to node revision

kernelci/api/models.py
This is a workaround to remove error conditions during testing. Remove all "data" restrictions from Node subtypes, that is, allow extra fields and make all defined fields optional.
=> api.models: workaround: remove data restrictions from Node subtypes

kernelci/api/helper.py
Until now, if self._api.node.add(job_node) failed we got an exception but no reason about it. This commit unpacks the error provided by the server and propagates the exception to the caller.
=> kernelci.api.helper: unpack and propagate errors in create_job_node

kernelci/api/helper.py, kernelci/config/job.py, tests/configs/jobs.yaml
Add a new "kind" property to Jobs, so that we can define what "kind" of node each define Job should create.
=> Implement Job types

config/core/test-configs.yaml
The labs which have Raspberry Pi 4s (including mine) seem to have quite
a bit of free capacity with multiple devices available and frequently
idle so let's use the capacity to fill in some of our coverage, add some
LTP suites which we don't currently cover on arm64 together with the
core LTP smoke tests.  Since we currently only run the preempt RT tests
on systems with in order cores also add them here to ensure coverage
with out of order cores.
=> test-configs.yaml: Enable more test coverage for Raspberry Pi 4

config/core/build-configs-chromeos.yaml
Generic ChromeOS defconfig files have been renamed from `chromiumos-<arch>.flavour.config` to
`chromiumos-<arch>-generic.flavour.config`, let's update our configs to use the proper filenames from now on.
Fixes #2310
=> CHROMEOS build-configs-chromeos: fix defconfig filenames

config/core/test-configs.yaml, config/lava/kselftest/generic-depthcharge-tftp-nfs-kselftest-template.jinja2
Chromebook/Chromebox devices might operate with or without a battery.
The `kselftest-dt` test checks whether drivers are probed correctly, including the battery gauge driver. 
Use the battery LAVA tag to target only Chromebooks where the battery is actually connected, to avoid reporting false regressions.
Signed-off-by: Laura Nao <laura.nao@collabora.com>
=> test-configs.yaml: Use battery tag in kselftest-dt jobs for Chromebooks

config/runtime/base/kubernetes.jinja2
Scratch volume i believe deprecated feature from legacy system. Emptydir for workspace might improve compiling performance.
=> kubernetes.jinja2: Add emptydir compile volume, remove scratch

config/core/test-configs.yaml
The ALSA selftests were merged in v5.17 so there is no point in running them on older kernels, add a filter. We block all v5.x since there are no longer any active v5.x kernels based on anything newer than v5.15 so it's not worth the effort of writing the filter.
=> test-configs.yaml: Only run ALSA selftests where they exist

config/core/test-configs-chromeos.yaml
Enable fluster decoder tests on `mt8186-corsola-steelix-sku131072` for the H264, VP8 and VP9 formats.
Run the tests on the `for-kernelci` branch of the `collabora-chromeos-kernel` tree.
=> Enable fluster tests on corsola for collabora-chromeos-kernel tree

config/core/test-configs.yaml
The Raspberry Pi has a GPU called V3D and a display driver called VC4
both of which have specific tests in the IGT GPU tests, add coverage of
them on the Pi 4.  Since there are additional tests we need to duplicate
the test list in the VC4 entry, simply adding the new tests overwrites
the generic KMS tests.
=> test-configs.yaml: Add VC4 tests

kernelci/api/models.py
Add field to store job ID received from runtime for `kbuild` and `test` nodes.
=> kernelci.api.models: add `job_id` field to Node data

config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, kernelci/cli/job.py, kernelci/runtime/__init__.py, kernelci/runtime/lava.py
This PR allows to handle DTBs for arm64 devices by executing the following steps:
* download the `metadata.json` file from the `kbuild` job
* extract from this file the URL to the DTB as defined in the device type parameters
* add this to the node's artifacts list with the name `dtb`
The boot templates are modified accordingly and made device-agnostic in the process.
=> Handle DTB for devices requiring it

config/runtime/base/kubernetes.jinja2, kernelci/runtime/kubernetes.py
If we have multiple clusters defined in config - pick random one. This is enough for now.
=> runtime/kubernetes: Add trivial context load-balancing

config/runtime/base/kubernetes.jinja2
We are not using this feature/storage type in our environment.
=> kubernetes.jinja2: Remove ssh key from k8s template

kernelci/api/helper.py
Until now, if self.api._put() failed we got an exception but no reason about it. This commit unpacks the error provided by the server and propagates the exception to the caller.
=> kernelci.api.helper: unpack and propagate errors in submit_results

kernelci/cli/__init__.py
Introduce the `=~` operator (a la perl) to match a query parameter using a mongodb-compatible regular expression.
Requirement: https://github.com/kernelci/kernelci-api/pull/460
Examples:
`./kci node find "data.platform=~qemu"`
`./kci node find "name=~baseline"`
`./kci node fine "name=~x86"`
**NOTE**: Due to the query parameters translation done by the API, not every mongodb-compatible regex expression is supported. For instance: `./kci node find "state=~done|running"` won't work as expected.
=> kernelci.cli: add support for regexes in queries

config/core/rootfs-configs.yaml, config/core/rootfs-images.yaml, config/core/test-configs.yaml, config/rootfs/debos/scripts/debian-igt.sh
Old rootfs fails to build as one of subsystems require newer Meson.
=> igt: Update IGT rootfs to bookworm

kernelci/api/models.py
Free-form dict of debug attributes that can be used to specify debug flags in a node. These flags can then be used by the pipeline services to enable debug features, log additional traces or perform debug-specific actions.
Examples:
It could be used to define a checkout node to test-run the pipeline services, bypassing most actions and directly assuming "pass" (or "fail") for all results:
```
"debug": {
"dry_run": true,
"force_result": "pass" / "fail"
...
```
To make certain pipeline services more verbose:
```
"debug": {
"debug_log": ["scheduler", "tarball", "kbuild"]
```
To force certain artifacts instead of running actions to generate them:
```
"debug": {
"tarball": "https://mydomain.com/tarball"
```
The use cases are defined by the individual pipeline services and by the runtimes.
All …
=> api.models: new optional "debug" field for Nodes

config/docker/api.jinja2, config/docker/base/python-fixed.jinja2, config/docker/fragment/api.jinja2
Verification (on the assumption environment for `kci` tool is set and there is `kernelci-api` repo in the CWD parent):
```
diff <(./kci docker generate api) ../kernelci-api/docker/api/Dockerfile.production
```
Difference should only include:
- stripped license header (moved to a relevant fragment from which Dockerfile is generated)
- cosmetic changes in comments
Then build the image with: `./kci docker build --prefix=kernelci/ api`
Fixes: https://github.com/kernelci/kernelci-core/issues/2331
=> Add recipe for kernelci/api-production image

config/runtime/base/python.jinja2, kernelci/kbuild.py
Requirement: https://github.com/kernelci/kernelci-core/pull/2326
If the input node specifies a "dry_run" result in its debug parameters, bypass all the script running, artifacts upload, etc. and simply return the fake result.
=> Dry run support for python runtime and kbuild

kernelci/api/models.py, kernelci/runtime/kubernetes.py
Introduce `kcontext` instance variable to store k8s cluster name that ran the job in k8s runtime.
Implement `Kubernetes.get_context` to get the cluster name.
=> runtime/kubernetes: store k8s cluster name

kernelci/api/models.py
Add parameter that might help to explain infrastructure errors, if node went to state "fail".
=> api/models.py: Introduce new optional parameter error_code

config/runtime/boot/grub.jinja2, config/runtime/boot/u-boot.jinja2, kernelci/kbuild.py
We currently hardcode the kernel "type" in job templates requiring it, but this parameter can change depending on the target architecture and/or make target used to build the kernel: it is actually the lowercase kernel image filename.
For example, it should be `image` for arm64 devices, but `zimage` for arm32 ones.
Fixes https://github.com/kernelci/kernelci-api/issues/472
=> Dynamically generate kernel "type"

config/runtime/base/python.jinja2, kernelci/api/helper.py
PUT `/nodes` request is truncation `Node.data` field and only preserve value of `Node.data.kernel_revision`. Fix `submit_results` helper function to resolve the issue.
=> kernelci.api.helper: fix `Node.data` trucation

kernelci/api/models.py
We need to indicate when node reached timeout,
it is likely infrastructure issue, not real node failure.
=> models.py: Add node_timeout in errors

config/runtime/base/lava.jinja2
As noted by Mark, priority should be low, to not interfere with other lab jobs. We need to open issue also to make this value configurable at least per lab.
=> lava.jinja2: Hardcode priority as 10, lower than medium

config/runtime/base/python.jinja2
If any job-related code contain error, and generate exception, k8s will keep trying to re-run the job. This will prevent generating error code on exit, but still print useful debug information.
=> python.jinja2: Prevent exceptions from looping k8s nodes

config/docker/fragment/api.jinja2
Unfortunately pyproject.toml is not up to date in kernelci-api, so fall back to recipe similar as we are using on staging.
=> docker/api: Update recipe

kernelci/api/helper.py
To make rendering of test jobs simpler, without fetching or storing parent node data, inherit parameter kernel_type to test node from parent.
=> api/helper.py: Inherit data.kernel_type for tests

kernelci/runtime/lava.py
We need to retrieve job status, to know if it was executed properly or failed.
=> runtime/lava: Add method to get job status

kernelci/api/models.py
By mistake i defined error_code directly in node root, while this field might not exist for all kinds of nodes. Moving error_code in model definition to kbuild and test nodes.
=> models.py: Move error_code to data parent

kernelci/cli/__init__.py
Fixes https://github.com/kernelci/kernelci-core/issues/2368
Fix logging of HTTP exception when API returns `HTTP 422 Unprocessable entity` error.
=> kernelci.cli: fix `catch_error` for logging 422 HTTPError

kernelci/api/models.py
According to my local cli-based tests, this could be the missing bit for actually propagating this field to test nodes.
=> models: allow `kernel_type` field in kbuild/test node data

kernelci/cli/job.py, kernelci/config/__init__.py, kernelci/config/platform.py, kernelci/runtime/__init__.py, kernelci/scheduler.py
The current platform config is taken exclusively from the legacy `device_types` configuration. We have to parse similar parameters for the new system, avoiding collisions with legacy config.
This PR creates a new class for parsing the new system's config and makes use of it instead of the legacy config.
=> Get platforms/device types from pipeline configuration for the new system

config/rootfs/debos/overlays/cros-flash/opt/chromeos/install-modules
The new KernelCI system provides URLs with appended GET parameters for authentication, causing this script to fail due to some of those being URL-encoded in the base URL, but decoded in the file name.
This change fixes this behavior.
=> CHROMEOS rootfs: debos: cros-flash: fix install-modules for new system

config/core/build-configs.yaml, config/rootfs/debos/overlays/cros-flash/opt/chromeos/install-modules, config/runtime/base/lava.jinja2, config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, config/runtime/boot/u-boot.jinja2, config/runtime/chromeos/base.jinja2, config/runtime/tests/baseline.jinja2, config/runtime/tests/tast.jinja2, kernelci/kbuild.py
Chromebooks use a ChromeOS-specific test suite called "Tast", requiring a different workflow than baseline tests:
* those tests run under ChromeOS, requiring an altered boot process
* they involve more that just running a set of shell commands
=> Rework templates and add Tast tests

config/core/rootfs-images.yaml
We will start gradually updating rootfs images.
First verification - newer build of bullseye and in some cases bookworm.
=> rootfs-images.yaml: Update most of images to recent build

config/docker/fragment/kernelci.jinja2
As the support of building and installing `kernelci-core` package using `pyproject.toml` has been in place, delete a line to explicitly install requirements as the TOML would take care of it internally.
Fixes: cc937787 ("config/docker/fragment: update `kernelci.jinja2`")
=> fragment/kernelci.jinja2: drop requirements installation using `pip`

config/core/build-configs-stable.yaml
As per https://github.com/kernelci/kernelci-core/issues/2346 Adding two more trees to monitor
=> Add stable 6.7 trees

kernelci/api/models.py
For `int` fields, pydantic internally converts fields to integer if possible e.g. request field value `"2"` is converted to `2` in the FastAPI request handler for model parsing. That's why `KernelVersion.version` is converted to `int` when received by API.
Instead of relying on implicit data type conversion for `int` field, use `StrictInt` to enforce defined data type in the request itself.
=> kernelci.api.models: use `StrictInt` for version fields

kernelci/api/helper.py, kernelci/api/models.py
In order to perform effective api queries to search for regressions and test results we need to have these new fields in the models. In the case of tests, these will be populated from the parent node (either a kbuild or a test case node). In the case of regressions, they'll be taken from the associated test runs.
**WARNING:** Not tested locally.
=> Add data fields to Test and Regression models

kernelci/api/helper.py, kernelci/kbuild.py, pyproject.toml, setup.cfg
```
We're littering the code with #noqa markers just to make pycodstyle
happy, particularly wrt the length of some lines. While we try to keep
code lines reasonably short (<80 chars), some other lines are harder to
read or more cumbersome to maintain if they're forced to be
splitted (for instance, long strings).
Disable this check (E501). Please, keep being mindful of the length of
code lines, try to stay below 80 chars except in reasonable
situations. Use good judgement.
```
=> Disable pycodestyle warning for long lines and cleanup noqa markers

kernelci/cli/job.py
**LOW PRIORITY AND IMPACT PR**
The option to give a json node definition as a node input is both unsync'd with create_job_node() and unused. Remove it to avoid confusion.
Also, make the "input_node_id" option mandatory as an argument.
=> kernelci.cli: remove unused option for kci job new

kernelci/api/__init__.py
PR https://github.com/kernelci/kernelci-core/pull/2406 assume headers will be set correct, but seems they are not, and on kci user token by some reason it set headers as json. This PR fixes that.
=> api: Fix incorrect headers

config/rootfs/debos/rootfs.yaml
When we install Debian packages with apt these will be placed in
/var/cache/apt/archives, there is no need for them at runtime so we can
just remove them and reduce the size of the images.
=> rootfs: Don't ship .deb files we installed

config/rootfs/debos/rootfs.yaml
The rootfs images are quite large and get sent over the network a lot so
it's probably worth spending some CPU cycles trying to make them
smaller, ask xz and gzip to use maximum compression.  While we're at it
also allow xz to use all the available CPUs for compression to speed
things up a bit.
=> debos: Ask for maximal compression of the rootfs images

config/rootfs/debos/rootfs.yaml, config/rootfs/debos/scripts/strip.sh
The strip.sh script is passed a list of packages to remove.  For very
unclear reasons the list that is passed by debos is the extra_packages
list but this is a list of packages we want in the shipped image, there
is a separate extra_packages_remove which is intended for removal which
we already handle with a separate debos step.  Just remove the argument
and it's handling from strip.sh, ensuring that we don't remove
extra_packages.
This hasn't been apparent because strip.sh only takes effect for ext4
images, we don't use those images for many platforms.  That is a
separate issue which should also be addressed.
=> debos: Don't remove extra_packages

kernelci/kbuild.py
During development, executing `kci` and kernel build scripts from the root of the `kernelci-core` source tree is common practice. In such cases, instead of mandating the developer to create/update those under `/etc/kernelci`, we should look for the config file under `config/` first.
=> kbuild: look for legacy config in current folder first

kernelci/kbuild.py
Currently, `cros://` fragments used as a defconfig are special-cased so the defconfig node data is updated with the actual branch. However, this is done after `config_full` is updated, resulting in the latter still containing the `{kver}` placeholder.
This PR reworks this logic so we update all variables properly, and adds the ability to also use the `{arch}` placeholder in fragment names.
=> kbuild: improve cros defconfig handling

kernelci/api/models_base.py
Implement a dataclass `Index` to store model field names and constraints to create indexes. Also, write a method to get indexes to be implemented by child class.
=> kernelci/api/models_base: dataclass to store DB indexes

kernelci/runtime/docker.py
As in docker-compose.yaml we need to add mapping
in docker runtime, so we can access local instance of API.
=> Add hostname mapping for docker gateway

config/docker/fragment/kernelci.jinja2
Before `pyproject.toml` support, when `setup.py` was being used for package building, developer requirements were also installed in the package. Keep it the same while using `pyproject.toml` by adding `[dev]` option to the installation command.
=> Build `kernelci` package with developer requirements

config/runtime/tests/tast.jinja2
The legacy implementation relied on Tast tests being listed as a single string in the job config, then uses the `wordwrap()` jinja2 function to output one test per line in the job definition.
This is needlessly complex, storing the list of tests as a string array and using a classic `for` loop makes things more straightforward and understandable to external contributors.
=> config: runtime: tests: tast: use "for" loop to enumerate tests

config/core/rootfs-configs.yaml
The mm selftests require liburing. The binaries error out if liburing
isn't found at runtime. This will fix the following class of errors:
error while loading shared libraries: liburing.so.1: cannot open
shared object file: No such file or directory
https://lava.collabora.dev/scheduler/job/12674655#L3643
=> rootfs-configs.yaml: Add liburing for mm selftests

config/core/rootfs-configs.yaml
A recent change[1] to test-definitons has added use of the Python tappy
package when parsing the kselftest output in order to deal better with
nested KTAP output, especially useful with the MM selftests.  Add the
tappy package to our ksselftest rootfs images so that it's there when we
update to the latest test-definitions version.
[1] https://github.com/Linaro/test-definitions/commit/6e2cfcd26c4c805c4a3061dc22cf46c1b9b47f4b
=> rootfs-configs.yaml: Add tappy to the kselftest images

kernelci/api/__init__.py
Fixes 6e8d6c5b8dec943431c1f9d305cba1fd11d0f34d, see also a6df5594ca6508869fd3438310da4b902aa0c785.
The requests library can automatically encode data as json and set the proper Content-Type header. Remove the default header hardcoding in the requests and use the `json` option of the requests calls.
In the `_post` method, this is selectable and it accepts json data (by default) or a www-form-urlencoded string payload.
=> kernelci.api: remove manual json data handling in requests

kernelci/api/helper.py
When submitting test results via `submit_results()`, a tree of nodes is created hanging from a root node. These nodes aren't created in the same way as nodes built with `create_job_node`, where certain node types will inherit specific parameters from the parent node. Fix submit_results() so that the child nodes will inherit additional data parameters if they're defined in the parent node.
=> kernelci.api.helper: make node hierarchies inherit parameters from parent

kernelci/api/helper.py
Apparently, not all HTTPErrors raised by requests to the server are formatted as json. Remove the json parsing to propagate the raw response text to the caller.
=> kernelci.api.helper: disable json parsing in error propagation

kernelci/api/models.py
Do not translate version fields with `None` value. Fix below error:
```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
=> kernelci.api.model: fix version translation

kernelci/api/helper.py, kernelci/cli/job.py, kernelci/config/job.py, kernelci/config/platform.py, kernelci/config/runtime.py, tests/configs/jobs.yaml, tests/configs/lava-runtimes.yaml, tests/configs/runtimes.yaml
As all devices might not be equally supported by all kernel trees and versions, this PR implements filtering based on rules defined per job, platform and/or runtime. This is achieved by setting rules affecting any field present in the node structure, with the ability to provide both allowed and forbidden values.
If one of those items include at least one such rule, checks will be conducted during node creation, which will be aborted if one of the rules isn't satisfied.
For example, a job can be configured to run only on arm64 devices, with a kernel version >= 6.6, built with any defconfig except `allnoconfig`, and using the `kselftest` fragment but not the `arm64-chromebook` one, by adding the following to the job definition:
```yaml
rules:
min_version:
version: 6
patchlevel: 6
arch:
- …
```
=> Implement initial filtering capabilities

kernelci/api/helper.py, kernelci/api/models.py
Currently, tests and regressions only contain the defconfig info from the kbuild but not the config fragment info. The easiest way to do it is to pass the complete 'config_full' field downwards.
Remember that in KernelCI, knowing the "defconfig" of a kernel build may be only a partial picture of the whole config, since the complete config applied to the kernel may include any number of additional KernelCI-defined config fragments.
=> Define config_full in models and propagate it to test and regression nodes

kernelci/runtime/lava.py
Currently, the `submit()` method includes a round-trip through the `yaml` module, which is needed to ensure the job will be properly formatted for LAVA. This includes, for example, processing commands span over multiple lines.
However, this implies the submitted job is different from the output from `generate()`, which can cause issues, for example when using `kci job generate` which relies solely on the latter and doesn't reflect how the job data is processed in `submit()`. This can ultimately to a false sense of correctness when testing locally, while an actual pipeline run will cause errors due to the additional processing.
In order to avoid such cases, ensure the output from `generate()` is identical to the submitted job by moving the yaml round-trip earlier in the chain.
=> runtime: lava: generate job as it will be submitted

config/runtime/base/python.jinja2, kernelci/kbuild.py
This hopes to ease the work of ensuring nodes only reference the artifacts they create.
Requires https://github.com/kernelci/kernelci-pipeline/pull/453 on the pipeline side.
=> Fetch `tarball` artifact from parent if not present in node

kernelci/api/helper.py, kernelci/config/scheduler.py, kernelci/legacy/cli/sched.py, kernelci/scheduler.py, tests/configs/scheduler.yaml
The filtering capabilities implemented in #2413 only apply to job and platform entries. It could, however, be useful to add such capabilities to scheduler entries as well.
This PR ensures the generic mechanisms for doing so are in place, but the actual filtering will be executed within [kernelci-pipeline](https://github.com/kernelci/kernelci-pipeline)
=> Apply rules to scheduler entries as well

kernelci/runtime/__init__.py
In some cases, for example incorrectly set dtb for x86, we might crash cause metadata file wont exist for such platforms.
=> runtime: prevent crash on missing metadata

kernelci/api/models.py
Add these two fields to regression data, they will be used to carry the error_code and error_msg fields from the failed node.
=> kernelci.api.models: add error_code and error_msg to regressions

config/runtime/boot/u-boot.jinja2
Update the kselftest rootfs URL to the latest one which includes tappy, and is thus able to parse the kselftest results without throwing an error:
ModuleNotFoundError: No module named 'tap'
=> config: runtime: boot: Use latest kselftest rootfs to avoid tap issue

kernelci/cli/job.py
In most situations, jobs need artifacts generated by their parent. As those are no longer automatically propagated, we need to import them when generating the job.
=> cli: job: import artifacts from parent node before generating job

config/runtime/base/lava.jinja2, kernelci/api/helper.py, kernelci/cli/job.py, kernelci/config/base.py, kernelci/config/job.py, kernelci/config/platform.py, kernelci/kbuild.py
Our config files currently have to specify lots of nearly-identical parameters, especially for chromebooks. Those parameters usually depend on the device/job target architecture, name or family.
In order to make things more flexible and reduce config verbosity, this PR implements string formatting for job/platform params, substituting placeholders with the values of the corresponding object attributes.
A special `krev` placeholder is also handled: it doesn't match any object attribute, but it is constructed from the code as the kernel revision in the form `major.minor`, extracted from node data.
Example:
```yaml
chromebook-device: &chromebook-device
arch: arm64
mach: mediatek
params:
myconfig: 'config-{arch}-{mach}-{base_name}.config'
device-1: *chromebook-device
device-2:
<<: …
```
=> Format config params using objet attributes

kernelci/api/helper.py
When creating a new job node, we don't want it to automatically inherit the parent node artifacts. This leads to nodes carrying irrelevant information in most cases, such as test nodes including the build artifacts of the parent kbuild node.
@nuclearcat let's see how this works in staging first and then we can decide whether it's worth it or not.
=> kernelci.api.helper: don't inherit parent node artifacts

kernelci/runtime/lava.py
Fixes https://github.com/kernelci/kernelci-api/issues/470
Node result is missing for nodes with child test nodes e.g. `dmesg` or `tast` nodes. Get the suite node result and set it while getting node hierarchy.
=> kernelci/runtime/lava: fix missing node result

config/core/build-configs-stable.yaml
- build-config-stable.yaml: Add coverage for v6.7 stables
- build-configs-stable.yaml: Correct indentation for v6.7 queue entry
- build-configs-stable.yaml: Add v6.8 stable coverage
=> build-configs-stable.yaml: Some fixes and an update for v6.8

kernelci/kbuild.py
After fixing stderr/stdout file we got lost DTBS_CHECK_OK/FAIL result trigger in build.log output, return it back.
=> kbuild: Fix back dtbs_check "magic word"

config/core/build-configs.yaml, config/core/rootfs-configs.yaml, config/core/rootfs-images.yaml, config/core/test-configs.yaml, config/lava/wifi/generic-depthcharge-tftp-nfs-wifi-template.jinja2, config/lava/wifi/generic-grub-tftp-nfs-wifi-template.jinja2, config/lava/wifi/generic-qemu-wifi-template.jinja2, config/lava/wifi/generic-uboot-tftp-nfs-wifi-template.jinja2, config/lava/wifi/wifi.jinja2, config/rootfs/debos/overlays/wifi/usr/bin/wifi-basic-parser.sh
Add support for a basic WiFi test and run it on an initial set of target Chromebooks, based on the WiFi chip:
- Intel(R) Wi-Fi 6 AX201 160MHz - `asus-cx9400-volteer`
- Intel(R) Wi-Fi 6E AX211 160MHz -  	`acer-cbv514-1h-34uz-brya`
- Intel(R) Wi-Fi 6 AX200 160MHz - `lenovo-TPad-C13-Yoga-zork`
- Intel(R) Dual Band Wireless AC 7265 - `hp-x360-14-G1-sona`
- Intel(R) Wireless-AC 9560 160MHz - `dell-latitude-5400-8665U-sarien`
- Marvell SD8897-B0 - `mt8173-elm-hana`
- RTL8852AE - `acer-cp514-3wh-r0qs-guybrush`
- RTL8822CE - `asus-CM1400CXA-dalboz`
- QCA6174 - `acer-R721T-grunt` , `mt8183-kukui-jacuzzi-juniper-sku16`
- mt7921e - `mt8195-cherry-tomato-r2`
=> Add WiFi basic test

config/core/test-configs.yaml
There is a video CODEC block with upstream support on the Le Potato,
enable the V4L2 decoder tests for the CODECs it supports.  It also
supports MJPEG but that doesn't seem to be a suite we cover.
=> test-configs.yaml: Enable V4L decoder tests on Le Potato

config/core/test-configs.yaml
The i.MX6 SoCs on the UDOO boards have a video decoder, enable coverage
of H.264.  There are a number of other CODECs supported and there is
encoding support but we don't have testsuite stanzas for them.
=> test-configs.yaml: Basic coverage for video decode on Udoo

config/core/rootfs-images.yaml
By mistake it was updated, while not buildable for now.
=> rootfs-images.yaml: Fix buildroot image

kernelci/api/models.py
Fixes https://github.com/kernelci/kernelci-api/issues/451
When using `Any` for event payload `data` field allows all the values including `None`. Events with `None` payload will break pipeline services as per current design. Update the field to be mandatory and dictionary type to make it compatible with pipeline service usage.
=> kernelci.api.models: fix event payload data type

config/lava/baseline/baseline.jinja2
Unfortunately bootrr tests introduce more noise than useful results. Disable them for now.
=> baseline: Disable bootrr tests

kernelci/kbuild.py
It often happens k8s containers have unreliable DNS, retry download on DNS error
=> kbuild: wget retry on DNS error

config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, config/runtime/boot/u-boot.jinja2, config/runtime/chromeos/base.jinja2, kernelci/config/platform.py, kernelci/runtime/__init__.py
Device-tree files can be renamed upstream, like it happened for the `trogdor-kingoftown` Chromebook during the 6.4 developement cycle. In such cases, we have to provide several possible file names and select the appropriate one based on which files are present in the test kernel artifacts.
This PR makes it possible to store either a single string or a list of values in the platform config `dtb` field, and stores the selected value as a top-level `device_dtb` parameter to be used by templates. It also includes the corresponding rework of the existing templates.
To be merged in sync with https://github.com/kernelci/kernelci-pipeline/pull/495
=> Allow listing multiple dtbs for a single platform

kernelci/kbuild.py
Don't fail kernel build if kselftest failed to build, as it's normal for some old kernels like 4.19.
=> kbuild: Make kselftest build non-critical

config/docker/api.jinja2, config/docker/base/python.jinja2
Depends on https://github.com/kernelci/kernelci-api/pull/504
Fixes https://github.com/kernelci/kernelci-api/issues/479
Since Python 3.11 support has been enabled for API, use the same version for building `api` docker image.
Remove conditional block from `base/python.jinja2` that was used to decide Python version as a part of a temporary solution for API until it supports Python 3.11.
=> T40464 config/docker/api.jinja2: use python 3.11

kernelci/api/models.py
Encode the concept of "active" and "inactive" regressions. A regression is "active" if the test is still failing after the failure was introduced. The regression has "fail" as a result. A regression is "inactive" if the test has passed after the regression was created. The regression result in this case is "pass".
A new "node_sequence" field to stores the list of failed test runs after the first failure for active regressions. For inactive regressions it stores up to the first passing test run.
=> kernelci.api.models: node_sequence field in regressions data

kernelci/api/helper.py, kernelci/api/models.py, kernelci/legacy/cli/show.py, tests/api/conftest.py
Related issue: https://github.com/kernelci/kernelci-core/issues/2462
**NOTE**: This should be merged before https://github.com/kernelci/kernelci-api/pull/503 , but that PR includes the DB migration script required for this change.
=> Encode a Node path using a regular slash-separated string instead of a string list

kernelci/api/helper.py, kernelci/api/models.py, kernelci/legacy/cli/show.py, tests/api/conftest.py
Reverts kernelci/kernelci-core#2466
=> Revert "Encode a Node path using a regular slash-separated string instead of a string list"

kernelci/api/helper.py, kernelci/api/models.py
If this field have defined list, schedulers in pipeline can schedule jobs ONLY specified in list.
This might be useful for bisection, so custom checkout will make node that will run only specific build(s) and specific test(s).
=> models: Add jobfilter field

config/core/test-configs-chromeos.yaml
We experience a lot of failures due to `platform.Histograms` no longer existing. Moreover, recent investigations confirmed that `platform.Memd` and `platform.DLCService*` simply cannot run on mainline kernels, as they rely on downstream ChromeOS features.
=> CHROMEOS test-configs-chromeos: drop failing/absent tests

config/docker/data/tast_parser.py
This script was initially meant to run only once, running Tast tests and parsing the corresponding results in a single operation. However, there isn't any obligation to enforce such a behaviour. It can even be useful to split those functionality and choose to either run the tests or parse the results using command-line options.
This change introduces the `--run` and `--results` flags to this effect: if either of those is present, only the corresponding feature will be executed; otherwise, we revert to the previous behaviour in order to maintain compatibility with the legacy system.
When called with `--results`, the script will return the number of failed tests, allowing us to mark the whole test suite as failed in this case.
=> config: docker: data: tast_parser: split functionality

config/docker/data/tast_parser.py
This script was initially meant to run only once, running Tast tests and parsing the corresponding results in a single operation. However, there isn't any obligation to enforce such a behaviour. It can even be useful to split those functionality and choose to either run the tests or parse the results using command-line options.
This change introduces the `--run` and `--results` flags to this effect: if either of those is present, only the corresponding feature will be executed; otherwise, we revert to the previous behaviour in order to maintain compatibility with the legacy system.
This is basically #2478 but targetting the `chromeos` branch, which is the one used for actually building the docker images.
=> CHROMEOS config: docker: data: tast_parser: split functionality

config/docker/api.jinja2, config/docker/fragment/api.jinja2
Atm we are building and installing `kernelci` python package from `api.jinja2` template to avoid python package version conficts while building `api` with `kernelci` fragment.
Since the support for Python 3.11 has been enabled for API, that issue has been resolved. Now, we should be able to use `kernelci` fragment to build `api` docker image as per the normal practice for all `core` docker images. An attempt has already been done to create `api` docker image with `kernelci` fragment and that requires `pymongo` related package adjustment for underlying `bson`.
Details can be found here: https://github.com/kernelci/kernelci-core/pull/2485#issuecomment-2029743842
To avoid these adjustments, use `api` as fragment for `kernelci` image. Fix `WORKDIR` in the `api` fragment template as `api` will …
=> config/docker/fragment/api.jinja2: modify `WORKDIR`

config/docker/fragment/pipeline.jinja2, config/docker/pipeline.jinja2
This patch duplicates the whole `kernelci/k8s:kernelci` image recipe so that it can be built without depending on it as a base image.
The same result could be achieved by:
```
kci build --prefix=kernelci/ k8s kernelci pipeline
```
Resulting image would be `kernelci/k8s:kernelci-pipeline`. To get `kernelci/pipeline` image out of it, retagging image would be required (which could result in more confusion in staging/production deployment scripts) or alternatively providing a custom name at build (which would require rewriting name handling in `kci docker` tool).
This duplication will probably require revisiting in the future but for now the key deliverable is to provide versioned production images using `kci docker` tool.
Fixes: #2350
=> Add recipe for kernelci/pipeline image

config/docker/data/tast_parser.py, config/runtime/chromeos/base.jinja2, config/runtime/tests/tast.jinja2
This is the counterpart to #2497 for the new system.
Similarly, it implements the following to ensure Tast tests are (a bit) more reliable:
* implement proper shutdown at the end of Tast tests
* identify `self_repair` boot message as a failure, so we can more quickly spot (and fix) corrupt devices
Depends on #2496
=> Improve the reliability of Tast tests and detect corrupt devices

kernelci/scheduler.py
```
today at 4:52:34 PM04/02/2024 01:52:34 PM UTC [ERROR] Traceback (most recent call last):
today at 4:52:34 PM  File "/home/kernelci/pipeline/base.py", line 69, in run
today at 4:52:34 PM    status = self._run(context)
today at 4:52:34 PM             ^^^^^^^^^^^^^^^^^^
today at 4:52:34 PM  File "/home/kernelci/./pipeline/scheduler.py", line 190, in _run
today at 4:52:34 PM    for job, runtime, platform, rules in self._sched.get_schedule(event):
today at 4:52:34 PM  File "/usr/local/lib/python3.11/site-packages/kernelci/scheduler.py", line 44, in get_schedule
today at 4:52:34 PM    for config in self.get_configs(event, channel):
today at 4:52:34 PM  File "/usr/local/lib/python3.11/site-packages/kernelci/scheduler.py", line 39, in get_configs
today at 4:52:34 PM    if sched_event.items() …
```
=> scheduler: Fix crash if event is str

config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, config/runtime/boot/u-boot.jinja2, kernelci/config/base.py
This PR adds new, "virtual" (i.e. not used directly in config files), attributes for platform configuration in order to make it easier to account for differences in architecture strings used by the different systems (e.g. `x86` for Buildroot, `amd64` for Debian, `x86_64` for ChromeOS). More specifically, the following attributes are now available:
* `crosarch` for the ChromeOS-compatible architecture string
* `debarch` for the Debian version
* `karch` for the one used by the Linux kernel and Buildroot
The `boot` templates are modified to use those new properties instead of plain `arch`.
Closes #2500
=> Add system-specific "arch" fields to account for differences

kernelci/api/models.py
Add `error_code` and `error_msg` fields to Checkout `data` field to store failure information.
Define `CheckoutErrorCodes` that is an enumeration for failures in checkout operation.
=> kernelci/api/models: store error information to checkout node

kernelci/api/__init__.py
We have very often pipeline crashes due intermittent network issues. With proper retry strategy (retry with backoff) we can try to mitigate that.
=> api: Improve retry strategy on _post calls

config/runtime/tests/tast.jinja2
Currently, we try to ping the DUT indefinitely, leading to the job to timeout after 30 mins. This is way too long and impacts other users, so we should limit the number of retries and raise an error if the device is unreachable.
This change ensures the job fails after 2 mins (60 iterations, 1s for `ping` + 1s for `sleep` per iteration).
=> config: runtime: tests: tast: fail early for unreachable devices

config/lava/chromeos/cros-tast.jinja2
Currently, we try to ping the DUT indefinitely, leading to the job to timeout after 30 mins. This is way too long and impacts other users, so we should limit the number of retries and raise an error if the device is unreachable.
This change ensures the job fails after 2 mins (60 iterations, 1s for `ping` + 1s for `sleep` per iteration).
Cherry-pick of #2515 for the legacy system.
=> CHROMEOS config: lava: cros-tast: fail early for unreachable devices

config/core/build-configs.yaml
media tree is broken for several month and seems nobody is going to repair it, so disabling for now as it is breaking jenkins jobs:
```
+ kci_build update_repo --build-config=media --kdir=/data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/configs/media --mirror=/data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/linux.git
Cloning into '/data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/configs/media'...
warning: remote HEAD refers to nonexistent ref, unable to checkout
fatal: couldn't find remote ref HEAD
```
=> build-configs.yaml: Disable media tree

kernelci/api/models.py, kernelci/runtime/lava.py
In case we experience problem during template rendering, we often cannot identify even task caused this exception.
Add some more debug to help with that.
=> runtime/lava: Generate more info on exception

config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, config/runtime/boot/u-boot.jinja2, kernelci/config/base.py, kernelci/runtime/__init__.py
We currently allow using the `crosarch`, `debarch` & `karch` virtual
params in configuration files, but those should also be accessible from
job templates. This used to be possible with the initial implementation
as those were part of the `Platform` config object, but this was changed
as it caused negative side effects.
As the current implementation is more robust, stick to it but make it
available to other modules so we can make those params usable from
`Runtime` objects.
=> kernelci: update system-specific arch params in runtime.get_params()

config/core/build-configs.yaml
Jobs submitted from LAVA always pass an ip= parameter to the kernel (eg on depthcharge see [1]).
Chromebooks wired to the network using a servo board rely on the RTL8152 driver in order to have a working network interface.
Since the RTL8152 driver is currently enabled as a module in the arm64 defconfig, it is only available once the ramdisk loads the modules. However, due to the ip= parameter, the kernel tries to do IP auto configuration before the ramdisk has loaded, but since there are no network interfaces available, it waits for 12 seconds, in order to wait for some potential slow interfaces to get up [2], before carrying on with the boot process. Meanwhile, when 10 seconds elapse between the registering of two consecutive drivers, the deferred probe timer times out, which can result …
=> build-configs.yaml: Prevent deferred probe timeout errors

kernelci/api/helper.py
Enable sending `data` dictionary fields from root node while submitting hierarchy of results.
=> kernelci.api.helper: fix `submit_results`

.github/workflows/rootfs.yml
For staging we need to specify repo and branch, by trusted user, from where to generate experimental rootfs.
=> workflows: rootfs generator updates

kernelci/api/helper.py
Probably due some bug this key was missing in some cases.
=> api/helper.py: Don't crash if kernel_revision is missing, but report error

kernelci/runtime/lava.py
Fixes https://github.com/kernelci/kernelci-core/issues/2522
It seems like not all the failed lava jobs has
failure metadata available.
Fix the below error observed on staging for some
failed jobs:
```
29/04/2024 11:38:45 Traceback (most recent call last):
29/04/2024 11:38:45   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
29/04/2024 11:38:45     self.run()
29/04/2024 11:38:45   File "/usr/local/lib/python3.11/threading.py", line 982, in run
29/04/2024 11:38:45     self._target(*self._args, **self._kwargs)
29/04/2024 11:38:45   File "/home/kernelci/pipeline/lava_callback.py", line 93, in async_job_submit
29/04/2024 11:38:45     hierarchy = job_callback.get_hierarchy(results, job_node)
29/04/2024 11:38:45 …
```
=> kernelci.runtime.lava: fix setting failed job metadata

kernelci/api/models.py, kernelci/runtime/lava.py
It can be useful to know the exact device on which a job ran, without having to open the LAVA job page. Ensure this is possible by adding a new `get_device_id()` method to the `Callback` class.
=> kernelci: runtime: lava: add method for retrieving device ID

config/core/build-configs.yaml
Add in the arm64-chromebook config fragment the firmware required by MT8195-Cherry-Tomato to successfully probe the sound card. This change can be verified by checking that the '/mt8195-sound' test case in the kselftest-dt test now passes.
LAVA run before: https://lava.collabora.dev/scheduler/job/12640584
LAVA run after: https://lava.collabora.dev/scheduler/job/12640545
=> build-configs.yaml: Add missing firmware for sound on MT8195-Tomato

config/core/build-configs.yaml, config/core/test-configs.yaml
The videodec fragment was created to hold configs for decoder support, required to run decoder conformance tests on Chromebooks. The fragment is currently holding only one config for the kevin Chromebook, while decoder specific configs for other platforms were added to the arm64-chromebook fragment instead. Add the CONFIG_VIDEO_ROCKCHIP_VDEC
option to the arm64-chromebook fragment and drop the videodec one.
=> Merge videodec and arm64-chromebook fragments

config/core/build-configs.yaml
Some devices in Collabora's lab are connected to the wired network using an ASIX AX88772B ethernet adapter. The kernel config for it needs to be enabled in order for tests that require working network to succeed. Furthermore it needs to be builtin for the same reason as commit ed888aa7f200 ("build-configs.yaml: Prevent deferred probe timeout errors").
Since this is specific to the hardware used at the Collabora lab, add a new config fragment for it.
@laura-nao Talking to you I got the impression the ASIX adapter is something standalone and specific to Collabora's setup. Can you confirm that? The alternative would be that the ASIX adapter is present in a newer revision of the servo board, in which case I'd consider it a generic setup, and include this config in the `arm64-chromebook` …
=> build-configs.yaml: Add fragment with Collabora lab specific configs

config/rootfs/debos/overlays/baseline/opt/kernelci/dmesg.sh
Update the exit code for the dmesg test script to return 1 in the event of one or more test cases failing. This ensures that when the test is executed in LAVA, the overall pass/fail status of the dmesg test suite reflects the outcome of the individual test cases (i.e. status should be fail if any test cases fail).
=> config/rootfs: dmesg.sh: Change exit code for dmesg test script

config/docker/data/tast_parser.py
In some cases (e.g. the DUT crashes while running one testcase), the Tast run might not finish but still yield important results, which we're losing if we error out before parsing them.
This change ensure we report existing results and only then error out in such cases.
Manually tested in LAVA: https://lava.collabora.dev/scheduler/job/13841947
As expected, the job fails ("Incomplete") but reports the results of tests which actually ran.
=> CHROMEOS config: docker: data: tast_parser: report results then exit

config/runtime/tests/tast.jinja2
Calling `sync` after running Tast tests was a leftover from an old version, but it's been made useless as we now properly power off the device, with the kernel automatically performing this operation during shutdown.
This call failing caused wrong results to be reported, so let's drop it entirely.
=> config: runtime: tests: tast: drop useless "sync"

kernelci/kbuild.py
Some configuration doesn't build modules,
we should not attempt to build them.
=> kbuild: Add option to not install modules

config/core/api-configs.yaml, config/core/db-configs.yaml, config/core/storage.yaml
Update YAML configurations for staging instance.
Rename staging instance entries from `staging.kernelci.org` to `staging` to simplify TOML section names.
The the same convetion has been used here for similar reasons: https://github.com/kernelci/kernelci-pipeline/commit/1991f2cfd18fe0fde12c3a13c8738f381f483aa5
=> config/core: rename staging entry

kernelci/api/helper.py, tests/api/test_api.py
Depends on https://github.com/kernelci/kernelci-api/pull/529
PubSub event data has a field called `is_hierarchy` to distinguish events of submission of hierarchy of results from a single node submission.
Return this field value from `APIHelper.receive_event_node` method along with node.
=> kernelci.api.helper: get `is_hierarchy` from event data

config/docker/data/tast_parser.py
When the test run failed before yielding a single result, the JSON file containing the results is missing. This leads to an exception being raised, rather than properly erroring out with a meaningful message.
Avoid this issue by ensuring the file is present before opening it.
=> CHROMEOS config: docker: data: tast_parser: handle missing results file

config/core/build-configs.yaml
I'm still seeing long boot delays on mt8186-steelix: https://lava.collabora.dev/scheduler/job/13696724 . Upon closer inspection I see `CONFIG_USB_USBNET` is `=y`, but `CONFIG_USB_NET_AX8817X` is `=m`, even though it's supposed to be builtin by default. So I'm enabling it explicitly here, which should hopefully fix the issue. Since I was adding one more config for the ethernet adapters it seemed a good moment to do the move to a separate lab-setup fragment. Fixes #2540.
---
Add a new fragment to contain configurations required for the lab setup which, at least for now, consists of builtin network and NFS support.
These configs come from the arm64-chromebook and x86-board fragments, but aren't removed from those fragments for now in order to not impact legacy KernelCI.
An extra config, …
=> build-configs.yaml: Add lab-setup fragment

config/core/build-configs.yaml
Enable the driver for the Elan Touchpad devices, found on some of the x86 Intel Chromebooks.
Should have been part of https://github.com/kernelci/kernelci-core/pull/2556 , but I forgot to add it.
=> build-configs.yaml: Enable Elan Touchpad driver found on x86 Intel Chromebooks

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/debian-igt.sh
During armhf build we noticed disk space issues.
https://github.com/kernelci/kernelci-core/actions/runs/9280775475/job/25535588226
```
2024-05-29T05:35:03.8358631Z 2024/05/29 05:35:01 a630_sqe.fw | cat: write error: No space left on device
```
=> rootfs-configs.yaml: Increase image size for igt

kernelci/runtime/lava.py
We might need to retrieve log as variable in some cases in LAVA callback.
=> runtime/lava: Introduce method to get log to variable

config/lava/chromeos/cros-boot.jinja2
There are numerous cases where LAVA either fails to recognize the login (and/or shell) prompt, leading to a job failure even if everything actually goes well.
Allowing `boot` actions to be retried is an effective way to work around those issues and reduce our waste of resources time.
=> CHROMEOS config: lava: chromeos: cros-boot: retry boot actions

config/runtime/boot/fastboot.jinja2
qcs6490-rb3gen2 corresponds to gen 2 of Qualcomm robotics kit. This device type is pre-configured to use "fastboot boot" as boot method.
=> config: add qcs6490-rb3gen2 device type

config/core/build-configs.yaml, config/runtime/tests/watchdog-reset.jinja2
Add template for watchdog reset test. Enable the required watchdog configs to run the test on x86_64 and arm64 Chromebooks.
=> Add watchdog reset test template and enable watchdog configs

kernelci/config/job.py, tests/configs/jobs.yaml
Every KernelCI test job will have mapping to KCIDB test suite name to unify the test names with other CI systems.
Add `kcidb_test_suite` attribute to job configurations that will store the mapped KCIDB test suite name.
=> kernelci.config.job: add attribute 'kcidb_test_suite'

config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, config/runtime/boot/u-boot.jinja2, config/runtime/chromeos/base.jinja2
There are numerous cases where LAVA either fails to recognize the login (and/or shell) prompt, leading to a job failure even if everything actually goes well.
Allowing `boot` actions to be retried is an effective way to work around those issues and reduce our waste our resources time.
=> config: runtime: allow to retry boot actions

config/runtime/tests/tast.jinja2, kernelci/api/helper.py, kernelci/api/models.py, kernelci/runtime/__init__.py, kernelci/runtime/lava.py
- Introduce `Job` model for job/test suite nodes
- Introduce `setup` test suite for pre-check runs for `tast` test
- Tweaked LAVA callback data parsing to re-structure test hierarchy
- Calculate job node results based on child test nodes
=> Introduce `Job` model and re-structure test hierarchy

config/runtime/base/python.jinja2
Update `_submit` method in `BaseJob` and drop its returned value as it's not being used anywhere.
=> config/runtime/base/python.jinja2: update `BaseJob._submit`

kernelci/docker.py
Add timeout value to docker API on push, otherwise rust image fails on default timeout.
=> kernelci/docker: Add timeout value

kernelci/cli/job.py
Fixes https://github.com/kernelci/kernelci-core/issues/2574
`kci job submit` is not able to find `runtime_token` for the TOML configuration.
Fix the bug by providing `api` config entry as it will look for `api.<api-config>.runtime_token` in the
`kci.secrets` section of the TOML file.
=> kernelci.cli.job: fix `kci job submit` command

config/core/storage.yaml
Legacy require storage.kernelci.org, so 200bfa86296c023959f059568dc3c070b7069de7 breaks legacy setup for staging. Adding back option
=> config/storage: Fix legacy option

pyproject.toml, requirements.txt
Fixes https://github.com/kernelci/kernelci-pipeline/issues/653
The latest version `7.1.0` has a fix applied to support `requests 2.32.2` version.
See the changelog:
https://docker-py.readthedocs.io/en/stable/change-log.html#id1
=> Bump `docker` from `6.1.2` to `7.1.0`

config/docker/fragment/kselftest.jinja2
The libubsan is missing and is required for some kselftest suites such as openat2. The error is as following:
[error while loading shared libraries: libubsan.so.1: cannot open shared object file: No such file or directory](https://storage.kernelci.org/next/master/next-20240529/arm/multi_v7_defconfig/gcc-10/lab-broonie/kselftest-openat2-beaglebone-black.html)
=> config/docker: add libubsan to kselftest fragment

config/docker/fragment/pipeline.jinja2
As we are moving kcidb bridge to production, for kubernetes we need this dependency.
=> pipeline.jinja2: Add kcidb dependency to pipeline

config/core/build-configs-android.yaml
As requested by Todd Kjos add the Android 16 v6.6-lts branch to the
coverage.
=> build-configs-android.yaml: Add android16-6.6-lts branch

config/core/build-configs-android.yaml
Disable the gki_defconfig builds at the request off Todd Kjos, it is a
focus of their internal testing and pahole causes issues with KernelCI
so makes noise.
=> build-configs-android.yaml: Block gki_defconfig builds

config/docker/base/host-tools.jinja2
As such links pose egg and chicken problem, we need first to place patch somewhere. Now after we get everything merged, we can use direct link.
=> host-tools.jinja2: Fix link from private repository to kernelci

.github/workflows/rootfs.yml
Reason for this request is verification of https://github.com/kernelci/kernelci-core/pull/2577 + https://github.com/kernelci/kernelci-pipeline/pull/642
Initial attempt resulted in [skipped workflow](https://github.com/kernelci/kernelci-core/actions/runs/9794201636)
=> workflows: Grant "pawiecz" permission to build rootfs

kernelci/runtime/__init__.py
Add template variable defined over environment, as LAVA callback usually is instance dependent, and hardcoding it in config will require to modify config for each instance.
=> config/__init__.py: Add instance_callback for LAVA template

config/runtime/base/lava.jinja2
Right now we define callback URL for LAVA labs in config, which doesn't make sense, as this URL is pipeline instance specific, and complicates deployment of staging vs production instances. It is better to define callback URL as environment variable, for now.
=> base/lava.jinja2: Add instance_callback retrieved from environment

config/runtime/tests/tast.jinja2
Remove an individual `setup` test suite and add `setup` as test set inside `tast` test suite. This will cover tests like checking CrOS version (`os-release`) and creating tast tarball (`tast-tarball`).
=> config/runtime/tests/tast: add `setup` test set

config/runtime/tests/tast.jinja2, kernelci/runtime/lava.py
`kernelci.runtime.lava.py`: add `_get_stage_result`
Get suite/stage result from LAVA. If it's `pass`, evaluate manually from child node results to overcome
an issue with LAVA that it set `pass` to test suites even if one of the sub-tests is failing.
=> Use LAVA stage result

config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py
Dots are used in KCIDB to denote test hierarchy; this can lead to misinterpretation when they're used in LAVA test sets and case names. Modify the fluster parser script to replace dots with dashes to prevent this issue.
=> config/v4l2-decoder-conformance: Replace dots in LAVA test set/case names

kernelci/api/helper.py
Currently the rules can only specify allowed/denied trees or branches as
a whole, but we lack a way to authorize (or exclude) only a specific
branch for a given tree.
This change implements tree/branch combination-based rules, by allowing
to specify such combinations using the `tree:branch` format under the
`tree` and/or `branch` rules.
Note: the `:` character has been chosen as a separator because git
forbids its use in branch names.
Fixes #2548
=> Implement tree/branch combinations in rules

config/core/runtime-configs.yaml
As planned, we are shutting down lab-collabora from legacy
=> runtime-configs.yaml: Disabling lab-collabora

config/core/build-configs.yaml
I've reproduced the failure locally. The cyclicdeadline requires sched_feature or sched/feature directory. Add these directories by including SCHED_DEBUG config in the kernel.
=> config: core: add SCHED_CONFIG needed for cyclicdeadline rt-test

.github/workflows/rootfs.yml
nfraprado often does changes to tests that require rootfs update, so it will help to unblock him on this process.
=> rootfs.yml: Add nfraprado to list as allowed to generate rootfs

config/docker/fragment/kselftest.jinja2
This library is missing and hence build errors are encountered while building kselftests specifically net suite. Hence add this library.
=> config: docker: net kselftest suite required openssl library

config/rootfs/debos/scripts/bookworm-gst-fluster.sh
Test suite was renamed in the upstream repository: https://github.com/fluendo/fluster/commit/cc9fb13dbd2a43ac9f7ab2e40a43c0b64010318f
=> rootfs/bookworm-gst-fluster: Rename H265 vc-hevc test suite

config/rootfs/debos/scripts/bookworm-gst-fluster.sh
This patch changes missing test suite error handling to:
- fail (with message) if no test suite was passed to downloader function
- allow readlink to fail and then handle its error with debugging message
=> rootfs/bookworm-gst-fluster: Rework error handling for missing test suites

config/runtime/base/kubernetes.jinja2, kernelci/runtime/kubernetes.py
Right now API key in k8s compiling nodes are hardcoded in template, and on staging we are live-patching kubernetes template. We can make it configurable, similar as we did job name in k8s job names.
=> feature(k8s-runtime): Make api key configurable

kernelci/api/__init__.py, kernelci/api/latest.py
Update `API.Node.subscribe` method to provide `promisc` field while calling API `subscribe/` endpoint.
=> kernelci.api: enable `promisc` flag for subscription

kernelci/api/helper.py
Sometimes "Fragments missing one of ['preempt_rt']" a bit confusing, as it might be misinterpreted as some fragment is missing in config or template is missing. Lets add prefix "rules: " to such messages.
=> helper.py: Add to rule related messages a bit more clarity

kernelci/api/helper.py, kernelci/api/latest.py
In some cases, when a k8s or lava job is stuck for a longer time than an allowed timeout, the result is set to `incomplete` with timeout error metadata.
However, these jobs manage to be completed after a period of time and set node result and data accordingly.
Remove timeout error metadata for such cases.
Update helper function for single node update and submitting hierarchy accordingly.
=> kernelci.api: remove timeout error metadata

config/core/build-configs.yaml
The firmware mediatek/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682-dts.tplg has been removed upstream [1]. The plan seems to be to use another firmware for MT8195 Tomato, but a kernel change [2] needs to land before that can happen. In the mean time, consider audio functionality for MT8195-Tomato broken, and drop the file from the config so we can build again. Fixes
https://github.com/kernelci/kernelci-pipeline/issues/726.
[1] https://lore.kernel.org/all/20240719022132.30990-1-xiangzhi.tang@mediatek.com/
[2] https://lore.kernel.org/all/20240318183004.3976923-1-cujomalainey@chromium.org/#t
=> build-configs.yaml: Drop removed firmware file for SOF on MT8195

config/core/build-configs.yaml
Enable the CONFIG_MEDIATEK_MT6359_AUXADC config option (which provides the mt6359-auxadc driver) in the arm64-chromebook fragment. This makes the test case /soc/pwrap@10024000/pmic/adc in the DT kselftest pass on the mediatek chromebooks, which has been failing in linux-next since the addition of commit b0a4ce81f327 ("arm64: dts: mediatek: Add ADC node on MT6357, MT6358, MT6359 PMICs") in the kernel.
=> build-configs.yaml: Add MT6359_AUXADC config to arm64-chromebook

config/docker/cros-tast.jinja2, config/docker/fragment/cros-lava.jinja2
Few small things missing, now cros-tast is buildable.
Fix package name for bookworm, and also change username in fragment (it was using old username cros-tast).
=> fix(chromeos): Few small fixes to make cros-tast buildable

config/runtime/boot/u-boot.jinja2
Device/job definitions can specify a NFS rootfs URL as the `nfsroot` param. However, this one is currently ignored when using the `u-boot` boot method. This patch ensures the `nfsroot` param is used when booting with an NFS rootfs, falling back to the default/hardcoded value only if this param is missing.
Needed for https://github.com/kernelci/kernelci-pipeline/pull/700
=> config: runtime: boot: u-boot: use `nfsroot` if defined

config/docker/data/tast_parser.py
Fix error:
/tast_parser.py --results\n### BEGIN STDERR DUMP ###\n### END STDERR DUMP ###\n Traceback (most recent call last):\nFile "/home/cros/./tast_parser.py", line 191, in <module>\nparse_test_results()\nFile "/home/cros/./tast_parser.py", line 161, in parse_test_results\nfor test_data in parse_results(results):\n File "/home/cros/./tast_parser.py", line 118, in parse_results\n for element in json_data:\nTypeError: \'NoneType\' object is not iterable
=> fix(tast_parser): Fix if data is not iterable

config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py
This is a continuation of the PR https://github.com/kernelci/kernelci-core/pull/2609 accidentally closed by me.
This change adds `--verbose` option for fluster parser to make fluster more verbose to facilitate debug. When `--verbose` is provided, the `fluster_parser.py` script will forward it to fluster which will enable the verbosity of GStreamer.  The GStreamer verbosity facilitates the debug on regressions investigations.
The low verbosity level enabled by fluster adds few hundreds of lines on logs when this option is provided, without significant impact on the performance. Anyways, the verbosity option should be disabled by default on  `fluster_parser.py` and will not be used by kernel-ci pipeline by default. 
The intention is to enable users to add `--verbose` flag manually only when …
=> rootfs:overlays:fluster Add verbose option for fluster parser

kernelci/config/platform.py
Enable platform configurations to have device-tree compatible information stored as list such as
`compatible: ['raspberrypi,2-model-b', 'brcm,bcm2836']`.
Related to https://github.com/kernelci/kernelci-pipeline/pull/760
=> kernelci/config/platform: add `compatible` property

config/core/rootfs-configs.yaml, config/runtime/tests/rt-tests.jinja2
I've removed a step at execution time and added rtla package which is needed for execution.
=> Fix osnoise and timerlat rt-tests

config/docker/fragment/api.jinja2, config/docker/fragment/lava-callback.jinja2, config/docker/fragment/pipeline.jinja2
Sometimes we need to determine which snapshot of code used in docker container. Easiest way is to provide environment variable.
=> feat(docker): Add env var with build information

kernelci/api/models.py
For easier tree tracking we introduce unique tree identified, treeid, which is sha256 hash of (treeurl + branch + time).
=> feat(models): Add treeid field

config/runtime/tests/kselftest.jinja2
This change will allow us to run some kselftests which requires to pass parameters
=> Add support for environment variable

config/runtime/boot/depthcharge.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, config/runtime/boot/u-boot.jinja2, config/runtime/chromeos/base.jinja2
The timeout for actions on jobs with failure retries needs to be adjusted to allow sufficient time for the retries. Set a short timeout for the login-action and extend the parent auto-login-action timeout accordingly. Also extend the main boot action timeout to accommodate 3 retries of the auto-login action.
- Current job example with the exception `No time left for remaining 1 retries. 2 retries out of 3 failed for depthcharge-retry`: https://lava.collabora.dev/scheduler/job/15129757
- Example job after further refining the individual action timeouts: https://lava.collabora.dev/scheduler/job/15614027
_Note_: this is a temporary measure to ensure all expected retries are executed. LAVA upstream is exploring better alternatives, including options to eliminate the need for users to manually …
=> config: runtime: further refine timeouts for job with retries

config/runtime/tests/rt-tests.jinja2
Add default timeout value to template and set it to 10 minutes. Also increase the duration of test to 10 minutes.
Close https://github.com/kernelci/kernelci-project/issues/417
=> config: rt-tests: Add default timeout and duration values

config/runtime/tests/fluster-chromeos.jinja2
Fix remaining right-stripping white space from the template and line breaking (details in the commit messages).
=> v4l2:fluster: Fix config/runtime/tests/fluster-chromeos.jinja2

config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py, config/runtime/tests/fluster-chromeos.jinja2, config/runtime/tests/v4l2-decoder-conformance.jinja2
This commit will:
- Replace the result directory from `/opt/fluster` to `/tmp`. Chromeos uses a read-only filesystem and the program is failing when writing on the previous directory.
- Uses `wget` to fetch the latest version of `fluster_parser.py` from the kernelci-core repo
- Execute `cat /etc/os-release > /tmp/osrel.tmp` in loop to wait the `ssh` host to be available.
- Add the `--run` flag on the `fluster_parser.py` execution to follow the current struct of the program in the repo. Execute the same script with the `--results` flag to collect the results.
- Install the dependency `python3-junitparser` to parse `fluster_parser.py` results.
=> fluster: Use /tmp as result directory and small fixes

config/docker/cros-tast.jinja2, config/runtime/tests/fluster-chromeos.jinja2
Right now we are installing python3-junitparser by apt, it is better to pre-build it with docker image.
=> feat(docker/cros-tast): Add package to cros-tast image

config/rootfs/chromiumos/scripts/build_board.sh
Tast-tests: Add files to be copied to DUT to the Tast tarball
Built on top of: https://github.com/kernelci/kernelci-core/pull/2663
This commit add files to the Tast tarball aiming to be dynamically copied to the DUT (local) when testing with non-chromeos (i.e. Debian) root filesytem. Specifically, add:
- `local_test_runner` - The local Tast agent
- `libtest_trace_processor.so` - The necessary library for v4l2 tests
- `v4l2_stateless_decoder` - The decoding application binary
- `cros` - Test bundle in binary format
- `validate` - Utility to compare bitstreams
- `test_vectors` containing the test vectors for the v4l2 tests
=> Add tast dut files

config/runtime/tests/tast.jinja2
The data directory has files which are required by some tests. Copy the go.chromium.org directory to /usr/share/tast/data location so that tast can find these files.
https://github.com/kernelci/kernelci-pipeline/pull/789 is a pre-requisite for this PR.
=> config: tast: Extract tast data directory at correct location

config/runtime/tests/rt-tests.jinja2
The priority of 96 if passed to rt-migrate causes failure. The test isn't designed well to handle high priority of 96. The test takes this priority and adds the count of number of tasks which becomes greater than 99. The 99 is the highest priority level for SCHED_FIFO. Hence, the priority setting of the main thread fails, we get warning and later test failure:
Warning, can't set priority of main thread!
Instead of fixing the test at this time, let's use priority of 90 instead of 96 such that the total priority of main thread remains below highest priority level. We can set any other lower priority than 90 here as well such as 51 which is set in the rt-migrate-test.sh by default.
Relates https://github.com/kernelci/kernelci-project/issues/439
Signed-off-by: Muhammad Usama Anjum …
=> config: rt-tests: set default priority of rt-migrate test

config/runtime/tests/rt-tests.jinja2
Fixes: 0888c9cc0ec8 ("config: rt-tests: Add default timeout and duration values")
=> config: rt-tests: fix default timeout value in minutes

config/core/build-configs.yaml
Add missing configurations needed to run rtla timerlat and osnoise tests.
Relates https://github.com/kernelci/kernelci-project/issues/439
=> config: build-configs: Add missing kernel configs for preempt-rt

config/runtime/chromeos/base.jinja2
ChromeOS uses teo by default on arm64 targets by specifying it in the command line arguments. Do the same in kernelci. Not only our cpuidle tast test will pass with it. But also we may have more similar behaviours like ChromeOS.
=> config: chromeos: Select teo cpuidle governor for arm64 devices

kernelci/runtime/lava.py
Sometimes LAVA doesn't like job, but HTTP error code not enough, to understand why. Let's log also response.
=> feat(runtime/lava.py): Add more LAVA submit error logging

config/runtime/base/lava.jinja2, kernelci/config/job.py, kernelci/runtime/lava.py, tests/configs/jobs.yaml
Closes https://github.com/kernelci/kernelci-pipeline/issues/513
- Support `priority` field for job definitions
- Add method to calculate job priority from job definition priority and priority min and max values from lab configurations
=> Enable job priority setting for LAVA jobs

config/core/build-configs.yaml
[PATCH v4 1/8] usb: misc: onboard_hub: rename to onboard_dev rename CONFIG_USB_ONBOARD_HUB to CONFIG_USB_ONBOARD_DEV
=> fix(amd64-chromebook.fragment): Fix fragment due config rename in new kernels

config/docker/data/tast_parser.py, config/docker/fragment/gsutil.jinja2, config/rootfs/debos/overlays/tast/usr/local/bin/fake_crossystem.sh, config/rootfs/debos/overlays/tast/usr/local/bin/fake_initctl.sh, config/runtime/tests/tast-debian.jinja2
Linked to https://github.com/kernelci/kernelci-pipeline/pull/803
Add support for `Tast` tests on Debian. Specifically:
- Create a template `tast-debian.jinja2` based on `tast.jinja2` to execute Tast against DUT running Debian root filesystem.
- Add the option `-checktestdeps=false` for `tast_parser.py` to allow the execution on non-chromeos DUTs.
- Hack: Create a shell script utility named `fake_initctl.sh` to simulate the required `initctl` command from ChromeOs on Debian.
- Hack: Create a shell script utility named `fake_crossystem.sh` to simulate the required `crossystem` command from ChromeOs on Debian.
=> tast-on-debian: Create a new test method for Tast on Debian fs

config/docker/cros-tast.jinja2
It seems gsutil moved from scripts to bin, fixing it.
=> fix(cros-tast.jinja2): Fix path to gsutil as it got changed again

config/runtime/tests/rt-tests.jinja2
When MLOCKALL is set to 'true', the lava job has MLOCKALL becomes true [1] which in turn translates to "True" while job execution [2]. It causes error as the test expects true instead of True.
./pi-stress.sh -D 60s -m True -r false -w hackbench
./pi-stress.sh: 37: True: not found
Fix it by using double quotes instead.
[1] https://lava.collabora.dev/scheduler/job/15562666/definition#defline43
[2] https://lava.collabora.dev/scheduler/job/15562666#L220
=> config: rt-tests: fix MLOCKALL getting set to True

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-kselftest.sh
Do the setup needed to be able to run the discoverable devices probe kselftest in KernelCI. This involves adding a missing dependency to the kselftest rootfs, deploying additional files used by the test, and exposing a newly introduced parameter to allow passing parameters to kselftests.
This depends on https://github.com/Linaro/test-definitions/pull/511.
=> Enable running discoverable devices probe kselftest

kernelci/api/models.py, kernelci/build.py
Add more checkout fields to `Revision` i.e., to store a list of git commit tags, git commit message string, and bool flag to denote tip of the branch.
=> kernelci.api.models: add more checkout fields

config/runtime/tests/rt-tests.jinja2
The timeout of the job is set to 10 minutes. We should run the test for less than that. Reduce the total duration of the test to 540 seconds. Leave 60 seconds for logging in, setting the environment and triggering the test runner script.
We wanted to have total time of this job to be 10 minutes and run the test for as much duration as possible. So reducing to 540 seconds or 9 minutes is okay.
=> config: rt-tests: reduce the duration of the test

config/runtime/tests/tast.jinja2
The data directory has been added to tast archive which when extracted generates 3 thousands log lines per execution. In total, there are 6 thousands log lines in every job. In the past, verbose option may be usefult to know which files got extracted. But now it creates too much noise.
In verbose mode:
https://lava.collabora.dev/scheduler/job/15997406
Without verbose mode::
https://lava.collabora.dev/scheduler/job/15998558
=> config: tast: Disable verbose mode while tast.tgz is untar

.github/workflows/production.yml
Due fat fingers i missed complete cleanup of config, completing it.
=> fix(workflows): Clean up production config

kernelci/api/helper.py, kernelci/api/models.py
Add filter that allows to restrict tests on specific platform. This feature required for proper bisection implementation, as some tests might be scheduled on multiple platforms.
=> feat(helper/models): Add platformfilter

kernelci/kbuild.py
Some kernel builds does not require to build kselftest.
=> feat(kbuild): Add kselftest disable option

config/runtime/base/kubernetes.jinja2, kernelci/config/job.py, kernelci/runtime/__init__.py
We had previously hack with hardcoding ghcr.io.
Now we make it more flexible, so people can set their own image url, and our staging instance automatically add staging- prefix in appropriate place.
=> fix(docker/k8s): Fix image naming

kernelci/storage/azure.py, pyproject.toml, requirements.txt
As requested by kcidb team, it will be easier to handle files if they have proper content-type set.
=> feat(storage/azure.py): Add content_type option for .gz files

.github/workflows/docker_images.yml
Name of repo will be invalid and use caller(who initiated workflow) name.
=> fix(workflows/docker_images): Fix name of repo

.github/workflows/docker_images.yml
Reverts kernelci/kernelci-core#2716
i386 handled by x86, and riscv by riscv64
=> Revert "fix(workflows/docker_images): Extend list of built arch"

config/docker/base/host-tools.jinja2
The usage of gawk has recently appeared in the linux kernel. The build fails if it isn't found. Add the gawk package.
=> config: docker: Add gawk package to all build containers

config/runtime/tests/kselftest-platform-parameters.jinja2
This introduces a new template which is a copy of the kselftest template with the difference that an archive of the 'platform-test-parameters' repository is downloaded before running the kselftest. This provides the test with the most up-to-date version of the platform-specific details that some of them require.
=> config: runtime: tests: Add template kselftest-platform-parameters

kernelci/kbuild.py
kbuild process prone to have networking issues due way k8s works. Implement proper retry.
Fixes: https://github.com/kernelci/kernelci-core/issues/2730
=> fix(kbuild): Implement file download retry

kernelci/build.py
Fixes https://github.com/kernelci/kernelci-pipeline/issues/846
Bug: `tip_of_branch` is always set to `False`.
Fix the method by stripping subprocess command output to get the correct value for `tip_of_branch`.
=> kernelci/build.py: fix `git_branch_tip`

kernelci/kbuild.py
As often firmware git clone fails - implement retry, so build wont fail.
=> fix(kbuild): Implement command retry to firmware clone

kernelci/api/models_base.py
Add a hack to handle `exclude` fields while dumping model fields to dictionary.
The hack should be removed after a pydantic bug is fixed: https://github.com/pydantic/pydantic/issues/6575 Also, use `SerializationInfo` to get mode of serialization and convert `ObjectId` fields to string only if `json` response is required with `mode=json` in `model_dump` function. That is due to other operations such as
inserting or updating objects in DB doesn't need the conversion as data types should be `ObjectId` in the DB.
=> kernelci.api.model_base: update `model_serializer`

kernelci/cli/event.py
We have API promisc flag for pub/sub events, and it is useful to have it available in cli too, to listen for all events on api instance.
=> feat(cli/event): Implement promisc flag

kernelci/api/models.py, kernelci/runtime/lava.py
Add a method to get `measurement`(chromeos version) field for `os-release` test case from LAVA callback data.
Store the information into `node.data.misc` field of test node.
=> Get chromeos version for `tast` tests

config/lava/boot/generic-fvp-boot-template.jinja2
The latest shrinkwrap release has updated the containers we're using for
the FVP to a new version which moves SVE support from a plugin into the
main model.  This has been causing all our FVP jobs to fail as the
arguments supplied are invalid, update with parameters suitable for the
new version of the model.
=> lava: Update FVP commands for latest shrinkwrap release

config/docker/fragment/pipeline.jinja2
Docker recipe is required to build pipeline container, and this container is used in k8s deployment.
At moment kcidb bridge is broken due missing logspec, fixing that.
=> fix(pipeline.jinja2): Add logspec to docker recipe

config/core/build-configs.yaml
Due changes of 1abab1ba0775036bb67c6c57945c637be644c04f ChromeOS tests not passing anymore. Regression bisection pointed to this commit.
=> fix(build-configs.yaml): Add CONFIG_CPUSETS_V1

config/core/api-configs.yaml, config/core/storage.yaml
Rename configurations for `early-access` to `production`. Early access instance was setup for the initial release phase. It's been used as production now.
=> config/core: rename `early-access` entries

kernelci/runtime/kubernetes.py
We can load balance k8s based on number of pending pods, use one with 0, or least pods.
=> feat(runtime/kubernetes): Proper load balancing of k8s

kernelci/api/models.py
In principle, all the dictionary fields should have empty `dict` as their default value.
This also reduces chances of pipeline service crash due to issues such as iterating over a dict field with `None` as its value.
=> kernelci.api.models: update `default` values for `Dict` fields

kernelci/api/models.py
To make kcidb data transmission more reliable introduce processed_by_kcidb_bridge flag, which indicates if node was processed by kcidb bridge service.
=> feat(models.py): Introduce processed_by_kcidb_bridge flag 

kernelci/api/helper.py
Observed error with pod crash:
```
11/27/2024 10:24:52 PM UTC [ERROR] Traceback (most recent call last):
File "/home/kernelci/pipeline/src/base.py", line 69, in run
status = self._run(context)
^^^^^^^^^^^^^^^^^^
File "/home/kernelci/pipeline/./src/scheduler.py", line 296, in _run
self._run_job(job, runtime, platform, input_node)
File "/home/kernelci/pipeline/./src/scheduler.py", line 80, in _run_job
node = self._api_helper.create_job_node(job_config, input_node,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kernelci/api/helper.py", line 456, in create_job_node
job_node['data'] = platform.format_params(job_node['data'], extra_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> fix(helper.py): Handle better exception in kbuild

kernelci/api/models.py
We need to clarify this flag is a bit special.
=> upd(api/models.py): Update comment on flag

kernelci/api/latest.py
Implement feature in PR: https://github.com/kernelci/kernelci-api/pull/583
=> feat(api/latest.py): Implement noevent flag

kernelci/api/helper.py
We need to reprocess results by kcidb on update, so reset the flag.
=> fix(api/helper): Reset kcidb state on submit_results

config/docker/cros-baseline.jinja2, config/rootfs/debos/overlays/baseline/opt/kernelci/dmesg.sh
Ignore "No irq handler for vector" errors in baseline tests [1]. These errors are harmless. But because of these errors the baseline test gets marked as failed which makes results dirty. It would have been better to ignore these errors as known errors on the dashboard. But as we don't have the functionality at this time. We have decided to ignore these during the test until we have the functionality.
[1] https://kcidb.kernelci.org/d/test/test?orgId=1&var-datasource=default&var-build_architecture=x86_64&var-build_config_name=cros:%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-amd-stoneyridge.flavour.config&var-id=maestro:67455b8c3be6da94b19fde34&from=now-100y&to=now&timezone=browser&var-origin=$__all&var-test_path=&var-issue_presence=$__all Close …
=> config: dmesg.sh: Ignore missing handler errors in baseline tests

config/core/rootfs-configs.yaml, config/rootfs/debos/overlays/h26forge/usr/bin/h26forge-parser.sh, config/rootfs/debos/scripts/bookworm-gst-h26forge.sh, config/runtime/tests/h26forge-debian.jinja2
Create a rootfs with rustc compiler to compile
and run h26forge.
h26forge will generate h264 test files to be parsed with Gstreamer h264parse element.
=> add h26forge test

config/core/rootfs-configs.yaml, config/rootfs/debos/rootfs.yaml
As part of work to prepare kselftest rootfs we need to add packages required to run netdev related tests properly.
=> feat(rootfs-configs.yaml): prepare rootfs for netdev/kselftest

config/core/build-configs.yaml, config/runtime/boot/grub.jinja2
Board Aaeon UP squared 6000 with X6425RE needs IGB driver to have functioning networking.
=> fix(yaml/jinja): Add IGB and grub nfs support

config/docker/fragment/kselftest.jinja2, kernelci/kbuild.py
kselftest (for example net) require correct CC/HOST_CC variable to compile some of the components.
=> fix(kbuild): Add CC/HOST_CC variables for kselftest

config/core/storage.yaml, config/runtime/base/kubernetes.jinja2, kernelci/runtime/kubernetes.py
Add new kernelci-storage definition.
It is plain http storage, already supported as "backend".
=> feat(storage.yaml): Add new storage

.github/workflows/docker_images.yml
buildroot package was not added to list of images that should be built with all docker images.
=> fix(workflows/docker_images.yml): Add missing buildroot

config/runtime/boot/u-boot.jinja2
While adding barebox bootloader support in https://github.com/kernelci/kernelci-core/pull/2782#discussion_r1930452334 it was discovered that the default nfsroot image in the u-boot template has not been updated in some time. Update to the current most recent version 20250117.0.
Thanks to @pawiecz for noticing this in https://github.com/kernelci/kernelci-core/pull/2782.
=> config: runtime: boot: u-boot: update the default nfsroot to 20250117.0

config/core/build-configs.yaml
This allows boards like the Genio 700 EVK and Genio 350 EVK to run NFS jobs.
=> build-configs.yaml: Add MediaTek ethernet drivers to lab-setup fragment

config/runtime/boot/barebox.jinja2
We are currently in the process of reviving the [Pengutronix LAVA lab](https://lava.pengutronix.de/) for use with the new KernelCI infrastsructure.
As a first step we need [Barebox](https://www.barebox.org/) bootloader support, since it is used by all boards in the Pengutronix lab.
This PR replaces #2600 by @pawiecz and includes the following suggestion by @a-wai https://github.com/kernelci/kernelci-core/pull/2600#issuecomment-2320699175:
> This doesn't take into account the case where `boot_commands == nfs`; I'd rather suggest to just copy the u-boot template and `s/u-boot/barebox/` there, as it seems they should be otherwise identical.
The barebox template is indeed a copy of the u-boot template with the method set to `barebox`.
=> config: runtime: boot: add support for barebox bootloader

kernelci/api/helper.py
Add support of promisc flag to subscribe_filters
helper function. Will be used in kcidb-bridge, to
listen for all users events.
=> feat(helper.py): Add promisc to subscribe_filters

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-blktest.sh, config/rootfs/debos/scripts/create_initrd_ramdisk.sh
1)Remove in create_initrd_ramdisk.sh code with expr, as expr anyway missing in initramfs and this code
breaks local non-nfs boot.
2)Add various packages to satisky blktest requirements 3)Enable one of package install over rust/cargo
4)Disable removal of ncurses-bin as blktest require tools from it.
=> upd(various): Various updates for blktest enablement

config/core/rootfs-configs.yaml
blktest need to fetch kernel sources.
This tools might not be needed later.
=> upd(rootfs-configs.yaml): Add wget and curl to fetch artifacts

config/rootfs/debos/scripts/bookworm-blktest.sh
…from contrib
For proper blktest operation we need tool from contrib that is not installed by default.
=> fix(bookworm-blktest.sh): It is better to use nvme_target_control.py from contrib

config/core/rootfs-configs.yaml
During DDP check and using netlink_cli program we need also python jsonschema as well.
=> upd(rootfs-configs.yaml): Dependency for nvme-tcp ddp test

config/docker/cros-tast.jinja2, config/runtime/tests/tast-debian.jinja2, config/runtime/tests/tast.jinja2
This commit includes the test vectors in the `cros-tast` image to avoid download of these artifacts on every test, reducing the test time and the network usage. Some additional notes:
- This aims to include the test vectors on tests targetting both Debian and ChromeOS.
- The test vectors are split in 2 files: `test_vectors.tar.gz` and `test_vectors-vp9.tar.gz`. The rationale behind this is that the test vectors targetting vp9 requires 11.1 GB of storage, while all the other test vectors for other codecs requires 349M.
- For this change to take effect, `kernelci/cros-tast` will need to be rebuilt. However, `||true` statements on the end of the `scp` and `ssh` commands on the jinja templates were placed to not break the tests while the `kernelci/cros-tast` image is not updated.
Examples of …
=> tast-v4l2-decoder: Include test vectors on Docker image to avoid download on runtime

config/runtime/boot/grubhd0.jinja2, config/runtime/tests/blktests-ddp.jinja2
This is very early version of blktests, more specifically test nvme/056, which tests nvme-tcp DDP offload on mlx network cards. It involves setting up hypervisor, 2xQEMU, PCI passthrough, and custom hardware.
This is very first version, jsut to make it works, but then a lot of improvements will follow up.
=> add(blktests-nvme-ddp*): Add rudimentary version of new, unique test

kernelci/kbuild.py
git.kernel.org sometimes unreachable or Azure k8s issue, so lets keep at least firmware locally on Azure storage.
=> feat(kbuild.py): Download linux-firmware from kci infra

config/rootfs/debos/scripts/bookworm-blktest.sh, config/runtime/tests/blktests-ddp.jinja2
Recent changes in Linux kernel change path to tool used to manipulate parameters over netlink. As soon as PR merged to blktest, we need to change back.
=> upd(bookworm-blktest.sh): Temporary change to custom repo

.github/workflows/production.yml
We need to be notified if someone triggered production deploy, when it started, by whom, why, and when it ended.
=> (workflows): Add discord notifications for prod deploy

kernelci/kbuild.py
In configuration where cros:// config is defconfig, node will have incorrect entry for config_full, missing cross:// (defconfig) part.
Fixes: https://github.com/kernelci/kernelci-core/issues/2812
=> (kbuild) Fix missing cros:// defconfig

.github/workflows/staging.yml
Due github changes, this is necessary parameter now
=> fix(staging.yaml): Fix secrets inherit parameter

config/docker/base/debian.jinja2, config/docker/base/debos.jinja2, config/docker/base/host-tools.jinja2, config/docker/base/python.jinja2
Docker Hub introducing severe pull limits, we need a workaround, such as using mirrors, to solve that.
=> (docker) Use google container mirror to workaround pull limits

config/docker/base/host-tools.jinja2
We need to download pahole, and use release tarball, otherwise staging builds are failing.
=> git.kernel.org started to throttle github runners

kernelci/api/models.py, kernelci/legacy/config/build.py
We might need to restrict kernel builds additionally, as some architecture-specific trees don't want to build and test all kind of architectures. This is initial enablement patch, with with several others following.
=> (models.py): Add architecture_filter to checkout node

config/runtime/base/lava.jinja2
Update context with extra_kernel_args when defined in the job parameters.
=> config: runtime: base: add extra_kernel_args parameter to LAVA job template

.github/workflows/docker_images.yml, config/docker/fragment/kernelci.jinja2
Suddenly pip stopped to work for kernelci docker image builds on staging. Most likely reason is --break-system-packages, probably one of base images changed distro and this flag now mandatory.
=> (fragment/kernelci.jinja2) Fix, add --break-system-packages to pip

.github/workflows/docker_images.yml
We have failure in kci docker build, and current amount of messages is not enough for debugging.
=> (workflows) Add --verbose flag to kci docker build

config/docker/fragment/kernelci.jinja2
We need to fix staging failure.
```
Building wheel for bson (setup.py): started
Building wheel for bson (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
[end of output]
```
=> (pyproject.toml) Fix pip install

config/docker/fragment/lava-callback.jinja2
Path to requirements.txt is changed, reflect it in docker recipe
=> (docker/lava-callback.jinja2) Update path to lava-callback requirements.txt

config/core/build-configs.yaml
When testing the chromeos-6.6 kernel on Brya, a BUG in intel_context_init() occurs during boot if the GuC and DMC firmware are missing[1]. This results in a failed GT initialization, leaving engine->gt->vm NULL and causing a kernel crash. Add the required firmware files to prevent the issue.
[1] https://dashboard.kernelci.org/issue/maestro%3Aea171ee4639b31e59d833248e4d66a2664c02f83?iv=1&tf%7Cb=a&tf%7Cbt=a&tf%7Ct=f
=> build-configs.yaml: Add missing GuC/DMC firmware for brya

kernelci/docker.py
Building Docker images using the kci tool results in dangling intermediate images, which can lead to unnecessary disk space usage over time and leave the system in a dirty state
This PR updates the build process to properly clean up intermediate images after the build is complete, preventing the accumulation of dangling images.
=> Docker: remove docker intermediate images after build

config/docker/base/host-tools.jinja2
Some headers in the kernel reference userspace headers provided by the uuid-dev package. Install it on all build containers.
Fixes: https://dashboard.kernelci.org/issue/maestro%3A6b8da43ff8bc6bf9d93cc9cf86c3c5b5c5ab20a2?iv=1
=> config: docker: Install uuid-dev package

config/rootfs/debos/scripts/bookworm-ltp.sh
kirk is an alternative LTP runner under active development, including among
other things better support for extracting per-test log information and
support for parallel execution. Install it in our LTP rootfs images so we
can take advantage of these features.
=> rootfs: bookworm-ltp: Install kirk into the LTP rootfs images

pyproject.toml
Fixes:
```
Collecting pyyaml==6.0 (from kernelci==1.1)
Using cached PyYAML-6.0.tar.gz (124 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
```
=> (pyproject.toml) Fix pip install (pyyaml upgrade)

config/core/build-configs.yaml
We are working on adding a test based on fault injection into KernelCI, hence, add a fragment to enable fault injection specific configs
=> build-configs.yaml: Add a fragment for fault injection

.github/workflows/main.yml
Action "setup-python@master" has not been updated for 5 years and is still using a deprecated version of "cache" action. Updating it to "v5" will allow successful runs of this CI stage.
Fixes: #2861
=> chore: Update actions/setup-python to v5

config/runtime/boot/fastboot.jinja2
Enhancing the fastboot template to dynamically extract the DTB blob. This approach aims to make post-processing more generic and adaptable for various fastboot boot targets.
=> runtime:boot: Improve fastboot template for dynamic dtb blob extraction

config/core/build-configs.yaml, kernelci/kbuild.py
As we plan on adding code coverage capabilities, we need to ensure `kbuild` nodes can extract and upload the required data:
- full source code *as configured for the build* (including symlinks)
- gcov data files (`*.gcno`)
This relies on a new `coverage` config fragment in order to enable code coverage.
=> kernelci: kbuild: manage coverage "source" artifacts

config/core/rootfs-configs.yaml
This file is still used by new Maestro ecosystem and we use part of legacy code to generate rootfs. Removing confusing remark.
=> (rootfs-configs.yaml) Remove legacy remark

pyproject.toml, requirements.txt
Dependabot reports about security issue in old jinja2. Not like it is too relevant to us, we dont have externally supplied data in this templates, but better to upgrade.
=> Make dependabot happy for jinja2

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-fault-injection.sh, config/runtime/tests/fault-injection.jinja2
Add a basic fault injection test template which will be currently used to add a suspend/resume test.
=> Add fault injection template

config/runtime/tests/blktests-ddp.jinja2, config/runtime/tests/ltp.jinja2
At some point, we might want to provide "generic" test definitions to be included in specific tests. However, in order to do so, all test definitions entries must be consistently indented, which is mostly the case already. Howver, some test templates are a bit off in this regard, so fix this by re-indenting the "faulty" ones.
=> config: runtime: tests: consistently indent test definitions

config/core/rootfs-configs.yaml
As we're enabling code coverage in LTP test jobs, we need a way to upload the coverage data from LAVA. The simplest way is to just use `curl` to POST the artifacts to KernelCI storage, so let's add this tool to the rootfs used for LTP jobs.
=> config: core: rootfs-configs: add `curl` to bookworm-ltp

config/runtime/tests/fault-injection.jinja2
Interval is making the probablity of fault occurrences less, hence remove it from the template.
=> tests: Remove interval for fault injection testing

config/core/rootfs-configs.yaml
This package is needed for using `curl` on SSL/TLS connections, but it is only a `Recommends`, so it must be explicitly listed as a wanted package.
=> config: core: rootfs-configs: add `ca-certificates` to bookworm-ltp

kernelci/api/helper.py, kernelci/kbuild.py
Currently, `kbuild` nodes transition to state `done` as soon as they complete, even though they often have many child nodes running afterwards. This is confusing as `checkout` nodes first transition to `available` state, then `closing` (waiting for child nodes to complete) and only transition to `done` once all child nodes have completed.
This behaviour should be applied to `kbuild` nodes as well, both for consistency and to be able to easily schedule post-processing jobs (e.g. by triggering those on the `state: done` event).
Also add a `holdoff` value (10 minutes, identical to `checkout` nodes) so the corresponding service properly handles state transitions for those nodes.
Fixes  #2875
Depends on https://github.com/kernelci/kernelci-pipeline/pull/1164
=> kernelci: kbuild: transition to `available` state when complete

kernelci/config/base.py
This PR fixes arch naming for riscv64 platform arch for buildroot rootfs.
Steps to reproduce the bug:
`kernelci-pipeline/config/platforms.yaml`:
```
...
platforms:
qemu:
base_name: qemu
arch: riscv64
boot_method: qemu
mach: qemu
context:
arch: riscv64
cpu: rv64
guestfs_interface: virt
...
```
When a test job is on this platform the rootfs url would be similar to the the following:
`http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230421.0/riscv64/rootfs.cpio.gz`
when instead the correct url is:
`http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230421.0/riscv/rootfs.cpio.gz`
=> Fix buildroot rootfs naming for riscv64 arch

kernelci/api/helper.py, tests/api/test_apihelper.py
Since we have repeated mistake, we should add basic test case. Tests still need fixing, as some other of them are failing.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/1157
=> (kernelci/api/helper) Fix sanitizer and add test

config/runtime/tests/ltp.jinja2
Some of the LTP suites (especially the syscalls suite) are extremely
large and take a very long time to run, in order to make jobs more
managable the test-definitions integration for LTP supports sharding
the suites.  Add support for this to our template.
=> lava: Support sharding for LTP

config/rootfs/debos/scripts/debian-igt.sh
The link for the upstream repository git://anongit.freedesktop.org/mesa/drm became obsolete with the move to Gitlab server in March 2024. Update the link from anongit to the Gitlab server.
=> debian-igt.sh: update link to Gitlab server

config/core/rootfs-configs.yaml
Kirk needs Python3, install it into the LTP images so we can make use of
it.
=> rootfs-configs.yaml: Add Python3 to the LTP rootfs

config/core/rootfs-configs.yaml
The mm selftests use killall from one of the scripts, hanging if it's
not available.  Add psmisc so it's available.
=> rootfs-configs.yaml: Add psmisc to the kselftest rootfs for mm

kernelci/kbuild.py
We had false positive, when we try to disable crash on command error by set -e, TRAP still worked and quit legit grep command with exit code 0.
This caused several days of "false good" builds, sorry :(
=> Fix trap logic

config/runtime/util/gcov-upload.jinja2
The LTP rootfs doesn't include `xz`, so we can't use that compression method. Revert to `gz` as those artifacts aren't that big anyway.
=> config: runtime: util: gcov-upload: fix compression method

kernelci/kbuild.py
We should not submit_failure if already we detected failure by other means, because submit_failure doesnt add artifacts.
=> (kbuild) Verify image existence only if build pass

config/rootfs/debos/scripts/bookworm-ltp.sh
Currently we build LTP using whatever the current commit on the master
branch is. This means that any development on the rootfs could change the
set of LTP tests we're running and that we will be running just some random
snapshot of LTP, not an actual release, so could end up carrying bugs that
wouldn't make it into a release. Fix the version of LTP at the recently
released 20250530 version.
=> roofs: ltp: Use a fixed release of LTP when building it's rootfs

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-kvm-unit-tests.sh, config/runtime/tests/kvm-unit-tests.jinja2
Add a rootfs and job template fragment for the KVM unit tests.
- rootfs: Build rootfs with kvm-unit-tests installed
- runtime: Add template fragment for kvm-unit-tests
=> Enable KVM unit tests

kernelci/runtime/lava.py
Nodes are created in `running` state by default. Recent changes to the API helper functions copy the `state` field from the node instead of setting it to `done` by default, meaning result nodes stay `running` until they time out.
Fix this by making those nodes `done` right from the beginning.
=> kernelci: runtime: lava: ensure result nodes are in "done" state

kernelci/api/helper.py
Nodes are created with `'artifacts': null`, meaning calling `update()` could lead to an uncaught exception, and therefore a crash. Avoid this situation by ensuring this field is a dict before calling `update()`.
=> kernelci: api: helper: don't crash when adding artifacts to node

config/docker/base/host-tools.jinja2
`gcovr` is needed to post-process coverage data. However, the version available in Debian Bookworm is old and lacks features we need, such as generating `lcov`-compatible tracefiles. Install it using `pip` as a temporary workaround.
=> config: docker: base: host-tools: add gcovr

config/runtime/base/python.jinja2
The base `python` template was designed with post-checkout jobs (`kbuild`, `kunit`...) in mind and doesn't work too well with test or post-processing jobs due to the following issues:
* it assumes we need the kernel source from the parent `checkout` node
* it doesn't provide a way to retrieve arbitrary artifacts from a node or its parent
* the `_get_source()` function doesn't allow specifying an arbitrary target folder to extract tarballs to
Ensure we only download/extract/cd to the kernel source if the current node is a child to a `checkout` node, otherwise let the job definition prepare its workspace as needed.
Also add a generic `_get_artifact_url()` for downloading arbitrary artifacts and make the existing `_get_tarball_url()` use it to avoid duplicating code.
Finally, add an optional …
=> config: runtime: base: python: make more generic

config/core/rootfs-configs.yaml
Add packages which are required for lava-job-submitter and igt tests.
=> rootfs-configs.yaml: Add packages to the deqp-runner rootfs

kernelci/api/helper.py, kernelci/api/latest.py
Right now receive_event is blocking, and even on receiving keep alive it stay inside its own busy loop, which makes impossible to implement proper scheduling, watchdogs, health monitoring.
We make optional parameter, where on keep alive message, (sent each 45 sec by kernelci-api) it will return None. We keep backward compatible defaults, as lot of code is not expecting None in return.
=> receive_event: Make it optionally semi-nonblocking

kernelci/runtime/lava.py
Do not create `setup` node if `auto-login-action` and `kernel-messages` test cases are not perfomed in a lava job.
For example https://lava.ciplatform.org/scheduler/job/1289216 job doesn't even reach login prompt due to infra error.
=> kernelci.runtime.lava: fix `setup` node

config/core/api-configs.yaml
Update maestro production API URL to `https://api.kernelci.org`. The former URL is an alias of the new URL and it's still working fine but this looks like more readable and standard URL.
The new URL is also being used in other places such as KCIDB submissions and documentation.
=> config: update production instance URL

config/docker/base/python.jinja2
This upgrade is inteded to make use of [recent changes](https://docs.python.org/3.12/library/tempfile.html#tempfile.NamedTemporaryFile) in handling temporary files (in "tempfile" module).
Depends on: https://github.com/kernelci/kernelci-pipeline/pull/1229
=> config: docker: Bump Python version for base template

kernelci/api/helper.py, kernelci/api/models.py
- Add a field to `Node` model to keep track of a number of job retries
- Enable setting `retry_counter` while creating a job node
=> Enable job retry

config/runtime/tests/ltp.jinja2
Add ltp-fault-injection.jinja2 based on ltp.jinja2 with fault injection arguments (-F 50) to kirk.
=> config: runtime: add ltp fault injection template

config/runtime/tests/kselftest-platform-parameters.jinja2, config/runtime/tests/kselftest.jinja2, config/runtime/tests/kvm-unit-tests.jinja2, config/runtime/tests/ltp.jinja2, config/runtime/tests/rt-tests.jinja2
Switch from the kernelci/test-definitions mirror to the official linaro/test-definitions repository since kernelci/test-definitions is deprecated.
=> tests: use linaro/test-definitions repository

config/core/build-configs.yaml
Update fault injection configs to include support for null_blk fault injection. blktests can be used to run fault injection tests on raw block devices with the null_blk driver.
=> build-configs.yaml: Update fault injection configs

config/core/build-configs.yaml
Unfortunately we are still using this config for kernel fragments configuration
=> Remove deprecation notice from config that are still used

config/core/build-configs.yaml
Include iwlwifi-so-a0-gf-a0-89.ucode to fix missing firmware error for intel chromebooks.
iwlwifi 0000:00:14.3: Detected crf-id 0x400410, cnv-id 0x80400 wfpm id 0x80000020
iwlwifi 0000:00:14.3: PCI dev 51f0/0094, rev=0x370, rfid=0x2010d000
iwlwifi 0000:00:14.3: Detected Intel(R) Wi-Fi 6E AX211 160MHz
iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-so-a0-gf-a0-89.ucode failed with error -2
iwlwifi 0000:00:14.3: no suitable firmware found!
iwlwifi 0000:00:14.3: iwlwifi-so-a0-gf-a0-89 is required
iwlwifi 0000:00:14.3: check git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
=> build-configs: add iwlwifi-so-a0-gf-a0-89.ucode

config/runtime/tests/fault-injection.jinja2
fault-injection: update fault injection parameters
Set the default probability for fault-injection tests to a random
value between 1 and 100. This ensures each job run uses a different
probability value. Set times default to -1 for unlimited failures and
add interval to limit how often failures are injected. interval=1 allows
every eligible allocation to fail.
=> fault-injection: update fault injection parameters

config/runtime/base/lava.jinja2, kernelci/runtime/__init__.py
On Maestro base_name parameter until now was broken. We are fixing it for backward compatibility,
and also in next commit introducing more logical parameter, device_type.
=> runtime/platform: Fix base_name logic

config/runtime/boot/ipxe.jinja2
Based on observation, for example: https://lava.ciplatform.org/scheduler/job/1311593 3 minutes is not enough for bootloader.
=> config/iPXE: increase timeouts
