kernelci/kernelci-core

build.py, jenkins/build.jpl, jenkins/dockerfiles/clang-8/Dockerfile, jenkins/kernel-arch-complete.sh, jenkins/lava-boot-v2.sh, labs.ini, src/org/kernelci/util/Job.groovy
Summary:
* Add support for Clang with clang-8 Docker image
* Remove old unused labs definitions
* Update build.py for MIPS
* Adjust email reports sent to linux-media (only v4l2 results in plain text)
=> Staging 20181221

jenkins/bisect.jpl, jenkins/debian/Dockerfile_debos, jenkins/dockerfiles/build-base/Dockerfile, jenkins/dockerfiles/debos/Dockerfile, jenkins/dockerfiles/gcc-6.3.0_mips/Dockerfile, jenkins/stretch-igt.jpl, jenkins/stretch-v4l2.jpl, jenkins/stretch.jpl, push-bisection-results.py, src/org/kernelci/debian/RootFS.groovy
Summary:
* Add Docker image for Debos and use it in Debian Jenkins jobs
* Add python3-yaml package to build-base Docker image
* Fix bisection job to use new CC and CC_VERSION parameters
* Only send bisection email reports in plain text
* Fix bisection email recipients parsing of get_maintainer.pl output
=> Staging 20190102

build-configs.yaml, jenkins/build-trigger.jpl, kci_build, kernelci/build.py, kernelci/configs.py, src/org/kernelci/build/Kernel.groovy
Summary:
* Fix arm-soc_fixes configuration (branch name has changed)
* Add build environment definitions to the YAML-based config
* Use the build environment variants when generating kernel build jobs
* Leave the default to `gcc-7` and do not enable any other compilers as yet
=> Staging 20190222

requirements.txt
=> Init requirements for python scripts

jenkins/debian/debos/scripts/stretch-igt.sh, templates/igt/igt.jinja2
Fix the `stretch-igt` build and related test template `igt`.
=> T13820 fix stretch-igt

README.md
Rewrite the README.md file to make it reflect the current status of
this repository with links to the KernelCI wiki.
=> T13683 README: rewrite to reflect current status of this repository

jenkins/build-trigger.jpl, jenkins/monitor.jpl, kci_build
Improve the `kci_build` command line syntax handling using sub-parsers for each command to check all the require arguments are provided and add per-command help messages.
=> T13683 kci build help fixup

jenkins/lava-boot-v2.sh, test-configs.yaml
Signed-off-by: Michael Grzeschik <m.grzeschik@pengutronix.de>
=> test-configs: fixes and testplans for barebox boards

jenkins/kernel-arch-complete.sh
=> Add google's clang list to -next build reports

build-configs.yaml
=> Add stable_5.1 and stable-rc_5.1 to build-configs

jenkins/buildroot-builder.sh
=> jenkins: add buildoot builder script

jenkins/lava-boot-v2.sh, labs.ini
My lab is now ready to handle jobs.
=> labs: Add lab-clabbe

README.md, kci_build, kernelci/build.py
This is to add some documentation with docstrings in `kernelci.build` and sample `kci_build` commands in `README.md`.
=> T14908 kci_build documentation

build-configs.yaml
Add the integration-experimental branch from the qcom-lt tree.
Link: https://groups.io/g/kernelci/topic/new_experimental_branch_for/32403935
=> build-configs.yaml: add qcom-lt/integration-experimental branch

build-configs.yaml
=> Add stable 5.2 and 5.2-rc branches

test-configs.yaml
This patch adds more boards already working in my lab.
=> test-configs.yaml: Add boards from lab-clabbe

build-configs.yaml
Add Viresh Kumar's tree and branch for-kernelci.
Link: https://groups.io/g/kernelci/topic/my_branch_not_getting_tested/32724989
=> build-configs.yaml: add Viresh Kumar's tree

build-configs.yaml, jenkins/kernel-arch-complete.sh
* rename the filter alias to avoid confusion.
* only build the main defconfig for each architecture with vireshk's for-kernelci branch.
* send email reports for vireshk's tree
=> vireshk build filter

jenkins/lava-boot-v2.sh, templates/boot/generic-qemu-boot-template.jinja2, test-configs.yaml
This is a fixup PR for #100 to make the templates and test config more maintainable.
=> add UEFI tests

kernelci/configs.py, lava-v2-jobs-from-api.py, test-configs.yaml
Clean up test-configs.yaml content and schema to make it more future-proof.
=> T16036 test-configs.yaml: clean up and consolidate device types

test-configs.yaml
=> test-configs: new Amlogic board: meson-g12a-u200

jenkins/lava-boot-v2.sh, test-configs.yaml
This depends on #160 to be merged first, and is a clean-up of #161.
=> QEMU UEFI rework

build-configs.yaml
delete: android-4.14
add: android-4.14-r
delete: android-4.19
add: android-4.19-r
delete: android-4.9
=> Update android trees as per Todd request

kernelci/configs.py, lava-v2-jobs-from-api.py
Cherry-pick and rebase @touilkhouloud's patches from #94 to add parameters to device types.
=> Device type params

kernelci/build.py
Create a dtbs.json file in kernelci.build.install_kernel() with the
list of all the dtb files.  This can then be pushed to the storage
server alongside the dtb files and other kernel binaries.  It's useful
when filtering which devices should run a kernel build without having
to discover the list of dtb files again when this information is
already gathered during the install_kernel step.
=> T9980 kernelci.build.install_kernel: create dtbs.json

jenkins/lava-boot-v2.sh, test-configs.yaml
Now that the baseline test plan is available, enable it on all the
platforms.
=> test-configs.yaml: enable baseline on all the devices

build-configs.yaml
=> Add stable 5.3 and 5.3-rc branches

jenkins/kernel-arch-complete.sh
=> kernel-arch-complete.sh: add new uefi email reports

kernelci/config/lab.py, lab-configs.yaml
Add `lab-configs.yaml` with the Python code to parse it.  This file is intended to define all the config parameters for each lab where tests should be run.
=> T16583 lab configs

jenkins/kernel-arch-complete.sh
Andy's email has been bouncing for awhile, updated it to his
kernel.org address.
=> arch-complete: fix agross email address

jenkins/build-trigger.jpl, jenkins/build.jpl, jenkins/test-runner.jpl, kci_test, kernelci/cli.py, kernelci/test.py
It adds a new Jenkins Pipeline job `test-runner.jpl` to run tests for a given kernel build, using `kci_test`.  It also makes `build-trigger.jpl` start a job for each completed kernel build to run tests as soon as the build is available.
=> T16453 test runner

kernelci/build.py
Make it possible to pass KCONFIG_* variable to configure a kernel.  One
example that will be solved is when building an allmodconfig kernel that
can boot, we need to pass the defconfig file to the variable
KCONFIG_ALLCONFIG when configuring the kernel with 'make allmodconfig'
=> kernelci.build: add support for KCONFIG_* variables

.travis.yml, kci_build, kci_test, kernelci/build.py, kernelci/config/build.py, kernelci/config/test.py
This PR depends on #226 to be merged first (to fix a unit test)
Add basic Travis CI definition to run existing unit tests and pep8 checks.
=> Add Travis CI

kci_test, kernelci/build.py, kernelci/cli.py, kernelci/config/lab.py, kernelci/lab/__init__.py, kernelci/lab/lava.py, kernelci/test.py
Add docstrings and clean up a few loose ends in recently added modules and kci_test.
=> T16859 doc and clean up

push-bisection-results.py
The lib.configuration module isn't used by other scripts, supports for
a config file now needs to be added in kernelci.config instead.  Drop
support for the config file in push-bisection-results.py as it's the
last place where it was used.
=> push-bisection-results.py: drop dependency on lib.configuration

.github/ISSUE_TEMPLATE/new-kernel-branch.md
Add missing questions about the actual branch to add (repo URL and
branch name).  Also improve the wording a bit.
=> issues/new-kernel-branch.md: add missing bits

templates/base/kernel-ci-base.jinja2, templates/boot/generic-qemu-boot-template.jinja2, test-configs.yaml
This PR add more qemus machines to boot
=> Add more qemus

build-configs.yaml
Cleanup a few trees from Linaro / LSK that appear to be unused.
=> Cleanup unused trees

kci_build, kernelci/build.py, kernelci/cli.py
Hi,
I have been trying to use kernel-ci core with (yet) another CI tool: concourse
Being able to configure the install path make thing easier with it .. so here it my modest contribution
=> Make install and module path configurable

jenkins/bisect.jpl, lava-v2-callback.py, push-bisection-results.py
Enable bisecting single test cases.
Please note that this will require some matching backend changes in order to trigger bisections with a single test suite and test case, as well as to be able to send bisection reports accordingly.
=> T12179 test case bisect

build-configs.yaml
Signed-off-by: Lee Jones <lee.jones@linaro.org>
=> build-configs: Add i386 builds to Lee's android-3.18 job

.travis.yml
=> TravisCI: Enable kci_rootfs validation check

build-configs.yaml
=> build-configs: add stable v5.4

.gitreview
This is VERY legacy from ye olde Linaro days, might as well just remove it.
=> Delete the .gitreview file

lab-configs.yaml, test-configs.yaml
Add NXP lab and initial ls2088-rdb board
As requested by:
- Suram Suram <suram@nxp.com>
- Philippe Mazet <philippe.mazet@nxp.com>
=> add new lab-nxp lab

lab-configs.yaml
=> lab-configs: lab-baylibre: drop kselftest

test-configs.yaml
adding imx6q-sabresd and imx7d-sdb to kernelci.org
=> adding imx6q-sabresd and imx7d-sdb to kernelci.org

jenkins/rootfs-builder.jpl, jenkins/rootfs-trigger.jpl, kci_rootfs, kernelci/rootfs.py
Depends on #328 to be merged first.
=> T17420 kci rootfs fixup

jenkins/dockerfiles/clang-10/Dockerfile
=> dockerfiles: Add a container for clang-10 builds

rootfs-configs.yaml
Include buster-v4l2 and buster-igt rootfs configurations
=> Add buster-v4l2 and buster-igt configs

build-configs.yaml
Requested-by: Todd Kjos <tkjos@google.com>
=> build-configs: android: drop arc, mips builds

rootfs-configs.yaml
Include buster-cros-ec rootfs configurations.
=> Add buster-cros-ec configs

README.md
Fix trivial spelling mistake
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>
=> README: foncig -> config

README.md, doc/staging.md
Add staging.md page with a description of how staging.kernelci.org
works and the development workflow around it.
=> T22051 doc: add staging.md

build-configs.yaml
Add linux-5.7.y branches to both stable and stable-rc trees.
=> build-configs.yaml: add stable_5.7 and stable-rc_5.7

test-configs.yaml
=> test-configs: update to buildroot 2020.05

build-configs.yaml, kernelci/config/__init__.py, kernelci/config/build.py, lab-configs.yaml, test-configs.yaml
Replace the blacklist/whitelist filter names with their new standard equivalents blocklist/passlist and update the YAML config files accordingly.
=> Rename blacklist/whitelist filters to blocklist/passlist

build-configs.yaml
Depends on #429 to be merged first.
=> Fix android build config names

.travis.yml, db-configs.yaml, kci_data, kernelci/config/data.py, kernelci/data/__init__.py, kernelci/data/kernelci_backend.py
This fixes a few loose ends in kci_data and the related modules.
=> T22068 kci_data fixup

lab-configs.yaml
Currently just virtual targets reflecting my current upstream work.
=> lab-configs: Add my lab

lab-configs.yaml
Prioritize my own personal use!
=> lab-configs: Set priority for jobs submitted to my lab to low

kci_test, kernelci/cli.py
Fix a few issues in `kernelci.cli` to print a help message when no arguments are provided and to avoid duplicated logic.
=> T22068 Fix some issues in kernelci.cli

jenkins/debian/debos/scripts/buster-ltp.sh, rootfs-configs.yaml
Include build and install script for LTP and update rootfs-config.yaml
=> Add rootfs for Linux Test Project (LTP)

build-configs.yaml
Add queue branches from the stable-rc tree as requested.
Link: https://github.com/kernelci/kernelci-core/issues/301
=> build-configs.yaml: add stable-rc queue branches

build-configs.yaml
Add linux-5.8.y branches for stable, stable-rc and stable-rc/queue.
=> build-configs.yaml: add linux-5.8.y branches

lab-configs.yaml, templates/ltp/generic-depthcharge-tftp-nfs-ltp-template.jinja2, templates/ltp/ltp.jinja2, test-configs.yaml
=> test-configs.yaml: Add simple LTP test plan

build-configs.yaml
Add build environment definition for clang-11.
Depends on #469.
=> Add clang-11 build environment

build-configs.yaml, jenkins/kernel-arch-complete.sh
=> Add robh's tree

lab-configs.yaml, templates/ltp/ltp.jinja2, test-configs.yaml
=> ltp: Add ltp ipc tests using Linaro test-definitions

rootfs-configs.yaml
=> rootfs-configs.yaml: Include armel,armhf architecture

test-configs.yaml
=>  test-configs.yaml: Enable ltp-ipc tests on rk3288-veyron-jaq

test-configs.yaml
=> wandboard fixup

templates/ltp/generic-uboot-tftp-nfs-ltp-template.jinja2, test-configs.yaml
=> test-configs.yaml: Enabling ltp-ipc on u-boot devices in lab-collabora

jenkins/dockerfiles/gcc-8_arm/Dockerfile, jenkins/dockerfiles/gcc-8_arm64/Dockerfile, jenkins/dockerfiles/gcc-8_x86/Dockerfile
=> T24394 - fix headers files problems in arm, arm64 and x86

templates/ltp/ltp.jinja2, test-configs.yaml
Added LTP job timeout to avoid job being stuck forever
=> LTP: Add timeout parameter

test-configs.yaml
Signed-off-by: Michael Grzeschik <m.grzeschik@pengutronix.de>
=> test-configs: change dove-cubox to mach mvebu

doc/kci_testsuite.md
This commit fixes build instructions for buster-btrfs rootfs. Moves
build time dependencies to the build script and cleans up some
unnecessary files.
=> kci_doc: Fix buster-btrfs build documentation

lab-configs.yaml, templates/igt/generic-grub-tftp-ramdisk-igt.jinja2, test-configs.yaml
Add initial test plan for i915 GPU.
=> Add igt_i915 test plan

test-configs.yaml
There are on-going issues due to some Renesas platform being renamed, this is a WIP to fix it.
=> Fix renesas rename

kci_build, kernelci/build.py
Consolidate the `kernelci.build.Step` class initialisation and how it's used in `kci_build`.
=> T25311 consolidate kci_build

build-configs.yaml
Signed-off-by: Wang Mingyu <wangmy@cn.fujitsu.com>
=> build-configs.yaml: enable i386 for clang-10 and clang-11 of next

lab-configs.yaml, test-configs.yaml
add a test plan to run lib kselftest collection on hip07-d05 device.
Depends on #583 
=> test-configs.yaml: add kselftest-lib test plan

lab-configs.yaml, test-configs.yaml
This depends on https://github.com/kernelci/kernelci-core/pull/568
=> test-configs.yaml: Enable LTP-mm tests on devices in lab-collabora

templates/kselftest/kselftest.jinja2
this commit changes variable names according used in the linaro's test definitions.
=> templates: update kselftest subset parameters

kernelci/build.py
This is to create an `artifacts.json` file to contain information about all the artifacts being installed during the kernel build.
=> T25311 add artifacts.json

config/rootfs/debos/scripts/buster-ltp.sh
Build LTP open_posix_testsuite and install them
=> rootfs: Build open-posix-testsuite

config/core/build-configs.yaml
Updates to Android trees requested by Todd.
=> build-configs.yaml: Android updates

kernelci/build.py
When listing all the combinations to build, use the short fragment
name rather than the expanded one.  The expanded one will be
determined later when doing the actual kernel build.
=> kernelci.build: use short fragment name when listing builds

kci_build, kci_data, kci_test, kernelci/build.py, kernelci/cli.py, kernelci/data/__init__.py, kernelci/data/kernelci_backend.py, kernelci/test.py
Update `kci_test` and `kernelci.test` to use the new build meta-data.
=> T25311 kci test

config/lava/ltp/generic-depthcharge-tftp-nfs-ltp-open-posix-template.jinja2, config/lava/ltp/generic-grub-tftp-nfs-ltp-open-posix-template.jinja2, config/lava/ltp/generic-uboot-tftp-nfs-ltp-open-posix-template.jinja2, config/lava/ltp/ltp-open-posix.jinja2
Add ltp-open-posix-template to run functional group tests
=> templates: Add LTP open posix template

config/core/build-configs.yaml
Not for merge yet, clang-12 still didn't actually release
=> Clang 12 build

config/core/lab-configs.yaml, config/core/test-configs.yaml
=> test-configs.yaml: Enable LTP-pty tests on devices in lab-collabora

config/core/test-configs.yaml
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>
=> test-configs.yaml: add Kontron pitx-imx8m board

doc/kci_build.md, doc/kci_test.md
Fix documentation in `kci_build.md` and `kci_test.md` following the `kci_build` rewrite.
=> T25311 doc fixup

config/core/build-configs.yaml, config/core/test-configs.yaml
Enable more of the existing test plans to run on x86 Chromebooks.
=> T25739 x86 chromebooks

config/core/test-configs.yaml
Update all the Debian rootfs URLs to 20210520.0.
=> test-configs.yaml: update Debian rootfs URLs

config/lava/base/kernel-ci-base-tftp-deploy.jinja2, kernelci/config/test.py, kernelci/test.py
=> T28818 rootfs params

config/core/build-configs.yaml
=> build-configs.yaml: CIP add linux-5.10.y-cip to the testing tree

doc/config.md, doc/kci_build.md
Add and update the page about the YAML builds configuration.
=> docs: fixup builds YAML config

config/core/test-configs.yaml
Upgrade Debian URLs to 20210722.0
=> test-configs.yaml: upgrade Debian URLs to 20210722.0

doc/config/_index.md, doc/config/build-configs.md, doc/config/filters.md, doc/config/test-configs.md
Improve the YAML config documentation section and add a page for test configurations.
=> T29625 doc test configs

doc/kci_build.md, doc/kci_data.md
Add a documentation page for `kci_data`.
=> doc: add kci_data.md

config/docker/buildroot/Dockerfile
=> Dockerfile: Add KernelCI packages to buildroot image

setup.py
Install kci_data script.
Signed-off-by: Denis Efremov <efremov@linux.com>
=> setup.py: install kci_data script

config/core/test-configs.yaml
=> test-configs.yaml: Add xilinx-zcu102 device

config/docker/build-and-push.sh, config/docker/coccinelle/Dockerfile, config/docker/cvehound/Dockerfile
Add docker images for running coccinelle and cvehound.
Depends on #811
=> Coccinelle+Cvehound

config/core/build-configs.yaml, config/k8s/gen.py, kernelci/build.py
=> Add cip config fragment

config/core/build-configs.yaml
Rebased https://github.com/aliceinwire/kernelci-core/pull/2 onto main branch
Fixes #745
=> CIP configs fixup

config/docker/qemu/Dockerfile
Add qemu-utils package which is necessary to convert raw images to qcow2
=> Add qemu-utils

config/core/lab-configs.yaml, kernelci/config/lab.py, kernelci/lab/__init__.py, kernelci/lab/lava_rest.py
Retrieve the LAVA lab info using the REST API rather than XMLRPC which is showing some critical performance issues in some labs.
=> T30846 lava info rest api

config/core/build-configs-android.yaml
Add android13-5.15 branch as requested by Todd Kjos.
=> build-configs-android: add a new branch

config/core/rootfs-configs.yaml
Add bullseye rootfs image configuration.
=> bullseye rootfs: Add bullseye rootfs image

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bullseye-igt.sh
Add bullseye-igt rootfs configuration
=> rootfs-configs.yaml: Add bullseye-igt rootfs image

kernelci/config/build.py, kernelci/config/data.py, kernelci/config/lab.py, kernelci/config/rootfs.py, kernelci/config/test.py
Align the code formatting and syntax for all the kernelci.config.*
modules to make it easier to maintain and more consistent.
=> kernelci.config: align coding style and syntax

kernelci/config/data.py, kernelci/data/__init__.py, kernelci/data/kernelci_api.py, kernelci/data/kernelci_backend.py, requirements.txt, setup.py
Add initial support for the KernelCI API.
Fixes: https://github.com/kernelci/kernelci-api/issues/22
Depends on #879
=> T31049 add kernelci api

config/core/test-configs.yaml
Replace buster-igt with bullseye-igt
=> Bullseye IGT 20211118.0

config/core/lab-configs.yaml
Marking this as draft as I'm not sure if the '*' wildcard can be used for the branchname.
=> Reduce tests submitted to lab-cip

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bullseye-ltp.sh
Add bullseye-LTP rootfs configuration
=> rootfs-configs.yaml: Add bullseye-LTP rootfs image

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bullseye-libcamera.sh
Add bullseye-libcamera rootfs image
=> rootfs-configs.yaml: add bullseye-libcamera

config/docker/clang-14/Dockerfile
Add clang-14 dockerfile to generate the docker image.
=> config/docker: Add clang-14 dockerfile

config/core/test-configs.yaml, kernelci/config/__init__.py, kernelci/config/base.py, kernelci/config/build.py, kernelci/config/data.py, kernelci/config/lab.py, kernelci/config/rootfs.py, kernelci/config/test.py, tests/test_configs.py
Group default filters under `default_filters` and clean up YAML configuration.
=> kernelci.config: default filters and clean up

.github/workflows/main.yml, requirements-dev.txt
Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>
=> Fix GitHub actions running checks

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bullseye-v4l2.sh
Add bullseye-v4ltp rootfs image
=> rootfs-configs.yaml: Add bullseye-v4l2 rootfs

config/core/test-configs.yaml
Update the Debian and buildroot rootfs URLs with the latest images.
=> test-configs.yaml: update rootfs URLs

config/core/test-configs.yaml, config/lava/ltp/generic-qemu-ramdisk-ltp-open-posix-template.jinja2
Signed-off-by: Robin Lu <robin.lubin@shopee.com>
=> test configs: Allow ltp-timers to be tested in qemu device

kernelci/data/kernelci_api.py
Fixes: https://github.com/kernelci/kernelci-api/issues/66
kernelci/data/kernelci_api.py: Add put handler
kernelci/data/kernelci_api.py: Add logic in submit() to use PUT
in case the object already exists
Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>
=> Add the implementation in kernelci.data.kernelci_api.submit() to use PUT

kernelci/rootfs.py
Add a RootfsBuilder class as a base class to build rootfs images with
an abstract .build() method and refactor the implementations for debos
and buildroot to use it.
=> kernelci.rootfs: add RootfsBuilder class

config/core/lab-configs.yaml
Should be academic until more machines come online (but I'm working on
that).
=> lab-configs: Enable more testsuites for my lab

kernelci/build.py
ChromeOS maintain its own defconfigs as splitconfig files in its
repository.
Create a helper that is capable of fetching that configuration and
convert it into a standard oldconfig.
Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
=> kernelci.build: Add support for cros defconfigs

config/core/test-configs.yaml
=> Fixup for kselftest on imx6q-sabrelite

config/core/test-configs.yaml
Update kernel, modules, initrd and rootfs paths for chromeos-flash job.
=> CHROMEOS test-configs.yaml: Update chromeos-flash paths

config/core/test-configs.yaml
=> test-configs.yaml: update rootfs URLs to 20220411.0

config/core/test-configs.yaml
Another board in my lab that's able to run more tests than we currently do. This could use some more passes once some of my other pull requests have gone in.
=> Enable test coverage on Le Potato

config/scripts/base-python.jinja2, config/scripts/base.jinja2, setup.py
Add base templates for running tests with scripts in a local shell.  This is used by the PoC with the new pipeline.
Depends in #1140
=> T34835 scripts templates

kernelci/config/lab.py, kernelci/config/test.py, kernelci/lab/kubernetes.py, requirements.txt, setup.py
Add an initial `kubernetes` lab type as well as device type for early experiments.
=> T34238 kubernetes lab type

config/kubernetes/base-k8s-python.jinja2, config/kubernetes/base-k8s.jinja2
Add templates for generating Kubernetes jobs with Python inline.
Depends on #1141 for the setup.py part
=> T34238 kubernetes templates

config/core/build-configs.yaml
As requested in https://github.com/kernelci/kernelci-core/issues/1120
=> build-configs.yaml: Add weiny2 tree

config/core/test-configs.yaml
=> test-configs.yaml: update rootfs URLs to 20220428.0

config/core/test-configs.yaml
update rootfs URLs to 20220506.0
=> test-configs.yaml: update rootfs URLs to 20220506.0

kci_build, kci_data, kci_rootfs, kci_test
Fix a typo in the code and also align `kci_rootfs validate` with the other command line tools.
=> Fix a couple of issues with the kci_* validate commands

config/core/test-configs.yaml
=> test-configs.yaml: update rootfs URLs to 20220527.0

config/core/test-configs.yaml
=> test-configs.yaml: update rootfs URLs to 20220603.0

config/core/test-configs-chromeos.yaml, config/lava/chromeos/cros-boot.jinja2
Add asus-C436FA-Flip-hatch_chromeos device type
=>  CHROMEOS test-configs-chromeos.yaml: add asus-C436FA-Flip-hatch_chromeos device type

config/core/test-configs.yaml
=> test-configs.yaml: update rootfs URLs to 20220716.0

config/kubernetes/base-k8s-python.jinja2, config/scripts/base-python.jinja2
Need to update the value of `Node.status` and add `Node.result` to accommodate new node schema from API.
=> T36372 Update base template for new node schema

config/runtime/base/python.jinja2
Update the node status from 'completed' to 'complete' in the
python.jinja2 template as per the latest changes in the API.
=> config/runtime: update status to 'complete' in python.jinja2

config/core/build-configs.yaml, config/docker/clang-15/Dockerfile, config/docker/clang-16/Dockerfile
Updates for the pending clang-15 release.
=> Updates for clang-15 release

config/core/test-configs-chromeos.yaml
Include baseline test plan for grunt.
Depends on #1313
=> Add baseline test plan for grunt

config/docker-new/kci_docker
Add the --push command line argument to push the image to the Docker
Hub after building it.  This is only used by the kci_docker build
command.
=> config/docker: add kci_docker build --push option

kernelci/db/kernelci_api.py
Add a KernelCI_API.submit_results() method to submit a hierarchy of
test results in one request to the API.
Depends on https://github.com/kernelci/kernelci-api/pull/174
=> kernelci.db: add KernelCI_API.submit_results() method

kernelci/db/kernelci_api.py
Fixes https://github.com/kernelci/kernelci-core/issues/1412
Need to add parameters `_limit` and `_offset` to `KernelCI_API` class specific to pagination.
Use the default values of params to return nodes when client doesn't provide them externally. Otherwise use the values provided by the client to return nodes matching attributes.
=> T37626 kernelci_api: add pagination params and use it in `get_nodes`

config/core/test-configs.yaml
This series of commits will add several new devices available at lab-collabora
=> test-configs.yaml: Add new devices

config/docker/cros-tast/tast_parser.py
Some Tast tests take measurements. The measurements are available in the result-charts.json file. This commit adds measurent handling and publishing in LAVA test runs, which in turn are passed to KernelCI in a callback.
When Tast measurements are available, their names are converted to LAVA test cases and Tast test case names become LAVA test sets. Tast measurements have two level hierarchy, LAVA test cases names are using dotted notation to separate the hierarchy levels.
E.g.
filemanager.ZipPerf Tast test case takes various measurements e.g.
{ "tast_zip_500_small_files": {
"summary": {
"units": "ms",
"improvement_direction": "down",
"type": "scalar",
"value": 601
}
}
}
This will produce the following LAVA test result:
case: tast_zip_500_small_files.summary
measurement: 582.0
result: pass …
=> CHROMEOS tast_parser.py: Add measurements handling

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20220919.0

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20220923.1

config/core/test-configs.yaml
=> test-configs.yaml: Add CIP device r8a7743-iwg20d-q7

config/core/rootfs-configs-chromeos.yaml, config/core/test-configs-chromeos.yaml, config/rootfs/chromiumos/scripts/build_board.sh
rootfs-configs-chromeos.yaml: add chromiumos-coral
test-configs-chromeos.yaml: add chromiumos-coral
build_board.sh: apply patches specific to coral
=> T37035 CHROMEOS Integrate coral device type

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221007.0

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221024.1

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221107.1

config/rootfs/chromiumos/scripts/build_board.sh
This update add minor comments about manifest generation, and update artifacts extraction to add one more file "cros" required by new Tast tests, with more verbose build progress.
=> CHROMEOS build_board.sh: Update rootfs builder for R106

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221116.0

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221125.0

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221202.0

config/core/build-configs-android.yaml
Add builds of android as requested in https://groups.io/g/kernelci/message/1618
=> build-configs.yaml: Add android13-5.15-lts, android13-5.10-lts branches

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221209.0

config/core/rootfs-configs-chromeos.yaml, config/rootfs/chromiumos/scripts/build_board.sh
As we got quite long list of "if", we can convert them to more elegant switch/case.
Also added extraction of dtb artifacts for arm64 trogdor.
=> CHROMEOS build_board.sh: Rewrite if to switch and add trogdor artifacts

config/core/lab-configs.yaml
=> lab-configs: enable LTP in lab-baylibre

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221216.0

config/core/test-configs.yaml
We have one more Qualcomm based device(trogdor/arm64), we need add it to list of devices.
=> test-configs.yaml: Add sc7180-trogdor-kingoftown device type

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20221230.0

config/core/test-configs.yaml
Add new timens test, and add few more existing tests to improve test of arm64 platform
=> test-configs.yaml: Add more tests coverage for trogdor (arm64)

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20230114.0

kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/validate.py
Add `kernelci.cli.sub_main()` and use it with `kernelci.cli.validate`.
Depends on #1582
=> Add kernelci.cli.sub_main()

config/core/lab-configs.yaml
=> lab-configs: lab-baylibre: block android tree

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20230120.0

config/rootfs/chromiumos/scripts/build_board.sh
We need to address several issues that appear during development: 1)In case of repeating builds, especially if they fail by some reason, we need to keep SDK intact. Introduce "flag file" .keep, which is if present in output directory will prevent script from deleting SDK after build. 2)On repeating builds, if some directories already exist - don't fail
=> CHROMEOS build_board.sh: Add build improvements

config/k8s/wait.py
If more than 1 pod found - don't fail, try to continue. If pod really failed - wget will fail to fetch data. Another case is when there is networking errors inside kubernetes, and because it generate exceptions specific to urllib3, we cannot handle them easily in our code, so we handle it as generic exception, which is not nice and thing to fix in future. And few pycodestyle fixes i missed.
=> wait.py: Handle 2 more errors properly

.github/workflows/main.yml, kernelci/storage/__init__.py, kernelci/storage/backend.py, kernelci/storage/ssh.py
Fix all pylint warnings in `kernelci.storage` and enable it to run in GitHub actions.
=> Run pylint on kernelci.storage

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20230127.0

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20230203.0

config/core/test-configs.yaml
Update collabora-related devices test-plans and definitions according to availability and load.
=> Update collabora devices

.github/workflows/main.yml, tests/configs/labs.yaml, tests/test_configs.py, tests/test_runtime.py
Fix all pycodestyle and pylint errors in unit tests and enable coverage accordingly in GitHub actions.
=> Clean up unit tests

config/core/rootfs-configs.yaml, config/core/rootfs-images.yaml, config/core/test-configs.yaml, config/lava/vdso/generic-barebox-tftp-nfs-vdso-template.jinja2, config/lava/vdso/generic-depthcharge-tftp-nfs-vdso-template.jinja2, config/lava/vdso/generic-grub-tftp-nfs-vdso-template.jinja2, config/lava/vdso/generic-qemu-ramdisk-vdso-template.jinja2, config/lava/vdso/generic-uboot-tftp-nfs-vdso-template.jinja2, config/lava/vdso/vdso.jinja2, config/rootfs/debos/scripts/bullseye-vdso.sh
This enables the vDSO testsuite, a small and quick running testsuite providing focused cover of the vDSO interface.
=> vDSO testsuite support

config/core/rootfs-images.yaml
=> rootfs-images.yaml: update rootfs URLs to 20230211.0

config/core/build-configs.yaml, config/docker/clang-17-arm.jinja2, config/docker/clang-17-arm64.jinja2, config/docker/clang-17-armv5.jinja2, config/docker/clang-17-mips.jinja2, config/docker/clang-17-riscv64.jinja2, config/docker/clang-17-x86.jinja2, config/docker/clang-17.jinja2
Bump our toolchain versions for the clang-16 release.
=> Update for clang-17 release

.github/workflows/main.yml, Makefile
Enable the linter annotations in GitHub actions.  This is what what it looks like:
Depends on #1736
=> Enable GitHub linter annotations

config/core/test-configs-chromeos.yaml
We have one more Trogdor Chromebook which is a bit different from Limozeen. Add standard tast tests and start testing it.
=> CHROMEOS test-configs-chromeos.yaml: Add kingoftown Chromebook

config/core/rootfs-images.yaml
rootfs-images.yaml: update rootfs URLs to 20230224.0
This one fixes issues with #1768
=> Rootfs 20230224.0

kernelci/legacy/lava/__init__.py
Copy methods from `Runtime` into the legacy `LavaRuntime` so the new `Runtime` base class can evolve without breaking `LavaRuntime` for backwards compatibility.
=> Separate `LavaRuntime` from the new `Runtime` class

config/rootfs/debos/scripts/install-bootrr.sh
Update bootrr version for bullseye-nfs image.
=> install-bootrr.sh: Update bootrr to latest revision

Makefile, kernelci/cli/job.py, kernelci/runtime/__init__.py, kernelci/runtime/kubernetes.py, kernelci/runtime/lava/__init__.py, kernelci/runtime/lava/lava_rest.py, kernelci/runtime/lava/lava_xmlrpc.py, kernelci/runtime/legacy/lava_rest.py, kernelci/runtime/legacy/lava_xmlrpc.py, kernelci/runtime/shell.py
Rework the `Runtime` class to make it better aligned with the new API & Pipeline.
=> Runtime rework

Makefile, kernelci/cli/__init__.py, kernelci/cli/config.py, kernelci/config/__init__.py
Rename `kci validate` as `kci config` with commands to validate the YAML config and list the YAML source files.
=> `kci config` command

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/__init__.py, kernelci/cli/api.py, kernelci/cli/base.py, kernelci/cli/job.py, kernelci/cli/node.py, kernelci/cli/pubsub.py, kernelci/cli/user.py
Define and implement API methods for using the Pub/Sub.  Add new tool `kci pubsub` to use them manually.
Depends on #1792
=> Add API Pub/Sub methods and `kci pubsub` tool

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/base.py, kernelci/cli/job.py, kernelci/cli/node.py
Add implementation for the requests to get / count / create / update nodes.  Update the `kci node` tool accordingly.
=> Add API implementation for node requests

kernelci/cli/job.py, kernelci/cli/node.py
Some minor clean-up and fixes in `kernelci.cli`.
=> Fixups in `kernelci.cli`

kernelci/cli/job.py, kernelci/runtime/__init__.py, kernelci/runtime/kubernetes.py, kernelci/runtime/lava/__init__.py, kernelci/runtime/shell.py
Add `Runtime.get_job_id()` method and use it in `kci job submit` to print the job id.
=> Print job id in `kci job submit`

Makefile, kernelci/config/api.py, kernelci/config/base.py, kernelci/config/build.py, kernelci/config/storage.py, kernelci/config/test.py, tests/configs/storage-configs.yaml, tests/test_configs.py
Convert `kernelci.config.storage` objects to YAML objects and add a unit test for it.
=> Convert storage config to YAML objects using default `.to_yaml()`

kernelci/cli/__init__.py, kernelci/cli/base.py, kernelci/cli/storage.py
Add an initial `kci storage upload` command to upload files to any storage.
=> Add `kci storage` initial command

config/core/runtime-configs.yaml, config/runtime/base/docker-python.jinja2, docker-env, kernelci/config/runtime.py, kernelci/config/test.py, kernelci/runtime/docker.py, tests/configs/runtimes.yaml, tests/test_configs.py
Add an initial Docker runtime to run jobs locally in Docker containers.
=> Docker runtime

kernelci/cli/show.py
If the root node has some data, also dump it in a "Data" section.
=> kernelci.cli: add data section in "kci show results"

kernelci/api/helper.py, kernelci/cli/job.py, kernelci/runtime/__init__.py, kernelci/runtime/docker.py, kernelci/runtime/kubernetes.py, kernelci/runtime/shell.py
Add a `kernelci.runtime.Job` class to contain a job's data and use it with `Runtime`.
=> Add `kernelci.runtime.Job` class

config/core/build-configs.yaml
- build-configs.yaml: Add v6.1-rt stable tree
- build-configs.yaml: Drop old RT stable releases
- build-configs.yaml: Add -next versions of the RT stable trees
=> build-configs.yaml: Updates for RT stable trees

config/core/test-configs.yaml
LAVA device-type is upstream:
https://git.lavasoftware.org/lava/lava/-/merge_requests/2037
=> test-configs.yaml: add imx8mm-innocomm-wb15-evk

doc/kci_rootfs.md
Fix some doc errors in kci_rootfs.
=> Fix kci rootfs doc

config/core/rootfs-images.yaml
Please close (without merging) PR #1924 before merging this PR.
=> rootfs-images.yaml: update rootfs URLs to 20230512.0

kernelci/config/job.py, tests/configs/jobs.yaml
As per the discussion for the new YAML pipeline configuration schema, rename Job.conditions to Job.run_on.  Update unit tests accordingly.
See the GitHub discussion: https://github.com/kernelci/kernelci-core/discussions/1907#discussioncomment-5719345
=> kernelci.config: job: rename .conditions to .run_on

config/core/test-configs-chromeos.yaml
This commit series fix some entries, update R111 update and add new devices discovered during new firmware update automation tests.
=> CHROMEOS test-configs-chromeos.yaml: Update ChromiumOS test devices

config/core/test-configs.yaml
This board is currently available in the Collabora lava staging and should soon also be in the collabora production lab
=> test-configs: Add Renesas R-car Starter Kit H3e-2G

config/rootfs/chromiumos/cros-snapshot-release-R114-15437.B.xml
Add R114 manifest as part of preparation to ChromiumOS 114 uprev.
=> CHROMEOS cros-snapshot-release-R114-15437.B.xml: Add manifest R114

config/core/test-configs.yaml
Add 3 new devices in Collabora Lab
=> Add new devices (guybrush, puff, brya)

config/core/rootfs-configs-chromeos.yaml, config/core/test-configs-chromeos.yaml
Update relevant files for upcoming R114 images upgrade
=> R114 chromeos update

config/rootfs/chromiumos/cros-snapshot-release-R111-15329.B.xml, config/rootfs/chromiumos/cros-snapshot-release-R114-15437.B.xml
Add manifests for Chromium OS R111 and R114 from the `chromeos` branch.
=> config/rootfs: add R111 and R114 Chromium OS manifests

config/core/test-configs-chromeos.yaml, config/rootfs/debos/overlays/cros-flash/opt/chromeos/flash
This commits are required to add newer Chromebook to Tast testing
=> Add guybrush to ChromiumOS tast testing

Makefile
Also run mypy as part of "make test" since it's passing and covers the API bindings.
=> Makefile: add mypy to test target

requirements-dev.txt
Upgrade all the development packages to the latest release version
available in PyPI to keep the tools up-to-date with the latest bug
fixes.
Depends on #1982
=> Upgrade dev requirements

config/core/test-configs.yaml, config/lava/v4l2-decoder-conformance/v4l2-decoder-conformance.jinja2, config/rootfs/debos/overlays/fluster/usr/bin/fluster_parser.py, config/rootfs/debos/scripts/bullseye-gst-fluster.sh
Replacement PR for #1935 after rebase on top of `main`.
=> Add qcom fluster

config/rootfs/chromiumos/scripts/build_board.sh
We add new features that can be enabled by environment variables for easier development and ChromiumOS uprev.
=> Sandbox workaround + vanilla manifest

config/core/test-configs.yaml
This board is another one that's interesting for the audio hardware.
=> test-configs.yaml: Add Toradex Vedrin i.MX8MP

config/rootfs/chromiumos/scripts/build_board.sh
During development, it can be useful to run builds based on a fork of `kernelci-core`. This patch relies on the following environment variables:
* KCICORE_URL: the URL to the forked `kernelci-core` repo
* KCICORE_BRANCH: the name of the branch to fetch the manifest from
If those variables aren't set, it will use the `origin` remote URL and the name of the currently checked out branch. If either of those isn't available (no `origin` remote configured, detached state, not a git repo...) it falls back to using the upstream repo and `chromeos.kernelci.org` branch, as was previously the case.
=> build_board.sh: allow working from a kernelci-core fork

kernelci/cli/storage.py, kernelci/config/storage.py, kernelci/storage/__init__.py, kernelci/storage/backend.py, kernelci/storage/ssh.py
Fix and improve a few things in `kernelci.config.storage` and `kernelci.storage`:
* fix docstrings
* fix YAML tags to match the class names
* convert Storage class to ABC
* add `._connect()` method
* allow `._upload()` method to return the URL mapping to override the default implementation
=> Storage fixups

config/core/test-configs.yaml
Add new Chromebook for testing, for now just baseline.
=> test-configs.yaml: Add Cherry Tomato MT8195 Chromebook

kernelci/cli/docker.py
If Docker image build failed, we should return non-zero, so deploy scripts are aware about failure.
Also print some debug information about failure.
=> docker.py: Return non-zero exit code on build failure

config/rootfs/chromiumos/scripts/build_board.sh
While adding more comprehensive help, forgot to close quotation mark which breaks whole script
=> CHROMEOS build_board.sh: Fix last minute mistake

.gitignore
Use default Github `.gitignore` template for python projects
=> Add python project gitignore

doc/toml_settings.md, kernelci.toml.sample
Fixes https://github.com/kernelci/kernelci-core/issues/1999
=> Add documentation for TOML settings 

config/core/test-configs-chromeos.yaml
As we upgraded ChromiumOS version we have more tast tests available for testing.
=> CHROMEOS test-configs-chromeos.yaml: Add more tast tests for R114

config/core/api-configs.yaml
Add a config entry for the early-access API instance.
=> config/core: api: add early-access API config entry

config/core/db-configs.yaml
Add a YAML storage config entry for AzureFiles to be used with the Early Access deployment.
=> config/core: add early-access-azure storage entry

config/core/db-configs.yaml
Update public Azure SAS token as per ZDI-CAN-22317.
Reported-by: Denys Fedoryshchenko <denys.f@collabora.com>
=> config/core: update public Azure SAS token

kernelci/config/__init__.py
Handle YAML parser exceptions while validating the config files to provide a better validation result with the actual error message from the exception.
=> kernelci.config: handle YAML parser exceptions in validation

kernelci/cli/__init__.py, tests/test_cli.py
Add a new kernelci.cli.split_attributes() method to be used with the
Click command line tools.  This is based on the previous
implementation with symbolic comparison operators but with a revised
implementation.  Update unit tests accordingly.
=> kernelci.cli: rewrite split_attributes() method

config/core/build-configs-android.yaml
By request of maintainer, we are adding more coverage for android trees, and update clang version.
=> build-configs-android.yaml: Update clang-17 and add more builds

config/runtime/base/lava.jinja2, config/runtime/boot/grub.jinja2, config/runtime/boot/qemu.jinja2, kernelci/runtime/__init__.py
This PR passes necessary information and adds basic parameters to the LAVA TestJob template.
Verification steps will follow in the comment below.
=> Add basic parameters to LAVA job template

config/core/rootfs-images.yaml
Update fluster rootfs URL to new build.
=> rootfs-images.yaml: Update fluster rootfs URL

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/user.py
Depends on https://github.com/kernelci/kernelci-api/pull/377
`kci user` sub-commands rework.
=> `kci user` rework due to `fastapi-users` integration

config/rootfs/chromiumos/scripts/build_board.sh
The artifacts extraction currently acts based on hardcoded board names, which can be misleading and lead to incorrect results when working on a new board. Moreover, it copies the kernel image as `bzImage` no matter what the architecture is, although only x86 devices should provide this kind of kernel image.
This change reworks artifact extraction by inspecting the CrOS sources and leverages the board overlay config to find out:
* what the board architecture is so we can extract the correct kernel image (`bzImage` or `Image`)
* what vendor is the chipset from and which DTBs should be extracted on ARM64
=> CHROMEOS build_board: use board overlays instead of harcoding values

config/docker/base/host-tools.jinja2, kernelci/build.py
Fix dependencies and also produce error if in future copy-firmware script quit with error.
=> Fix linux-firmware dependencies

config/core/build-configs-chromeos.yaml, config/core/build-configs.yaml
This PR fixes a Tast test on asurada and update the tracking branch for the 6.6 build config.
=> CHROMEOS Fixes and improvements for 6.6

config/runtime/boot/depthcharge.jinja2
Add depthcharge method to support Chromebooks booting.
=> config/runtime: Add depthcharge boot method

config/runtime/base/lava.jinja2
=> config/runtime: base: drop wrong device_type defaults

kernelci/cli/__init__.py
Port the catch_http_error decorator from the legacy implementation to the new kernelci.cli package based on Click.  This can be used with command functions to show a user error whenever an HTTP exception is caught.
=> kernelci.cli: add catch_http_error decorator

config/core/rootfs-images.yaml
This image built by new rootfs script, verify it in staging, and if no problem observed - merge.
=> rootfs-images.yaml: Update fluster rootfs image

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/user.py
Fix and improve the `kci user` command implementation.
=> `kci user` command fixup

config/core/rootfs-images.yaml
Built on staging branch, using:
https://github.com/kernelci/kernelci-core/pull/2209 https://github.com/kernelci/kernelci-core/pull/1831
=> rootfs-images.yaml: Update kselftest-bookworm

kernelci/api/__init__.py, kernelci/api/helper.py, kernelci/api/latest.py, kernelci/cli/node.py, tests/api/conftest.py, tests/api/test_api.py
Move the Node API bindings to a nested abstract class API.Node and update all the related implementation accordingly.
=> Add API.Node abstract class

config/runtime/base/python.jinja2, kernelci/api/helper.py, kernelci/cli/job.py
Fix a few more places to use the new API.Node bindings class.
=> Use new API.Node bindings in a few more places

kernelci/storage/azure.py
If destination file needs subdirectory we need to make sure it exist, as Azure wont create them automatically.
=> azure.py: Verify if directory exist if destination file have subdir

kernelci/cli/__init__.py, kernelci/cli/api.py, kernelci/cli/event.py, kernelci/cli/job.py, kernelci/cli/node.py, kernelci/cli/storage.py, kernelci/cli/user.py
Fixes https://github.com/kernelci/kernelci-core/issues/2260
Extend the decorator to catch `KerError` exception and raise `ClickException` from it. This is to handle errors while reading YAML configurations in different `kci` tools.
=> `kci`: Handle exception while reading YAML configs

config/core/test-configs-chromeos.yaml
This is a `sarien` board, so we can use the same parameters here.
=> CHROMEOS test-configs-chromeos: add tests for arcada

config/core/rootfs-images.yaml
Update rootfs links to newer version, merging also with pending PR from staging.
=> rootfs-images.yaml: Update fluster to new version

config/runtime/base/lava.jinja2
New data model have a bit different location for describe, update it accordingly.
=> lava.jinja2: Update lava template to new data model

kernelci/kbuild.py
Cleanup, remove staging config left by mistake.
=> kbuild.py: Remove hardcoded staging config

kernelci/api/models.py
Make some changes to the Node models to make them fit the current use cases
=> Refine Node subtype models to match current pipeline usage

config/runtime/base/kubernetes.jinja2, kernelci/kbuild.py, kernelci/storage/azure.py
We need certain options for cross-compiling, environment variables mostly, and also to support building and packing dtb files.
=> kbuild.py: Add arm64 support and dtb support

kernelci/kbuild.py
Add riscv image names to kbuild
=> kbuild.py: Add more architectures to targets

kernelci/kbuild.py
As node might have new data, retrieve it from API just before submitting updated one.
=> kbuild.py: Refresh node before submit

kernelci/kbuild.py
This makes it easier to check whether the final config is correct.
=> kbuild: add build config to artifacts

config/docker/fragment/api.jinja2
Revert changes I made for testing and fix API url and revision branch.
=> config/docker/fragment/api.jinja2: fix API url and revision

kernelci/api/__init__.py
Simplify the base case, document the method and make it capable of handling both string and dict payloads (automatically detected).
The default and most frequent use case will still be to pass a dict to it, which will be sent to the server as a json object or as an encoded string, depending on the <json_data> parameter.
The additional capability of accepting a string fits the use cases where we might have an already processed json definition to POST instead of a python dict.
=> kernelci.api: rework and enhance the api _post() method

kernelci/api/helper.py
It might create complicated logic if submitter have his own updated data as well, for example new artifacts.
Instead, refresh node in submitter (kunit and lava_callback at moment)
Related-to: https://github.com/kernelci/kernelci-pipeline/pull/434
=> helper.py: Merge root node with refreshed node

config/core/test-configs.yaml, config/rootfs/debos/overlays/igt/usr/bin/igt-parser.sh
- test-configs.yaml: Add DRM tests for Raspberry Pi display driver
- test-configs.yaml: Add tests for Raspberry Pi GPU
=> test-configs.yaml: Add tests for Raspberry Pi GPU

kernelci/kbuild.py
This patch is the initial introduction of kselftest. Further changes will follow as patches to job templates and pipeline configuration.
=> Build kselftest

kernelci/runtime/docker.py
Try to pull image from hub, but if it fails, try to use local image. This is useful for local testing purposes. Also introduce NO_DOCKER_PULL environment variable.
=> runtime/docker: Add mechanism for local images

config/runtime/base/python.jinja2
As reported in issue, we need to make sure DNS working properly in container, before starting real job.
Fixes: https://github.com/kernelci/kernelci-core/issues/2429
=> python.jinja2: Add DNS test and retry

config/runtime/boot/u-boot.jinja2, config/runtime/tests/kselftest.jinja2
Please see commit messages for detailed description of the purpose of this PR.
=> config: runtime: tests: add new "kselftest" template

config/docker/base/host-tools.jinja2, kernelci/kbuild.py
Add dtbs check as build test and implement properly sub-nodes results.
=> Add dtbs check test

kernelci/kbuild.py
To follow same idea as legacy system, we need to generate log files that include all logs and separate stderr that will make easier to detect new warnings and build failures and same time keep easy to track where they belong.
=> kbuild: Generate file with stdout+stderr and separate stderr file

config/runtime/tests/sleep.jinja2
Add sleep template for sleep/resume test.
=> runtime/tests: Add sleep template

kernelci/kbuild.py
Add clang compiler support to kbuild
=> kbuild: Add clang support

kernelci/api/helper.py
Similar to the existing `min_version` rule, implement the needed bits for a new `max_version` rule. This can be useful if fundamental aspects of a given platform support is modified, or if support for a given platform is deprecated upstream.
=> kernelci: api: helper: add new `max_version` rule

kernelci/kbuild.py
To save space and egress fees it is better to compress log artifacts
=> kbuild: compress log artifacts

config/core/test-configs.yaml
Update available devices according the lab instructions
=> test-configs.yaml: Update volteer devices

kernelci/kbuild.py
It seems there has been a change in https://chromium.googlesource.com/ causing the config files to no longer be under a `chromeos` subdir. Until we can ensure how the generated tarball is laid out, we can try both with and without the subdir and move on with whichever option succeeds.
=> kernelci: kbuild: handle case where cros configs aren't in a subdir

config/core/api-configs.yaml
k8s being moved from eastus to westus3.
=> api-configs.yaml: Update API FQDN

kernelci/cli/node.py
Fixes https://github.com/kernelci/kernelci-core/issues/2521
Add `kci` command to submit hierarchy of results.
=> kernelci.cli.node: add command to submit hierarchy

.github/workflows/rootfs.yml
Attempt to create rootfs builds using github runners.
=> github: Add rootfs build workflow

.github/workflows/rootfs.yml
Small fixes discovered after merging
=> workflows: fixes for rootfs

.github/workflows/rootfs.yml
After test run discovered repo is expected in different format.
=> workflows: Fix repo parameter

.github/workflows/rootfs.yml
It requests to have channel as env variable.
=> workflows: Slack notification fixes

config/runtime/tests/v4l2-decoder-conformance.jinja2
Copy file template file v4l2-decoder-conformance.jinja2 and edit it.
Note: This is my first PR. Please review it and I'll improve it.
=> config: runtime: tests: Add v4l2 fluster tests lava template

kernelci/kbuild.py
1)Do not try to build dtbs for architectures that doesnt have it.
2)Add more clarity to non-critical scripts
3)Add notification that build script ended in log and script
=> kbuild.py: Add more clarity to build script logs

kernelci/kbuild.py
Few bits needed to be added for UM Linux.
=> kbuild: Add User Mode Linux support

.github/workflows/docker_images.yml
Initial version of docker workflows to test if docker images are buildable
=> workflows: Add initial version of docker images building workflows

.github/workflows/docker_images.yml
Update test docker building workflow
=> workflows: Update docker building workflow

kernelci/kbuild.py
In some cases we need to have complex targets, such as: make defconfig allmodconfig hardened.config
or
make imx_v6_v7_defconfig allmodconfig
Now we can set it as, for example:
kbuild-gcc-12-arm-android-allmodconfig:
<<: *kbuild-gcc-12-arm-android-job
params:
<<: *kbuild-gcc-12-arm-params
defconfig:
- imx_v6_v7_defconfig
- allmodconfig
=> kbuild: Allow list in defconfig option

config/core/build-configs.yaml
Update branch names for chrome-platform:
* for-kernelci -> for-next.
* for-firmware-kernelci -> for-firmware-next.
=> build-configs.yaml: update branch names for chrome-platform

config/runtime/tests/preempt-rt.jinja2, config/runtime/tests/rt-tests.jinja2
Please find the description in individual commits.
=> Add lava templete of preempt-rt

.github/workflows/rootfs.yml
Allow @musamaanjum to generate rootfs images
=> workflows/rootfs: Add Muhammad Usama Anjum to permit list of rootfs

.github/workflows/docker_images.yml
As preparation to move production to workflows, we need to build more docker images.
=> feat(workflows): Add more architectures

config/runtime/tests/wifi-basic.jinja2
Add template for WiFi basic test.
=> config: runtime: tests: add wifi basic test template

.github/workflows/docker_images.yml, .github/workflows/staging.yml
To have elegant prod/staging deploy it is preferable to split one giant workflow into reusable workflows.
This PR lay beginning of this.
=> feat(workflows): Introduce reusable workflows

config/docker/cros-sdk.jinja2, config/docker/data/tast_parser.py
We have separate chromeos branch, which is becoming hard to maintain. Let's merge as much as possible to main branch.
=> feat(chromeos): Merge cros-tast differences between chromeos and main branch

kernelci/kbuild.py
Often we have kselftest build failing, but it doesn't register as failure anywhere. Now we will add kbuild sub-node with kselftest suffix to indicate success or failure of kselftest build.
=> feat(kbuild): Add kselftest node

.github/workflows/docker_images.yml, .github/workflows/staging.yml
We need also to add generation of API and PIPELINE docker images, so staging environment can use updated images.
=> feat(workflows): Add staging building script, updates

kernelci/api/helper.py
treeid and submitter should be borrowed from parent node
=> fix(api/helper): Fix child nodes fields treeid and submitter

kernelci/kbuild.py
Right now we rely on config option, which turns to be too much of burden to maintain. Let's detect lack of modules support dynamically.
=> fix(kbuild): Detect if module dont have modules support

config/rootfs/chromiumos/scripts/build_board.sh
Tast updates ported from main tree
=> Tast updates

config/rootfs/chromiumos/scripts/build_board.sh
Some files might exist only on arm64
=> chromeos: fix(build_board): Do not crash if some files missing

config/runtime/tests/tast-debian.jinja2
=> fix(tast-debian): Various fixes for tast on debian

kernelci/api/models.py, kernelci/kbuild.py
Generate incomplete state with proper error message for easier diagnostics, for example missing fragment.
=> fix(kbuild): On kbuild failures generate failure for node

.github/workflows/production.yml
Add preliminary version of production deploy config.
=> feat(workflows): Add production config template

.github/workflows/docker_images.yml
Also auth as kernelci using github token.
=> fix(workflows/docker_images): Fix remaining repository names

kernelci/api/models.py
Now we need default value for every field.
=> fix(models.py): Add default value to model

kernelci/api/__init__.py, kernelci/api/latest.py, kernelci/cli/node.py
We have fast, non-paginated search, implement CLI function to test it.
=> feat(cli): Add findfast command for /node/fast search

kernelci/api/__init__.py, kernelci/api/helper.py, kernelci/api/latest.py, kernelci/api/models.py, kernelci/api/models_base.py
And change last commit, so prod update can proceed.
Also adding myself on files where i introduced reasonably significant changes.
=> fix(*.py): Bump copyright year and add author

kernelci/cli/node.py
To facilitate faster production update :)
=> fix(node.py): Update copyright year

kernelci/api/helper.py
In some situations we need better debug on allow/deny list
=> feat(helper.py): Better allow/deny list debug

kernelci/runtime/lava.py
In some situations request might get stuck,
take precautions against such situations.
=> fix(runtime/lava.py): Add timeout for POST

.github/workflows/docker_images.yml
Add some verbosity to troubleshoot build issues
=> feat(workflows): Add verbose output on docker build

.github/workflows/docker_images.yml
We need to upload images to Docker Hub as well.
=> feat(workflows/docker_images.yaml): Add upload to Docker Hub

.github/workflows/docker_images.yml, .github/workflows/production.yml, .github/workflows/staging.yml
1)Upload images also to DockerHub as mirror.
2)Do not build arc with clang, clang dont have this arch.
=> upd(workflows): Upload to DockerHub and stop building arc/clang

config/runtime/tests/kselftest.jinja2
We need skipfile support to skip some of tests.
=> feat(runtime/tests/kselftest.jinja2): Add skipfile support

.github/workflows/production.yml
Add to production deploy last missing step, kubernetes deployment.
=> feat(production.yml): Update k8s / deploy

kernelci/api/helper.py, kernelci/api/latest.py
This is initial work to fix files formatting and fix CI failures.
=> formatting/ci: Fix formatting using black and fix CI issues

kernelci/kbuild.py
Fixes: https://github.com/kernelci/kernelci-project/issues/509
=> feat(kbuild): Add vmlinux to artifacts

config/core/rootfs-configs.yaml
=> upd(rootfs-configs.yaml): Add zgrep to blktests

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-blktest.sh
Even more dependencies after testing tools/ scripts in kernel. Also increase image size, we need to download kernel sources :(
=> fix(rootfs-configs.yaml): blktest more dependencies

config/core/rootfs-configs.yaml, config/rootfs/debos/scripts/bookworm-blktest.sh
Last tools discovered by completing blktest tests setup.
=> fix(rootfs-configs): Final adjustments for blktest rootfs

config/rootfs/debos/scripts/setup-networking.sh
We are observing very strange resolving issues:
https://github.com/kernelci/kernelci-pipeline/issues/1064
This is attempt to improve DNS reliability.
=> (setup-networking.sh): Add cloudflare resolver

config/core/storage.yaml
Add kernelci-storage on files.kernelci.org
=> Add new storage for production

kernelci/api/helper.py
As we need to replace {kver} for ChromeOS config strings, we treat all node["data"] as f-string, but same time some entries are user supplied and might contain curly braces, which will cause confusion. Fix that by escaping curly braces.
Fixes: https://github.com/kernelci/kernelci-core/issues/2842
=> (api/helper.py) Escape all curly braces in f-strings

kernelci/kbuild.py
cip:// was processed properly in legacy system, so we need just to port code from old system.
Fixes: https://github.com/kernelci/kernelci-core/issues/2873
=> (kbuild) Add cip:// fragments proper handling

kernelci/kbuild.py
There is many dtb files in artifacts and they make kbuild pod busy due slow one-by-one upload. Let's reduce time spent in upload 10x.
=> (kbuild) Implement parallel upload

kernelci/kbuild.py
Before we reported any failure of shell script as build failure, but we need to report only build failure as "FAIL", any other failures are infrastructure failures.
=> (kbuild) Report properly infrastructure errors

.github/workflows/rootfs.yml
Fix old version of scp action and migrate slack to discord notifications
=> Workflows improvements

kernelci/cli/config.py
We can show in forecast test names, labs and platforms.
Command remain same: 
`kci config forecast -c ../kernelci-pipeline/config/`
For example:
```
Checkout: vireshk:for-kernelci
Identical builds: <<skipped>>
Number of builds: 18
Builds:
- kbuild-clang-17-arm
Number of tests: 0
- kbuild-clang-17-x86
Number of tests: 0
- kbuild-gcc-12-arm
Number of tests: 24
- baseline-arm (lava-collabora) ['imx6q-sabrelite', 'odroid-xu3', 'rk3288-rock2-square', 'rk3288-veyron-jaq']
- baseline-arm-baylibre (lava-baylibre) ['am57xx-beagle-x15', 'at91-sama5d4_xplained', 'beagle-xm', 'beaglebone-black', 'da850-lcdk', 'jetson-tk1', 'mt7629-rfb', 'sun7i-a20-cubieboard2
']
- baseline-arm-broonie (lava-broonie) ['beaglebone-black', 'imx6dl-udoo', 'imx6q-udoo', 'stm32mp157a-dhcor-avenger96']
- baseline-arm-clabbe …
```
=> kci: Add tests in forecasting

kernelci/config/base.py
That PR(introduced it) was done in hurry due emergency, so linter was ignored.
=> linter: Fix pylint error

.github/workflows/docker_images.yml, .github/workflows/main.yml
Several optimizations to speed up CI/CD and docker images builds
=> workflows: Cache packages for matrix builds
