jenkins/build-trigger.jpl
test-configs.yaml

Summary: 
* Fix a typo in the test-configs.yaml
* Remove the generic_defconfig from MIPS builds as it is not a config that is expected to be buildable, and some builds are hanging until timing out due to an unset CONFIG_HZ
Note: The patch to build with the all_abi config fragment from Anders' work-in-progress branch is being kept on staging until this has been accepted in upstream Linux kernel.

Staging 20181009

---

jenkins/bisect.jpl
jenkins/build-trigger.jpl
jenkins/build.jpl
jenkins/stretchtests.jpl
src/org/kernelci/build/Kernel.groovy
templates/v4l2/v4l2.jinja2
test-configs.yaml

Summary:
* test-configs: enable missing `vexpress_defconfig` on qemu arm
* v4l2: fix results parsing to remove spurious "v4p2-compliance" test case result
* bisect.jpl: use kernelci-core repo and use Kernel library class
* stretchtests: disable mips64el build since v4l2-compliance fails to build with this arch

Staging 20181019

---

jenkins/build.jpl
jenkins/debian/debos/overlays/tests/usr/bin/v4l2-parser.sh
jenkins/debian/debos/rootfs.yaml
jenkins/stretchtests.jpl
src/org/kernelci/debian/RootFS.groovy
templates/v4l2/v4l2.jinja2
test-configs.yaml

Summary:
* test-configs:
* add rock64 device type and run plain boot tests on it
* use 20181022.0 Debian rootfs
* enable v4l2 on rk3388-gru-kevin
* debian:
* add `test_overlay` config and tests overlay for `stretchtests` build
* use `docker && debos` labels to run debos Jenkins jobs
* v4l2:
* use /dev/kmsg to avoid log message collisions
* add `v4l2-parser.sh` script in tests overlay to fix results parsing
* build.jpl: use `docker && builder` labels to run Jenkins kernel build jobs

Staging 20181026

---

build.py
jenkins/build.jpl
jenkins/debian/debos/overlays/v4l2/usr/bin/v4l2-parser.sh
jenkins/debian/debos/scripts/stretch-v4l2.sh
jenkins/dockerfiles/gcc-7_arm/Dockerfile
jenkins/dockerfiles/gcc-7_arm64/Dockerfile
jenkins/dockerfiles/gcc-7_x86/Dockerfile
jenkins/dockerfiles/gcc-8_arm/Dockerfile
jenkins/dockerfiles/gcc-8_arm64/Dockerfile
jenkins/dockerfiles/gcc-8_x86/Dockerfile
jenkins/kernel-arch-complete.sh
jenkins/lava-boot-v2.sh
lava-v2-jobs-from-api.py
lib/test_configs.py
templates/base/kernel-ci-base.jinja2
templates/v4l2/v4l2.jinja2
test-configs.yaml

Summary:
* add GCC plugin dev packages for arm, arm64 and x86
* improve v4l2-compliance test plan to run on either vivid or uvcvideo driver
* add build environment meta-data
* pass original compiler version in the build meta-data so it can be used in bisections
* add meson-gxl-s805x-p241 board
* fix some MIPS builds using the `all` target
This depends on kernelci-backend `2019.1.2` and was tested on staging as described in https://github.com/kernelci/kernelci-backend/pull/111#issuecomment-458746284.

Staging 20190129

---

jenkins/bisect.jpl
kci_build
kernelci/build.py
push-bisection-results.py

Summary:
* Fix git describe verbose by always fetching tags from torvalds' tree
* Fix bisection email reports by including the build environment in the paths

Staging 20190214

---

build-configs.yaml
build.py
jenkins/bisect.jpl
jenkins/build-trigger.jpl
jenkins/lava-boot-v2.sh
kci_build
kernelci/build.py
kernelci/configs.py
labs.ini

Summary:
* add `lab-drue` for staging and production
* add missing android release branches and new android-4.19 branch
* add Linus Walleij's GPIO tree with 2 branches
* monitor linux-4.19.y which is the new LTS and drop linux-4.18.y which has reached end-of-life
* accept any `make` target in `build.py` to fix issue with MIPS defconfig `32r2el_defconfig`
* describe which kernels to build in `build-configs.yaml` and remove logic in `build-trigger.jpl`
Note: #21 will also be merged along before this one.
Going forward, we'll start using branches in this `kernelci-core` project and stop using `kernelci-core-staging` as it's causing confusion.  More on this later on the mailing list `kernelci@groups.io`.

Staging 20190315

---

kernelci/configs.py

Add docstrings for all the build config related classes.

T13683 kernelci.configs: add docstrings for build configurations

---

jenkins/build-trigger.jpl

Add missing comment about the KCI_STORAGE_URL parameter which is
required for the job to run.

build-trigger.jpl: add missing comment about KCI_STORAGE_URL

---

test-configs.yaml

Upgrade buildroot to version 2018.11, which includes working upstream
support for new arches: MIPS, ARC, and RISC-V

test-configs: upgrade buildroot to 2018.11, add MIPS

---

templates/boot-nfs/generic-barebox-tftp-nfs-template.jinja2
templates/boot/generic-barebox-tftp-ramdisk-boot-template.jinja2
templates/kselftest/generic-barebox-tftp-ramdisk-kselftest-template.jinja2
templates/sleep/generic-barebox-tftp-ramdisk-sleep-template.jinja2
test-configs.yaml

Signed-off-by: Michael Grzeschik <m.grzeschik@pengutronix.de>

test-configs: fix imx6ul-pico-hobbit boot method to barebox

---

jenkins/stretch-igt.jpl

The current master branch of i-g-t doesn't build on MIPS due to the
use of some hardware atomics that are not supported on MIPS.  An
upstream fix is being worked on, but disable MIPS builds in the
meantime so we can get the latest version on other architectures.

T13960 stretch-igt: disable MIPS builds as currently broken in i-g-t

---

Makefile
kernelci/configs.py
requirements.txt
tests/configs/empty-architecture.yaml
tests/configs/minimal.yaml
tests/test_configs.py

- Test parsing ./build-configs.yaml
- Add some additional test yaml files to verify edge cases
- Fix issues in configs.py related to empty fragments, build_config_defaults,
and when architecture is None
Makefile provided for convenience, with recommended invocation of
pytest. Due to the way this project is structured (specifically, that it
lacks a setup.poy), pytest must be run using python -m.
Example usage:
drue@xps:~/src/kernelci/kernelci-core$ make
python -m pytest
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.15, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/drue/src/kernelci/kernelci-core, inifile:
collected 3 items
tests/test_configs.py ... …

Add basic configs tests using pytest

---

jenkins/lava-boot-v2.sh
test-configs.yaml

BeagleBoard-X15 is the next generation Open Source Hardware BeagleBoard based
on TI's AM5728 SoC featuring dual core 1.5GHz A15 processor. The platform
features 2GB DDR3L (w/dual 32bit busses), eSATA, 3 USB3.0 ports, integrated
HDMI (1920x1080@60), separate LCD port, video In port, 4GB eMMC, uSD, Analog
audio in/out, dual 1G Ethernet.
For more information, refer to:
BeagleBoard-X15 Wiki:
http://www.elinux.org/Beagleboard:BeagleBoard-X15
Support for x15 was first added in linux v3.19. The LAVA implementation for
this board uses 'setenv console ttyS2,115200n8', which requires
CONFIG_SERIAL_8250_OMAP to be set. However, CONFIG_SERIAL_8250_OMAP was not
added to multi_v7_defconfig until v5.0.
This initial x15 implementation in kernelci will therefore restrict x15 to
v5.0+, so that it can use …

Add am57xx-beagle-x15

---

test-configs.yaml

This patch adds support for sun8i-h2-plus-orangepi-r1 and
sun8i-h2-plus-orangepi-zero

test-configs.yaml: add two orange pi opi0 and opi-r1

---

build-configs.yaml

These branches are expected to only be updated to LTS once a week.
I have tested that they parse with kci_build and produce the expected results

Add android-q branches to build-configs

---

test-configs.yaml

Fix the x86 default filters with the standard defconfig names as these
are now specific to i386 and x86_64 since the x86 arch was split and
the base defconfigs are named in build-configs.yaml.

test-configs.yaml: fix x86 default defconfig filters

---

build.py

The install phase is not installing any kernel images for RISC-V.  Fix
that.
Signed-off-by: Kevin Hilman <khilman@kernel.org>

build.py: fix riscv kernel image install

---

build-configs.yaml
build.py
jenkins/bisect.jpl
jenkins/build-trigger.jpl
jenkins/build.jpl
jenkins/dockerfiles/build-base/Dockerfile
kci_build
kernelci/__init__.py
kernelci/build.py
kernelci/configs.py
kernelci/elf.py
src/org/kernelci/util/Job.groovy

Add build commands to the `kci_build` tool and the `kernelci.build` library and use that in the build job in place of the legacy `build.py` script.  It makes the code more maintainable and focused on the KernelCI use-case with still some flexibility to build kernels manually with arbitrary configs.  It also relies on the `build-configs.yaml` data to simplify job parameters.
Following this change, the current `build.py` script will not be used any more in this repo and could therefore be removed.
Sample commands to use this locally to build a kernel from linux-next:
1. Optional: set up a local mirror
If you already have a linux check out:
```
git clone \
--mirror git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
--reference=~/src/linux linux-mirror.git
```
Then to update …

T14297 kci_build to build kernels

---

build.py

The 'make all' target doesn't actually build uImage.gz, which is the
image file needed to boot the current MIPS boards in
kernelCI (pistachio_marduk)

build.py: mips: use uImage.gz build_target

---

kernelci/build.py

Build uImage.gz by for MIPS, which isn't included in "make all".  This
is now the default kernel binary uploaded for MIPS.

kernelci.build: build uImage.gz for MIPS

---

jenkins/debian/debos/scripts/stretch-v4l2.sh

Fix the v4l2-compliance build by adding the autopoint package as a
build requirement.  Also reorder the packages alphabetically.

T14553 stretch-v4l2: add autopoint to fix v4l2-compliance build

---

kernelci/build.py

Revert to running "make all" for mips as not all defconfigs enable
uImage.gz to be built.

kernelci.build: make all for mips

---

jenkins/dockerfiles/build-and-push.sh

A (hopefully) helpful script to rebuild and push all the dockerimages used by kernelci builds.
It can also be used to build for a developer tag.

Add a script to build + push all the docker images

---

jenkins/dockerfiles/build-and-push.sh

Replace the -h option which was to provide the Docker Hub account name
with -t to provide a Docker tag prefix.  This essentially does the
same when pushing the tagged images as the beginning of the tag name
gives the account name, but it also fixes the case where a a longer
string prefix is required in the tag i.e. "-t kernelci/staging-".

dockerfiles/build-and-push.sh: replace -h option with -t for tag

---

jenkins/debian/debos/overlays/v4l2/usr/bin/v4l2-parser.sh

As discussed with Hans, v4l2-compliance tests that produce a "OK (Not
Supported)" result should be considered as passing rather than
skipped.  It means the test actually verified that it is correct for a
feature to not be supported and that there are no actual functional
errors.

stretch-v4l2: treat "OK (Not Supported)" results as PASS

---

build-configs.yaml

Once the build and boots email fixes are tested and merged, we should be good to enable clang-8 builds for arm64 on linux-next.
Tested locally that the right outputs come out of kci_build

Enable clang-8 builds on linux-next for arm64

---

jenkins/kernel-arch-complete.sh

Sent the v4l2-compliance email reports to the linux-media and kernelci
builds mailing lists as all the required changes in the report format
have now been made.

kernel-arch-complete.sh: send v4l2 reports to linux-media and kernelci

---

build-configs.yaml

Add android-4.19-gki-dev and android-mainline branches to build-configs.
Extra GCE builders have been added to production jenkins to help with the load these may add.

Add extra android trees

---

test-configs.yaml

lab-mhart has a hikey which is driven by LAVA as a standard uboot device. Add this to test-configs so that it can start receiving jobs.
Tested jobs are created as expected.

Add hi6220-hikey with uboot to test-configs

---

build.py

This was a mistake as not all MIPS defconfigs actually have a
uImage.gz target.  Switch back to 'make all'
This reverts commit c781f6d72d983334e375371fb31429c6a03919dc.

Revert "build.py: mips: use uImage.gz build_target"

---

jenkins/bisect.jpl
kci_build
kernelci/build.py

This is to enable running bisections with config fragments that are not in the kernel git tree, such as `kselftest` and `virtualvideo` but are generated using `kci_build`.

T12984 bisect with fragments

---

test-configs.yaml

Enable IGT test plan for kevin, limit kernel versions to 4.19+

Add IGT test plan for gru-kevin

---

build-configs.yaml

Add Chrome Platform's tree and the 'for-kernelci' branch.

build-configs.yaml: add chrome-platform tree

---

jenkins/buster.jpl
jenkins/debian/debos/scripts/crush.sh

Add a Debian Buster rootfs:
* add jenkins/buster.jpl to build a basic rootfs
* keep libdevmapper1.02.1 as it is required for systemd in Buster
* use "rm -f" for files that may be there in Stretch but not in Buster

T14955 Add buster rootfs

---

build-configs.yaml
jenkins/dockerfiles/gcc-8_arc/Dockerfile

Current toolchain produces unbootable kernel.
When using the new 2019.03-rc1, I produces working kernel.

dockerfiles: arc: update toolchain to 2019.03-rc1

---

test-configs.yaml

The cros-ec test plan is really called "cros-ec", not "cros_ec".
Tests were not run for this plan due to this typo.

test-configs.yaml: fix cros-ec test plan name

---

jenkins/build.jpl

Run kci_build build_kernel --verbose to have the full output stored in
the build log.

build.jpl: enable --verbose kernel builds

---

build-configs.yaml

Add definitions to build only the main defconfig of each architecture, and use it in chrome-platform as requested by @eballetbo.

chrome-platform build filters

---

test-configs.yaml

We have a meson-gxm-khadas-vim2 in lab-baylibre, ready to accept jobs.

test-configs.yaml: Add support for the meson-gxm-khadas-vim2

---

test-configs.yaml

While doing some statistics about our lab, I found that the salavtor-x
didnt worked since a long time.
The boot-method of r8a7795-salvator-x is wrongly set as qemu.
Since this board is not a qemu device, this is wrong.

test-configs: fix r8a7795-salvator-x boot method

---

test-configs.yaml

The cubietruck is lab-seattle since a long time and dont get any job.
This patchs (re?)add it.

test-configs: Add cubietruck

---

test-configs.yaml

The ox820-cloudengines-pogoplug-series-3 is on our lab since a long time
and is waiting for jobs!

test-configs: Add ox820-cloudengines-pogoplug-series-3

---

templates/base/kernel-ci-base-tftp-deploy.jinja2

On lab-baylibre, we have many slaves running on potato.
While they are still powerful enough for running lot of jobs in
parallel, they lack a bit on IO.
So while running many deploy in parallel, they hit sometimes the deploy timeout.
This patch increases the deploy timeout, 2 minutes is too short.

Increase deploy timeout

---

jenkins/buster.jpl
jenkins/debian/debos/rootfs.yaml
jenkins/debian/debos/scripts/crush.sh
src/org/kernelci/debian/RootFS.groovy
test-configs.yaml

This is to reduce the size of the Buster file system.  On `arm64`, the Stretch ramdisk is 11MB:
http://staging-storage.kernelci.org/images/rootfs/debian/stretch/20190506.0/arm64/rootfs.cpio.gz
The current Buster one is around 18MB:
https://storage.kernelci.org/images/rootfs/debian/buster/20190607.0/arm64/
This PR should bring it down to about 14MB by fixing things in the build scripts and removing a couple more things.  The `buster-igt` file system (#84) should also get smaller as a result.

T15160 optimize buster rootfs size

---

test-configs.yaml

We have a sun5i-a13-olinuxino-micro in lab-baylibre, ready to accept jobs.

test-configs.yaml: Add support for the sun5i-a13-olinuxino-micro

---

kernelci/build.py

Fix the case where a new git repo needs to be initialised and no
reference repo/mirror is provided.

kernelci.build: fix initial git clone with no reference

---

jenkins/kernel-arch-complete.sh

Currently next/pending-fixes don't have clang results, so don't send the build reports email to the clang-built-linux mailing list.

Only send build reports for next/master to clang-built-linux

---

build-configs.yaml

Andy's tree has moved, so update the build config in line with [1]. Also
update the branch which is monitored to allow for running the CI step
before the tree lands in linux-next (the way we though it was setup
already).
[1] https://lore.kernel.org/linux-arm-msm/1559936691-15759-1-git-send-email-agross@kernel.org/
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>

build-configs.yaml: Update agross repo and branch

---

kernelci/lava.py
lava-v2-submit-jobs.py
tests/test_lava.py

In addition to looking up available device_types in each lava instance,
also look for aliases.
Create a new lookup function, get_device_type_by_name(), to simplify the
lookup. Provide 6 unit tests for the new function.
Example run:
./lava-v2-submit-jobs.py --username dan.rue --token='XXX' --lab lab-linaro-lkft --jobs foo
Loading jobs from foo
LAVA API: https://lkft.validation.linaro.org/RPC2/
Connecting to Server...
Connection Successful!
connect-to-server : pass
Fetching all devices from LAVA
Fetching all device-types from LAVA
Fetching all device-type aliases from LAVA
Submitting Jobs to Server...
Submitting job kernelci-staging.kernelci.org-v5.2-rc5-178-gdac6ebf0e111-arm-multi_v7_defconfig-gcc-8-no-dtb-qemu-boot to device-type qemu
Submitting job …

Find LAVA devices by aliases, when available

---

jenkins/kernel-arch-complete.sh

The way build-trigger.jpl works is that it waits for all the kernel
builds to have completed before calling kernel-arch-complete.sh once
for each architecture.  So all the builds are already there the first
time the script is called, and we can drop the magic number of "4".
This fixes cases where some trees build fewer architectures.
This is still not optimal but it will become a lot better when
replaced with a pipeline step to generate the test jobs on a per-build
basis.

kernel-arch-complete.sh: trigger email when first arch is complete

---

jenkins/buster-igt.jpl

Now that i-g-t builds again for MIPS we can re-enable it in the
buster-igt variants.
Patches that fixed the MIPS build for i-g-t:
https://patchwork.freedesktop.org/series/62048/

buster-igt.jpl: enable mips architecture again

---

build-configs.yaml
labs.ini

Add the definition for the kernelci tree to be able to use it in production with a `kernelci.org` branch.  The `staging.kernelci.org` branch should not be in this file on the master branch to avoid triggering production every time a new revision is pushed to test on staging.
Also enable kernels build from this tree to run in the LKFT lab.

Add kernelci tree

---

jenkins/buster.jpl

Keep the "diff" utility in the Buster rootfs as it is needed for the
usb test plan.

buster.jpl: keep "diff"

---

build-configs.yaml

As per Todds request, the android-4.4 branch is being deprecated so remove it from build-configs.yaml

Remove the android-4.4 branch from the android tree

---

kernelci/build.py

All jobs generated for ARC devices uses "type: uImage.gz".
Since this type is unknow, LAVA try to convert the kernel file to an
uImage and corrupt it.
Using "type: uImage" fix this problem.
Since the file is not strictly speaking gzip compressed, that the build
create a symlink uImage->uImage.gz, the easiest fix is to tell kernelci
to use uImage.

Fix the arc imagetype

---

kernelci/configs.py
test-configs.yaml

This patchs adds support for the ARC architecture.
It adds the first boards using this arch, the HSDK

Add first ARC device: hsdk

---

test-configs.yaml

The rk3399-gru-kevin device is a device that, like other Chromebooks,
has a CrOS Embedded Controller. So, enable the cros-ec test plan for it.

test-configs.yaml: enable cros-ec test plan on rk3399-gru-kevin

---

build-configs.yaml
jenkins/kernel-arch-complete.sh
kernelci/configs.py

Reduce the number of builds for the `linusw` build configs and add support for regex filters to be able to do that.  Also send email reports to the linux-gpio mailing list.
See discussion: https://groups.io/g/kernelci/message/428

linusw build config

---

lava-v2-jobs-from-api.py
templates/base/kernel-ci-base.jinja2
templates/boot/generic-depthcharge-tftp-ramdisk-boot-template.jinja2
templates/boot/generic-qemu-boot-template.jinja2
templates/boot/generic-uboot-tftp-ramdisk-boot-template.jinja2
templates/v4l2-compliance/generic-qemu-v4l2-compliance-template.jinja2

syslog-style printk message from the kernel are available when booting
with "console_msg_format=syslog" on the kernel command-line.  This
makes it much easier for log parsers to get the log-level information
from the kernel boot logs.
Automatically add this command-line argument to all u-boot and qemu
jobs.

templates/boot: add console_msg_format to kernel cmdline

---

jenkins/bisect.jpl

Bisection jobs keep their data in the workspace in order to avoid
having to do a fresh git checkout.  However, build diretories can keep
accumulating if they are not removed as there are many possible
combinations of architectures and compilers.
To keep the disk usage under control, remove existing build
directories before starting a bisection except if there is one that
matches exactly the required arch/compiler combination as it may
contain some useful cached data when running similar bisections in a
row.

T15937 bisect.jpl: only keep one kernel build directory

---

kernelci/build.py

In order to make ccache more likely to be useful, and to be able to
discard it when necessary, keep the .ccache directory inside the
kernel build directory.  That way, it should always cache build data
relevant to the build done in that build directory, and when removing
unused build directories the cache will be removed at the same time.
Also include both the CPU arch and the compiler name in the ccache
directory name, in case a build directory is being reused multiple
times (typically, for manual builds rather than on kernelci.org).

T14893 kernelci.build: keep .ccache directory inside the build directory

---

kernelci/build.py

Export compiler names when calling `merge_config.sh` as otherwise it keeps using `gcc` even when building with `clang`.
Also do some related minor code clean-up.

T16118 clang merge config

---

templates/base/kernel-ci-base.jinja2

As the job timeout is different from one job to another so we change this
to be a configurable variable with a 10 min per default value.
Signed-off-by: Khouloud Touil <ktouil@baylibre.com>

Set the overall job timeout as a variable

---

test-configs.yaml

We have a meson-g12-odroid-n2 in lab-baylibre, ready to accept jobs.
Signed-off-by: Khouloud Touil <ktouil@baylibre.com>

test-config.yaml: Add support for meson-g12-odroid-n2

---

test-configs.yaml

This patch adds two H6 boards:
- pineh64 tested on lab-baylibre
- OrangePi 1+ tested on my lab
They are present on upstream LAVA:
https://git.lavasoftware.org/lava/lava/merge_requests/661
https://git.lavasoftware.org/lava/lava/merge_requests/680

test-configs.yaml: add two H6 boards

---

requirements.txt

pyelftools is a requirement for elf.py (import elftools):
$ ./kci_build
Traceback (most recent call last):
File "./kci_build", line 26, in <module>
import kernelci.build
File "/home/drue/src/kernelci/kernelci-core/kernelci/build.py", line 32, in <module>
import kernelci.elf
File "/home/drue/src/kernelci/kernelci-core/kernelci/elf.py", line 24, in <module>
import elftools.elf.constants as elfconst
ImportError: No module named elftools.elf.constants

Add pyelftools to requirements.txt

---

test-configs.yaml

This board has failed to boot this config for a long time, so blacklist it

Stop booting odroid-x2 with LPAE configs

---

build-configs.yaml

The android-4.19-gki-dev branch has now been deprecated and renamed to
deprecated/android-4.19-gki-dev.  Remove it from the build
configurations.

build-configs.yaml: remove deprecated android-4.19-gki-dev branch

---

jenkins/dockerfiles/clang-8/Dockerfile
jenkins/dockerfiles/clang-9/Dockerfile

Add Debian testing for clang-8 and experimental for clang-9 to resolve
the dependencies with the latest versions of these packages from
apt.llvm.org.

docker: add testing and experimental repos for clang-8 and clang-9

---

build-configs.yaml

Disable special fragments with clang builds on linux-next/master until
the issues related to merging fragments with defconfigs has been
solved.  This is to avoid noise in the build reports when we know
these are going to fail but not because of actual kernel issues.

build-configs.yaml: disable fragments with clang builds

---

test-configs.yaml

This patchs adds 2 more amlogic boards:
- meson-gxl-s805x-libretech-ac
- meson-gxl-s905d-p230
For meson-gxl-s805x-libretech-ac
https://git.lavasoftware.org/lava/lava/merge_requests/676
For p230
https://git.lavasoftware.org/lava/lava/merge_requests/674

test-configs: Add 2 more amlogic boards

---

lava-v2-jobs-from-api.py
templates/base/kernel-ci-base.jinja2

Use the device type names in YAML as the logical ones tracked by
KernelCI via the device.type meta-data, and use the "type:" attribute
as the the actual device type names to use in LAVA jobs.  By default,
these are the same.  Only qemu makes use of this feature, to introduce
different qemu_* device type variants.

lava-v2-jobs-from-api.py: distinguish device.type from device_type

---

templates/boot/generic-qemu-boot-template.jinja2
test-configs.yaml

test-configs.yaml: define qemu arch and cpu directly in context
Rather than having default values for arch and cpu defined in the qemu
boot template, define them in the YAML device configuration.

test-configs.yaml: define qemu arch and cpu directly in context

---

kernelci/configs.py

On my gentoo, using yaml.load now give:
Traceback (most recent call last):
raise RuntimeError("Unsafe load() call disabled by Gentoo. See bug #659348")
RuntimeError: Unsafe load() call disabled by Gentoo. See bug #659348
Note that on recent ubuntu, a warning appears also.
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
This is due to a security risk of using yaml.load()
Since kernelci-core does not rely on any behavour provided by load(), let's convert the call to safe_load().

Use yaml safe_load insteald of load

---

test-configs.yaml

This board has never worked on v4.14, and fixes for more recent
kernels have not been backported this far and are unlikely to ever be.
Signed-off-by: Kevin Hilman <khilman@kernel.org>

test-configs: disable hsdk for v4.14

---

jenkins/debian/debos/overlays/v4l2/usr/bin/v4l2-parser.sh

Signed-off-by: Alex P <alexandra.pereira@collabora.com>
This update will make update v4l2 test plan adding device present as a new test case. 
An important thing here is ensure that you have a media driver before running the v4l2-compliance test suite, otherwise it will works. 
You can verify the new test case in a v4l2 device available before running the v4l2-compliance test suite(https://lava.collabora.co.uk/results/1779885/0_v4l2-compliance-uvc?page=1#table).

v4l2: add device-presence test case

---

templates/v4l2-compliance/generic-qemu-v4l2-compliance-template.jinja2

Signed-off-by: Alex P <alexandra.pereira@collabora.com>
Stop passing the `no_error_inj=1`  parameter to the vivid driver as it's not required any more with the latest version of v4l2-compliance as per Hans Verkuil.

Remove vivid no error from v4l2 test template

---

kernelci/configs.py
lava-v2-jobs-from-api.py
templates/base/kernel-ci-base.jinja2
test-configs.yaml

As discussed in previous PRs, this is to fix rename the `DeviceType.type_name` attribute to clarify things.

Device type fixup

---

lava-v2-jobs-from-api.py
test-configs.yaml

Add support for filtering test jobs by build environment.
Then use this support to stop boot testing clang builds until the boot emails issue is properly resolved.

Add support to stop boot testing Clang

---

kernelci/build.py

Fix pep8 errors in kernelci.build to use raw strings with special
characters in them.

kernelci.build: fix pep8 errors

---

Makefile

Rather than letting pytest discover unit tests in the whole tree,
limit the scope to the tests directory.  This is where all the tests
currently hare, and if there is a kernel tree checked out locally it
won't be scanned by mistake.

Makefile: run pytest in tests directory

---

kernelci/build.py

When building with verbose turned on, show the full output of
merge_config.sh as well as the regular make commands.

kernelci.build: enable verbose merge_config.sh

---

test-configs.yaml

The vexpres_defconfig produces unbootable kernel for
qemu_arm-virt-gicv3, let's remove it from the qemu_arm-virt-gicv3's defconfig used.

Remove vexpres_defconfig for qemu_arm-virt-gicv3

---

jenkins/buster-v4l2.jpl
jenkins/debian/debos/scripts/buster-v4l2.sh

Signed-off-by: Alex P <alexandra.pereira@collabora.com>
The goal is to update v4l2 to use a buster rootfs image, in order to complete this we need to have some steps:

v4l2: replace stretch rootfs image with buster rootfs

---

templates/baseline/baseline.jinja2

Add test cases to the baseline test plan to check for kernel errors
using dmesg.  One test case is created for each log level starting
from "error" and up to "emergency".  Log messages at the "warning"
level are also checked but not reported as a test case.
All the kernel log lines matching these levels are then output again
in the log for debugging purposes.  The backend can't at the moment
store anything like arbitrary log strings to track individual errors,
so detecting whether there were any errors is a first step.
This relies on the latest version of the "baseline" KernelCI buildroot
file system which has the standard dmesg implementation from
util-linux rather than the busybox one.

T16420 baseline: add dmesg tests

---

kernelci/config/test.py
lava-v2-jobs-from-api.py

Make the plan argument optional in TestConfig.match() to be able to
use it to filter based on build meta-data only.
Update lava-v2-jobs-from-api.py accordingly.

T9980 kernelci.config.test: optional plan name in TestConfig.match()

---

kci_build
kernelci/build.py

Rename the build.json file created during the install phase as
bmeta.json and make it a superset of the bmeta.json file created
during the initial build.  Also simplify the builds.json created
during the publish step to have a list of data structures like
bmeta.json with the dtbs.json incorporated into them as dtb_dir_data
to match what gets stored in the backend.
This depends on https://github.com/kernelci/kernelci-backend/pull/163 to be merged at the same time.

T9980 kernelci.build: install bmeta.json and simplify JSON publish format

---

kernelci/config/test.py
lava-v2-jobs-from-api.py
test-configs.yaml

This patchs adds support for the RISCV architecture.
It adds the first boards using this arch, the hifive-unleashed-a00.
Support for LAVA is merged upstream:
https://git.lavasoftware.org/lava/lava/commit/1d5097e474fac155738994926395e27f22adfc99

Add first RISCV device: hifive-unleashed-a00

---

build-configs.yaml
jenkins/kernel-arch-complete.sh

Add Sasha's tree "sashal" and the stable-next branch to build with the
same filters as stable branches.
Suggested-by: Sasha Levin <sashal@kernel.org>
Link: https://github.com/kernelci/kernelci-core/issues/191

build-configs.yaml: add sashal tree with stable-next branch

---

kernelci/config/test.py

Fix the logic in TestConfig.match() with brackets around the condition
where there is no test plan defined.  The "and" operator takes
precedence over the "or" operator, leading to wrong results in the
corner case when the plan is None.
Fixes: b301fc1e1888 ("kernelci.config.test: optional plan name in TestConfig.match()")

kernelci.config.test: fix TestConfig.match()

---

test-configs.yaml

Use the boot_qemu test plan for qemu_i386, otherwise the generated job
doesn't boot on qemu.
Fixes: b2c29012079c ("test-configs.yaml: add qemu_i386 and clean up")

test-configs.yaml: use boot_qemu for qemu_i386

---

kernelci/build.py

When using the local .config file already present and no --defconfig
option is being used, set the defconfig name to "none" in the build
meta-data.  This should not happen with automated builds but can
happen with local builds with a .config manually created.

kernelci.build: set none defconfig when there is no defconfig

---

test-configs.yaml

Add baseline_qemu to use with all QEMU devices and update test
configurations accordingly to use it.  The regular baseline test plan
variant does not produce job definitions that work with QEMU.

test-configs.yaml: add baseline_qemu

---

build-configs.yaml

Add definition for the minimal set of builds with the main defconfig for each arch, and the "thermal" tree with testing branch which uses the minimal set of builds.

thermal testing branch

---

jenkins/monitor.jpl
kci_build
kci_test
kernelci/cli.py
kernelci/lab/__init__.py
kernelci/lab/lava.py
kernelci/test.py

Add a `kci_test` command line utility to generate and submit all the tests for a given kernel build.  It can talk to LAVA labs directly, but other types of labs can be added with extra Python modules implementing `kernelci.lab.LabAPI`.

T16583 kci_test

---

build-configs.yaml
kernelci/config/build.py

The 'variants' section has been created under build_configs_defaults and
the current content has been moved to it. It allows to creating other
default values sections in future and keeping defaults in a common
place.

Create 'variants' section in build_configs_results

---

templates/baseline/baseline.jinja2

Baseline tests should be very quick, a few seconds at most.  Reduce
the timeout from 10min to 1min for both dmesg and bootrr tests to
avoid having failing jobs stuck for much longer than needed.

baseline: set 1min timeout for each sub-test

---

kernelci/test.py

Some architectures such as arm64 and riscv have dtb files in
sub-directories, but the job name and job definition file name can't
have slashes in them.  So always get the dtb file basename to solve
this issue across all architectures.

kernelci.test: always get dtb name from file basename

---

build-configs.yaml

Add three more android branches to the build
android-4.9-q-release
android-4.14-q-release
android-4.19-q-release

build-configs: add three more android q releases

---

kci_test

If a job fails to get submitted, print an error message and carry on
with the others.

kci_test: catch exception when failing to submit a job

---

build-configs.yaml

x86 kernels with kvm guest support isn't built since the path to the
fragment isn't correct.
kvm_guest.config got moved from arch/x86/configs to kernel/configs.

build-configs: fix path to the kvm_guest.config fragment

---

lab-configs.yaml

Add missing tree whitelist filter for lab-clabbe.
Fixes: 893bea670a4e ("add lab-configs.yaml")

lab-configs.yaml: add lab-clabbe tree whitelist

---

test-configs.yaml

Suspend/resume on kevin should just work but, specially, after a merge
window, breaks. In order to catch such regressions soon, enable the sleep
test plan for this board.

test-configs.yaml: Add sleep to the test_plan for rk3399-gru-kevin

---

kernelci/config/build.py

Lack of "build_configs_defaults" section or lack of "variants" section
within it caused KeyError during the build-configs.yaml parsing. This
fix provides appropriate default values in case these sections are
missing.

kernelci.config.build: Fix "variants" section reading from configuration

---

kernelci/config/test.py
kernelci/test.py

Add missing call to TestPlan.match() for all the test plans in a test
config before adding it to the list of jobs to run.  This was causing
unwanted things such as v4l2-compliance-vivid being run on all kernel
builds rather than only those with +virtualvideo fragment.
Fixes: a1a08c3876cf ("add kernelci.test with functions to generate test jobs")

kernelci.test: add missing plan filter check in match_configs()

---

lab-configs.yaml

The android tree is causing a lot of builds from downstream kernel
branches.  As such, they are not part of the initial goal of
kernelci.org which is to test the upstream kernel.  The extra load
added to test labs is significant enough to justify blacklisting this
tree when needed.
For these reasons, blacklist the android tree in lab-collabora as it
is starting to hit the limit of the lab's capacity.

lab-configs.yaml: blacklist android jobs in lab-collabora

---

kci_test

If the build status is not PASS then don't generate any job
definitions.

kci_test: don't generate jobs for builds that failed

---

jenkins/build-trigger.jpl
jenkins/build.jpl

Add a NODE_LABEL parameter in build.jpl to dynamically pick a Jenkins
node on which to run the build.  Use this in build-trigger.jpl to
select a "big-config-builder" node with maximum number of parallel
build processes when the defconfig contains allmodconfig.

build-trigger.jpl: set special build job params allmodconfig

---

build-configs.yaml
jenkins/bisect.jpl
kci_build
kernelci/config/build.py

This PR consists of 2 changes:
1. Add get_reference subcommand to kci_build
2. Use the above in the bisection job definition
---
get_reference subcommand of kci_build prints reference tree and branch
for bisections. These are taken from the reference section of build
config or from reference_defaults when not found in the build config.
Default values of reference tree and branch are supposed to be in the build-configs.yaml file's `reference_defaults` section
e.g.
```yaml
[...]
reference_defaults:
tree: mainline
branch: 'master'
[...]
```
If specific values for a build config are needed they should be placed in the `reference` section of the appropriate build config.
e.g.
```yaml
build_configs:
[...]
mgalka:
tree: mgalka
branch: 'mgalka'
variants:
gcc-8:
build_environment: gcc-8 …
```

Define reference tree and branch for bisections

---

kci_build
kernelci/config/build.py

If for any reason no reference can be used with a build configuration,
and none is set either in the build configuration or in the defaults,
then set the reference to None.
Update kci_build accordingly to return False if there was no matchin
build configuration with a reference.
This also fixes the unit tests.
Fixes: 3b40138f4f4e ("kci_build: Add get_reference subcommand")

kernelci.config.build: make reference optional

---

test-configs.yaml

This patch adds support for:
meson-g12b-a311d-khadas-vim3
meson-gxm-q200
sun4i-a10-olinuxino-lime
sun7i-a20-olinuxino-lime2
sun7i-a20-olinuxino-micro
LAVA commit for q200 and olinuxino-micro
https://git.lavasoftware.org/lava/lava/commit/175c2678a414fc71a9197f3b30503c5fd46b1b16
LAVA commit for limes
https://git.lavasoftware.org/lava/lava/commit/324746e822732258a62ee1bff25bf52b59b505d0
LAVA commit for vim3
https://git.lavasoftware.org/lava/lava/commit/45d2120e5a8ed534660cb1e3ffa21b79a604c0d3

test-configs: Add more boards

---

kernelci/lab/lava.py
kernelci/test.py
templates/base/kernel-ci-base.jinja2

Add a job parameter "plan_variant" and use it in the base job template
as "test.plan_variant" meta-data.  This is to be able to trace the
test plan variant used when generating the job, e.g. when running
baseline on QEMU the test plan variant is baseline_qemu.

T17213 kernelci.test: add plan_variant job param and  meta-data

---

jenkins/bisect.jpl

Replace the PLAN job parameter with TEST_PLAN and TEST_PLAN_VARIANT,
and use it to run test jobs with kci_test.  Also store the lab info
JSON file and stash it along with the build meta-data and dtbs JSON
files produced by kci_build install_kernel.
This relies on the matching change in kernelci-backend to trigger
bisections with the new parameters including the test plan variant
name.

T17213 bisect.jpl: use kci_test with test plan variant parameter

---

jenkins/bisect.jpl

Remove the git describe to shorten the email subject and move the test
plan name after "bisection:" in preparation for test case bisections.
For example, rather than:
```
broonie-sound/for-next boot bisection: v5.4-rc6-292-gc1efaea10be0 on sun8i-h3-libretech-all-h3-cc
```
we would now have:
```
broonie-sound/for-next bisection: boot on sun8i-h3-libretech-all-h3-cc
```
or potentially:
```
broonie-sound/for-next bisection: v4l2-compliance on sun8i-h3-libretech-all-h3-cc
```
The git describe string was also a bit misleading as it's the "bad"
kernel revision initially tested, not the one found by the bisection.
To better connect this report with the commit it has found, we should
make it reply to the original thread when the patch was submitted on a
mailing list.

bisect.jpl: tweak email subject

---

jenkins/build-trigger.jpl
kernelci/build.py

Deal with failure to update a git repo in build-trigger.jpl by removing it and starting again.  Also improve error propagation in `kernelci.build`.

T17441 recover git repo

---

jenkins/build-trigger.jpl

Now that allmodconfig is being built on large builders with the
big-config-builder label, the arm64 defconfig is clearly the one that
takes the longest to complete with the default "make -j4" approach.
This can take up to 45min.  For this kind of medium-sized builds, we
can have dedicated smaller builders to run say at -j8 or -j12 and keep
each individual build well under 30min.

T16848 build-trigger.jpl: build arm64 defconfig with medium-config-builder

---

kernelci/build.py

Re-implemented to use the Python built-in tarfile module instead of the
tar binary from the underlying OS.

kernelci.build: Change make_tarball to pure Python implementation

---

build-configs.yaml

stable-rc build configs have now a 'stable-rc' tree with an appropriate branch
as a bisection reference.

build-configs.yaml: Add reference trees for stable-rc_* configs

---

test-configs.yaml

This patch adds support for imx8mn-ddr4-evk.
Tested on lab-baylibre, healthcheck generated via ./lava-v2-jobs-from-api.py
LAVA support merged upstream:
https://git.lavasoftware.org/lava/lava/commit/a808170c89190f135cb1bf15c3cae89b80540dde

test-configs.yaml: add support for imx8mn-ddr4-evk

---

build-configs.yaml

There shouldn't be any reason to have 'allmodconfig' builds for Arm64 and
x86_64 and to leave Armv7 out of the equation.
Signed-off-by: Lee Jones <lee.jones@linaro.org>

build-configs: Add 'allmodconfig' builds to Armv7's default configuation

---

kernelci/build.py

The git describe "verbose" attribute in the build meta-data should be
called git_describe_v rather than git_describe_verbose to match what
kernelci-backend is expecting.  Fix this so the git_describe_v gets
stored correctly in the build documents.

kernelci.build: fix git_describe_v in build meta-data

---

test-configs.yaml

Add the meson-sm1-sei610 board.
Lava device-type already merged.
link:
https://git.lavasoftware.org/lava/lava/blob/master/etc/dispatcher-config/device-types/meson-sm1-sei610.jinja2
Signed-off-by: Khouloud Touil <ktouil@baylibre.com>

Add the meson-sm1-sei610

---

kci_build
kernelci/build.py
kernelci/cli.py

Add the ability to specify the 'publish_path' which is used
to set the 'file_server_resource' in the build metadata.
This feature is useful when using kci_build + kci_test without a
kernelci-backend, and where the build output is desired in a specific
place.

kci_build: install_kernel: add publish_path

---

jenkins/dockerfiles/build-base/Dockerfile
jenkins/dockerfiles/debos/Dockerfile
kci_build
kci_test
kernelci/__init__.py
kernelci/build.py
kernelci/cli.py
kernelci/config/__init__.py
kernelci/config/build.py
kernelci/config/lab.py
kernelci/config/test.py
kernelci/lab/__init__.py
kernelci/lab/lava.py
kernelci/test.py
push-bisection-results.py
push-source.py

Convert all the kci_* utilities, the kernelci package and other
scripts to Python 3.

Convert all Python files to Python 3

---

test-configs.yaml

Convert the only 32-bit amlogic platform from mach=meson to
mach=amlogic to match the 64-bit platforms.

test-configs: meson8b-odroidc1: use amlogic for mach

---

build-configs.yaml

Todd Kjos <tkjos@google.com> writes:
> ... please undo my previous request to enable testing on "-r"
> branches
>
> Specifically:
>
> repo: https://android.googlesource.com/kernel/common
>
> 1) android-4.14 will live on and android-4.14-r won't
>
> delete: android-4.14-r
> add: android-4.14
>
> 2) android-4.19 will live on and android-4.19-r won't
>
> delete: android-4.19-r
> add: android-4.19

build-configs: android updates

---

test-configs.yaml

This patch adds support for the orangepi 3 board.

test-configs: add orangepi 3 board

---

kci_test
kernelci/cli.py

Add support for generating only jobs for a specific 'mach'.
This is useful for arch/platform/SoC maintainer trees where they are
primarily concerned with tests on a specific SoC family.

kci_test: generate: support --mach

---

test-configs.yaml

Run baseline_qemu on the new QEMU device variants, and fix the
alphabetical order of the device entries.
Fixes: 8e56ea5f5862 ("test-configs: add more ARM qemus")

test-configs.yaml: add baseline to new QEMU devices

---

.travis.yml
push-source.py

Extend Travis CI to run pep8 on all the *.py files in the top directory.

Travis CI: extend pep8 to all *.py files

---

kci_test

When creating the lab-json file, make sure that any directory
components exist before creating the file.

kci_test: get_lab_info: ensure dir exists

---

push-source.py

Open the files to push in binary mode, otherwise some UTF-8 decoding
errors appear such as this one:
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Fixes: 984d70940cdf ("Convert all Python files to Python 3")

push-source.py: open files in binary mode

---

push-source.py
src/org/kernelci/debian/RootFS.groovy

Python community recommends against making the python name point to
Python 3. The PEP-394 states that:
"If the python command is installed, it should invoke the same version of
Python as the python2 command."
Now that we switched to Python 3 the symlink is not created anymore and
the following error appears pushing the source
python push-source.py --token **** --api
python: not found
To fix this, call explicitily python3.

push-source: RootFS.groovy: Use explicitily Python 3

---

templates/base/kernel-ci-base.jinja2

LAVA doesn't accept job names over 200 characters, this is the error
it produces when that happens:
<Fault 400: "Problem with submitted job data: length of value must be at most 200 for dictionary value @ data['job_name']">
While we should be trying to keep the generate name length under 200
anyway, truncating it in the template ensures we're not causing some
job submission failures due that that.  The job name is only for
informative purposes, all the actual data saved in the KernelCI
database comes from the meta-data in the job definition so this should
not have any side-effects.

templates: truncate LAVA job names at 200 characters

---

push-bisection-results.py

Decode each line read from the output of `git bisect log` as required
with Python 3 to convert the incoming bytes into a string.

push-bisection-results.py: decode bisect log as required with Python 3

---

build-configs.yaml

Todd Kjos <tkjos@google.com> writes:
> We recently added the android-5.4 kernel, please add it to kernelci testing.
>
> repo: https://android.googlesource.com/kernel/common
> branch: android-5.4

build-configs: add android-5.4

---

kci_rootfs
kernelci/config/rootfs.py
rootfs-configs.yaml

Add basic initial implementation of the `kci_rootfs` tool which includes:
- configuration parser
- simple buster debos based rootfs configuration in rootfs-configs.yaml
- `kci_rootfs validate` subcommand that lists all configuration data based on the YAML file
- `kci_rootfs list_configs` subcommand that lists all rootfs configs available in the YAML file

Add kci_rootfs command line tool

---

.travis.yml

As KernelCI runs on Python3 now. This commit changes TravisCI
configration to use Python3 to run tests.

.travis.yml: Change Python version to 3.7

---

test-configs.yaml

This patch adds support for the pine64+ board.
Tested in lab-baylibre.
The LAVA device-type is upstream since a long time.

test-configs: add pine64+

---

test-configs.yaml

There was a typo in both at91-sama5dx, preventing any job to be
generated in lab-baylibre for them.

test-configs: fix at91-sama5dx name

---

jenkins/bisect.jpl

Since the bisection only runs one job at a time, generate the job
definition in a single file to simplify the code.

bisect.jpl: generate single job.yaml

---

test-configs.yaml

The basic x86_64_defconfig does not permit to use any VIRTIO devices.
So all baseline jobs fail to mount the virtual drive with LAVA tests.
Let's use the already present ide interface for qemu-x86_64.
Same problem and same solution for i386.

test-configs: fix running of test on qemu-x86_64/i386

---

templates/sleep/sleep.jinja2

Increase the rtcwake delay from 1s to 5s in the sleep test plan to
give enough time for the system to fully suspend before triggering
resume.
Also use multi-line YAML string to make it easier to read the shell
commands.

templates/sleep: increase rtcwake delay to 5s

---

jenkins/debian/debos/rootfs.yaml
jenkins/debian/debos/scripts/crush.sh

Instead of crushing all components from image, provide skip (-s) option to ignore
specific components from available list. By default, all components will be removed.
Signed-off-by: Lakshmipathi.G <lakshmipathi.ganapathi@collabora.com>

Modify debos crush.sh to skip specific components whenever required

---

jenkins/bisect.jpl

If for any reason the kernel git clone appears to be broken, remove it
and create a new one.  This is pretty rare but it can happen as it's
kept from one job to the next to avoid recreating one every time.

bisect.jpl: remove kernel git clone if it appears broken

---

kci_rootfs
kernelci/cli.py
kernelci/config/rootfs.py
kernelci/rootfs.py

Build rootfs images using debos command.
Usage: kci_rootfs build --config buster --debos-path /path/to/debos
Signed-off-by: Lakshmipathi.G <Lakshmipathi.Ganapathi@Collabora.com>

Add kci_rootfs build option

---

jenkins/bisect.jpl
push-bisection-results.py

Add `--no-auto-recipients` option to `push-bisection-results.py` to disable sending bisection email reports to the automatically generated list of recipients.
Use it in `bisect.jpl` to not send email reports initially as the new test case bisection is being rolled out.  If the reports appear to be fine with real use-cases then this can be reverted to enable them again.

T18197 disable sending bisection email reports to automatic recipients

---

kci_rootfs
kernelci/config/rootfs.py
kernelci/rootfs.py

Handle debos test_overlay and crush_image_options options

kci_rootfs: Include debos test_overlay, crush_image_options options

---

jenkins/buster-cros-ec.jpl
jenkins/debian/debos/scripts/buster-cros-ec-tests.sh

This new rootfs contains the python packages required to run the
Chromebooks Test Suite written in python and the test suite itself. This
is a replacement of the current cros-ec tests.

debian: add new buster-crostests rootfs

---

jenkins/dockerfiles/debos/Dockerfile

python3-yaml is needed by kci_rootfs tool which is going to be run
inside this docker image.
Tested locally.

Add python3-yaml to kernelci/debos Dockerfile

---

jenkins/build-trigger.jpl
jenkins/kernel-arch-complete.sh

Drop `$ARCH.done` files in `kernel-arch-complete.sh` to avoid having to set up a Jenkins runner on the storage server.  Also this isn't needed any more since the build trigger job knows when all the builds are complete.

Drop done files

---

test-configs.yaml

This patch adds sun50i-h5-nanopi-neo-plus2 which is ready in my lab.
The LAVA device-type is upstream for a long time.

test-configs.yaml: add sun50i-h5-nanopi-neo-plus2

---

test-configs.yaml

This patch adds sun8i-r40-bananapi-m2-ultra which is ready in my lab.
The LAVA device-type is upstream for a long time.

test-configs.yaml: add sun8i-r40-bananapi-m2-ultra

---

kci_rootfs
kernelci/build.py
kernelci/cli.py
kernelci/rootfs.py
kernelci/storage.py

Upload rootfs images to kernelci backend.
Usage: ./kci_rootfs upload --rootfs-dir=/path/to/rootfsdir
--upload-path=path/to/uploaddir --api=ip-address --token <token>

Add kci_rootfs upload option

---

templates/cros-ec/cros-ec.jinja2
test-configs.yaml

We have now a cros-ec test plan for all Chromebooks devices. So remove the
dummy and obsolete cros-ec test and use the new cros test plan. The
cros-ec test plan is using the `cros-ec-tests` python package composed of
a number of modules that will help you to do stand alone tests or setup a
fully automated tests.

Switch to use the new cros-ec test plan

---

kernelci/build.py

Currently, the KernelCI command line tool page assumes that the kernel
directory is initialized through the update_repo command
(https://github.com/kernelci/kernelci-doc/wiki/KernelCI-command-line) in
which case git describe would return a tag. However, when a user sets
the kdir to their own local checkout possibly on a branch that doesn't
have default tags, a "fatal: no tags can describe ..." error occurs.
This is resolved by adding the --always flag to the git
describe commands.
Signed-off-by: Heidi Fahim <heidifahim@google.com>

kernelci: adding --always flag to git describe

---

build-configs.yaml

Update the main defconfig for the "arc" CPU architecture which is now
haps_hs_smp_defconfig.
Link: https://lore.kernel.org/lkml/20191018121545.8907-7-Eugeniy.Paltsev@synopsys.com/

build-configs.yaml: fix arc defconfig name

---

kernelci/test.py

The URL for DTB files is missing 'dtbs' for boot jobs coming from
LAVA.  This is because the platform.dtb field in the LAVA metadata is
missing the 'dtb_dir' prefix from the build metadata (bmeta).
Fix this by checking if dtb_dir exists in the build metatdata.  If so
prepend it to the DTB relative path.
Link: https://github.com/kernelci/kernelci-backend/issues/131

kci_test: fix dtb_dir

---

kci_rootfs
kernelci/rootfs.py

By default, rootfs will be created for all architecture listed under
rootfs-configs.yaml. With this option, if required, rootfs image for given
architecture can be created.
Signed-off-by: Lakshmipathi Ganapathi <lakshmipathi.ganapathi@collabora.co.uk>

kci_rootfs: Include --arch option

---

test-configs.yaml

This platform cannot do NFS boots without a ramdisk providing network
modules.  Drop NFS boot tests for now.

test-configs: imx8mn-ddr4-evk drop boot-nfs

---

test-configs.yaml

This patch adds support for meson-sm1-khadas-vim3l.
LAVA device-type merged: https://git.lavasoftware.org/lava/lava/merge_requests/958
Device up in lab-baylibre.

test-configs: add meson-sm1-khadas-vim3l

---

test-configs.yaml

This patch adds support for bcm2711-rpi-4-b.
LAVA device-type merged:
https://git.lavasoftware.org/lava/lava/merge_requests/978
Device up in lab-baylibre.

test-configs: add bcm2711-rpi-4-b

---

kci_rootfs

Display rootfs configurations along with their supported architectures.

Add kci_rootfs list_variants command

---

jenkins/build.jpl
kci_build
kernelci/build.py
kernelci/cli.py

Slightly lower the required disk space for kernel builds, by removing
the tarball after it has been extracted.
Change-Id: I7d0f51906446e9a81786d2e92be7b263c12700c1

kci_build: Add option to delete the tarball after downloading

---

test-configs.yaml

Update buildroot URL to pick the latest version which includes fixes
in bootrr for some Rockchip Chromebook devices.

test-configs.yaml: update buildroot to latest build version

---

build-configs.yaml

Normalize repo URLs to `https://`, where possible, to satisfy [KCIDB schema
requirements][1]. Fallback to `git://` where that's not possible (to be
permitted by KCIDB schema).
This will help the URLs to match between CI systems.
[1]: https://github.com/kernelci/kcidb/blob/c1d776df9490ed26a587b830a9b8e485df88b96e/kcidb/io_schema.py#L80-L86

Normalize repo URLs to HTTPS where possible

---

kci_test
templates/baseline/generic-barebox-tftp-ramdisk-baseline-template.jinja2

Add template for the baseline test plan on barebox devices, to fix job submission with the Pengutronix lab.
Also fix error propagation in `kci_test` when a job definition fails to get generated.

Baseline barebox

---

build-configs.yaml

With this commit:
$ ./kci_build list_kernel_configs --kdir=<linux kernel dir> \
--config=next | grep clang | sort
arm64 allmodconfig clang-9
arm64 allnoconfig clang-9
arm64 defconfig clang-9
arm allmodconfig clang-9
arm allnoconfig clang-9
arm aspeed_g5_defconfig clang-9
arm multi_v5_defconfig clang-9
arm multi_v7_defconfig clang-9
x86_64 allmodconfig clang-9
x86_64 allnoconfig clang-9
x86_64 defconfig clang-9
Before this commit, we were testing 113 targets with Clang, including
broken fragments like x86_64_defconfig+kernel/configs/kvm_guest.config
and most ARM configs. The above listing gives us basic coverage of
ARMv{5|6|7|8} and x86_64.

restrict clang defconfigs

---

test-configs.yaml

Some URLs were using HTTPS while others HTTP, align them all to use
HTTP instead.  In particular, this makes it possible to have file
caching in test labs with Squid.

test-configs.yaml: align all URLs to use plain HTTP

---

build-configs.yaml

Remove EOL stable branches and add linux-3.16.y and linux-5.6.y.

build-configs.yaml: update list of stable branches

---

jenkins/dockerfiles/build-base/Dockerfile

kselftest build/install has (unexplained) dependency on rsync.  While
this may be removed eventually, let's add so we can build/install
current (and older) kselftest.

jenkins/dockerfiles: build-base: add rsync

---

jenkins/bisect.jpl
jenkins/build-trigger.jpl
jenkins/build.jpl
jenkins/monitor.jpl
jenkins/test-runner.jpl

Remove the build- part of the DOCKER_BASE strings and add it in each
job that actually requires it.  This is to be able to have the same
DOCKER_BASE for jobs that require other types of Docker images such as
kernelci/debos.

jenkins: remove build- from DOCKER_BASE

---

jenkins/rootfs-builder.jpl
jenkins/rootfs-trigger.jpl

Use kci_rootfs in Jenkins job to create required rootfs for given architecture.
Signed-off-by: Lakshmipathi Ganapathi <lakshmipathi.ganapathi@collabora.co.uk>

Build Buster rootfs using kci_rootfs

---

README.md
doc/kci_build.md
doc/kci_test.md

Add a "doc" directory with detailed documentation for kci_build and
kci_test.  Update README.md with links to them and add some general
introduction about the project.
A rendered version of the files on the incoming branch can be seen here:
https://github.com/gctucker/kernelci-core/tree/cli-doc

doc: add detailed sections for kci_build and kci_test

---

build-configs.yaml

Add the android stable branches for 4.14, 4.19 and 5.4 as they are
among the most important ones to cover.  For some reason they had
never been built on kernelci.org before.

build-configs.yaml: add android-{4.14,4.19,5.4}-stable branches

---

kernelci/__init__.py
kernelci/build.py

Add and use kernelci.print_flush() in kernelci.build functions to have
messages such as the "make" commands printed on stdout immediately.
This is to deal with the cases where it might be buffered in
automation systems and keep the output as intended.

kernelci.build: use kernelci.print_flush()

---

lab-configs.yaml

My internet line got upgraded to fiber and I increased the throughput of
my lab.
So it can handle more tree job.

lab-configs: enable stable and mainline in lab-clabbe

---

build-configs.yaml

Starting with v5.7, the media test drivers need MEDIA_TEST_SUPPORT=y
to be enabled.  Add this to the virtualvideo config fragment.
Link: https://lore.kernel.org/linux-media/20200415142147.1ed3487e@coco.lan/

T20625 build-configs.yaml: add MEDIA_TEST_SUPPORT=y to virtualvideo

---

kci_build
src/org/kernelci/util/Job.groovy

Fix the output of `kci_build show_build_environment` and update the Jenkins library to use it rather than hard-coding the mapping between architecture names for the kernel and compilers.

kci_build: fix show_build_env and use it for Docker image names

---

build-configs.yaml

Add the build environment definition for clang-10 and build arm64 and
x64_64 defconfigs with it on linux-next/master branch.  Also clean up
the clang-9 config for linux-next to keep them consistent.

build-configs.yaml: add clang-10 for linux-next/master

---

test-configs.yaml

Add definition for the mt8173-elm-hana arm64 Chromebook device and
enable some relevant test plans to run on it.

test-configs.yaml: add mt8173-elm-hana arm64 Chromebook

---

jenkins/dockerfiles/gcc-8_arm64/Dockerfile

arm64 supports 32 bit arm userspace, including a VDSO for that userspace
which needs a 32 bit toolchain to build, so add the arm toolchain so we
can provide coverage for it.

dockerfiles: Include arm toolchain in the arm64 GCC container

---

build-configs.yaml
kci_build
kernelci/build.py
kernelci/config/build.py

These two patches update kci_build to build the compat VDSO on arm64, giving us coverage of that.
Doing these builds will depend on having a docker container with the Arm compiler added as enabled by the separate pull request https://github.com/kernelci/kernelci-core/pull/353

Cross compile compat

---

lab-configs.yaml

Our lab has move and is now accessible only via https.

lab-configs: use the new LAVA url to access lab-baylibre

---

lab-configs.yaml

As discussed with Dan, lab-drue is now going to be offline until
further notice so remove it from the YAML config.

lab-configs.yaml: drop lab-drue as it's permanently offline

---

test-configs.yaml

Update to latest buildroot version kci-2019.02-10-g24600c76ce51 which
includes a KernelCI overlay with the dmesg.sh script for the baseline
test plan.

T20434 test-configs.yaml: update buildroot with built-in dmesg.sh for baseline

---

templates/baseline/baseline.jinja2

The baseline rootfs images now have a dmesg.sh script which can be
called to run the dmesg tests and reduce the noise in the LAVA log.
Use it in the baseline job template rather than defining the steps
inline.

T20434 baseline: use dmesg.sh script from the rootfs

---

test-configs.yaml

The stm32mp157c-dk does not boot with kernel produced by stm32_defconfig.
More generaly (quoting Alexandre Torgue):
For mpu boards you have to use multi_v7_defconfig.
The stm32_defconfig has to be used for MCU boards (f4/f7/h7) only.

test-configs: blacklist stm32_defconfig for stm32mp157c-dk

---

jenkins/build-trigger.jpl

The build trigger should pass it's arguments on to the build job, in
particular those that affect kernelci-core repo usage and the kernelci
API.

build-trigger: pass-on params to build

---

push-bisection-results.py

Fix simple new pycodestyle errors due to short variable names "l".

push-bisection-results.py: fix pycodestyle errors with short variables

---

jenkins/dockerfiles/build-and-push.sh
jenkins/dockerfiles/dt-validation/Dockerfile

The kernel has started moving devicetree schemas to a format which
allows for automatic validation.  This requires a separate build target
and a toolset (currently not packaged for any distro) so create a new
docker container with the toolset installed that we can use to run these
tests.

dockerfiles: Add container for DT validation

---

README.md
doc/kci_rootfs.md

Provide quick kci_rootfs How-To doc to build existing rootfs
images and create a new rootfs image.

doc: Add kci_rootfs usage

---

jenkins/build-trigger.jpl

build.jpl doesn't use KCI_STORAGE_URL, don't pass it.
Fixes: 1a1c57041c61 (build-trigger: pass-on params to build)

build-trigger: don't pass KCI_STORAGE_URL to build

---

test-configs.yaml

The DTB of all renesas board was renamed in v5.6, so renesas boards wont
get new jobs.
The simple fix is to duplicate them in kci and use LAVA aliases.

test-configs: handle rename of renesas boards

---

test-configs.yaml

Some i.MX* boards were imx, others freescale.  Align them all on imx
which is also the mach name in the kernel source tree.
Fixes: 253bc4591c07 ("adding imx6q-sabresd and imx7d-sdb to kernelci.org")
Fixes: 06c33cb4532b ("test-configs.yaml: add support for imx8mn-ddr4-evk")

test-configs.yaml: move all i.MX* boards to imx mach type

---

build-configs.yaml

A couple of tweaks to the configuration for the EFI tree configuration - add the urgent branch for testing fixes and restrict the configurations built to a subset since the main goal for EFI testing is boot rather than build coverage.
@ardbiesheuvel - does this look OK to you?

EFI tree updates

---

test-configs.yaml

D2500CC is an x86_64 board with an "embedded" intel CPU.
This board lacks PXE, so it is booted via a fake GRUB.
It is a bash init script which emulates GRUB commands and then kexec the final kernel.

test-configs: add D2500CC

---

test-configs.yaml

The arm64 emulation in qemu supports architectural features which are not
present in currently shipping CPUs that are emulated by qemu. Many of
these have support in software and it would be good to get coverage for
them so rather than emulating cortex-a57 (which has plenty of physical
implementations) instead specify the CPU as "max" when invoking qemu which
will make the CPU as featureful as possible.
This does mean that the exact feature set of the CPU being emulated will
vary depending on the target system, the qemu version and when the host
is arm64 based the host hardware will control what gets selected. We will
need to pay attention to this going forwards.

test-configs.yaml: Use max CPU for arm64 qemu targets

---

jenkins/bisect.jpl

It has been 6 months since automated bisections were enabled on all
test cases, and this is proving to be working well.  We can now have
the email reports sent automatically to all the recipients.
This reverts commit 0df55b7061b0520b3b36323fd21bd943e7b71ebb.

Revert "bisect.jpl: disable automatic email recipients"

---

lab-configs.yaml

The lab-free-electrons, which would now have to become lab-bootlin, is
offline with no plans to bring it back online in the near future.  As
aggreed with Bootlin contacts, remove it from the kernelci.org
configuration.

lab-configs.yaml: drop lab-free-electrons as confirmed with Bootlin

---

build-configs.yaml

Add a for-kernelci branch in my misc tree for testing of changes without
putting them into a production branch - this will be infrequently used,
the intention is to allow me to check changes that I'm worried might be
disruptive on a wide range of hardware without publishing them in my normal
development branches where they can cause trouble in trees like -next.
The goal here is to get runtime testing so ideally the built configurations
could be limited to those that will usefully boot, unfortunately we don't
really have a way of specifying that at present.

build-configs.yaml: Add a branch in my misc tree

---

.travis.yml
kci_build
kci_test

Add basic validation of the YAML config to detect syntax errors and run it in Travis CI.  Proper validation should be added as a follow-up using `jsonschema`.

YAML validation

---

jenkins/dockerfiles/build-k8s/Dockerfile

Add new container capable of submitting build jobs to a k8s cluster.
The service-account key must be mounted at docker-run time for
'gcloud auth` to work correctly.

dockerfiles: add k8s build node

---

jenkins/dockerfiles/build-and-push.sh

Add a -k option to build-and-push.sh to also build the Docker image
for submitting Kubernetes jobs.

dockerfiles: add build-and-push.sh -k option for k8s

---

test-configs.yaml

Currently we only build test with clang, we don't boot the resulting
binaries as there were some issue with the boot-specific reporting.  As
that is being phased out there is now no reason not to include clang
binaries in testing so do so, existing use of clang by developers and
results on staging do not suggest this is likely to result in many
additional failures.

test-configs: Enable clang boot testing

---

test-configs.yaml

Add imx6qp-sabresd, imx6sll-evk, imx6sx-sdb, imx6ul-14x14-evk, imx6ull-14x14-evk, imx7ulp-evk, imx8mm-ddr4-evk, imx8mp-evk to kernelci tests
Following are the jobs verified
imx8mp-evk
baseline: https://lavalab.nxp.com/scheduler/job/23466
imx6sx-sdb
baseline - https://lavalab.nxp.com/scheduler/job/21321
imx6ul-14x14-evk
baseline - https://lavalab.nxp.com/scheduler/job/21311
imx6ull-14x14-evk
baseline - https://lavalab.nxp.com/scheduler/job/21313
imx6sll-evk
baseline - https://lavalab.nxp.com/scheduler/job/21307
imx6qp-sabresd
baseline - https://lavalab.nxp.com/scheduler/job/21308
imx7ulp-evk
baseline - https://lavalab.nxp.com/scheduler/job/22625

Add various NXP i.mx boards to kernelci

---

templates/k8s/gen.py
templates/k8s/job-build.jinja2
templates/k8s/wait.py

Updates from v1:
- rebase onto master branch
updated from last time
- CPU limit/request paramterized based on PARALLEL_BUILDS
- KCI_API_TOKEN stored as k8s secret
- new docker image (khilman/build-k8s) for driving k8s.  Based on build-base w/gcloud-sdk installed
- jenkins "k8s" nodes now have env variables to configure
all gcloud secrets and environment
Issues
- kci_build needs a way to pass secrets (e.g tokens) not on the cmdline (otherwise they show on stdout from k8s)

RFC v2: demonstrate k8s builders

---

kernelci/build.py

The merge_config.sh script needs CROSS_COMPILE_COMPAT env set in order
to properly merge configs, otherwise some settings that depend on
that (e.g. VDSO-related) will get disabled during the merge.

build.py: merge_config needs CROSS_COMPILE_COMPAT

---

db-configs.yaml
kci_data
kernelci/cli.py
kernelci/config/data.py
kernelci/data.py

kci_data is a tool to feed test data to different types of result
storages. This commit adds basic functionality of the tool that allows
to submit data to /test API of kernelci-backend.

Add kci_data commandline tool

---

test-configs.yaml

Update the URLs for the UEFI firmware binaries provided by Ard to use
edk2-stable202005.  Also switch to using the same 32-bit i386 UEFI
binary with the "mixed" variant for x86_64 kernel.

test-configs.yaml: update UEFI binaries with edk2-stable202005

---

lab-configs.yaml

The "simple" test plan has been dropped, and "kselftest" is not ready to be run yet.  Drop both from filters in lab-configs.yaml to only  run baseline in lab-nxp and lab-theobrama-systems.

Fix lab-configs.yaml by removing simple and kselftest from filters

---

build-configs.yaml

Request from Google (Todd Kjos):
> We renamed a couple of Android kernel branches, so the old names
> should be removed from kernelci and the new ones added (the old names
> still work, but will go away in a few weeks). Also, the android-4.19
> branch is deprecated (other android-4.19-* branches should still be
> tested):
>
> Repo: repo: https://android.googlesource.com/kernel/common
> Remove: android-5.4, android-5.4-stable, android-4.19
> Add: android11-5.4, android12-5.4

build-configs: android branch renames

---

kernelci/cli.py
kernelci/config/__init__.py
kernelci/config/lab.py
kernelci/config/rootfs.py
kernelci/config/test.py
kernelci/lab/__init__.py

Use the Python 3 class definition style without (object) for base
classes, and plain super() for calling direct parent method.

kernelci: use Python 3 class and super()

---

README.md
doc/lava.md

Add a basic documentation page to explain what LAVA is, how it's used
with KernelCI in general and how to add a LAVA lab to kernelci.org.
Also add a paragraph about a user guide with a link in the top-level
README.md file.

T22670 doc/lava.md: add page to explain how to connect a LAVA lab

---

test-configs.yaml

The qemu_arm-vexpress-a15 jobs have been showing some GIC kernel
errors such as this one:
GIC CPU mask not found - kernel will fail to boot.
This can be fixed by enabling 2 CPU cores using the "-smp 2" QEMU
parameter.  Add it to the extra options accordingly.
Reported-by: "André Przywara" <andre.przywara@arm.com>

test-configs.yaml: add -smp 2 option on QEMU vexpress-a15

---

templates/k8s/job-build.jinja2

Fix mistake with "kci-api-token-staging" being hard-coded in the k8s
job template by using the KCI_API_TOKEN_ID environment variable
instead.  This can be set to whatever is required on each host.
Fixes: 725929c08091 ("templates: support tools/scripts/templates for k8s builds")

templates/k8s/job-build.jinja2: use KCI_API_TOKEN_ID

---

lab-configs.yaml

Currently the LKFT lab has a specific list of branches that are accepted,
mainly used to filter exactly which stable trees are covered. Since there
have been issues with submitting jobs for a considerable time this now
only covers very old stable branches so let's update to include newer ones.
Do this by replacing the explicit list of branches with just accepting
trees as a whole, comparing the list of stable trees that KernelCI covers
with those covered in LKFT's native testing they look to be the same at
the minute. For the other trees covered, -next and kernelci, all the
branches in those trees are included in the explicit list already so there
should be no change. Doing things by tree will reduce the maintenance
overhead going forwards.

lab-configs: Accept all stable trees on LKFT lab

---

kernelci/test.py

Currently we do not supply the branch name in the filter set we use to
determine which tests to run on a given lab. This is useful for trees
like stable with many branches and currently causes the filters set up
for the LKFT lab which include the branches to not match anything
resulting in no jobs being scheduled there. Add the branch name.

kernelci.test: Allow filtering on branches

---

jenkins/dockerfiles/debos/Dockerfile

In order for debootstrap to work from sid/unstable with debian-ports,
we need the keyring debian-ports.

dockerfiles/debos: add keyring for debian-ports

---

jenkins/debian/debos/rootfs.yaml
kci_rootfs
kernelci/config/rootfs.py
kernelci/rootfs.py
rootfs-configs.yaml

riscv64 support is available in debian, but only in unstable/sid.  It
also requires using debian-ports.
In order to use debian-ports, the debian mirror needs to be a config
parameter.

kci_rootfs: add debian riscv64 support for sid / debian-ports

---

doc/kci_build.md
doc/kci_test.md
kci_build
kci_data
kci_rootfs
kci_test
kernelci/cli.py
templates/k8s/job-build.jinja2

Replace Args.token with Args.db_token and Args.lab_token, with
argument names --db-token and --lab-token to avoid any ambiguity.

kernelci.cli: replace --token with --db-token and --lab-token

---

templates/k8s/gen.py

Azure nodes with 32 vCPUs refuse jobs with CPU request > 30.  This is
causing all "big" jobs stay stuck in a Pending state.
Support ticket open with Azure.

TEMP: k8s: lower CPU request for 32-CPU VMs

---

jenkins/debian/debos/scripts/setup-networking.sh
rootfs-configs.yaml

Add a DHCP client to the full rootfs (removed for the minimal rootfs).
This is required for proper network setup in a NFSroot setup, since
debian systemd does not properly setup DNS when the kernel has been
booted with kernel IP autoconfig (e.g. booting the kernel with
"ip=dhcp" on the command-line.)
The solution is to run "dhclient" immediately after login
to (re)configure networking before DNS is usable.

rootfs-config: buster: add DHCP client to full rootfs

---

test-configs.yaml

The Cavium ThunderX is an arm64 server class system, generally booting
using ACPI based firmware.

test-configs: Add ThunderX

---

rootfs-configs.yaml

Fix typo in path to baseline overlay.
Fixes: 9b69ba3c84f7 (rootfs-configs: add baseline overlay to default buster)

rootfs_configs: fix baseline overlay path

---

doc/kci_build.md
doc/kci_rootfs.md
doc/kci_test.md
kci_build
kci_data
kci_rootfs
kci_test
kernelci/cli.py
templates/k8s/job-build.jinja2

This is in preparation for adding support for settings files.  Some commands may be using multiple configurations, such as a database and a build configuration or a test lab.  For this reason, it's necessary to be able to distinguish between them so each config argument should be specific i.e. `--build-config`, `--lab-config`, `--db-config` rather than a generic `--config`.

T23120 config args

---

kci_rootfs

Do not print anything by default when running kci_rootfs, only if
--verbose is provided as the main purpose is to validate the YAML
configuration.

kci_rootfs: align implementation of the validate command

---

setup.py

When installing kernelci via pip, all the dependencies are
not properly installed:
```
~ ϟ kci_build --help
Traceback (most recent call last):
File "/home/mkorpershoek/.local/bin/kci_build", line 23, in <module>
import kernelci.build
File "/home/mkorpershoek/.local/lib/python3.8/site-packages/kernelci/build.py", line 32, in <module>
import kernelci.elf
File "/home/mkorpershoek/.local/lib/python3.8/site-packages/kernelci/elf.py", line 24, in <module>
import elftools.elf.constants as elfconst
ModuleNotFoundError: No module named 'elftools'
```
```
~ ϟ pip3 show kernelci
Name: kernelci
Version: 1.0
Summary: KernelCI core functions
Home-page: https://github.com/kernelci/kernelci-core
Author: kernelci.org
Author-email: kernelci@groups.io
License: UNKNOWN
Location: …
```

setup: add all dependencies to setup.py

---

requirements.txt
setup.py

Drop they "keyring" package from the list of requirements as it's not
used anywhere.  Update requirements.txt accordingly.

setup.py: drop keyring from requirements

---

kernelci/build.py

Add conditional step to build_kernel that builds the in-kernel
selftests.  Build is conditioned on "kselftest" being in
defconfig_extras.
If kselftests are build, install_kernel will create a
kselftests.tar.xz archive that will be published in the publish_step,
and added to bmeta.json (key: kselftests)

build.py: build/install kselftests

---

README.md
doc/settings.md
kci_build
kci_data
kci_rootfs
kci_test
kernelci.conf.sample
kernelci/cli.py

Add support for a settings file with sections per component and per command line utility, with the possibility to override any of these values with command line arguments to keep compatibility with current use-cases.

T23210 settings file

---

jenkins/dockerfiles/clang-10/Dockerfile
jenkins/dockerfiles/clang-9/Dockerfile

In order to support testing of LLVM=1 builds include lld and llvm in the
images for the existing versions of clang.

dockerfiles: Add lld and llvm to the clang Docker images

---

build-configs.yaml

The clang-10 build configuration did not provide compat cross compilers
meaning that we weren't getting coverage of the arm64 compat vDSO. While
clang can build arm without any compat tools the kernel build system
currently requires that a compat cross toolchain be explicitly configured
to enable build of the arm64 compat vDSO.
Reported-by: Kevin Hilman <khilman@baylibre.com>

build-configs.yaml: Set compat cross compilers for clang-10

---

kernelci/build.py

If building with clang, also set LLVM=1 which will enable all the
other LLVM tools as well, including linker.  When doing so, do not set
HOSTCC since that is already handled by LLVM=1
Also note that 'make LLVM=1' only works in v5.4+, but currently, we're
only doing clang builds in linux-next, so enabling this as the default
should be fine.

kci_build: clang builds use LLVM=1

---

kernelci/build.py

When using LLVM/Clang, also pass LLVM=1 when calling merge_config.sh
as this gets propagated to make sub-processes unlike CC and HOSTCC.

kernelci.build: use LLVM=1 with merge_config.sh and clang

---

kci_test
kernelci/build.py

Some platforms don't use any dtb file, and while the dtbs.json file is
normally always generated by the build_kernel() command, it's not
strictly required to keep it and use it again for platforms that don't
need it.  So make dtbs_json an optional argument in .load_json() and
update kci_test accordingly when generating test jobs.

kernelci.build: make dtbs.json optional in .load_json()

---

kernelci/cli.py

Put the lab_json option in the per-lab section in the settings file.
Each lab should have a separate JSON file with a locally saved copy of
its particular data (i.e. online device types...).

kernelci.cli: put lab_json option in lab section

---

kernelci/test.py
templates/base/kernel-ci-base.jinja2

Clean up the meta-data passed in LAVA jobs as part of the more general clean-up of the kernelci-backend schema for non-LAVA labs.
Depends on https://github.com/kernelci/kernelci-backend/pull/249

T23119 schema clean up

---

build-configs.yaml

The devel branch disappeared when the renesas-devel repo moved from horms
to geert.
Signed-off-by: Chris Paterson <chris.paterson2@renesas.com>

build-configs: Change Renesas devel branch to master

---

build-configs.yaml
lab-configs.yaml

arm64 supports a range of page sizes, including 64K. In testing on other
systems we seem to turn up a small but interesting stream of bugs on 64K
pages which it'd be good to keep an eye on so let's enable a build with
that config option enabled.
This is added for clang-9 simply because we're not really focused on which
compiler is used for the coverage but clang-9 is the only compiler which
has a list of configs already specified so it's the least invasive change.

build-configs: Enable coverage of 64K pages on arm64

---

kernelci/build.py

Replace any instance of a slash character "/" in each component making
up the file server resource path with a "-" so they don't end up
creating sub-directories.  This was already done for the
defconfig_full component, but it needs to be done for all of them as
it's a common issue with branch names in particular.
Depends on https://github.com/kernelci/kernelci-backend/pull/254
Depends on https://github.com/kernelci/kernelci-frontend/pull/124

T21323 kernelci.build: use - instead of / in resource path components

---

kernelci/test.py
lab-configs.yaml
templates/kselftest/generic-uboot-tftp-nfs-kselftest-template.jinja2
templates/kselftest/kselftest.jinja2
test-configs.yaml

Update the kselftest test-plan:
1) use the kselftest tarball that is now part of kernelci builds.
2) use debian NFS root (ramdisk + modules, then pivot-root to NFS)
3) use Linaro test-definitions repo for running kselftests
Sharing test-defintions with LInaro/LKFT will allow better collaboration on keeping kselftests running/reliable.
NOTE: this draft PR is based on staging due to dependencies on existing PRs not yet merged into master.

update kselftest, use Linaro test-defintions

---

kernelci/build.py

The LAVA test-definition has been fixed to handle .tar.xz, so
compress kselftest tarball with xz now.

kernelci/build: kselftest use .tar.xz

---

build-configs.yaml

Now that slash "/" characters can be used in git branch names, enable
the arm/fixes branch in the soc tree.

build-configs.yaml: enable arm/fixes branch in soc tree

---

jenkins/dockerfiles/clang-10/Dockerfile
jenkins/dockerfiles/gcc-8_arm/Dockerfile
jenkins/dockerfiles/gcc-8_arm64/Dockerfile
jenkins/dockerfiles/gcc-8_x86/Dockerfile

Add build dependencies for x86, arm and arm64 to the gcc-8 and
clang-10 Docker images.  This causes some duplication, but there is no
easy way around it at the moment.

T23362 docker: add kselftest build dependencies to gcc-8 and clang-10

---

templates/sleep/sleep.jinja2
templates/sleep/sleep.sh
templates/sleep/sleep.yaml
test-configs.yaml

Costomize the sleep test to use parameters and run the suited tests.
The parameters to be added in the test-config.yaml file to each board
that supports the test.
Add a check for the existence of the rtc otherwise it won't execute
the test.
Signed-off-by: Khouloud Touil <ktouil@baylibre.com>

Costomize the sleep test

---

build-configs.yaml
lab-configs.yaml
templates/preempt-rt/generic-uboot-tftp-nfs-preempt-rt-template.jinja2
templates/preempt-rt/preempt-rt.jinja2
test-configs.yaml

Add minimal set of build configurations, including PREEMPT_RT=y config for the rt-stable branches.
Also add a test-plan based on LAVA test-definition from Daniel Wagner's fork of LInaro test-definition repo.
NOTE: PR currently based on the kselftest PR #445 due to conflicts in adding test-plan to test-configs and lab-configs.
Things to fix

add build config and test-plan for PREEMPT_RT

---

jenkins/dockerfiles/clang-11/Dockerfile

The next release of clang is due at the end of August (it's scheduled
for the 26th) so get a docker container ready for it.

dockerfiles: Add clang-11 docker container

---

jenkins/dockerfiles/clang-11/Dockerfile

Copy the dependencies for building kselftest from clang-10 into the
clang-11 image.

docker: add kselftest dependencies to clang-11 image

---

build-configs.yaml

Now that it is released add clang-11 coverage for -next, covering the
same set of configs as we do for the current clang-10 builds.  Leave the
clang-10 builds in place since this is the minimum clang version the
kernel currently uses on the basis that coverage of both newest and
oldest releases would be useful, when clang-12 arrives we can replace
clang-11 with it.
Before deploying this the clang-11 docker containers should be rebuilt
to pick up the release.

build-configs: Add clang-11 coverage for -next

---

test-configs.yaml

tinyconfig/allnoconfig does not work at all on d2500cc, block them.

test-configs: d2500cc: block tinyconfig/allnoconfig

---

doc/kci_testsuite.md

Document steps required to add new testsuite to a rootfs image.

kci_docs: How to add new rootfs testsuite and how to add LAVA tests

---

kernelci/build.py

Many of MIPS build have no kernel due to the fact they use vmlinux.
The case which I care are all malta defconfig.
So this patch adds vmlinux as valid kernel for MIPS and add the ability
for seek kernel images in the base output directory.

Handle vmlinux for MIPS build

---

jenkins/debian/debos/scripts/setup-networking.sh

systemd networking appears different on sid and this setup script is
failing.  Add some sanity checks before attempting to start services
that may not be installed on a basic debootstrap'd system.

debos: sid: systemd-networking fixups

---

templates/k8s/job-build.jinja2

Many selftests are looking for header files in kernel directory, so it changes output of build_kernel to kernel dir as default.

update build directory in kubernetes template

---

jenkins/dockerfiles/gcc-8_arm/Dockerfile
jenkins/dockerfiles/gcc-8_arm64/Dockerfile
jenkins/dockerfiles/gcc-8_x86/Dockerfile

include libhugetlbfs and libmnl header files that have not been installed in arm, arm64, x86_64 platforms during build process.

add libhugetlbfs and libmnl headers 

---

test-configs.yaml

This patch adds support for imx8mq-zii-ultra-zest:
LAVA device-type is upstreamed: https://git.lavasoftware.org/lava/lava/-/merge_requests/????

test-configs: Add imx8mq-zii-ultra-zest

---

build-configs.yaml

Enable clang-10 builds on mainline using the same set of architectures
and configs as on linux-next.
Fixes #518

build-configs.yaml: enable clang-10 builds on mainline

---

kci_build

Fix message about command line options install_kernel since --config
has been renamed --build-config.
Fixes: 66a7727ecdf8 kci_build: ("use --build-config instead of --config")

kci_build: fix message in install_kernel

---

kernelci/build.py

Add missing kernel image target definitions for x86_64 and i386.  This
is needed to build only the kernel image, separately from modules or
anything else.
Fixes: 723f653f00e6 ("kernelci.build: add functions to build and publish kernels")

kernelci.build: add missing kernel image targets for x86

---

lab-configs.yaml

The lab will contain upstreamed Kontron products. We are starting with:
* KBox A-230-LS
* SMARC-sAL28 on a SMARC Evaluation Carrier 2.0
Signed-off-by: Michael Walle <michael@walle.cc>

lab-configs: add Kontron's lab

---

test-configs.yaml

Add the definitions for the following two boards:
* KBox A-230-LS
* SMARC-sAL28 on a SMARC Evaluation Carrier 2.0
Signed-off-by: Michael Walle <michael@walle.cc>

test-configs.yaml: add Kontron sl28 boards

---

kernelci/build.py

Use an absolute path based on the current working directory when
setting the value of INSTALL_MOD_PATH to avoid creating a
sub-directory relative to the root of the kernel source tree.
Reported-by: Wang Mingyu <wangmy@cn.fujitsu.com>

kernelci.build: use absolute path for INSTALL_MOD_PATH

---

build-configs.yaml
jenkins/dockerfiles/clang-10/Dockerfile
jenkins/dockerfiles/clang-11/Dockerfile
kernelci/build.py
kernelci/config/build.py

Add the riscv architecture to the list of configs built with clang, with all the core changes needed to be able to support it. This is used with clang-10 on mainline and clang-11 on linux-next.

build-configs.yaml: add riscv to the clang configs

---

lava-v2-callback.py

Update _add_login_case() to look for either `auto-login-action` or the
new name `login-action` which changed in LAVA 2020.03.  This is to fix
bisections for the `login` test case e.g. `baseline.login`.
Also remove a duplicate of the _add_login_case() function which was
likely the result of a merge conflict.
Fixes: 07b9a0ae3c99 ("lava-v2-callback.py: add support for login test case")

lava-v2-callback: fix login test case and remove dead code

---

build-configs.yaml
kernelci/build.py

Add more parameters to the filters used in build-configs.yaml and use it to define a blocklist for riscv on kernels earlier than v4.19.
Fixes: #541

Add more params for build config filters and use it with riscv

---

kernelci/build.py

Drop the make O= option when the output directory is the same as the
kernel source tree.  This should result in the same thing, but with
kernels earlier than 4.9 there appears to be a difference in the
kernel build system causing some builds to fail when usig O= in that
case.
This may be an alternative to #544.

kernelci.build: drop O= option when output is kernel tree

---

templates/k8s/job-build.jinja2

Many selftests are expecting to find headers in kernel directory, so it updates the output to kdir during build.

T24886 - templates/k8s: update kernel build output

---

doc/kci_testsuite.md

Step by step instructions to add simple LAVA test to KernelCI. It's aim
is to give clear starting instructions for the project newcommers.

doc: Add steps to add simple btrfs test LAVA job definition

---

kci_build
kernelci/build.py
kernelci/cli.py

This is a first step to redesign how the builds are run in `kci_build`.  It adds the concept of a build step, with the state between steps being kept in `bmeta.json`.  This defines a number of new `kci_build` commands without affecting how `kci_build build_kernel` currently works, until the new commands can be used instead.
Some changes may then be required with the integration in Jenkins and the Kubernetes build job definitions, but it is not yet required as part of this PR.
In this example, we're going to build the mainline kernel with `gcc-8` for `arm64` with the generic `defconfig` and `KCONFIG_KASAN=y` on top of it using the new commands provided by this PR.
First, let's use a local `kernelci.conf` file to simplify the command line arguments:
```ini
[kci_build]
kdir: linux
build_env: …
```

T23360 Refactor kci_build build_kernel with separate steps

---

kci_build
kernelci/build.py

Add the `kci_build make_kselftest` command to build kselftest as a separate step.
Depends on #554 
To test this locally, first create a `kernelci.conf` file in the current kernelci-core directory (to override any user or system-wide one):
```ini
[kci_build]
kdir: linux
build_env: gcc-8
j: 4
output: linux/build-kselftest
log: build.log
verbose: true
```
Then run these commands to generate the kselftest fragment and build in a Docker container:
```
$ ./kci_build generate_fragments --build-config=next
$ docker run -it -v $PWD:/root/kernelci-core kernelci/build-gcc-8_x86 /bin/bash
```
(the kselftest fragment can also be generated from within the container)

T23360 kci_build make_kselftest

---

kernelci/build.py

Generate config fragments included in a subset architectures as well
as full build variants.

kernelci.build: generate arch fragments

---

build-configs.yaml

Add an `x86-chromebook` config fragment to enable the serial console on most x86 Chromebooks (AMD and Intel), as well as the USB-Ethernet adapter found in the [Servo v4](https://chromium.googlesource.com/chromiumos/third_party/hdctools/+/master/docs/servo_v4.md#Type_C-Version) debug boards.

T22500 x86 chromebook fragment

---

test-configs.yaml

Add x86-chromebook fragment and hp-11A-G6-EE-grunt device type which uses it.
This is pending Depthchage changes to be merged upstream for loading a ramdisk over TFTP on x86 platforms, and the device type to be added to LAVA upstream.
LAVA prerequisite changes for x86 Depthcharge: https://git.lavasoftware.org/lava/lava/-/merge_requests/1283
LAVA device type: https://git.lavasoftware.org/lava/lava/-/merge_requests/1395
Depends on #560 and #561 to be merged first.

T22500 grunt

---

kci_test
kernelci/__init__.py
test-configs.yaml

Add checks to `kci_test validate` to detect when device types are not in alphabetical order.  Fixed any issues so the checks pass.

T24749 Add checks for alphabetical order of device types

---

build-configs.yaml
kci_build

Add checks for alphabetical order of trees, fragments and build configs in `build-configs.yaml`.  Also fix a few alphabetical issues found.
Depends on #530.

T24749 build config sort check

---

templates/baseline/baseline.jinja2

Sometimes the output is interrupted by the kernel messages, for example:
https://lavalab.kontron.com/scheduler/job/1174#L1000
Use /dev/kmsg to mitigate that; as it is already used in the bootrr test
case.
Signed-off-by: Michael Walle <michael@walle.cc>

baseline: use kmsg for test shell messages

---

kci_rootfs
rootfs-configs.yaml

Add checks for sorting configuration in `rootfs-configs.yaml` alphabetically and fix issues.

T24749 kci rootfs alpha

---

kci_build
kernelci/build.py
kernelci/cli.py

Implement the "install" method for each build step.
This introduces the `--install` option when running any `kci_build make_*` command, to also install the binary files in the `_install_` directory.
Depends on #574. 
* The `make modules_install` command is now only called if the `--install` option is enabled, rather than implicitly at the end of the modules build.
* Each install "action" will be added to the `steps.json` file as a separate entry, e.g. `modules install`.
* Each step now has a default separate log file with the step name, e.g. `modules.log` and it will be overwritten if the modules are built again.
The same applies to each step: `config`, `kernel`, `modules`, `dtbs`, `kselftest`.  The `--log` option can be used to manually override this behaviour, in which case the log file …

T25311 kernel build install

---

templates/kselftest/kselftest.jinja2

includes job template parameters to specify kselftest collections and tests to run.

templates: add kselftest subset parameters

---

templates/boot/generic-qemu-boot-template.jinja2

Hello,
Here is a pull-request to add the possibility to set the console used by QEMU
using 'params' keyword in test-configs.yaml.
The default console will be the value of 'console_dev' entry, as done previously.
Thanks to that, if the emulated device has a different console than the one defined in the top of the file, it is possible to modify it using this `params: console:` entry.
Let me know what you think about it.
Best regards,
Mylène

templates: boot: generic-qemu: Add console params

---

build-configs.yaml

The arc architecture is not actually supported by clang, this was most
likely enabled by mistake.  Drop them for now until the architecture
can at least get built in theory so that KernelCI results become
useful.

build-configs.yaml: disable arc builds with clang

---

.github/workflows/main.yml

The standalone Python scripts have moved from the root directory to
scripts, so update the pycodestyle check accordingly.

workflows: update path to scripts for pycodestyle

---

config/core/build-configs.yaml

Add the "tip" tree and monitor the "master" branch as it is an
integration branch with all the changes going into tip.

build-configs.yaml: add tip/master branch

---

config/lava/sleep/sleep.sh

Move the check for the presence of the rtc0 device outside of the main
loop, and add a check for wakeup enabled.  Abort if any of these
checks fail before starting the main loop to keep the script easier to
maintain.
Depends on #586

T24646 sleep: add wakeup check and abort if checks fail

---

config/core/build-configs.yaml

Add peterz "queue" tree with the "kernelci" branch using the minimal
set of build variants.

build-configs.yaml: add peterz queue/kernelci branch

---

jenkins/debian/debos/scripts/buster-ltp.sh

Make sure to configure open-posix-testsuite and build.
This helps to run timers testcases.

rootfs-configs.yaml: Update buster-ltp rootfs

---

kci_test
kernelci/lab/__init__.py
kernelci/lab/lava.py

Pass a DeviceType configuration object to Lab.device_type_online() and
let the implementation of the method decide how to look up the status
of the device type.  This is because the base name is used with LAVA
labs, so using DeviceType.name doesn't work.  Other types of lab may
need the specific name instead, and in any case this is not something
the API users should have to deal with.
This fixes issues with submitting jobs to qemu and r8a77960-ulcb
devices in particular.
Fixes: 9ba487d2f861 ("kernelci.lab.lava: fix and simplify logic to handle LAVA aliases")

T25987 kernelci.lab: pass DeviceType object to .device_type_online()

---

config/k8s/job-build.jinja2

Currently, we build everything in a memory-backed tmpfs using a volume
with the properties:
emptyDir: { medium: "Memory" }
However, k8s limits the max size of tmpfs volumes to 50% of the memory
of the node.  The smallest nodes we use have 16G of memory, leading to
a max size tmpfs of 8Gb.
Some kernel builds (notably arm64 defconfig using CONFIG_DEBUG_INFO=y)
can have build artifacts that, combined with the kernel source, exceed
this limit.
To workaround that, don't build the kernel in tmpfs, instead just use
the default storage, backed by whatever storage is configured for the
cluster (typically an SSD disk.)

k8s: build kernels using normal storage

---

kernelci/lab/lava.py

Fix the LAVA.device_type_online() logic by looking for the status
value rather than if the device type is merely listed in the status
dictionary.  Also rename the status dictionary to online_status to
make it clearer that it's not a list of online device types.
Fixes: 9ba487d2f861 ("kernelci.lab.lava: fix and simplify logic to handle LAVA aliases")

kernelci.lab.lava: fix .device_type_online() logic

---

config/core/test-configs.yaml

This patch adds support for stm32mp157c-lxa-mc1
LAVA device-type is upstreamed: https://git.lavasoftware.org/lava/lava/-/merge_requests/1438

test-configs: Add stm32mp157c-lxa-mc1

---

config/core/lab-configs.yaml

Depends on #558 to be merged first.
This fixes the "baseline" test plan filters in `lab-configs.yaml`.

T24799 docker qemu fixup

---

config/core/test-configs.yaml

Remove ltp-mm job from Collabora device bcm2836-rpi-2-b-cbg-0

test-configs.yaml: Remove ltp-mm from a Collabora lab device

---

kci_build
kernelci/build.py

Add extra optional arguments to `RevisionData.run()` for when building a kernel source tree that is not a Git repository (e.g. a extracted from a source tarball).

T25311 bmeta fixup

---

kci_build
kernelci/build.py
kernelci/storage.py

Refactor the `kci_build push_kernel` implementation to use the new meta-data based on `kenrelci.build.Step`.
Note: Other changes for `kci_build publish_kernel` and in `kernelci-backend` are required before this can be enabled on staging, hence the `staging-skip` tag.

T25311 push kernel

---

config/core/db-configs.yaml
kci_data
kernelci/data/__init__.py
kernelci/data/kernelci_backend.py

Update implementation to submit the kernel build meta-data to the backend:
* move the "publish_kernel" from kci_build to kci_data since it's sent via the Database abstract interface.
* use the MetaStep class to load the build meta-data and pass it to the Database.submit_build() method
* generalise the Database.submit() method by including the "path" for the data in the payload (e.g. "test", "build"...)
This is still a work in progress as ideally it should be possible to just use the Database.submit() method.  Things may be simplified when all the components have been updated with the new meta-data format.
Depends on #612.

T25311 publish kernel

---

kernelci/build.py
kernelci/data/kernelci_backend.py

Rework how `artifacts.json` is created so it can be consumed by the backend.  Also send all the meta-data directly to the backend when publishing a new kernel build.
Depends on #614 and https://github.com/kernelci/kernelci-backend/pull/281

T25311 artifacts

---

config/core/test-configs.yaml

Update all the Debian rootfs URLs including buster-ltp as the builds
are now completing for all 3 architectures.

test-configs.yaml: update Debian rootfs URLs

---

config/core/test-configs.yaml

To prevent longer queue and job wait time remove ltp-mm from
odroid-xu3 and beaglebone-black devices.
Signed-off-by: lakshmipathi <lakshmipathi.ganapathi@collabora.com>

test-configs.yaml: Remove ltp-mm from odroid-xu3 and beaglebone-black

---

config/k8s/gen.py
config/k8s/job-build.jinja2

Update the job-build.jinja2 Kubernetes template with the new kci_build
commands to build kernels in separate steps.  Generate a local config
file to simplify command line arguments and keep the API token secret
when sending data to the backend.

config/k8s/job-build.jinja2: update with new kci_build commands

---

kernelci/build.py

Fix a mistake in the call to add the build step meta-data which
resulted in the wrong status to be saved.
Fixes: fa346b304840 ("kernelci.build: use Step.name in meta-data")

kernelci.build: fix MakeSelftests build result

---

kernelci/cli.py

Handle the case where the requested option is not associated with the
command in Options.get().
This doesn't normally happen as the code using Options normally only
looks for options that were defined, but it may happen in some corner
cases when such things can't be determined.  Also, if it does happen
for any reason, it should return None rather than fail with an
exception.
Fixes: df17ad416551 ("kernelci.cli: add Options class to use a settings file")

kernelci.cli: handle case where option is not defined

---

config/core/lab-configs.yaml
config/core/test-configs.yaml

Add ltp-open-posix timers test definition. Enable ltp-open-posix timers
on lab-collabora devices where tests are passed.
Dependencies:

test-configs.yaml: Add and enable LTP-open-posix-timers on devices 

---

jenkins/dockerfiles/clang-12/Dockerfile

clang-12 is due for release any day now so let's add clang-12 containers
so we can use them to enable build testing with it.

docker: Add clang-12 containers

---

kernelci/build.py

Add User-Agent to HTTP requests.
This was requested by kernel.org sysadmins for experiments with
fetching kernel tar archives from kernel.org.

build.py: add HTTP user-agent

---

config/core/db-configs.yaml
config/k8s/gen.py
config/k8s/job-build.jinja2
kci_build
kci_data
kci_test
kernelci/build.py
kernelci/cli.py
kernelci/data/__init__.py
kernelci/data/kernelci_backend.py
kernelci/storage.py
kernelci/test.py

Full integration of the new build meta-data with k8s builds and generated LAVA jobs.
Should be merged at the same time as the following PRs:

Use new build meta-data

---

doc/kci_build.md

Update the example on the kci_build documentation page with the new
separate build steps and fix some inaccuracies and formatting in the
other parts of the page.

doc/kci_build: update with build steps and fix loose ends

---

config/core/build-configs.yaml

Add stable/stable-rc/stable-queue trees up to 5.20.
Signed-off-by: Sasha Levin <sashal@kernel.org>

build-configs.yaml: more stable trees

---

config/core/build-configs.yaml

This reverts commit 45778bc423e485b88e743976d88b406057af4bfe.
Now that kci_build has a separate make_kselftest command, we can
enable the kselftest fragment again in production.

build-configs.yaml: enable kselftest builds again

---

kernelci/build.py

Add default uImage.gz make target for MIPS otherwise some builds may
not produce any usable kernel image, depending on the defconfig.

T27948 kernelci.build: add default make target for MIPS

---

kernelci/test.py

Fix the logic around matching test configs using the list of dtbs, to
not match if the device type requires a dtb but there were no dtbs in
the build.
Fixes: e4919f1e743e ("kernelci.test, kci_test: use Metadata class")

T29745 kernelci.test: fix logic around dtbs handling

---

config/k8s/job-build.jinja2

Add a KCI_DB_CONFIG parameter to the Kubernetes job-build.jinja2
template to be able to specify the --db-config option to pass to
kci_data rather than having a hard-coded staging.kernelci.org.
Depends on https://github.com/kernelci/kernelci-jenkins/pull/54

T27947 config/k8s: add KCI_DB_CONFIG

---

config/core/test-configs.yaml

To reduce the load on specific devices we dropped
specific ltp testruns from few devices.
From now on, beaglebone-black runs only ltp-ipc.
rk3288-rock2-square runs only ltp-mm and
bcm2836-rpi-2-b runs only ltp-crypto. veyron-jaq
runs only ltp-timers.
Signed-off-by: lakshmipathi ganapathi <lakshmipathi.ganapathi@collabora.com>

core/test-configs.yaml: Drop few LTP jobs

---

kernelci/__init__.py
kernelci/build.py
setup.py

Add `kernelci.__version__` with the kernelci package version string
'1.1'.  Import it where the version is required in place of hard-coded
strings (setup.py, build.py).

kernelci: add __version__ with package version string

---

config/core/lab-configs.yaml

Se the LAVA priority to 45/100 in lab-collabora to better manage how
the resources are being shared with other projects which are running
at "medium" priority (50/100).

lab-configs.yaml: run in lab-collabora with priority 45/100

---

config/core/rootfs-configs.yaml

Include instructions to create a rootfs buster-kselftest to satisfy run time dependencies from kselftest.

rootfs-configs.yaml: add buster-kselftest

---

kci_build
kci_data
kci_rootfs
kci_test
kernelci/config/__init__.py

Drop the verbose option when loading the YAML config files as this
interferes with the output and generates more noise than useful
information.

kernelci.config: drop verbose when loading YAML config

---

config/core/db-configs.yaml

Add the chromeos.kernelci.org backend config entry to db-configs.yaml.

T27643 db-configs.yaml: add chromeos.kernelci.org

---

config/core/test-configs.yaml

It updates the test configurations to make kselftest test plan use the new buster-kselftest rootfs image.

test-configs.yaml: update kseltest test plan to use new rootfs

---

config/core/test-configs.yaml

Drop ltp-ipc until we add more devices in the lab, it has just one odroid-xu3 and queue is getting longer.

test-configs.yaml: remove ltp-ipc from odroid-xu3

---

config/core/build-configs.yaml

Add Mike Rapoport's tree and enable the for-kernelci branch with a
medium subset of builds.  Define the medium_variants anchor to
simplify syntax and reuse it where appropriate (lee_android_3.18).

build-configs.yaml: add rppt tree and define medium_variants

---

config/core/test-configs.yaml

The hip07-d05 platform takes a long time to boot with experimental
firmware and is therefore not able to cope with the test load being
scheduled, with a single instance available.  Keep only one collection
for kselftest and LTP as a simple measure to contain the queue length.

test-configs.yaml: reduce test plans on hip07-d05

---

config/core/test-configs.yaml

Add the `asus-C523NA-A20057-coral` Intel Chromebook device type.

T25488 coral

---

config/core/test-configs.yaml

Drop usb tests from r8a7796-m3ulcb until we can run usb tests only for mainline and linux-next.

test-configs.yaml: remove usb from r8a7796-m3ulcb

---

config/core/test-configs.yaml

Correct the link to debian buster kselftest ramdisk.

test-configs.yaml: fix typo in initrd link

---

config/core/test-configs.yaml
kernelci/test.py

Reduce the number of tests run on `imx6q-sabrelite` boards in Collabora's lab until more hardware becomes available.

Reduce sabrelite tests

---

config/core/build-configs.yaml
config/core/test-configs.yaml

Enable kselftest on x86 Intel Chromebook devices.
Also enable LTP on x86 AMD Chromebook `grunt`.
Depends on:

T25488 kselftest x86 chromebook

---

config/core/build-configs.yaml

The linux-amlogic tree has moved due to a switch to group
maintainership.  Update with the new repo URL.

build-configs: update amlogic repo

---

doc/kci_rootfs.md

In commit 5b583dced4ed ("config/rootfs/debos: move all debos files to new
directory") the directory 'jenkins/debian' was moved to 'config/rootfs'.
The documentation for the kci_rootfs, written before that commit, still
has references to the old directory structure. It's nice have the
documentation up-to-date with current directory structure, so update
that file and replace the old directory with the new one.
This makes the life a bit easier when you're following instructions and
do silly copy and pastes.

Rename references from 'jenkins/debos' to 'config/roots'

---

config/core/build-configs.yaml

Add kernel config options to be able to enable the eMMC on x86
Chromebook devices.  Tested on Grunt AMD platform.

build-configs.yaml: add eMMC configs to x86-chromebook

---

config/core/test-configs.yaml
config/lava/boot/generic-qemu-boot-template.jinja2

This patch adds suppport for RISCV qemu virt machine.
The device type is LAVA upstreamed:
https://git.lavasoftware.org/lava/lava/-/merge_requests/1255
But probably only my personal lab (LAVA patched with RISCV patch and recent qemu with riscV support installed) could ran it.
So I have set a flags qemu-riscv64 since qemu docker images are not yet ready.

test-configs: add support for qemu RISCV

---

config/core/test-configs.yaml

Define the debian-staging base rootfs type as a convenience to be able
to easily test new rootfs images on staging.kernelci.org.  It's normal
that this rootfs type is not used anywhere in the file on the main
branch since staging uses open pull requests to test changes.

test-configs.yaml: define debian-staging rootfs type

---

config/core/build-configs.yaml
config/docker/clang-13/Dockerfile
kernelci/build.py

ChromeOS maintain its own defconfigs as splitconfig files in its
repository.
Create a helper that is capable of fetching that configuration and
convert it into a standard oldconfig.
Fixes: #712
Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>

kernelci: Add support for cros defconfigs

---

config/core/build-configs.yaml
config/docker/clang-13/Dockerfile

ChromeOS uses clang-13, so lets make a docker image with that clang
version.
Fixes #714
Signed-off-by: Ricardo Ribalda <ricardo@ribalda.com>

config/docker: Add clang-13 configuration

---

config/core/rootfs-configs.yaml
config/rootfs/debos/overlays/libcamera/usr/bin/lc-compliance-parser.sh
config/rootfs/debos/scripts/buster-libcamera.sh

Add a rootfs and accompanying build script that contains libcamera and
its test suite: lc-compliance.
Running lc-compliance will be useful to test for regressions in the
media subsystem.

Add lc-compliance rootfs

---

config/k8s/gen.py
kernelci/build.py

Add the colon`:` to the list of characters to replace with dashes in the Kubernetes job names.
Also replace more than just slash `/` characters in the upload file path to avoid issues and keep it readable.
Depends on #729

Replace characters introduced by cros://

---

config/core/test-configs.yaml

Add "seccomp" and "lkdtm" kselftests to the default test configs, since they both have architectural variations.

test-configs.yaml: Add seccomp and lkdtm kselftest collections

---

config/core/test-configs.yaml

The minnowboard device type is congested as Apertis job, so running igt and kselftest is not possible, so it should be dropped.

test-configs.yaml: remove kselftest and igt from minnowboard

---

config/core/lab-configs.yaml
config/core/rootfs-configs.yaml
config/core/test-configs.yaml

Enable the newly added kselftest collections lkdtm and seccomp on x86 devices.
Depends on #735 and #737

Extend kselftest coverage

---

config/core/test-configs.yaml

I have an i945gsex-qs mother board in my lab.
It is an industrial mother board with an i386 N270 Atom.

test-configs: add i945gsex-qs

---

config/core/test-configs.yaml

Enable all the currently defined kselftest plans on mt8173-elm-hana as
nfsroot support with kselftest kernel builds is being fixed for this
platform in lab-collabora.

test-configs.yaml: enable all kselftest plans on mt8173-elm-hana

---

config/core/rootfs-configs.yaml
config/core/test-configs.yaml
config/rootfs/debos/overlays/nosuspend/etc/systemd/sleep.conf.d/nosuspend.conf
config/rootfs/debos/rootfs.yaml

Add "nosuspend" overlay for Debian Buster rootfs images to disable
suspend in systemd.  This is to work around spurious suspend requests
on Chromebook devices in particular.  Remove this file in the ramdisk
image as it's only an issue with nfsroot.
On a side note, the "sleep" and "usb" test plans use rtcwake which
bypasses systemd so this should not have any effect anyway.

config/rootfs/debos: add nosuspend overlay

---

config/rootfs/debos/scripts/buster-libcamera.sh

The refactor patch series of lc-compliance using Googletest has been
merged upstream [1]. That series changes the test output format and was
required for the lc-compliance tests. Now that it has been merged,
update the libcamera repository URL to point to upstream.
[1] https://git.linuxtv.org/libcamera.git/commit/?id=143b252462b9b795a1286a30349348642fcb87f5

rootfs: libcamera: Update repository URL to point to upstream

---

config/core/lab-configs.yaml

Add lab-collabora-staging which is a Collabora LAVA lab used for testing new device types and changes made in LAVA itself.  It is not a production lab and should only be used with staging.kernelci.org and potentially chromeos.kernelci.org.

lab-configs.yaml: add lab-collabora-staging

---

config/core/test-configs.yaml

Add the minnowboard-max-E3825 device type, which is now discontinued
and only present in lab-collabora-staging for the time being.

test-configs.yaml: add minnowboard-max-E3825

---

config/core/lab-configs.yaml

Drop the passlist plan filter for lab-collabora to enable all test
plans except those on the blocklist (baseline-qemu-docker).

lab-configs.yaml: drop plan filter for lab-collabora

---

config/core/test-configs.yaml

Enable all the LTP subsets currently defined on the mt8173-elm-hana
arm64 Chromebook.

test-configs.yaml: enable all current LTP subsets on hana

---

config/core/test-configs.yaml

Enable the ltp-timers test plan on rk3399-gru-kevin.

test-configs.yaml: enable ltp-timers on kevin Chromebook

---

config/core/build-configs.yaml
config/core/test-configs.yaml

Added a 'ltp-ima' fragment and a 'ltp-ima' test plan.
The test-definition part seems work fine with the latest LTP version by passing 'ima' to tst_cmdfiles.
Don't know if it's the correct way to use 'filters/passlist' in the test_plan to force it using a kernel with ltp-ima fragment.

Add ltp-ima test plan (#710)

---

config/docker/build-and-push.sh
config/docker/buildroot/Dockerfile

Add Dockerfile that creates an image that contains all dependencies and
tools needed to build buildroot based rootfs images.
This docker image is to be used by Jenkins instead of a dedicated machine/node for buildroot builds.

Add buildroot Dockerfile

---

config/core/build-configs.yaml

Almost all of the ltp-crypto tests are being skipped since the required
kernel config option for crypto algorithms are not enabled.
Hence add ltp_crypto fragment in build-configs.yaml file which would
enable the config options.
Signed-off-by: Shreeya Patel <shreeya.patel@collabora.com>

build-configs: Add ltp-crypto fragment

---

config/core/test-configs.yaml

Enable a few missing LTP subsets on asus-C523NA-A20057-coral to cover
all the ones currently defined.

test-configs.yaml: enable all current LTP subsets on coral

---

config/core/build-configs.yaml
config/core/test-configs.yaml

Rename the ltp-ima kernel config fragment to ima to make it more
generic.  Update filters in test-configs.yaml accordingly.
Fixes: 2a8fe33f4349 ("test-configs.yaml: Add ltp-ima test case")

build-configs.yaml: rename ltp-ima fragment to ima

---

config/core/test-configs.yaml

As this platform doesn't have enough capacity available in any lab,
drop baseline-nfs to reduce the coverage to the bare minimal with only
baseline.

test-configs.yaml: only run baseline on minnowboard-turbot

---

config/core/test-configs.yaml

Add a filter in test-configs to only run the ltp-crypto test plan with
kernel builds that have the crypto fragment enabled.

test-configs.yaml: add ltp-crypto filters for crypto fragment

---

config/core/test-configs.yaml

Drop LTP test plans on devices that are now mostly offline (jeton-tk1,
hip07-d05) and reduce the number run on rk3399-gru-kevin to match the
documentation in https://kernelci.org/docs/tests/.

test-configs.yaml: adjust LTP coverage to match documentation

---

config/core/test-configs.yaml

Add definition for the asus-C433TA-AJ0005-rammus Chromebook device and
enable baseline/baseline-nfs test plans to run on it.
Signed-off-by: lakshmipathi.ganapathi <lakshmipathi.ganapathi@collabora.com>

test-configs.yaml: Add asus-C433TA-AJ0005-rammus Chromebook

---

config/core/test-configs.yaml

Enable acer-mt8183-cp311-3h-jacuzzi device type in kernelCI and include baseline and kselftest test plans to it.

test-configs.yaml: enable jacuzzi in kernelCI

---

config/rootfs/debos/scripts/buster-ltp.sh

Update LTP openposix-testsuite path on buster-ltp rootfs.
Signed-off-by: lakshmipathi.ganapathi <lakshmipathi.ganapathi@collabora.com>

buster-ltp: Fix openposix testsuite path

---

kci_bisect
kernelci/bisect.py
kernelci/cli.py

Add a new kci_bisect tool to start implementing the bisection steps
currently found in push-bisection-results.py, lava-v2-callback.py and
bisect.jpl.  Start with the get_recipients command to provide the list
of recipients to add as To: and Cc: in email reports, for a given git
commit found by a bisection.
This is particularly useful when triaging email reports which
currently aren't sent to the public automatically, to populate the
list of recipients for valid ones.

kci_bisect: start adding new tool to run bisection commands

---

config/core/build-configs.yaml

As CONFIG_DRM_FBDEV_EMULATION now doesn't enable CONFIG_FD as per
f611b1e7624c ("drm: Avoid circular dependencies for CONFIG_FB"),
enable it in the virtualvideo fragment used by KernelCI.  This fixes
the issue where the vivid driver is not built and the
v4l2-compliance-vivid.device-presence test case fails.

build-configs.yaml: enable CONFIG_FB in virtualvideo fragment

---

config/lava/cros-ec/cros-ec.jinja2

Sometimes the output is interrupted by the kernel messages, for example:
https://lava.collabora.co.uk/scheduler/job/4265012#L2561
Use /dev/kmsg to mitigate that; as it is already used in other test
cases.

cros-ec: use kmsg for test shell messages

---

config/core/test-configs.yaml

Update all the Debian Buster rootfs URLs with images built today in production, ahead of the update on Monday.

test-configs.yaml: update Debian Buster rootfs URLs

---

config/core/test-configs.yaml

Enable asus-C436FA-Flip-hatch device type and
include baseline, baseline-nfs, kselftest and
ltp test plans.

test-configs.yaml: enable hatch in kernelCI

---

kci_rootfs

Add a default value for the --data-path argument based on the rootfs
type.

kci_rootfs: add default value for --data-path

---

doc/_index.md
doc/config/_index.md
doc/config/build-configs.md
doc/config/filters.md
doc/config/test-configs.md
doc/kci_build.md
doc/kci_data.md
doc/kci_rootfs.md
doc/kci_test.md
doc/settings.md

Add Hugo "weight" attributes to each documentation page to sort them
in the index.  Also clean up minor things in the settings.md file.

doc: add weight attributes

---

config/docker/clang-13/Dockerfile

llvm-toolchain-buster leads now to clang-14 hence path to clang-13
packages needed an update.

Update clang-13 repository

---

config/core/rootfs-configs.yaml
kci_rootfs
kernelci/cli.py
kernelci/config/rootfs.py
kernelci/rootfs.py

- rootfs-configs.yaml: Add buildroot-basline rootfs definition
Add buildroot baseline rootfilesystem. Itroduced new buildroot rootfs_type.
- kci_rootfs: Add validation for buildroot rootfs type
Refactor kci_rootfs validate code. Add functions that validate buildroot
and debos rootfs configs. Move validation implementation from kci_rootfs to kernelci.rootfs.
- kci_rootfs: Add rootfs_type filter to kci_rootfs list_variants
Add --rootfs-type option to kci_rootfs list_variants. When option is
specified listed variants are limited to a rootfs type specified.
- kci_rootfs: Add rootfs_type filter to list_configs
--rootfs-type option has been added to kci_rootfs list_configs. When
specified only rootfs configs of a specific type will be listed.
Currently supported vlues are: debos and buildroot. …

Add kci_rootfs support for buildroot based rootfs images

---

config/core/build-configs.yaml

Add coverage of 16K pages on arm64 in -next since while it's available on
a number of systems it is not widely covered by test systems so can turn
up issues from time to time.

build-configs: Enable builds of 16K pages on arm64

---

config/core/build-configs.yaml

This is a simplification of PR 728 [1] to remove values enabled
by default (via make savedefconfig) and adds a few more configs
to enable EC tests which are independent of ChromeOS (eg can work
on Debian).
Manually tested on Eve (Adrian) and Coral (Sonny).
Ran cros-ec-tests on KernelCI Octopus and Coral boards [2] [3]
where test passes went from 0 to 4-7 depending on the board.
[1] #728
[2] https://lava.collabora.co.uk/scheduler/job/4249724#results_158406973
[3] https://lava.collabora.co.uk/scheduler/job/4249260#results_158391223
Signed-off-by: Sonny Rao <sonnyrao@chromium.org>
Fixes: #728

Extend x86_64_defconfig to support more drivers

---

setup.py

setup.py: install kernelci.data package

---

config/core/build-configs.yaml

Add the x86-chromebook fragment to cros x86_64 configs as this is required for LAVA automation (serial console, USB-Eth adapters...).
Depends on #729

x86 chromebook fragment

---

config/core/db-configs.yaml
config/core/test-configs.yaml
kci_build
kci_data
kci_test
kernelci/config/__init__.py

Validate each YAML file individually as top-level entries can now be merged from various separate files.  When this happens, the entries are put together in the order they appear in separate files, so the alphabetical check is irrelevant.

Validate YAML files individually

---

config/docker/build-and-push.sh
config/docker/build-k8s/Dockerfile
config/docker/clang-10/Dockerfile
config/docker/clang-11/Dockerfile
config/docker/clang-12/Dockerfile
config/docker/clang-13/Dockerfile
config/docker/dt-validation/Dockerfile
config/docker/gcc-8_arc/Dockerfile
config/docker/gcc-8_arm/Dockerfile
config/docker/gcc-8_arm64/Dockerfile
config/docker/gcc-8_mips/Dockerfile
config/docker/gcc-8_riscv64/Dockerfile
config/docker/gcc-8_x86/Dockerfile

It's required to automate containers creation for
$ ./build-and-push.sh -t kernelci/staging- ...

config/docker: respect prefix in Dockerfiles

---

config/core/test-configs.yaml

Disable all kselftest on mt8183-kukui-jacuzzi-juniper-sku16 as the
hack to set a custom ip=::: kernel command line argument is breaking
other use-cases on this device type in Collabora's LAVA lab.  This is
a temporary measure until the issue is fixed properly in the LAVA
device type templates or elsewhere.

test-configs.yaml: disable kselftest on mt8183-kukui-jacuzzi

---

doc/kci_rootfs.md

Staging images are not as stable and can break more often
so it's best to point instructions to non-staging images.

doc: kci_rootfs: point docker to non-staging images

---

config/core/build-configs-stable.yaml
config/core/build-configs.yaml

Now that the Docker images are being upgraded from Debian Buster to
Bullseye, the standard GCC version needs to change from gcc-8 to
gcc-9.
Depends on #807

build-configs.yaml: upgrade from gcc-8 to gcc-9

---

config/lava/base/kernel-ci-base.jinja2

Add "earlycon" to the default kernel command line as it should just
work on platforms with stdout-path set in their device tree.
Suggested-by: Rob Herring <robh@kernel.org>

config/lava: add earlycon to kernel command line

---

config/docker/dt-validation/Dockerfile

Update the dt-validation Dockerfile for Debian Bullseye, with GCC 10
and new package names (python3-yaml).

config/docker: update dt-validation for Debian Bullseye

---

config/docker/debos/Dockerfile
config/rootfs/debos/scripts/crush.sh

Upgrade the debos Docker image to Bullseye and work around an issue with `dpkg -l` in `crush.sh`.

Upgrade debos Docker image to Bullseye

---

config/rootfs/debos/scripts/buster-libcamera.sh

/tmp has a lower size limit by default, which was causing out-of-memory
issues when building libcamera inside of it. Move the build out of the
/tmp directory to avoid this.

rootfs: libcamera: Move build out of /tmp to avoid out-of-memory issues

---

config/core/rootfs-configs.yaml
config/rootfs/debos/rootfs.yaml
config/rootfs/debos/scripts/install-firmware.sh
doc/kci_rootfs.md
kernelci/config/rootfs.py
kernelci/rootfs.py

The first commit adds the mechanism then the second commit adds some example firmware required for `mt8173-elm-hana-next-2021-05-27` and `asus-C433TA-AJ0005-rammus`.
Fixes: #698

Add cmd to install firmware in rootfs

---

config/core/test-configs.yaml

Update Debian rootfs URLs except for buster-ltp and buster-v4l2 as the
builds failed.

test-configs.yaml: update rootfs URLs

---

config/core/rootfs-configs.yaml

Some of the ltp-mm tests require this package to fully run:
19:35:37.330653  tst_test.c:870: CONF: test requires libnuma >= 2 and it's development packages
...
19:38:09.697595  vma02       1  TCONF  :  vma02.c:169: test requires libnuma >= 2 and it's development packages
Signed-off-by: Gustavo Padovan <gustavo.padovan@collabora.com>

rootfs-configs.yaml: add libnuma-dev package to buster-ltp

---

config/core/rootfs-configs.yaml
config/rootfs/debos/scripts/buster-ltp.sh

This PR includes patch by @padovan from kernelci/kernelci-core#706 to enable following ltp-mm test cases:
- oom03
- oom04
- oom05
- vma02
- vma04

Add libnuma-dev package to enable additional ltp-mm test cases

---

config/core/build-configs-android.yaml
config/core/build-configs.yaml

Move all the Android build configs to `build-configs-android.yaml` and drop deprecated branches as requested by Todd:
https://groups.io/g/kernelci/topic/please_drop_deprecated/86747569

Update Android configurations - 2021-11-01

---

config/docker/build-base/Dockerfile
config/docker/k8s/Dockerfile

Set the MAINTAINER attribute to kernelci-tsc@groups.io in all the
Dockerfiles instead of individuals.  This is so that the Technical
Steering Committee of the project becomes the owner of such things to
ensure continuity.

config/docker: set MAINTAINER to kernelci-tsc@groups.io

---

config/rootfs/debos/rootfs.yaml

Tested locally, now the rootfs.ext4 image is without errors.

Fixes rootfs undefined behaviour from issue #863

---

config/core/lab-configs.yaml
kernelci/config/lab.py
kernelci/lab/__init__.py
kernelci/lab/lava/__init__.py
kernelci/lab/lava/lava_rest.py
kernelci/lab/lava/lava_xmlrpc.py

- Extract common parts from the LAVA API implementation.
- Create kernelci.lab.lava package
- Move XMLRPC based communication to lab.lava.lava_xmlrpc.
The redesign is a preparation for another implementing other means of  communication with LAVA labs.
- Add lava.lava_rest lab type
- Add hadnling LAVA jobs with LAVA REST API v0.2

T31087 lava rest support

---

config/core/lab-configs.yaml
kernelci/lab/lava/lava_xmlrpc.py

Make sure we have trailing slashes in XMLRPC API URLs so all labs accept API calls.

Add trailing slash for XMLRPC API URLs

---

config/core/build-configs-stable.yaml

Drop old stable branches that aren't LTS and have already reached
end-of-life: 5.6, 5.7, 5.8, 5.11, 5.12, 5.13.

build-configs-stable.yaml: drop linux-5.{6,7,8,11,12,13}.y

---

kernelci/data/__init__.py

Add the missing verbose argument to Database._print_http_error().
Fixes: 0618a1a3de47 ("kernelci.data: add Database._print_http_error()")

kernelci.data: add missing verbose argument to _print_http_error()

---

config/core/test-configs.yaml

Update all the Debian rootfs URLs to 20211118.0 except buster-ltp and
buster-libcamera which had some build failures on arm64.

test-configs.yaml: update Debian URLs

---

config/core/build-configs-stable.yaml
config/core/build-configs.yaml

Enable kselftest on stable kernels based on linux-5.14.y as it should be working well enough.  Future stable branches may be enabled if this appears to be producing valid results.
Also move the stable trees definitions to the stable builds config file to keep it more self-contained.

Enable kselftest on stable 5.14

---

kernelci/config/build.py
kernelci/config/data.py
kernelci/config/lab.py
kernelci/config/rootfs.py
kernelci/config/test.py

Add empty dictionaries by default when loading all the YAML
configurations as some command line tools may be run without all the
types of configurations defined.  This won't cause any side-effects as
it's the same as when trying to access a YAML configuration that
doesn't exist, so error handling for that is the same too.

kernelci.config: make all YAML config optional

---

config/core/rootfs-configs.yaml

mips big-endian architecture is not supported in bullseye as per this
announcement: https://lists.debian.org/debian-devel-announce/2021/01/msg00002.html
'it is probably time to drop this architecture from bullseye and sid'

rootfs-config: Remove mips architecture from bullseye config

---

config/core/test-configs.yaml

mips big-endian architecture is not supported in bullseye, so drop
ar9331-dpt-module device.
Below debian mailing list announcement:
https://lists.debian.org/debian-devel-announce/2021/01/msg00002.html
said "it is probably time to drop this architecture from bullseye and sid.
(i.e. the same we had for buster minus mips)"

Drop: ar9331-dpt-module device

---

config/core/rootfs-configs.yaml
config/core/test-configs.yaml

Replace the plain Debian Buster rootfs images with Bullseye.

Debian Bullseye 20211118.0

---

config/core/rootfs-configs.yaml

Add firmware used by the amdgpu driver in the bullseye-igt rootfs. This
will allow amdgpu igt tests to be run later.
Fixes #853. Since the `bullseye-igt` rootfs has been added in the meantime, I added the firmware to that rootfs instead of the `buster-igt` originally mentioned in the issue. 

rootfs-configs.yaml: bullseye-igt: Add firmware for amdgpu

---

config/rootfs/debos/overlays/igt/usr/bin/igt-parser.sh

The amdgpu igt binaries are installed in a subdirectory of the usual
path where other igt binaries are installed. Add this subdirectory to
the PATH variable as well so we can execute the amdgpu igt tests.

igt-parser.sh: Add amdgpu binaries directory to path

---

config/core/build-configs-stable.yaml

The next LTS will be based on 5.15, so move the kselftest fragment
from 5.14 to 5.15.

build-configs-stable.yaml: move kselftest from 5.14 to 5.15

---

config/core/test-configs.yaml

Upgrade the bullseye-igt rootfs image to 20211124.0 which contains all
the firmware files for amdgpu and i915 as well as the fix to include
amdgpu tests in $PATH.

test-configs.yaml: upgrade bullseye-igt to 20211124.0

---

config/core/build-configs.yaml

Add a new amdgpu config fragment that enables the AMDGPU driver.
Fixes #854.
This fragment was tested in grunt: https://lava.collabora.co.uk/scheduler/job/5023017
As can be seen in the LAVA log, the following tests fail still:
```
amd_bypass.8bpc-bypass-mode
amd_color.crtc-lut-accuracy
amd_info.query-timestamp
amd_info.query-timestamp-while-idle
```
Enabling further amdgpu configs didn't improve the results, so only the configs that improved results were kept in the fragment.
For record purposes, the full fragment tested was:
```
- 'CONFIG_DRM_AMDGPU=y'
- 'CONFIG_DRM_AMDGPU_USERPTR=y'
- 'CONFIG_DRM_AMDGPU_SI=y'
- 'CONFIG_DRM_AMDGPU_CIK=y'
- 'CONFIG_DRM_AMD_ACP=y'
- 'CONFIG_DRM_AMD_DC=y'
- 'CONFIG_DRM_AMD_DC_DCN=y'
- 'CONFIG_DRM_AMD_DC_HDCP=y'
- 'CONFIG_DRM_AMD_DC_SI=y'
- 'CONFIG_KGDB=y'
- …
```

Add amdgpu fragment for the AMDGPU driver

---

config/core/test-configs.yaml

Add a test plan to run IGT tests, both Core and AMD specific, on the AMDGPU driver, and enable it to run on hp-11A-G6-EE-grunt (aka grunt). This relies on the igt rootfs containing the firmware required by AMDGPU, which will get added by #884.
Fixes #883.
At the moment some tests still fail:
```
amd_bypass.8bpc-bypass-mode
amd_color.crtc-lut-accuracy
amd_info.query-timestamp
amd_info.query-timestamp-while-idle
```
Some more in-depth debugging will be needed to try and find out why, since just enabling the other amdgpu config symbols didn't solve it. If it's not possible to get all tests working then we could disable them.

Add igt amdgpu test plan and enable it on grunt

---

kernelci/data/__init__.py
kernelci/data/kernelci_backend.py

Import missing json package which is needed for
Database._print_http_error().  Also remove it from
kernelci.data.kernelci_backend as it's not needed there any more.
Fixes: 0618a1a3de47 ("kernelci.data: add Database._print_http_error()")

kernelci.data: add missing json import

---

config/core/build-configs-cip.yaml
config/core/build-configs.yaml

Enable kselftest on CIP kernels that support kselftest and are producing valid results. 
Future CIP kernel may be enabled if they appear to be producing valid results.
Also move the CIP trees definitions to the CIP builds config file to keep it more self-contained.

Enable kselftest on CIP kernels

---

config/k8s/job-build.jinja2

Generate config fragments as part of the build job instead of relying
on the tarball to already contain them.

config/k8s: generate fragments in the build job

---

config/core/build-configs-stable.yaml
config/core/build-configs.yaml
config/core/test-configs.yaml

Add a new fragment arm64-chromebook with missing config options to
boot on some arm64 Chromebooks.  In particular, this is required for
the mt8173-elm-hana platform until the following patch gets merged in
mainline kernel:
https://lkml.org/lkml/2021/10/11/489
Update test-configs.yaml accordingly.

build-configs.yaml: add arm64-chromebook fragment

---

kernelci/config/test.py
kernelci/test.py

Make the rootfs attribute of the TestPlan configuration object
optional as some tests may not require any root file system image.
Tests that do require one will report any error when trying to run
them.

kernelci.config.test: make TestPlan rootfs optional

---

kci_test
kernelci/lab/__init__.py
kernelci/lab/lava/__init__.py
kernelci/lab/lava/lava_rest.py
kernelci/lab/lava/lava_xmlrpc.py

Rather than passing a job definition object to LabAPI.submit(), pass
the path to a job definition file.  Then it's up to the implementation
code to open it and submit it.  All the current use-cases are based on
actual definition files; if being able to pass an object instead
becomes required at some point then the class can be adjusted
accoringly then.
Update kernelci.lab.lava and kci_test accordingly.

kernelci.lab.LabAPI: pass job_path to .submit()

---

config/core/build-configs-chromeos.yaml
config/core/build-configs.yaml

Move all the Chrome OS build configuration to a new file
build-configs-chromeos.yaml.  This reduces the scope for merge
conflicts and makes it easier to maintain on a separate branch.

config/core: move Chrome OS build configs to separate file

---

kernelci/rootfs.py

bullseye-ltp rootfs creation requires more than
2GB memory, so we need to update debos configuration.

debos: Increase debos memory limit from 2G to 4G

---

config/core/test-configs.yaml

Update all the Debian rootfs URLs except buster-libcamera which is
still failing to build on arm64.  The buster-ltp is finally building
again, so it's the first time it gets updated since October.

test-configs.yaml: update all Debian URLs except libcamera

---

kernelci/config/test.py

Adjust the logic in TestConfig.match() for when the device type has no
"arch" attribute.  This may be the case when running scripts on an
abstract platform without any particular kernel build rather than real
hardware.

T31651 kernelci.config.test: allow no arch in TestConfig.match()

---

kci_test
kernelci/lab/__init__.py

Add LabAPI.save_file() method to let each lab implementation the
possibility to save job definition files in a particular way.  Move
the implementation from kci_test to the LabAPI base class to provide
the same generic default behaviour.

T31651 kernelci.lab.LabAPI: add .save_file()

---

config/core/lab-configs.yaml
config/core/test-configs.yaml
config/scripts/base-python.jinja2
config/scripts/base.jinja2
config/scripts/check-describe.jinja2
kernelci/config/lab.py
kernelci/config/test.py
kernelci/lab/shell.py

Add initial support for running tests in shell scripts:
* add configuration for a "shell" lab type and "shell_python" device type
* add basic test plan "check-describe" with a Python script
The exit code will then tell whether the test passed or failed.  The next step is to make the test process self-contain and let it send the result to the API directly.

T31651 shell scripts

---

config/scripts/base-python.jinja2
kernelci/lab/shell.py

Run scripts in `kernelci.lab.Shell` as detached processes and pass the YAML configuration for the remote API to the template so they can send the results directly.

T31651 detached process

---

config/core/test-configs.yaml

Update the buildroot rootfs URLs to use the new 20211210.0 images
built using kci_rootfs.  Also drop the buildroot_ramdisk rootfs
variant as only the buildroot_baseline_ramdisk is being built and used
now.

test-configs.yaml: use new buildroot 20211210.0 images

---

config/docker/build-and-push.sh

Simplify the command line options to not have one for each Docker
image type but just accept the names of the images to build instead.
Update the comment accordingly.

config/docker/build-and-push.sh: simplify options

---

config/docker/chromeos-tast/Dockerfile

Add a kernelci/chromeos-tast Docker image to run the host tools for
Chrome OS Tast tests.  This is intended to be used on LAVA dispatchers
to run tests on Chromebook devices running Chrome OS user-space.

CHROMEOS config/docker: add chromeos-tast image

---

kernelci/build.py

Rather than simply replacing slash `/` characters, also replace
back-slash and colon characters to make the path is less likely to
cause issues with escape charaters and also more readable.  This is in
particular useful for kernels using a Chrome OS config.

kernelci.build: replace more characters in publish path

---

config/docker/build-and-push.sh
config/docker/clang-11/Dockerfile
config/docker/clang-12/Dockerfile
config/docker/clang-13/Dockerfile
config/docker/clang-base/Dockerfile

The clang docker containers contain a lot of duplicated content installing
utlilities used in the clang build, runtime dependencies for the kernel
build system and removing GCC. This means that any updates to those shared
elements need to touch multiple Dockerfiles. Simplify this by creating a
clang-base container which has everything except the actual clang packages
and basing the version specific clang packages on that.
Since clang-10 is now deprecated and the containers for it are based on
an older Debian release which isn't quite the same as the rest it is not
updated.

config/docker: Factor out common elements of clang containers

---

kernelci/build.py

Currently, each build step always appends its meta-data to steps.json.
This works well for automated building, where all steps are always run
in the same sequence. However when kci_build is used manually to build
an image, multiple runs of the same step may happen as part of the
iterative development process. Since the overall build status is the
aggregation of the individual steps' status, a previous failed build can
keep the overall status as FAIL in bmeta.json, preventing the usage of
kci_test.
This could be worked around by the user always running init_bmeta before
starting each build, but a better alternative is to make each step
overwrite the meta-data from a previous run of the same step. This
improves the usability from manual usage while not affecting the
automated usecase. …

kernelci.build: Make each build step overwrite its meta-data when re-run

---

config/k8s/run.py

Currently we have two scripts for driving Kubernetes, one to generate a
YAML file with a job description in it and another one to monitor the
status of such jobs after they have been submitted via kubectl. Let's cut
out the middleman and mush the two scripts together into one which directly
submits the generated job and then monitors the status. The structure is
taken from wait.py with generate.py moved to a function job_create() with
a small addition to actually submit the job to Kubernetes, returning the
resulting job name which is then used by the rest of the code instead of
having it provided on the command line.
An option is provided allowing the generated YAML to be written out to disk
for diagnostic purposes.
This is not a great way of doing things, it's an in place refactoring to …

config/k8s: Merge gen.py and wait.py into a single script to run obs

---

config/core/build-configs-cip.yaml

Fix the CIP build configurations with kselftest enabled as it was
using the wrong kind of YAML anchor, with all the compiler variants
rather than architecture-specific attributes.  Also, only recent
kernels such as 5.10 can actually be used with kselftest so disable it
for earlier kernels (4.4 and 4.19).
Fixes: 1338c0ab83c3 ("build-configs-cip.yaml: test kselftest with older kernel")

build-configs-cip.yaml: fix kselftest configs

---

config/core/rootfs-configs.yaml
config/rootfs/debos/scripts/bullseye-rt.sh

Add bullseye-rt rootfs image configuration with script to build the
latest version of rt-tests from source.

rootfs-configs.yaml: add bullseye-rt

---

config/core/test-configs.yaml
config/lava/preempt-rt/generic-depthcharge-tftp-ramdisk-preempt-rt-template.jinja2

Add a LAVA template to run `preempt-rt` on Depthcharge devices and enable it on several x86 and arm64 Chromebooks.

Enable preempt-rt on Deptcharge devices

---

config/core/build-configs.yaml

Add the clang-10 build environment again temporarily for mainline as
it's still the minimum supported version until the patch series to
change it to LLVM 11.0 is merged in the next release cycle.  The
clang-10 Docker image can stay unchanged as it was based on Debian
Buster and isn't supported any more, so the Dockerfile for clang-10
doesn't need to be added back.
Fixes: fc2dbb1615b5 ("build-configs.yaml: remove clang-10 and use clang-11")

build-configs.yaml: enable clang-10 again for mainline

---

config/core/test-configs.yaml

Add defconfig+arm64-chromebook to the default test plan filter so test
plans will be enabled by default on Chromebooks that rely on this
config fragment (mt8173-elm-hana at the moment).
Fixes: aeab1ef0cdc1 ("build-configs.yaml: add arm64-chromebook fragment")

test-configs.yaml: add arm64-chromebook to default filter

---

config/core/test-configs.yaml

test-configs.yaml: use bullseye-rt for preempt-rt

---

config/core/build-configs.yaml

Drop clang-11 from linux-next to focus on the latest version instead,
and the minimum version may change from time to time so it's hard to
keep it enabled on linux-next (currently moving from 10 to 11).
Enable clang-13 as the latest stable release on mainline, and keep
clang-10 there as well.
This should result in little change in terms of build resources, with
clang-11 removed from linux-next and clang-13 added to mainline.  Once
a clang-14 Docker image is available, we can start using that with
linux-next to cover clang-11 (mainline), 13 (mainline) and 14 (next).

build-configs.yaml: update clang configs for mainline and next

---

config/core/test-configs.yaml

Fix buster-libcamera URL as the 20211126.0 revision failed to build on
arm64.  Revert to the previous revision that built on all
architectures (20211112.0).
Fixes: eae1f11042ae ("test-configs.yaml: update Debian rootfs URLs")

test-configs.yaml: fix buster-libcamera URL

---

config/rootfs/debos/scripts/buster-libcamera.sh

After removing libgtest-dev, libcamera is not being built using qemu 6 on Bullseye, so this commit reverts the code from libcamera to the point that is working.

scripts/buster-libcamera.sh: revert libcamera commit

---

kernelci/config/test.py

Adjust the logic in TestConfig.match() for when the device type has no
"arch" attribute.  This may be the case when running scripts on an
abstract platform without any particular kernel build rather than real
hardware.

T32412 kernelci.config.test: allow no arch in TestConfig.match()

---

kernelci/config/base.py
kernelci/config/data.py
kernelci/config/test.py

Add support for exporting config objects as YAML and implement it for the main types of configuration objects that will be needed when running test jobs that can send results themselves to the backend / API.

T32412 export config as YAML

---

kci_test
kernelci/lab/__init__.py

Add LabAPI.save_file() method to let each lab implementation the
possibility to save job definition files in a particular way.  Move
the implementation from kci_test to the LabAPI base class to provide
the same generic default behaviour.

T32412 kernelci.lab.LabAPI: add .save_file()

---

config/core/test-configs.yaml

The sun50i-h6-pine-h64 device type doesn't have enough online
instances in the current labs to cover LTP test cases, so reduce the
load to only baseline.

test-configs.yaml: drop LTP on sun50i-h6-pine-h64

---

config/core/test-configs.yaml

Use the new bullseye-libcamera rootfs images instead of
buster-libcamera.

test-configs.yaml: use new bullseye-libcamera rootfs images

---

config/core/test-configs.yaml

Use the new bullseye-ltp rootfs images.

test-configs.yaml: use new bullseye-ltp rootfs images

---

config/core/build-configs.yaml

Add the latest clang version, clang-14 to the build-configs.yml. Replace
the clang-13 with clang-14 for builds.

build-configs.yml: add clang-14 build env and replace clang-13

---

kci_test

Sort alphabetically the output of the list_jobs command and tweak
variable names to remove any ambiguity with lab_config and lab_api.

kci_test: sort output in list_jobs

---

config/core/build-configs.yaml
config/core/test-configs.yaml

This adds a new kselftest test plan for the cpufreq collection, and enables it to run on mt8173-elm-hana.
The test output log can be seen here: https://lava.collabora.co.uk/scheduler/job/5242522
To run this test, `CONFIG_ARM_MEDIATEK_CPUFREQ` needs to be enabled as built-in. [A patch has been sent to the mailing list adding it to the defconfig](https://lore.kernel.org/linux-mediatek/20211217154452.868419-1-nfraprado@collabora.com/T/#u).
After that patch gets merged, we will still either need to block this test on older kernel branches tested by KernelCI or have a config fragment anyway for those, right?

Enable cpufreq kselftest on mt8173-elm-hana

---

config/core/test-configs.yaml

Add the hp-x360-14-G1-sona x86_64 Chromebook device type which is
present in lab-collabora and enable baseline and cros-ec test plans on
it for now.

test-configs.yaml: add hp-x360-14-G1-sona

---

config/core/test-configs.yaml
config/lava/sleep/generic-grub-tftp-ramdisk-sleep-template.jinja2

Add the lenovo-hr330a-7x33cto1ww-emag arm64 server device type and
enable only baseline-nfs on it as it takes a very long time to boot
with the current setup.  It relies entirely on UEFI and doesn't use
any dtb file.

test-configs.yaml: add lenovo-hr330a-7x33cto1ww-emag

---

config/core/lab-configs.yaml
kci_test
kernelci/config/lab.py
kernelci/lab/__init__.py
kernelci/lab/lava/__init__.py
kernelci/lab/shell.py

Add `kernelci.lab.shell` to run tests in a local process. Update `kci_test` accordingly to be able to use it.
Note: The script templates are not part of this PR as they are instead being added to [`kernelci-pipeline`](https://github.com/kernelci/kernelci-pipeline).

T32412 Add Shell lab type

---

kernelci/config/test.py

Add kernelci.config.test.DeviceType_shell which will be used to run
scripts in a local shell.

T32412 kernelci.config.test: add DeviceType_shell

---

config/core/build-configs.yaml

Add CONFIG_RTC_DRV_MT6397=y to the arm64-chromebook config fragment to
enable kselftest-rtc tests on mt8173-elm-hana.

build-configs.yaml: add RTC_DRV_MT6397 to arm64-chromebook

---

config/core/test-configs.yaml

This adds a new kselftest test plan for the rtc collection, and enables it to run on mt8173-elm-hana.
The test output log can be seen here: https://lava.collabora.co.uk/scheduler/job/5227298
As can be seen, 2 out of the 7 tests fail. Namely, `rtc.alarm_alm_set` and `rtc.alarm_alm_set_minute`. The reason behind this is that the MT6397 RTC driver doesn't implement the `alarm_irq_enable()` operation, which is required for the `RTC_AIE_ON/OFF` IOCTLs used in those tests.
That said, that doesn't seem to be a problem since the `wkalm` variants of those two tests pass, which use the `RTC_WKALM_*` IOCTLs instead, which are preferred over the `ALM` ones anyway. (According to `Documentation/ABI/testing/rtc-cdev` and `drivers/rtc/dev.c`)
To run this test, `CONFIG_RTC_DRV_MT6397` needs to be enabled …

Enable rtc kselftest on mt8173-elm-hana

---

config/core/build-configs-android.yaml

Enable clang-14 builds on 5.10 and 5.15 android branches. Also enable
the GKI configs.

build-configs-android: enable clang-14 android builds

---

config/core/test-configs.yaml
kci_test
kernelci/config/test.py

Add a `kci_test validate_rootfs_urls` command to verify all the rootfs URLs in `test-configs.yaml` are valid.  Fix a few loose ends in `test-configs.yaml` to keep the rootfs config names consistent.

Add kci_test validate_rootfs_urls

---

config/core/test-configs.yaml

Replace the buster-v4l2 rootfs images with the new bullseye-v4l2 ones.

test-configs.yaml: replace buster-v4l2 with bullseye-v4l2

---

config/core/test-configs.yaml

The rk3399-gru-kevin device uses the rtc-cros-ec driver for RTC. This PR adds the kselftest-rtc test on kevin to exercise this driver. The config needed to enable the driver is already part of the arm64 defconfig.
LAVA run: https://lava.collabora.co.uk/scheduler/job/5409783
As can be seen from the LAVA output, the `alarm_alm_set_minute` test, which sets an alarm, is failing with timeout. From a first look it seems like a bug in the `rtc-cros-ec` driver.

test-configs.yaml: Enable kselftest-rtc test plan on rk3399-gru-kevin

---

kci_bisect
kernelci/bisect.py

Add `kci_bisect get_mbox` command to get a Mailbox email from
lore.kernel.org that matches a given git commit number.  This is not
guaranteed to succeed as not all commits have an email in lore, and
some heuristics are used to determine which email to use when there
are several with a matching subject.  It's mostly a shortcut for
reporting an issue manually (typically, bisection results).

kci_bisect: add get_mbox command

---

config/core/lab-configs.yaml
config/core/test-configs.yaml

The QDF2400 is quite a powerful server platform and the system we have
available seems to have lots of spare capacity so let's enable kselftest
and LTP on it.

test-configs.yaml: Enable kselftest and LTP for QDF2400

---

kernelci/build.py

Stop converting all the elements in the publish path to lower case as
the config string with e.g. +CONFIG_SOMETHING=y needs to remain in
capital letters.  This was most likely introduced by mistake as
there's no apparent reason for using lower-case, even with Chrome OS
config names which the breaking change was originally required for.
Fixes: 2eccce7ab993 ("kernelci.build: replace more characters in publish path")

kernelci.build: don't convert publish path to lower-case

---

config/core/test-configs.yaml

Add the rk3399-rock-pi-4b device and enable the baseline tests on it.
Lava run for baseline OK: https://lava.collabora.co.uk/scheduler/job/5486817
Lava run for baseline-nfs OK: https://lava.collabora.co.uk/scheduler/job/5486703
The device tree used by this specific device variant, rk3399-rock-pi-4b.dts, was created only in 5.9. Before that a single generic dt was used for all RockPi4's. So a blocklist or allowlist needs to be added to ensure that only 5.10+ kernels run on this device. @gctucker how could that be done? I've seen the other examples, but I haven't been able to find the list of kernel releases that are run in KernelCI, so that I can block all the ones below 5.10.

test-configs.yaml: Add rk3399-rock-pi-4b

---

config/core/rootfs-configs.yaml
config/rootfs/debos/rootfs.yaml
config/rootfs/debos/scripts/bullseye-cros-ec-tests.sh
config/rootfs/debos/scripts/strip.sh

Add Debian bullseye based image configuration for cros-ec tests.
Depends on https://github.com/kernelci/kernelci-core/pull/995

Add bullseye-cros-ec rootfs image

---

config/core/test-configs.yaml

Replace buster-cros-ec with the new bullseye-cros-ec rootfs images.

test-configs.yaml: use bullseye-cros-ec

---

config/core/build-configs-android.yaml

All the *_defconfig are built by default. This is why even if gki_config
was a typo (instead of correct gki_defconfig) gki config is being built.
Remove it and simplify the file.
Fixes: af4646952a07 ("build-configs-android: enable clang-14 android builds")

build-configs-android: Remove gki_config

---

config/core/test-configs.yaml

Update the URL of the newly defined bullseye-ltp ramdisk which is used
on QEMU.

test-configs.yaml: use latest bullseye-ltp for QEMU

---

kernelci/data/kernelci_api.py

Fix how the PUT requests are used when updating documents by checking
whether the data contains an '_id' rather than 'id', and if there is
one then use it in the URL path as it's required for PUT requests.
Fixes: 63774f174681 ("kernelci/data/kernelci_api.py: Add logic to use PUT in submit()")

kernelci.data.kernelci_api: fix PUT requests when udating documents

---

config/core/build-configs-android.yaml

Enable clang-14 builds for android-mainline, android-mainline-tracking,
android11-5.4, android12-5.4 and android12-5.4-lts branches.

build-configs-android: Enable clang-14 builds for more android branches

---

kernelci/lab/lava/__init__.py
kernelci/lab/shell.py

Fix a couple of places where the `templates_path` was not being used correctly.

Fix how templates_path is used in kernelci.lab

---

kernelci/data/kernelci_api.py

Add method to request kernelci-api 'nodes' endpoint
to get a list of node objects matching with the commit SHA-1.
Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

kernelci/data/kernelci_api: add KernelCI_API.get_nodes_by_commit_hash 

---

config/core/test-configs.yaml

The arm64 Memory Tagging Extension (FEAT_MTE) is supported by qemu but is
not enabled, even with cpu=max. Get some test coverage for it by enabling
it for our virtual arm64 platforms when the built kernel supports it. There
is some specific coverage for it in kselftest too which will be exercised
when this is enabled.

test-configs: Enable MTE for virtual arm64 platforms

---

config/rootfs/debos/scripts/strip.sh

Remove temporary files after the descriptors are closed.

kci_rootfs: Remove temporary files in strip.sh

---

doc/kci_rootfs.md

Update all the examples using Bullseye and the current list of rootfs
configs rather than Buster.

doc/kci_rootfs.md: update with Bullseye

---

config/core/build-configs-android.yaml

Remove old android branches listed as requested by Todd:
android-4.4-p
android-4.4-p-release
android-4.9-p-release
android-4.14-p-release
https://groups.io/g/kernelci/message/1344

core/build-configs-android.yaml: drop old android branches

---

config/core/build-configs.yaml

Add the linux-kselftest tree with a build config for the "fixes" and "next" branches including a small set of builds to cover all the kselftest currently being run on actual hardware.
Link: https://lore.kernel.org/lkml/5fd1a35c-f84e-1c6a-4a3a-be76dda97ca3@collabora.com/

build-configs.yaml: add kselftest tree with fixes and next branches

---

config/core/build-configs.yaml

Add coverage for the fixes branches for my trees, these are no longer
merged into my -next branches and it's useful to check that they don't
have any dependencies on -next material. They are generally updated less
often than the -next branches.

build-configs: Add fixes branches for my trees

---

config/core/rootfs-configs.yaml

Add bullseye-kselftest rootfs image configuration.
Only required change was updating perl and perl modules version.

Update kselftest from buster to bullseye

---

config/core/lab-configs.yaml

Given that there are a lot of Renesas boards in lab-cip (specifically lab-cip-renesas) it would be good to expand upstream Renesas tree testing to test them.
Thanks

lab-configs.yaml: Enable testing for Renesas trees in lab-cip

---

config/core/build-configs.yaml
config/docker/clang-15/Dockerfile

Update clang-14 Dockerfile and add new one for clang-15 now that the
main repository has moved to clang-15.

config/docker: add clang-15

---

config/core/rootfs-configs.yaml

Newer bullseye-kselftest available and tested, so old buster can be dropped

rootfs-configs.yaml: drop buster-kselftest

---

kernelci/build.py
kernelci/test.py

The current way to detect endianess is to check if a BIG ENDIAN defconfig frag was added.
But this is wrong for defconfig which is are nativly big endian like arm
ixp4xx_defconfig.
So the ultimate way to know the endianess is to download the kernel
config and grep it.
Signed-off-by: Corentin Labbe <clabbe@baylibre.com>

Detect better the endianess of a build

---

config/core/rootfs-configs.yaml
config/docker/build-and-push.sh
config/docker/chromiumos/Dockerfile
config/rootfs/chromiumos/scripts/build_board.sh
doc/kci_rootfs.md
kernelci/cli.py
kernelci/config/rootfs.py
kernelci/rootfs.py

With just:
docker run -itd -v $(pwd):/kernelci-core --device /dev/kvm -v /dev:/dev --privileged kernelci/chromiumos
./kci_rootfs build --rootfs-config chromiumos --data-path config/rootfs/chromiumos --arch amd64-generic
(And several hours of build time)
I can get qemu bootable image:
config/rootfs/chromiumos/amd64-generic/chromiumos_test_image.bin
(Must be used with USB storage disk, if we use libvirt)
As ChromiumOS dont have strictly speaking "architecture", in our case it means ChromiumOS board name.
So it can be amd64-generic, hatch, etc. 

Add ChromiumOS image building functionality as rootfs option

---

config/core/build-configs.yaml

HI,
This is the kernelci-core counterpart to the [bootrr PR #12](https://github.com/kernelci/bootrr/pull/12).
[Here is an example run](https://lava.collabora.co.uk/results/testcase/170445026) of the bootrr test with these configs and tpm2-tools on my dev setup.

Enable cr50 tpm drivers

---

config/core/test-configs.yaml

Update the URL for the buildroot images used with the baseline ramdisk
tests.  This contains updates to run TPM tests as part of bootrr.

test-configs.yaml: update buildroot image URL

---

kci_rootfs

Clean up the implementation of kci_rootfs and include the rootfs type
in the output.  For example:
$ ./kci_rootfs list_variants --arch=arm64
buildroot-baseline arm64 buildroot
bullseye arm64 debos
bullseye-cros-ec arm64 debos
bullseye-igt arm64 debos
bullseye-kselftest arm64 debos
bullseye-libcamera arm64 debos
bullseye-ltp arm64 debos
bullseye-rt arm64 debos
bullseye-v4l2 arm64 debos

kci_rootfs: print rootfs type in list_variants and clean up

---

config/core/lab-configs.yaml
config/core/test-configs.yaml
config/lava/baseline/generic-qemu-baseline-docker-template.jinja2
config/lava/boot/generic-qemu-boot-template.jinja2

Convert configuration and LAVA job templates to always use Docker when running QEMU tests.
Fixes #1014

Run QEMU LAVA tests only in Docker containers

---

config/docker/clang-base/Dockerfile
config/docker/gcc-10_arm/Dockerfile
config/docker/gcc-10_arm64/Dockerfile
config/docker/gcc-10_x86/Dockerfile

Alsa test needs alsa library which comes from libasound2-dev package.
pkg-config package is being used in Makefile of the test. Add both
packages.

config/docker: Add packages for kselftest/alsa

---

config/docker/clang-base/Dockerfile

Add missing libhugetlbfs-dev package in clang-base to fix some kselftest builds such as the vm ones.

config/docker: add libhugetlbfs-dev for clang kselftest

---

config/core/test-configs.yaml

Add the asus-cx9400-volteer x86 Intel Tiger Lake Chromebook with a
small number of initial test plans to run.

test-configs.yaml: add asus-cx9400-volteer

---

config/docker/gcc-10_x86/Dockerfile

Add support for building 32-bit binaries to the gcc-10 x86 Docker
image.  This is useful for some kselftests (x86 and vm) which build
both 64-bit and 32-bit variants of some test programs.

config/docker: add 32-bit support to gcc-10 x86

---

config/core/test-configs.yaml

Add a definition for the kselftest-vm test plan and enable it on a few devices initially.
Depends on #1044
Depends on #1046

test-configs.yaml: add kselftest-vm

---

config/core/rootfs-configs.yaml

Some vm kselftests are failing due to missing libnuma.so.1:
```
```
Add the libnuma1 package to the rootfs config to fix this.

rootfs-configs.yaml: add libnuma to bullseye-kselftest

---

kci_rootfs
kernelci/rootfs.py

At current moment kci_rootfs generate artifacts in random, option specific directories,
which increase complexity of build configuration.
This patch adds mandatory --output option for directory, where artifacts generated.
Also it adds git clone option for buildroot, otherwise without it
buildroot rootfs option is incomplete and doesnt work "standalone".
Additionally it will have predictable structure for output:
{output_directory}/{config_name}/{arch}

kci_rootfs: Add --output option

---

kernelci/data/kernelci_api.py

Handle keep-alive events received on the pub/sub interface.  These are
only there to ensure the TCP connection stays active.

kernelci.data.kernelci_api: handle keep-alive events

---

kernelci/data/kernelci_api.py

Add function to call 'get_root_node/' endpoint of
kernelci-api.
Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

kernelci_api.py: Add KernelCI_API.get_root_node function

---

config/docker/chromeos-tast/Dockerfile

As qemu chromiumos need time to bring network up,
it is much easier and faster to wait it with ping.
Tested with https://lava.collabora.co.uk/scheduler/job/5827818

CHROMEOS Add ping to docker image

---

config/docker/chromiumos/Dockerfile

Jenkins run docker as "docker run -t -d -u 996:1001", so we are forced to use uid 996 to keep sudo and other scripts working.

CHROMEOS: Adjust uid for jenkins configuration

---

config/core/test-configs.yaml
config/lava/base/kernel-ci-base.jinja2
config/lava/chromeos/chromeos-tast-template.jinja2

Add a new lava job template to be used by chrome OS at this first step to run Tast tests.

T31627 - create lava job for chrome os

---

config/core/rootfs-configs.yaml
config/rootfs/debos/scripts/bullseye-v4l2.sh

Set debian release for bullseye-v4l2 to bullseye.
Signed-off-by: Laura Nao <laura.nao@collabora.com>

rootfs-configs.yaml: Fix bullseye-v4l2 release

---

config/core/build-configs.yaml

Bump mainline builds from clang-10 to clang-11 as it is now the
minimal version supported.

build-configs.yaml: bump mainline to clang-11

---

config/docker/dt-validation/Dockerfile

Add dependencies needed to build and install dt-schema Python package.

config/docker: Fix dt-validation Docker image

---

config/docker/gcc-10_x86/Dockerfile
config/docker/gcc-10_x86/gcc-header-fix.patch

Builds with allmodconfig or when ggc plugins enabled failing, for example:
https://storage.kernelci.org/mainline/master/v5.17-rc7/x86_64/allmodconfig/gcc-10/logs/build-errors.log
Build error message example:
/usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory
/usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory
Using patch proposed in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980609#72

Temporary fix for debian gcc-10, missing i386-cpuinfo.h

---

config/rootfs/chromiumos/scripts/build_board.sh

Use trap function, so it will clean not only on exit, but
also if script quit early due error.
This resolve problems with jenkins.
Also compress image, as it shrink image from 6GB to approx 2GB.

CHROMEOS Clean workspace on error or exit, compress image

---

config/core/build-configs.yaml
config/core/rootfs-configs.yaml
config/core/test-configs.yaml

This PR gets kselftest-tpm2 running on grunt.
Lava log: https://lava.collabora.co.uk/scheduler/job/5608585
Basically the results are:
```
```
The errors are caused by `tpm2.ProtocolError: TPM_RC_LOCKOUT: cc=0x00000153, rc=0x00000921`. There was [a commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a9920d3bad40201ee8ab1da36bee4674f7e50d69) in the past fixing those, but [it was later reverted](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5be206eaac9a68992fc3b06fb5dd5634e323de86). However the patch might make sense in KernelCI's usecase, where devices are there just for testing. That said, that patch requires the `tpm2_clear` tool, which is only available in bullseye.
I ran the tests using the `bullseye-kselftest` rootfs …

Run kselftest-tpm2 on grunt

---

config/docker/debos/Dockerfile

Add ssh to debos docker image which is necessary to upload images with
scp.

config/docker: add ssh to debos docker image

---

config/core/test-configs.yaml

Add lab-broonie to the passlist for QEMU tests which now requires
Docker support.

test-configs.yaml: add lab-broonie to QEMU passlist

---

kernelci/build.py

Update _create_cros_config() to look into a "chromeos" sub-directory
in the Chrome OS config tarball as the files appear to have now been
split between different categories.
Here's the contents of a sample config tarball:
https://chromium.googlesource.com/chromiumos/third_party/kernel/+archive/refs/heads/chromeos-5.10/chromeos/config.tar.gz
```
├── chromeos
│   ├── arm64
│   │   ├── chromiumos-arm64.flavour.config
│   │   ├── chromiumos-mediatek.flavour.config
│   │   ├── chromiumos-qualcomm.flavour.config
│   │   ├── chromiumos-rockchip64.flavour.config
│   │   └── common.config
│   ├── armel
│   │   ├── chromiumos-arm.flavour.config
│   │   ├── chromiumos-rockchip.flavour.config
│   │   └── common.config
│   ├── base.config
│   └── x86_64
│       ├── …
```

CHROMEOS kernelci.build: add "chromeos" sub-directory for configs

---

config/docker/debos/Dockerfile

Add jenkins user to debos container. It's needed for some jobs to have a `jenkins` user inside the container.

config/docker: add jenkins user to debos image

---

config/rootfs/chromiumos/scripts/build_board.sh

This will allow to include more supplementary files in future
Tested at https://bot.staging.kernelci.org/job/denysf/job/rootfs-builder-denysf/41/console
Result available at https://storage.chromeos.kernelci.org/images/rootfs/chromeos/crostest006/chromiumos-amd64-generic/amd64/

CHROMEOS Create tast.tgz instead of separate files

---

config/docker/chromeos-tast/Dockerfile
config/docker/chromeos-tast/tast-parser.py

As tast parser will remain same, it is reasonable to add it to docker image.
tast and remote_test_runner are generated with each rootfs image.

CHROMEOS Add tast parser to Docker image

---

config/core/rootfs-configs.yaml
kernelci/config/rootfs.py
kernelci/rootfs.py

Add YAML config for the Git URL and branch name to initialise the buildroot source tree.  Also reuse any existing clone to avoid recreating a fresh one every time.

Add Git URL and branch YAML config for buildroot

---

config/core/lab-configs.yaml
config/lava/base/kernel-ci-base.jinja2
kernelci/config/lab.py
kernelci/lab/lava/__init__.py

Since 2021.08, LAVA supports queue timeout.
Let's adds support for it in kernelCI.
Since my lab is recent enough, enable queue_timout in my lab.
Closes: 1086

Add support for queue timeout

---

config/core/lab-configs.yaml
config/lava/base/kernel-ci-base.jinja2
kernelci/config/lab.py
kernelci/lab/lava/__init__.py

Enable a queue timeout of 2 days for lab-collabora and 1 hour in lab-collabora-staging as an initial experimental value.
Depends on #1087

lab-configs.yaml: add queue timeout in Collabora's labs

---

config/core/test-configs.yaml
config/lava/chromeos/chromeos-tast-template.jinja2
config/lava/chromeos/chromiumosvm-tast-template.jinja2
config/lava/chromeos/tast.jinja2

As QEMU version of ChromiumOS have slightly different boot
sequence and uses tast built from ChromiumOS sources, it require separate LAVA template.

CHROMEOS Add LAVA template for QEMU tast tests

---

config/core/build-configs-chromeos.yaml

Add the arm64-chromebook fragment to all Chrome OS configs in the same
way that the x86-chromebook fragment was previously enabled.  This is
required to boot some Chromebook devices with serial console and other
tweaks that aren't in the upstream arm64 defconfig.

CHROMEOS build-configs-chromeos.yaml: enable arm64-chromebook fragment

---

config/core/build-configs-chromeos.yaml
config/core/build-configs.yaml

Add a `build-configs-chromeos.yaml` file with the Chrome OS build configuration used on chromeos.kernelci.org.  Depends on #1102.

build-configs-chromeos.yaml: add file with Chrome OS build configs

---

config/core/build-configs-cip.yaml

Add build variants with the preempt_rt fragment enabled and use them
with the -rt kernel branches.

build-configs-cip.yaml: enable preempt_rt on rt cip kernels

---

config/core/test-configs.yaml

Add the hp-x360-12b-ca0500na-n4000-octopus device type variant which
is currently only present in lab-collabora-staging with a smaller set
of test plans to run on it.

test-configs.yaml: add hp-x360-12b-ca0500na-n4000-octopus variant

---

config/core/build-configs.yaml
kernelci/build.py

Enable extra config options for the `kselftest` fragment and drop network interfaces that cause `ip=dhcp` to fail.

kselftest: drop debug network interface

---

config/core/test-configs.yaml

This board (a very old out of production AT91 reference system) is in my
lab.
The board only has 64M of RAM so is very restricted in terms of what it can
run from ramdisk but it has ethernet and is quite capable with NFS and is
a useful example of it's generation of audio hardware. With our current
setup it struggles to boot a multi_v5_defconfig in an initramfs due to the
size of the modules causing us to run out of memory, we may need to
explicitly block that.

test-configs: Add at91sam9g20ek

---

config/core/lab-configs.yaml

The LKFT lab has a current enough version of LAVA to do queue
timeouts so let's enable a timeout of one day which is probably
sensible enough for standard testing.
This should help us catch up with the backlog due to the QDF2400
being slow to boot.

lab-configs: Add a timeout for the LKFT lab

---

kernelci/build.py

Update _create_cros_config() to look into a "chromeos" sub-directory
in the Chrome OS config tarball as the files appear to have now been
split between different categories.
Here's the contents of a sample config tarball:
https://chromium.googlesource.com/chromiumos/third_party/kernel/+archive/refs/heads/chromeos-5.10/chromeos/config.tar.gz
├── chromeos
│   ├── arm64
│   │   ├── chromiumos-arm64.flavour.config
│   │   ├── chromiumos-mediatek.flavour.config
│   │   ├── chromiumos-qualcomm.flavour.config
│   │   ├── chromiumos-rockchip64.flavour.config
│   │   └── common.config
│   ├── armel
│   │   ├── chromiumos-arm.flavour.config
│   │   ├── chromiumos-rockchip.flavour.config
│   │   └── common.config
│   ├── base.config
│   └── x86_64
│       ├── chromeos-amd-stoneyridge.flavour.config …

kernelci.build: add "chromeos" sub-directory for configs

---

config/core/test-configs.yaml

Distribute core kernel kselftests on all available devices per
architecture. One kselftest should run on at least two different
devices of same architecture when there is no capacity issue. Add or
remove kselftests to different devices to make this normalization.
These changes have been done after doing analysis that how many devices
devices are available of certain architecture.
---
The latest proposal, "Proposal - 2" can be seen in the [spreadsheet](https://docs.google.com/spreadsheets/d/1ffrb_zP1WqKNaLx3W6eOdp39CbXzvpUKBwiWtgtxfwM/edit#gid=0).

test-config: distribute core kernel kselftests

---

config/rootfs/debos/overlays/chromeos-flash/opt/chromeos/flash
config/rootfs/debos/overlays/chromeos-flash/opt/chromeos/install-modules

Split chromeos-flash-modules.sh script into flash and install-modules
scripts. Flashing and module installing parts are logically separate and
are meant to be used by different LAVA jobs, hence script is split. It's
also moved from /usr/bin to /opt/chromeos in the rootfs image.
fixup_tmpfiles() function has been removed as it's not needed anymore.

CHROMEOS config/rootfs: Split chromeos-flash-modules.sh script

---

config/lava/chromeos/chromeos-flash-template.jinja2

Use /opt/chromeos/flash script instead of the old /usr/bin/chromeos-flash-modules.sh.
Depends on #1105

CHROMEOS Use new flashing script

---

config/core/test-configs.yaml

The board has built in ethernet which is well supported by the kernel.

test-configs: Enable baseline-nfs for Pine64+

---

config/docker/clang-base/Dockerfile
config/docker/gcc-10_arm/Dockerfile
config/docker/gcc-10_arm64/Dockerfile

This installs a copy of pkg-config we can actually use and ensures it finds libasound2 in cross builds.

Fix pkg-config

---

config/core/build-configs.yaml

Without NVMe support it is not possible to flash such Chromebooks.
Tested at: https://lava.collabora.co.uk/scheduler/job/6090176

build-configs.yaml: Add to fragment support of NVMe to Chromebooks

---

config/core/lab-configs.yaml
config/core/test-configs.yaml
kernelci/config/lab.py
kernelci/lab/__init__.py
kernelci/lab/lava/__init__.py

LAVA supports numerical priorities for jobs from 0 to 100. Currently we only allow a single priority to be configured for all KernelCI jobs in a lab, in order to allow labs to give us more flexibility in how we schedule jobs allow a minimum and maximum priority to be configured within which we can schedule jobs.
We then map this range onto a percentage priority configurable in each test plan, defaulting to 0 so all jobs are assigned the lowest priority allowed by the lab.
For robustness if only one of minimum or maximum is specified we set both minimum and maximum to a single value. For simplicity and robustness with people updating their configurations if the existing priority field is configured then we still retain it, if no range is specified it will be the minimum and maximum. The …

Lab priority ranges

---

config/core/test-configs.yaml

Using KVM acceleration means that when running natively instead
of emulating whatever qemu supports we directly virtualise
whatever CPU the host has. This results in a less consistent
target platform between test runs and means we miss coverage of
new features only available in emulation which is one of the
benefits of using qemu. It's reasonable to want to test
virtualisation but we should specifically do so as a separate
target.
This is unlikely to have had any effect at present since
currently I think all our host systems are x86 based.

test-configs: Don't use KVM acceleration for arm64 virtual platforms

---

config/core/rootfs-configs.yaml
config/core/test-configs.yaml

Hook up the ALSA kselftests. These do not require any physical setup of the
system so can be run on any device with the relevant hardware, they should
be very quick to run.
Since these tests are system specific I've enabled them for quite a wide
range of systems rather than picking a few per architectures, they will
gracefully handle systems with no sound cards so we could in theory just
enable them everywhere but there's the overhead from booting when run as
an independent testsuite. We may want to pare this back in future.

test-configs: Enable ALSA kselftests

---

config/docker/qemu/Dockerfile

Half the point of running all docker jobs in qemu is to allow us
to make use of features of and get coverage of architecture
emulation in current versions of qemu. Unfortunately we're just
using the default version from Debian which is v5.2, already more
than a year old and only going to get futher and further behind.
Change the container to pick up the verison of qemu from
backports which should be a lot more current - at time of writing
it's got the latest release.

config/docker: Use a current version of qemu

---

config/core/test-configs.yaml

The implementation of the architected pointer authentication implementation
in qemu is very slow so qemu provides optional support for an additional
implementation defined algorithm which runs much faster. This is not so
noticeable when userspace doesn't make use of pointer authentication but
once it does the performance improvement is dramatic. Switch our virtual
arm64 targets over to this, there's no real coverage impact for the kernel.

test-configs: Use implementation defined FEAT_PAUTH with qemu on arm64

---

kernelci/lab/lava/__init__.py
kernelci/lab/lava/lava_rest.py
kernelci/lab/lava/lava_xmlrpc.py

Move the .job_file_name() method to the base LavaAPI class as it's
common to XMLRPC and Rest API variants.

kernelci.lab.lava: move job_file_name() to base class

---

config/core/test-configs.yaml
kernelci/build.py

Many kselfests have no dependency on the kselftest fragment, such as those for core kernel features which are always enabled and those for drivers which require very device specific configuration expected to come from the defconfg. Even where there is a need for a config fragment the tests should handle it being missing gracefully at runtime. Remove the dependency on building kselftests and remove the runtime dependency from those selftests where it isn't needed.

Allow selftests to run without the kselftest fragment

---

kernelci/lab/shell.py

Add missing copyright header in kernelci/lab/shell.py

kernelci.lab.shell: add copyright header

---

kci_test
kernelci/lab/__init__.py
kernelci/lab/lava/__init__.py
kernelci/lab/shell.py

Drop the db_config argument from LabAPI.generate() as extra parameters
such as the db config YAML dump should be added to the parameters
before calling the method.

kernelci.lab: drop db_config from .generate()

---

config/core/test-configs.yaml

The board has suitable hardware to support the cpufreq and RTC tests and has built in ethernet so can NFS boot.
This builds on top of https://github.com/kernelci/kernelci-core/pull/1119 which is in the history, hopefully github handles that well...

test-configs: Enable more tests for Pine64+

---

setup.py

Add the LAVA template files to the kernelci package so they get
distributed with the code.  The idea is to only include generic config
files that can be reused in any installation.  Also fix the path to
where the documentation files are getting installed as a side-effect.

setup.py: add LAVA template files to package

---

config/core/test-configs.yaml

The arm port has two main defconfigs - multi_v7_defconfig for the more
modern hardware and multi_v5_defconfig for older system. Currently we
only consider the former where we need a list of defconfigs but we do
have some older platforms so consider multi_v5_defconfig part of our
standard architecture defconfig list.

test-configs: Add multi_v5_defconfig as a defconfig for 32 bit arm

---

config/core/test-configs.yaml

When priorities were added for test jobs we raised the priority of the
baseline job on the basis that it helps ensure we get some basic
coverage for the boards and will in future allow us to avoid scheduling
other tests on boards that have boot issues. A similar argument applies
to all the other baseline tests so let's also raise their priorities to
match.
Put the NFS boot jobs at a slightly lower priority since they are
generally a secondary boot method for boards that also boot using
another method, they are still important since many of the other tests
rely on being booted via NFS.

test-configs: Raise priorities of all baseline jobs

---

config/core/rootfs-configs.yaml

Remove sid rootfs image which is not used by any test jobs.

rootfs-configs.yaml: Remove sid rootfs image

---

config/core/test-configs.yaml

The standard LAVA interpretation of Juno includes support for rewriting
the firmware as part of the test job but not all labs will want to do
that since it makes jobs take longer to run and be more hassle to
specify. Add a separate device type for Juno r0 systems with fixed
u-boot firmware.

test-configs.yaml: Add a machine type for Juno with U-Boot firmware

---

config/core/rootfs-configs.yaml
config/rootfs/chromiumos/scripts/build_board.sh

Manually built and tested rootfs of octopus, grunt, hatch.
hatch require small patch (workaround) at current moment, otherwise build fail with error:
No boards found; assuming we're building for a fuzzer.
ERROR: chromeos-base/chromeos-ec-0.0.2-r12066::chromiumos failed (compile phase):
No EC boards found.
Also add extraction of kernel and modules, as LAVA depthcharge method require them for booting.

CHROMEOS Add chromebook definitions, extract kernel and modules from rootfs

---

config/core/lab-configs.yaml
kernelci/config/lab.py

Add `config_path` attribute to the lab configuration to know where to find things such as Jinja2 templates. Also populate the attribute with all the existing lab configs.

T34835 lab config path

---

config/docker/build-and-push.sh
config/docker/kernelci/Dockerfile
setup.py

Add a `kernelci/kernelci` Docker image with the `kernelci` Python package installed with its dependencies as well as the config files copied to `/etc/kernelci`.

T34238 kernelci Docker image

---

config/scripts/base-python.jinja2

Set the exit status to 0 in base-python.jinja2 even if the test case
failed as the script ran successfully.
An exit status of 1 should only mean that the script failed to run,
for example if no test result could be sent to the API.  Some
follow-up changes might be required to handle error propagation
correctly if defaulting to Python exceptions is not enough.

config/scripts: set exit status to 0 even it test failed

---

config/core/lab-configs.yaml

Time out jobs after 24 hours - that's well after e-mail reports have
been sent out and in most cases it's likely the tree being tested will
have moved on by that time anyway.

lab-configs: Add a timeout for my lab

---

config/core/test-configs.yaml

The LTP pty tests have been timing out in production, with only one
board managing to complete the tests recently. The default timeout is 15
minutes but running with a larger timeout showed that the test job took
17 minutes to complete on Pine64 Plus. Raise the timeout to 25 minutes,
covering that with some additional headroom for slower systems.

test-configs: Increase timeout for LTP pty tests

---

kernelci/build.py

Check the kernel version in `is_enable()` to only enable kselftest builds with v5.10 onwards.  Earlier versions don't have `gen_tar()` and don't have the scripts to only run a particular test collection.

Build kselftest only with v5.10 onwards

---

config/docker/build-and-push.sh
config/docker/chromeos-lavapost/Dockerfile
config/docker/chromeos-lavapost/add_modules.sh

LAVA require special docker image with libguestfs installed,
as libguestfs used to modify binary disk images with multiple
partitions and filesystems.

CHROMEOS Add LAVA postprocessing docker image

---

config/core/rootfs-configs.yaml

Bump up ChromiumOS release to be in sync with Chromebook builds versions.
Also R100 required as ./build_packages -> build_packages rename
introduced in it.

CHROMEOS Update version of QEMU ChromiumOS build to R100

---

config/core/test-configs.yaml
config/lava/chromeos/chromiumosvm-tast-template.jinja2

LAVA capable to add upstream modules into ChromiumOS rootfs image
using libguestfs, and this way we can test upstream kernels.
First tests:
"Fixed kernel" https://lava.collabora.co.uk/scheduler/job/6015601
Upstream kernel https://lava.collabora.co.uk/scheduler/job/6015641

CHROMEOS Modify LAVA template: add modules into rootfs

---

config/core/lab-configs.yaml

I'd be happy with boot tests only for Android, but with our present test
generation the number of Android trees and frequency of updates means we
are generating so many test jobs that they DoS all the other trees and
we can't control test jobs per tree per lab.

lab-configs: Block Android trees in my lab

---

config/core/test-configs.yaml

This series adds just the basic stanzas for some reasonably reliable kselftests which seem useful and which I've been using to have more kselftest fragments to work with for other development. 
It doesn't include any board enabements due to the concerns about picking systems to run things on, I will turn them on for AT91SAM9G20-EK once https://github.com/kernelci/kernelci-core/pull/1097 is in (and there's some overlap with https://github.com/kernelci/kernelci-core/pull/1116 too).

Enable various kselftests

---

config/core/test-configs.yaml
config/lava/chromeos/chromeos-flash-template.jinja2

Based on real testing, to improve reliability of flashing following changes are done:
1)Accept ChromiumOS as full URL, as it might be placed on various resources, not only internally
2)Assume image is compressed (significant space gains)
3)Use compressed scp (few minutes win over 100Mbps-forced port)
4)Flash over ssh, as serial console very unreliable
5)Specify root device for each device type flashing job
6)Include examples for known device types that was flashed successfully

CHROMEOS LAVA flash improvements

---

config/lava/chromeos/chromeos-flash-template.jinja2

Fix the name of the LAVA test action in the job template for flashing
Chrome OS images to make it "chromeos-flash" everywhere.

CHROMEOS config/lava/chromeos: fix flash test action name

---

config/rootfs/debos/overlays/chromeos-flash/opt/chromeos/flash

As some chromebooks might have mmcblk1, some nvme storage device,
we must allow to specify flashing device by environment variable FLASH_DEVICE.
Also allow special case "detect" when script will detect mmcblk0 OR mmcblk1,
as on some chromebooks device number change randomly on boot.

CHROMEOS Allow to modify root device prefix

---

config/core/build-configs-chromeos.yaml

Add a chromeos-stable build configuration based on v5.10 LTS.

CHROMEOS build-configs-chromeos.yaml: add chromeos-stable

---

config/core/build-configs-chromeos.yaml

Switch all Chrome OS build configs from clang-13 to clang-14.

CHROMEOS build-configs-chromeos.yaml: switch to clang-14

---

config/core/build-configs.yaml

For initial testing of real hardware and qemu we need serial console support,
through which we can check if the OS has booted, if there is a login prompt,
and it is better to carry out initial diagnostics over the serial console,
since the network connection may not be available.

 build-configs.yaml: Add SERIAL_8250 to x86-chromebook fragment #1165

---

config/core/rootfs-configs.yaml
config/rootfs/debos/rootfs.yaml
config/rootfs/debos/scripts/install-firmware.sh
doc/kci_rootfs.md
kernelci/config/rootfs.py
kernelci/rootfs.py

The config/rootfs/debos/scripts/install-firmware.sh script hardcodes the
commit to fetch from the linux-firmare repo. This changeset implements a
"linux_fw_version" key for rootfs configs that define
"extra_firmware". If defined (as a commit hash, tag or branch), it
overrides the commit originally defined in the script.
Signed-off-by: Ricardo Cañuelo <ricardo.canuelo@collabora.com>

rootfs: parameterize the linux-firmware repo version

---

config/core/test-configs-chromeos.yaml
config/core/test-configs.yaml

Create a test-configs-chromeos.yaml config file with all the test
configs related to Chrome OS to avoid conflicts with main branch and
simplify maintenance.

CHROMEOS test-configs-chromeos.yaml: split tests from main file

---

config/core/build-configs-chromeos.yaml

Add kernelci_chromeos-stable build config with test branch in kernelci
tree based on stable (5.10 LTS).

CHROMEOS build-configs-chromeos.yaml: add kernelci_chromeos-stable

---

config/core/rootfs-configs.yaml
config/core/test-configs-chromeos.yaml
config/lava/chromeos/chromeos-boot-chromebook-template.jinja2
config/lava/chromeos/chromeos-install-modules-template.jinja2
config/rootfs/debos/overlays/chromeos-flash/opt/chromeos/install-modules

Add LAVA job template for installing chromeos modules and a accompanying test-configs.yaml configuration.

CHROMEOS config/lava/chromeos: Add chromeos-install-modules-template

---

config/core/test-configs-chromeos.yaml
config/core/test-configs.yaml
config/lava/chromeos/chromeos-boot-chromebook-template.jinja2
config/lava/chromeos/chromeos-tast-template.jinja2

Enable `chromeos-boot`, `chromeos-boot-fixed`, `chromeos-tast` and `chromeos-tast-fixed` to run on both `octopus` variants.

CHROMEOS Enable Chrome OS tests to run on octopus Chromebook

---

config/core/test-configs-chromeos.yaml

Add chromeos-install-modules configuration which got lost when moving
configs from test-configs.yaml to test-configs-chromeos.yaml

CHROMEOS config/core/tes-configs-chromeos.yaml: Add chromeos-install-modules configuration

---

config/lava/chromeos/chromeos-flash-template.jinja2

Add wget -q option when downloading a Chrome OS image to flash as this
otherwise causes a lot of noise in the LAVA logs and it's not useful
as progress isn't shown dynamically anyway.

CHROMEOS config/lava: wget -q the Chrome OS image when flashing

---

config/core/test-configs.yaml

Update the URL of the Chromium OS image for octopus to R100.

CHROMEOS test-configs.yaml: use octopus Chromium OS R100 image

---

config/core/build-configs.yaml

Remove lee_android_3.18 as requested in https://github.com/kernelci/kernelci-core/issues/235#issuecomment-1122124032

build-configs.yaml: remove lee_android_3.18 build config

---

config/core/test-configs-chromeos.yaml
config/lava/chromeos/chromeos-install-modules-template.jinja2

Add a test plan variant `chromeos-install-modules-fixed` to install modules from the fixed reference kernel as this is needed to run the `-boot-fixed` and `-tast-fixed` test plans.

CHROMEOS Add test definition to install modules from the fixed reference kernel

---

config/lava/chromeos/tast.jinja2

Replace the "whoami" command with "cat /etc/os-release" in the
tast.jinja2 template.  This shows information about the Chrome OS
image version currently being used.  For example, with the current
R100 octopus image:
NAME=Chromium OS
ID=chromiumos
HOME_URL=https://www.chromium.org/chromium-os
BUG_REPORT_URL=https://crbug.com/new
VERSION=100
VERSION_ID=100
BUILD_ID=14526.105.2022_04_27_1612

CHROMEOS config/lava/chromeos: cat os-release in tast.jinja2

---

config/core/test-configs.yaml

This builds on top of https://github.com/kernelci/kernelci-core/pull/1121, adding the kselftests on top. At time of submission the lab configurations need updating to support the larger kernel that the kselftest fragments generate (though some will start working once https://github.com/kernelci/kernelci-core/pull/1116 goes in), the lab config for at least my lab will hopefully be updated in the next day or two when I find a quiet period in my lab.

Pine64+ kselftests

---

config/core/test-configs.yaml

Add a buildroot-staging rootfs definition for buildroot images built
on staging.  This is typically used with temporary patches to switch
test plans such as buildroot-baseline to using staging builds while
testing some changes.

test-configs.yaml: add buildroot-staging rootfs definition

---

config/core/test-configs.yaml

Update all the rootfs URLs to 20220513.0 except bullseye-libcamera
which failed to build.

test-configs.yaml: update rootfs URLs to 20220513.0 except libcamera

---

config/core/test-configs.yaml

The BeagleBone Black has both a sound card and a crypto engine so
enable both the ALSA kselftests and the LTP crypto tests to cover
both of these.  Since these tests run fairly quickly the load on
labs should be reasonably light.

test-configs.yaml: Enable hardware coverage for BeagleBone Black

---

config/core/test-configs.yaml

Provide a basic hookup for the arm64 kselftests and enable them for a bunch
of platforms. Other than qemu these platforms are picked mostly at random,
just to ensure that there's a selection of physical implementations. The
one it's most important to cover here is qemu since the arm64 kselftests
exercise bleeding edge architecture features which are generally supported
in emulation well before they are available in physical implementations.
The tests will detect missing features at runtime and cleanly skip tests
that don't apply to the current platform.

test-configs: Enable arm64 kselftests

---

config/core/test-configs.yaml

Enable kselftest-arm64 on mt8173-elm-hana.
Depends on #1089.

test-configs.yaml: enable kselftest-arm64 on hana Chromebook

---

config/core/test-configs-chromeos.yaml

Replace kernel 5.17 with 5.10 to keep cheomeos-flash and
chromeos-install-modules jobs consistent

CHROMEOS config/core/test-configs-chromeos.yaml: Change kernel in chromeos install-modules job to 5.10

---

config/core/test-configs.yaml

Stop running the sleep and usb test plans on odroid-xu3 as they take
too long to complete given there is only one device online for
kernelci.org at the moment.

test-configs.yaml: drop sleep and usb on odroid-xu3

---

config/core/build-configs.yaml

Since clang-14 is now a real release update our -next builds to use
clang-15, ensuring that we have coverage of the current in development
kernel stuff with it's clang equivalent.

build-configs.yaml: Update -next to build with clang-15

---

config/core/build-configs.yaml

Since clang-14 has now been released update our mainline build to use that
rather than clang-13, ensuring that we're covering the latest release.

build-configs.yaml: Update mainline to build with clang-14

---

config/lava/chromeos/chromeos-boot-chromebook-template.jinja2
config/lava/chromeos/chromeos-flash-template.jinja2
config/lava/chromeos/chromeos-install-modules-template.jinja2
config/lava/chromeos/chromeos-tast-qemu.jinja2
config/lava/chromeos/chromeos-tast-template.jinja2
kci_test
kernelci/cli.py
kernelci/test.py

Add --device-id option to kci_test commandline tool to add explicitly devices 
on which the test plan should be executed. 
The option produces device_ids argument being a list of device 
identifiers.
The --device-id commandline option can be repeated multiple times
providing single device id per occurrence.
Add support to specify device ids list to the Chrome OS related job templates based on device_ids list provided.

CHROMEOS Add --device-ids argument

---

config/lava/chromeos/chromeos-boot-chromebook-template.jinja2
config/lava/chromeos/chromeos-tast-template.jinja2

Devices that are detected asynchronously such as USB or MMC,
require rootwait option, so kernel wait root, instead of panic.
Without this option LAVA depthcharge boot become unreliable.
Also this option used by ChromeOS itself.

CHROMEOS config/lava/chromeos: Add rootwait to kernel options

---

config/core/test-configs-chromeos.yaml
config/core/test-configs.yaml

Split the hp-x360-12b-n4000-octopus device type into the 2 variants
currently available in lab-collabora and lab-collabora-staging called
hp-x360-12b-ca0010nr-n4020-octopus and
hp-x360-12b-ca0500na-n4000-octopus respectively.  They have very minor
harwdare differences but can use the same Chrome OS image and kernel.
Update test-configs-chromeos.yaml accordingly.

CHROMEOS test-configs.yaml: split octopus into 2 separate types

---

config/core/test-configs.yaml

Add `device_id` template parameter and define it for octopus devices so Chrome OS jobs run on only particular devices.
Depends on #1195

CHROMEOS add tags for octopus devices

---

config/core/rootfs-configs.yaml
config/rootfs/chromiumos/scripts/build_board.sh
kernelci/config/rootfs.py
kernelci/rootfs.py

As investigated, octopus are different from QEMU by using second serial,
so slight adjustments for build script required.
It is done such way that it will be easier to add similar Chromebooks in
future.
Patch tested by manual build and verified on LAVA for console functionality.

CHROMEOS build_board.sh: Build octopus with ttyS1 serial console

---

config/core/test-configs.yaml

Drop the ltp-mm test plan from rk3288-rock2-square as there is only
one board online in kernelci.org at the moment and it can't cope with
the test load.

test-configs.yaml: drop ltp-mm from rock2-square

---

config/core/test-configs-chromeos.yaml
config/lava/chromeos/chromeos-install-modules-and-boot-template.jinja2

Add job template and configuration for arbitrary and the fixed kernel
for installing modules and booting CrOS in a single 2-stage LAVA job.

CHROMEOS config/lava: Add 2-step job to install modules and boot Chromebook

---

config/docker/cros-qemu-modules/Dockerfile
config/docker/cros-qemu-modules/add_modules.sh
config/docker/cros-sdk/Dockerfile
config/docker/cros-tast/Dockerfile
config/docker/cros-tast/tast_parser.py

Add some Dockerfiles for creating images used to build Chrome OS user-space and run Chrome OS tests in LAVA.
Changes compared to the `chromeos` branch:
* `tast-parser.py` renamed to `tast_parser.py` and `pycodestyle` issues fixed
* images renamed with `cros-` prefix and less ambiguous names
* `build-and-push.sh` changes are not included in this PR, it can be done as a follow-up

Add Chrome OS Docker images

---

config/rootfs/debos/overlays/chromeos-flash/opt/chromeos/install-modules

In some circumstances during archive unpacking tar might modify /root
ownership and break ChromeOS rootfs booting.
Add flags to handle unpacking more safely.

CHROMEOS install-modules: Ignore uid/gid and attributes in tar

---

config/core/rootfs-configs-chromeos.yaml
config/rootfs/debos/overlays/cros-flash/etc/resolv.conf
config/rootfs/debos/overlays/cros-flash/opt/chromeos/flash
config/rootfs/debos/overlays/cros-flash/opt/chromeos/install-modules

Add a rootfs configuration to flash Chrome OS images on Chromebook devices in LAVA.

Add Bullseye rootfs image for flashing Chrome OS on Chromebook devices

---

config/core/test-configs.yaml

Rename hp-x360-12b-n4000-octopus as hp-x360-12b-ca0010nr-n4020-octopus
which is the full generic name for this variant.
Fixes: d0c7caf202aa ("test-configs.yaml: add hp-x360-12b-ca0500na-n4000-octopus variant")

test-configs.yaml: add hp-x360-12b-ca0010nr-n4020-octopus device type

---

config/core/test-configs.yaml

These two boards are unusual in that as well as having the
primary Arm system which KernelCI interacts with they also have
an Arduino on the same board. There are two different models with
i.MX6DL and i.MX6Q SoCs:
https://www.udoo.org/udoo-quad-dual/
Just add some very basic test coverage for now.

test-configs: Add Udoo i.MX boards

---

config/core/test-configs-chromeos.yaml
config/lava/chromeos/cros-boot-qemu.jinja2
config/lava/chromeos/cros-boot.jinja2
config/lava/chromeos/cros-flash.jinja2
config/lava/chromeos/cros-tast.jinja2

Depends on #1215 
Rework the parameters in the device type definitions to avoid
repeating URLs everywhere.  Use a base_url attribute and the name of
the path where to find resources instead.  Update the
cros-{flash,boot,tast}.jinja2 templates accordingly.

CHROMEOS rework device type parameters to avoid duplicated URLs

---

kernelci/lab/lava/__init__.py

Add extra processing step before generating LAVA test job definitions
to shorten the job name using a 1-to-1 mapping between long and short
strings for the Chrome OS configs and device type names.  Strings that
aren't in the mapping won't be shortened so it won't fail but might
result in longer names until they get added too.
This is required in order to avoid hitting the limit of 256 characters
for LAVA job names.  For example, without this change a job name could
have been (217 characters):
kernelci-chromeos-stable-chromeos-stable-20220526.0-x86_64-cros---chromeos-5.10-x86_64-chromeos-intel-denverton.flavour.config+x86-chromebook-clang-14-no-dtb-hp-x360-12b-ca0500na-n4000-octopus_chromeos-cros-tast-fixed
With the shortening done by this change we now have (136 characters): …

CHROMEOS kernelci.lab.lava: shorten Chrome OS job names

---

config/rootfs/debos/scripts/bullseye-libcamera.sh

Install cmake in the bullseye-libcameara.sh build script to fix a
build failure:
2022/05/27 11:32:39 bullseye-libcamera.sh | HEAD is now at 2c891fc Changes for v0.2.5 release
2022/05/27 11:32:39 bullseye-libcamera.sh |
2022/05/27 11:32:39 bullseye-libcamera.sh | Executing subproject [1mlibyaml[0m method [1mcmake[0m
2022/05/27 11:32:39 bullseye-libcamera.sh |
2022/05/27 11:32:39 bullseye-libcamera.sh | libyaml| Did not find CMake 'cmake'
2022/05/27 11:32:39 bullseye-libcamera.sh | libyaml| Found CMake: [1;31mNO[0m
2022/05/27 11:32:39 bullseye-libcamera.sh |
2022/05/27 11:32:39 bullseye-libcamera.sh | src/libcamera/meson.build:98:4: [1;31mERROR:[0m Unable to find CMake

rootfs/bullseye-libcamera: install cmake in build script

---

config/core/test-configs.yaml

For arm64 the KVM selftests really want to be run on a system with a single
CPU type, additional configuration is required for big.LITTLE systems. The
QDF2400 is interesting for this since it is a unique CPU implementation and
a server machine where KVM is one of the intended applications so let's
enable KVM there. Unfortunately the platform is also very slow to boot
which in conjunction with the ~6 minute runtime for the tests means that
we are on the edge of the current 10 minute job timeout, raise that a bit
to give some headroom.

test-configs.yaml: Enable KVM selftests on qdf2400

---

config/lava/boot-fastboot/generic-fastboot-boot-template.jinja2
config/lava/boot-nfs/generic-barebox-tftp-nfs-template.jinja2
config/lava/boot-nfs/generic-depthcharge-tftp-nfs-template.jinja2
config/lava/boot-nfs/generic-grub-tftp-nfs-template.jinja2
config/lava/boot-nfs/generic-ipxe-tftp-nfs-template.jinja2
config/lava/boot-nfs/generic-uboot-tftp-nfs-template.jinja2
config/lava/boot/generic-barebox-tftp-ramdisk-boot-template.jinja2
config/lava/boot/generic-depthcharge-tftp-ramdisk-boot-template.jinja2
config/lava/boot/generic-grub-tftp-ramdisk-boot-template.jinja2
config/lava/boot/generic-ipxe-tftp-ramdisk-boot-template.jinja2
config/lava/boot/generic-qemu-boot-template.jinja2
config/lava/boot/generic-uboot-tftp-ramdisk-boot-template.jinja2

Add a boot_timeout template variable which can be used to override the
boot timeout.  This can typically be set in the device type parameters
for devices that take longer to boot.

config/lava: add boot_timeout template variable

---

config/core/test-configs.yaml

Depends on #1217 
Set the boot_timeout parameter to 10 min for qcom-qdf2400 as it easily
takes more than 5 minutes to boot.

test-configs.yaml: set boot_timeout of 10min for qcom-qdf2400

---

config/core/test-configs.yaml

Disable tests in lab-collabora on `minnowboard-turbot-E3826` and enable `kselftest-alsa` on `minnowboard-max-E3825` as it should have enough capacity in `lab-collabora-staging` to run it.

Update minnowboard config filters

---

config/core/test-configs.yaml

There is a known regression on the hip07-d05 platform between v5.4 and
v5.10 so stop running kernels more recent than v5.4 until it's fixed
as all jobs with v5.10 onwards just time out.
Link: https://github.com/kernelci/kernelci-project/issues/113

test-configs.yaml: stop running v5.10 onwards on hip07-d05

---

kernelci/test.py

Use the describe_verbose meta-data attribute when applying filters
based on the kernel revision.  This attribute is formatted to always
rely on standard kernel release tags e.g. v5.4.123 rather than any
other tree-specific tags set by maintainers or linux-next etc.

kernelci.test: use describe_verbose for kernel filters

---

config/kubernetes/base-k8s.jinja2
config/scripts/base-python.jinja2
config/scripts/base.jinja2

Align the base templates in config/scripts with the ones in
config/kubernetes so that test plans templates such as check-describe
(in kernelci-pipeline) can include either base-python.jinja2 or
base-k8s-python.jinja2 depending on the runtime environment.

config/scripts: align base templates with kubernetes

---

config/core/build-configs.yaml

By default, with chromeos fragments CONFIG_SERIAL_8250_CONSOLE is disabled,
while it is important to have this option enabled to monitor kernel messages
in LAVA.

CHROMEOS build-configs.yaml: Enable kernel serial console

---

kernelci/lab/lava/__init__.py

Current regex fails on x86_64, for example defconfig_full:
chromeos-5.10/x86_64/chromiumos-x86_64.flavour.config+x86-chromebook

CHROMEOS lava/__init__.py: Fix regex failure on some configurations

---

config/core/test-configs-chromeos.yaml
config/lava/chromeos/cros-flash.jinja2
kci_test
kernelci/cli.py
kernelci/lab/__init__.py
kernelci/lab/lava/__init__.py
kernelci/test.py

Add a `cros-flash` test plan to flash Chrome OS images on Chromebooks, starting with `octopus`.

Add cros-flash test plan with parameters for octopus

---

config/core/lab-configs.yaml

Drop lab-mhart from the list of configs as it has been offline for
about two years now.

lab-configs.yaml: drop lab-mhart

---

config/docker/dt-validation/Dockerfile

Newer versions of the kernel are able to make optional use of yamllint in
DT validation so install it in the dt-validation container.

docker: Install yamllint for dt-validation

---

config/docker/clang-base/Dockerfile

Add some build dependencies for kselftest to enable kselftest builds with
clang.
There are currently issues with non-native clang builds upstream so this
won't work for the cross builds but that needs to be addressed in the
kernel.

docker: Add kseltest build deps to clang containers

---

config/core/test-configs.yaml

Now the board is setup in the kontron lab. A merge-requrest for the device-type in lava is also done.
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>

test-configs.yaml: add Kontron bl-imx8mm board

---

config/lava/v4l2-compliance/v4l2-compliance.jinja2
config/rootfs/debos/overlays/v4l2/usr/bin/v4l2-parser.sh

This PR changes the v4l2-parser.sh script and v4l2-compliance.jinja2 template in order to allow for two new parameters to be passed in v4l2-compliance test plans: `v4l2_capture_format` and `v4l2_output_format`. These allow a video node to be matched also based on its capture and/or output format. This is useful since there are some platforms (like mt8173) that have more than one codec device using the same driver, and the only difference between them is the capture/output format. So these arguments allow each of the codec on platforms like this to be tested independently.
The matching of the device node based on the format needs to be done in the v4l-get-device utility, so [a Merge Request](https://gitlab.collabora.com/gtucker/v4l2-get-device/-/merge_requests/1) was created adding this …

v4l2-compliance: Add support for capture and output format arguments

---

test-suites/cvehound

The script converts cvehound reports to kernelci tests format.
How to use:
$ cvehound --kernel /root/linux --report report.json
$ ./test-suites/cvehound --bmeta bmeta.json --report report.json --output kernelci-results.json
$ kci_data submit_test --data-file=kernelci-results.json --db-config=...
This is a part of #803.
Signed-off-by: Denis Efremov <denis.e.efremov@oracle.com>

cvehound: add a script to convert reports to kernelci format

---

config/core/test-configs.yaml

Upate all the rootfs URLs to 20220610.* builds from today.  The
buildroot-baseline ones were rebuilt with latest bootrr changes.  The
bullseye-v4l2 ones were rebuilt with latest changes in the
v4l2-parser.sh script.

test-configs.yaml: update rootfs URLs to 20220610

---

config/core/test-configs-chromeos.yaml

Drop the device_id parameters in the octopus device types as all
devices should be flashed with the same R100 image in production now.

CHROMEOS test-configs-chromeos.yaml: drop device_id from octopus

---

config/core/test-configs.yaml

We only have one Juno available and it's never going to be able to keep
up with all the LTP tests we're currently scheduling, don't try to
schedule any.

test-configs: Don't run slow LTP tests on Juno

---

kernelci/db/kernelci_api.py

Implement `KernelCI_API.get_regressions` to request `/regression` endpoint of API with regression name.

T35922 Implement APIs to request /regressions endpoint

---

config/core/test-configs.yaml

Update rootfs URLs to 20220617.0.
bullseye-ltp rootfs images were not updated due to build issues.

test-configs.yaml: update rootfs URLs to 20220617.0

---

config/core/build-configs-chromeos.yaml

Add a chromeos-stable_5.15 build configuration based on v5.15 LTS.

CHROMEOS build-configs-chromeos.yaml: Add 5.15 LTS stable tree

---

config/core/test-configs.yaml
kernelci/config/test.py
kernelci/test.py

This board has ethernet and can run NFS root (my own testing
includes something based on the KernelCI NFS tests as a regular
feature).

Support use of Debian armel port on systems that require it

---

config/docker/gcc-10_armv5/Dockerfile

To allow us to build v5 versions of kselftests provide a GCC version of
the toolchain.

docker: Add a GCC 10 image for armel

---

config/lava/base/kernel-ci-base.jinja2

In some tests, like ChromeOS, initrd might be not present.
Do not add it in metadata if it is not present to avoid LAVA errors like this:
Problem with submitted job data: expected str for dictionary value @ data['metadata']['job.initrd_url']

CHROMEOS kernel-ci-base.jinja2: Make initrd_url as optional value

---

config/core/test-configs.yaml

Update all rootfs URLs to 20220624.0 except bullseye-ltp which failed
to build again.

test-configs.yaml: update rootfs URLs to 20220624.0

---

config/core/lab-configs.yaml

Since we have to manually list all the testsuites we're willing to run
in each lab add patterns for all the currently defined ones to my lab.

lab-configs: Add yet more tests for my lab

---

config/core/test-configs.yaml

Enable igt-gpu for systems with the lima driver, enabled on pine64-plus
initially. There are no lima specific tests in upstream igt so it's just
the core tests.

test-configs: Provide igt-kms coverage for lima driver

---

config/core/test-configs.yaml

Add some IGT testing for the Vivante GPUs used in many SoCs, including some
i.MX generations. There aren't any etnaviv specific tests in upstream igt
yet.
I'll add these to the Udoo devices once support for those is merged, they
could also run this on other i.MX6 devices.

test-configs: Add etnaviv GPU test stanza

---

config/core/test-configs-chromeos.yaml

According to ChromiumOS SDK even Octopus board is chipset-glk,
kernel fragment should be used chromeos-intel-pineview.
Add filter, because kernel builds with wrong configs might give
false negative test results.

CHROMEOS test-configs-chromeos.yaml: Add pineview filter for Octopus

---

config/core/build-configs-chromeos.yaml
config/core/test-configs-chromeos.yaml

QEMU require it's own specific configuration, with virtio
and few other drivers.
This patch add new fragment for builds and limit QEMU to
test only with build that is compatible with it.

CHROMEOS config/core: Add fragments for ChromeOS qemu

---

config/core/rootfs-configs-chromeos.yaml

Add a config entry for building Chromium OS R100 for hatch.

CHROMEOS rootfs-configs-chromeos.yaml: add chromiumos-hatch

---

config/rootfs/debos/scripts/bullseye-ltp.sh

The commit introducing the issue #948 can't be reverted any more due
to conflicts with more recent changes.  Add a patch to do the same
thing with the latest code instead.

rootfs/ltp: add workaround patch for #948

---

doc/kci_data.md

Update the documentation section about how to create API users with
kci_data.  Add relative links to other parts of the documentation,
wrap long lines, mention it's still under development and simplify the
sample commands.

doc: update kci_data section about adding API users

---

config/core/test-configs-chromeos.yaml

As we need cros://chromeos-5.10/x86_64/chromiumos-x86_64.flavour.config
for proper qemu support, we should remove "cros" from blocklist.
Device already have proper filter.
It will solve issue with missing tests for -fixed tests.

CHROMIUMOS test-configs-chromeos.yaml: Remove blocklist for cros

---

config/core/test-configs-chromeos.yaml

Update the url of the bullseye-cros-flash NFS rootfs image with the
latest production build. There are some changes in install-modules
script which may break tests using older images.
This is slightly updated version of PR https://github.com/kernelci/kernelci-core/pull/1271

CHROMEOS test-configs-chromeos.yaml: update cros-flash NFS rootfs URL

---

config/core/test-configs-chromeos.yaml
config/docker/cros-baseline/Dockerfile
config/lava/chromeos/cros-baseline.jinja2

To improve tests information, it is useful to add test similar to other kernelci
baseline tests that show kernel messages with warn/error/crit levels,
mark test as fail if they are present, and highlight number of such messages.

CHROMEOS docker/cros-tast: Add dmesg baseline tests

---

config/core/test-configs.yaml

None of the labs have multiple pin64plus boards and we currently don't
have effective prioritisation of tests so the long running tests like
the LTP pty and timers tests are contributing greatly to a massive
backlog of tests on these boards. Drop those tests for now.

test-configs: Drop slow tests for pine64plus

---

config/core/test-configs.yaml
kernelci/lab/lava/__init__.py

This branch aims to mitigate the impact of longer running tests on labs which are overloaded by configuring lower priorities for jobs which are expected to have longer runtimes, trying to help us get a wider range of coverage more promptly with the bandwidth on the boards we have.
This won't fix anything if the lab is just completely overwhelmed but for cases where there are peaks in load it should help us get a wider set of results through more promptly as we catch up and if the lab has a queue timeout it should be these slower jobs that get timed out.

Lower priorities for longer running tests

---

config/core/test-configs.yaml

According to staging jenkins logs baseline-fastboot scheduled to meson-sm1-sei610
device, but device doesnt have fastboot tag and this cause error during job submit.
For example: https://bot.staging.kernelci.org/job/test-runner/34511/console
ERROR /data/workspace/bot.staging.kernelci.org/test-runner/workspace/test-runner/jobs/lab-baylibre/kernelci-staging-mainline-staging-mainline-20220707.0-arm64-defconfig-clang-11-meson-g12a-sei510.dtb-meson-g12a-sei510-baseline-fastboot.yaml: <Fault 400: "Device unavailable: No devices of type meson-g12a-sei510 are available which have all of the tags 'fastboot'.">
Also i cannot find any successfull baseline-fastboot test on staging or production.

test-configs.yaml: Remove baseline-fastboot from device not supporting fastboot

---

config/core/test-configs.yaml

At least my lab has multiple BeagleBone Blacks with plenty of spare
capacity at current loads so add a few more tests to increase coverage.

test-configs: Add more tests to BeagleBone Black

---

config/docker/cros-sdk/Dockerfile

Clean up the Dockerfile for the cros-sdk image:
* sort package names alphabetically
* split long lines and long commands
* fix indentation issue with mixed tabs and spaces
* rename "user" to "cros" user

CHROMEOS config/docker: clean up cros-sdk Dockerfile

---

config/core/lab-configs.yaml

As Collabora notified at 15/07/2022 they will change hostname
of LAVA from lava.collabora.co.uk to lava.collabora.dev.
This commit update relevant config.

lab-configs.yaml: Update Collabora LAVA URL

---

kernelci/db/kernelci_api.py

Fixes https://github.com/kernelci/kernelci-api/issues/130
Support multivalued PubSub filer by providing tuple values.
A PubSub event will be received even if any one value of the multivalued filter matches the event data.
Now we can provide filters like below:
{"op":("updated","created")}
{"revision":{"commit": ("a", "b")}, "status": ("pass","fail"), "op": "created"}

T35800 Allow multivalued PubSub filter

---

config/docker/qemu/Dockerfile

The collabora lab connects the qemu test device to a host bridge to
allow for predictable IP address per dut (so external test can acces
them). For this to work when running qemu in docker the bridge helper
acl needs to be configured.
This simply configures it to allow access to all host bridges.
Signed-off-by: Sjoerd Simons <sjoerd@collabora.com>

config/docker: Configure bridge helper ACLs

---

config/core/test-configs.yaml

Enable QEMU Docker jobs in lab-collabora now that is has been upgraded
to LAVA 2021.01.3.
Depends on #1245 which in turn depends on some extra LAVA changes to be merged and deployed in the lab.

test-configs.yaml: enable QEMU Docker in lab-collabora

---

config/core/rootfs-configs-chromeos.yaml

Add a config entry for building Chromium OS R100 for grunt.
Depends on #1267

CHROMEOS rootfs-configs-chromeos.yaml: add chromiumos-grunt

---

config/core/test-configs-chromeos.yaml

To run correct kernel for tests we need to add proper filter,
as investigated in https://github.com/kernelci/kernelci-core/issues/1250

CHROMEOS test-configs-chromeos.yaml: Add pineview filter to hatch

---

config/docker/kernelci/Dockerfile

Add a core_url build argument to the kernelci Dockerfile so the
kernelci-core git repo URL can be changed at build time.  This is
especially useful during development to build from a GitHub fork.

config/docker: add core_url arg for kernelci

---

config/core/rootfs-configs-chromeos.yaml

Add config entries for Chromium OS R100 rootfs images for the hatch and grunt Chromebooks.

Add hatch and grunt config for Chromium OS

---

config/lava/preempt-rt/generic-uboot-tftp-ramdisk-preempt-rt-template.jinja2

As reported in issue https://github.com/kernelci/kernelci-core/issues/1307
We have error that this template is missing and many preempt-rt tests are
not being executed.

generic-uboot-tftp-ramdisk-preempt-rt-template.jinja2: Add missing template

---

config/core/test-configs.yaml

I have three Tritiums available in my lab which are mostly idle with the
current loading, add some more hardware agnostic tests to make use of
them.

test-configs: Additional tests for Tritium

---

config/lava/chromeos/cros-tast.jinja2

It's time to expand the number of tast tests and include more interesting ones.
One of the tests switches different tabs in chrome, the second tests video decoding.

CHROMEOS cros-tast.jinja2: Add more tast tests (tabswitch + videodecode)

---

config/core/test-configs-chromeos.yaml

As discussed, cros-boot replaced by more comprehensive baseline test.

CHROMEOS test-configs-chromeos.yaml: Replace all cros-boot by baseline

---

kernelci/config/lab.py

This reverts commit add1ffa86a8658c9134f19020395d61fbd588c01.
It's not necessary to have a configured template path as all the base
templates should be in runtime/base.  Then they can extend other
templates in sub-directories if needed e.g. "extends
base/foo-bar/something.jinja2" without any YAML config.

Revert "kernelci.config.lab: add config_path attribute"

---

config/rootfs/chromiumos/cros-snapshot-release-R100-14526.B.xml
config/rootfs/chromiumos/scripts/build_board.sh

As we experienced problems with rootfs builds due rolling release
nature of ChromeOS tags, we introduce repo snapshot feature that
will allow us to freeze source tree to specific snapshot,
and build rootfs based on this snapshot

CHROMEOS cros-snapshot.xml: Add manifest snapshot support

---

config/runtime/base/python.jinja2

Add missing Python import for the requests package in the
base/python.jinja2 template.

config/runtime: add missing requests import

---

config/core/test-configs-chromeos.yaml

Enable grunt device to run cros-flash test-plan.

CHROMEOS test-configs-chromeos.yaml: add chromiumos-grunt

---

config/docker/build-base/Dockerfile
config/docker/build-base/kmod_kci.patch

Some tests (allmodconfig, ChromeOS) require
support for gzip/zlib compression of kernel modules,
for this we will patch and rebuild the kmod package
during the build-base Docker image rebuild.

docker/build-base: Add patched(+zlib) kmod install

---

config/runtime/base/kubernetes.jinja2

Add a tmpfs volume mounted in /dev/shm as this is required for running
KUnit tests in particular.

config/runtime: add /dev/shm to kubernetes.jinja2

---

config/runtime/base/kubernetes.jinja2
kernelci/config/test.py

Add a `TestPlan.image` configuration attribute and a `runtime_image` template variable in the Kubernetes template to be able to specify the Docker image to run for each test plan.
Depends on #1327

Add runtime_image template parameter for Kubernetes

---

config/lava/chromeos/cros-baseline.jinja2
config/lava/chromeos/cros-tast.jinja2

Correct wrong test names. "dmesg" test in cros-baseline.jinja2 was named
"cros-baseline", which is incorrect. Renamed it to "dmesg".
"cros-tast" test renamed to "tast".

CHROMEOS config/lava/chromeos: rename cros-baseline and cros-tast tests

---

config/docker-new/kci_docker

Fix the case where there is no build argument as the args.build_arg
variable is then None.
Fixes: df6106e71add ("config/docker: add --build-arg option to kci_docker")

config/docker: fix kci_docker with no build args

---

config/core/build-configs-cip.yaml

**Note: Not ready for merging yet, let's wait for some test results**
Trying to silence some build failures for invalid
kernel 4.4 - compiler - kernel configuration combinations. That should
help us to separate "noise" from real issues.
Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>

build-configs-cip.yaml: Add some blocklists for the 4.4 series

---

config/docker-new/data/gcc-header-fix.patch
config/docker-new/data/kmod_kci.patch

Copy some patch files used in Docker images to the new config directory so they can be used by kci_docker.

kci_docker patch files

---

config/docker-new/k8s.jinja2

Add the wget package to the k8s image as it's currently required to
download a JSON file with meta-data at the end of kernel builds using
Jenkins.

config/docker: add wget to the k8s image

---

config/docker-new/gcc-10-sparc.jinja2

Add a template for the sparc architecture with gcc-10 to be used with
the new kci_docker tool.  This can build both sparc32_defconfig and
sparc64_defconfig kernels.

config/docker: add gcc-10-sparc template for kci_docker

---

config/docker-new/base/debian.jinja2
config/docker-new/base/host-tools.jinja2

Based on https://github.com/kernelci/kernelci-core/commit/f8a03576724cdb78c94e75bf150b6e493d725cdb, add a multi-stage build in `host-tools.jinja2` for building kmod from source with compression enabled.  Then install it in the main image.

Build kmod with compression in kci_docker templates

---

kernelci/db/kernelci_api.py

Implement KernelCI_API.get_nodes
to get all the nodes from API.
Used this in https://github.com/kernelci/kernelci-pipeline/pull/71

T35078 Get all nodes matching attributes from API

---

config/docker-new/clang-14.jinja2
config/docker-new/clang-15.jinja2

The LLVM 15.0 release is now approaching and version 16 has become the
new one in the default repository.  Update the clang-15 repository
name accordingly.

config/docker: update clang-15.jinja2 template

---

config/k8s/job-build.jinja2

Run the builds as root user with the new Docker images that set the
default user to kernelci (1000).  The previous images used root by
default, and the build artifacts were all owned by root as a result.
It's important to keep that as kernel files are expected to be owned
by root.
A follow-up improvement could be to run the build with the regular
user and then have a step in another container to change the ownership
of the artifacts to root before uploading them.

config/k8s: run builds as root user

---

config/core/build-configs-chromeos.yaml

As investigated, 5.10 kernel doesnt have in-kernel modules decompression,
and because of ChromeOS specific use of LSM(LoadPin),
OS/kernel cannot load compressed modules.

CHROMEOS build-configs-chromeos.yaml: Remove modules compression on 5.10

---

kernelci/build.py

Call `make headers` first for kernels earlier than v5.20 and just call `make kselftest-gen_tar` for `v5.20` onwards. This relies on the changes described in https://github.com/kernelci/kernelci-project/issues/92 to have been merged in mainline (which should happen during the v5.20 merge window).
We may drop the 2-step make approach once the next LTS has been declared and stop building kselftest for earlier kernels (say, `v6.0` or something).

T33737 update kselftest make commands

---

config/docker-new/base/host-tools.jinja2
config/docker-new/gcc-10-x86.jinja2

Update the URLs of the patch files used for the kmod and gcc-10 x86 images to download them from the config/docker-new/data directory on the main branch now that they have been merged.

config/docker-new: update URLs for patch files

---

config/docker-new/kci_docker

Drop unnecessary dictionary comprehension in kci_docker as reported by
pylint since the dict() constructor can iterate over a list of pairs.

config/docker: remove unnecessary comprehension in kci_docker

---

kernelci/db/kernelci_api.py

Depends on https://github.com/kernelci/kernelci-api/pull/151
Implement a method to get a list of
regressions matching node id.

T35922 kernelci_api.py: update method to get regressions

---

config/core/test-configs.yaml

The Udoo boards in my lab are currently fairly lightly loaded, add more
generic tests to improve coverage.

test-configs: Add more tests for Udoo boards

---

config/core/test-configs.yaml

For arm64 the KVM selftests really want to be run on a system with a single
CPU type, additional configuration is required for big.LITTLE systems. Get
some coverage by enabling on:
- QDF2400 which is a unique CPU implementation and a server machine where
KVM is one of the intended applications.
- Le Potato which should be relatively abundant, especially once I have
the couple I have queued for addition to my lab deployed, and covers
Cortex-A53.

test-configs.yaml: Enable KVM selftests on some arm64 boards

---

config/core/test-configs.yaml

Update rootfs URLs to 20220812.0 except buildroot-baseline which failed
to build.

test-configs.yaml: update rootfs URLs to 20220812.0

---

doc/kci_build.md
doc/kci_data.md
doc/settings.md

Use gcc-10 which is the default toolchain now instead of gcc-8 in the
documentation examples so they should actually work with the current
YAML config.

docs: use gcc-10 instead of gcc-8 in examples

---

config/docker-new/clang-16.jinja2

Add a clang-16.jinja2 template to build clang-16 images with the
current latest LLVM version (not released yet).

config/docker: add clang-16.jinja2 template

---

config/core/rootfs-configs-chromeos.yaml
config/rootfs/chromiumos/cros-snapshot-release-R102-14695.B.xml
config/rootfs/chromiumos/scripts/build_board.sh

R102 is best suitable as it is Long-Term Candidate and expected to have several month of updates.
This commits address several things:
* Temporary build workaround
* Update manifest snapshot for R102
* Update versions in yaml file

Bump ChromeOS rootfs build version to r102 and update manifest

---

config/docker-new/base/clang.jinja2

Add the 32-bit i386 packages to clang.jinja2 to build kselftest on
i386 and some 32-bit host tools.

config/docker: add i386 packages to clang.jinja2

---

config/core/test-configs-chromeos.yaml

Fix incorrect rootfs image used for modules install.
While it is similar, it is too large and tests might fail because of that.

CHROMEOS config/core/test-configs-chromeos.yaml: Fix grunt rootfs image

---

config/docker/clang-base/Dockerfile
config/docker/gcc-10_arm/Dockerfile
config/docker/gcc-10_arm64/Dockerfile
config/docker/gcc-10_x86/Dockerfile

As reported in maillist https://groups.io/g/kernelci/message/1489 recent builds are failing,
because pahole tool is missing.
This patch add required support and tested locally.

docker: add dwarves package for pahole tool

---

config/core/build-configs-cip.yaml

arm64 was out of scope for the 4.4 series. Disabling it save some
resources and silences arm64 related testing issues.
Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>

build-configs-cip.yaml: Disable arm64 builds for 4.4-cip

---

config/runtime/base/python.jinja2

Add a `Job` class in `python.jinja2` to be able to override how jobs are run and how results are submitted.  Also print call stack when an exception is caught.

Add Job class in python.jinja2

---

kernelci/build.py

Fix the logic in Step._check_min_kver() which failed to treat the
minor version as a minor version number, causing the check to return
False if the minor version was lower even though the major version was
higher.
Fixes: 4930f88a76db ("kernelci.build: add Step._check_min_kver()")

kernelci.build: fix _check_min_kver() logic

---

config/docker-new/buildroot.jinja2

Add a buildroot.jinja2 template for building Docker images to build
Buildroot images.

config/docker: add buildroot.jinja2

---

config/docker-new/debos.jinja2

Add a debos.jinja2 template for building Docker images to build Debian
rootfs images using debos.

config/docker: add debos.jinja2

---

config/docker-new/qemu.jinja2

Add a qemu.jinja2 template to build the Docker image used to run QEMU
jobs.

config/docker: add qemu.jinja2

---

config/docker-new/coccinelle.jinja2
config/docker-new/cvehound.jinja2
config/docker-new/fragment/coccinelle.jinja2

Add a fragment/coccinelle.jinja2 template that can be reused by images
that need coccinelle to be installed.  Also add a coccinelle.jinja2
template to build an image with just coccinelle, and cvehound to build
an image with cvehound which includes the coccinelle fragment.

config/docker: add coccinelle and cvehound templates

---

config/docker-new/dt-validation.jinja2

Add a dt-validation.jinja2 template to build a Docker image suitable
for running the device-tree validation tools.

config/docker: add dt-validation.jinja2

---

config/core/rootfs-configs-chromeos.yaml
config/rootfs/debos/overlays/cros-flash/opt/chromeos/flash

For ChromiumOS PARTUUID change we need sgdisk tool capable to
change this parameter. Changing this parameter helps with
ChromiumOS devices where block device number is not predictable.

CHROMEOS rootfs-configs-chromeos.yaml: Add fixed PARTUUID and lid state ignore

---

config/core/test-configs-chromeos.yaml

As all Chromebooks and images are updated, we need to switch all links
to new R102 images, so tests will work properly.

CHROMEOS test-configs-chromeos.yaml: Upgrade test configuration to R102

---

config/core/test-configs.yaml

Having "v5.1" in the kernel blockist actually blocks v5.1*, which
explains why this board has not been booting on v5.10+ either. :(
Since we have not been build/boot testing v5.1 for a long time, just
removing this is an OK fix, but this is just a workaround for deeper
problem when kernel minor versions have two digits.  For example, the
v5.2 block would have also  blocked v5.20, but fortunately (for us),
the kernels past v5.19 are v6.

test-configs: hifive-unleashed: fix blocklist

---

kernelci/test.py

LAVA doesn't accept job names with more than 200 characters, drop dtb
from job name to reduce size and truncate job name below 200 characters

test.py: Remove dtb from job name and truncate below 200 chars

---

config/core/test-configs.yaml

Update rootfs URLs to 20220826.0 except buildroot-baseline which
failed to build for sparc64.

test-configs.yaml: update rootfs URLs to 20220826.0

---

config/core/test-configs-chromeos.yaml
config/lava/chromeos/cros-tast.jinja2

Extend cros-tast test plan with some kernel and platform tast tests.
Group tast tests into separate test plans.
Modify cros-tast jinja teamplate to run tests listed in the plan
definition.

CHROMEOS config/lava/chromeos: Add more tast tests (kernel + platform)

---

kci_build

As at current moment gki_defconfig generate exceptionally big
files that current backend have issues to handle,
we compress them as temporary workaround.
Fixes #1278 

kci_build: compress files for gki_defconfig

---

config/docker-new/base/host-tools.jinja2

As in https://github.com/kernelci/kernelci-core/pull/1158 we need
to add several packages to be able run pahole and other tools,
which is required to complete gki_defconfig build.

host-tools.jinja2: Add packages for gki_defconfig build

---

config/docker/cros-tast/Dockerfile
config/docker/cros-tast/ssh_retry.sh
config/lava/chromeos/cros-tast.jinja2

As discovered during lava tests, network stack of ChromeOS might
be pingable, but ssh daemon is not up yet (Connection refused).
As ssh don't have internal retry mechanism for such situation,
we add simple helper script for that.
This script will retry 10 times with delay, until it is able to connect
to DUT over ssh.
Example of failure
```
+ ping -c 1 -w 1 192.168.201.13
PING 192.168.201.13 (192.168.201.13): 56 data bytes
64 bytes from 192.168.201.13: icmp_seq=0 ttl=63 time=0.529 ms
--- 192.168.201.13 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.529/0.529/0.529/0.000 ms
+ lava-target-ip
+ lava-test-case os-release --shell ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/cros-tast/.ssh/id_rsa …
```

CHROMEOS ssh_retry.sh: Add ssh retry mechanism

---

config/core/build-configs-chromeos.yaml

For kernels 5.15 we need to use correct cros:// config fragments, also it is preferable to
test more(daily) ChromiumOS rootfs with kernel 5.15.

CHROMEOS build-configs-chromeos.yaml: Use correct fragment and set default builds to 5.15
